konflux-ci/build-definitions

- README.md
- pipelines/README.md
- pipelines/build-templates-bundle/devfile-build.yaml
- pipelines/build-templates-bundle/docker-build.yaml
- pipelines/build-templates-bundle/java-builder.yaml
- pipelines/build-templates-bundle/nodejs-builder.yaml
- pipelines/build-templates-bundle/noop.yaml
- pipelines/package-bundle.sh
- tasks/README.md
- tasks/analyze-devfile/Dockerfile.ubuntu
- tasks/analyze-devfile/README.md
- tasks/analyze-devfile/analyze-devfile.yaml
- tasks/appstudio-utils/Dockerfile
- tasks/appstudio-utils/README.md
- tasks/appstudio-utils/build
- tasks/appstudio-utils/test-all-tasks.sh
- tasks/appstudio-utils/util-scripts/analyze-devfile.sh
- tasks/appstudio-utils/util-scripts/image-exists.sh
- tasks/appstudio-utils/util-tasks/analyze-devfile.yaml
- tasks/appstudio-utils/util-tasks/appstudio-utils.yaml
- tasks/appstudio-utils/util-tasks/image-exists.yaml
This pull request contains the following changes
- pipelines previously define in the infra-deployment repo are now in this repo. This repository will be used to create the OCI bundle for App Studio build definitions pipelines
- new tasks to handle analyze-devfiles, testing for images (exists) to prevent rebuilds
- single container for utility tasks and an easy model to local and tekton way to test these tasks
> Pipelines and Tasks moved to this repo

- pipelines/build-templates-bundle/docker-build.yaml
Without this, we wouldn't be able to have these pipeline definitions consumed for webhooks.
> Parameterize the revision

- tasks/appstudio-utils/util-scripts/cleanup-build-directories.sh
When there are no build directories the pv-* matches nothing and returns the literal.
The errors printed during scans are unnecessary so this PR fixes that.
To be included in a published v0.1.1
> cleanup printing if build directories empty

- README.md
- tasks/appstudio-utils/README.md
- tasks/appstudio-utils/test-all-tasks.sh
- tasks/appstudio-utils/test-all-tasks/kustomization.yaml
- tasks/appstudio-utils/util-scripts/cleanup-build-directories.sh
This PR is intended to fix the cleanup task deleting subPaths: of a still running pipelinerun.
The issues found  
1) a single marker was used so if two of these runs execute concurrently one instance will delete the markers of another and those directories will be removed even if live. Using unique markers will prevent this. 
2) new PVs since the beginning of the cleanup will not contain a marker and would be deleted. This is handled by only processing the list of pvs you already marked and any one ones will have to wait until a future purge.
The script now 
- uses unique marker per run
- avoid race condition when new pvs arrive in middle of run by only using the same pv paths in both passes
also, the references to old versions (like v0.1.3) have been replaced in doc as vX.Y.Z so we don't …
> cleanup build directory fix

- hack/test-all-tasks/pipeline.yaml
- pipelines/devfile-build.yaml
- pipelines/docker-build.yaml
- pipelines/java-builder.yaml
- pipelines/nodejs-builder.yaml
- pipelines/noop.yaml
- pipelines/prototype-build-compliance.yaml
- tasks/buildah.yaml
- tasks/git-clone.yaml
- tasks/kustomization.yaml
- tasks/s2i-java.yaml
- tasks/s2i-nodejs.yaml
This PR contains the changes which remove references to clustertasks and replace with local task definitions. This is intended to enable pipelines on KCP
- added buildah, gitclone, s2i-java and s2i-nodejs tasks 
- changed references to all cluster tasks to local tasks
> remove clustertasks to work on kcp

- tasks/buildah.yaml
- tasks/s2i-java.yaml
- tasks/s2i-nodejs.yaml
Tekton Chains expects to see an IMAGE_URL taskrun result containing
the image repo url so let's provide it.
Avoids a "Did not find anything to attest" error from the chains
controller.
Similar to #24 which was merged recently.
Also:
- Make the result descriptions and task step scripts consistent
across each of the three tasks definitions
- Reword the IMAGE_URL description slightly
> Make s2i-java and s2i-nodejs chains friendly too

- tasks/configure-build.yaml
Pipeline task appstudio-configure-build is logging credentials in plain
form. Removing printing of the credentials.
> Remove logging of dockerconfigjson auth file

- pipelines/devfile-build.yaml
- pipelines/docker-build.yaml
- pipelines/java-builder.yaml
- pipelines/nodejs-builder.yaml
- pipelines/prototype-build-compliance.yaml
- tasks/buildah.yaml
- tasks/s2i-java.yaml
- tasks/s2i-nodejs.yaml
This aims at having
- a recent image, supporting automatic setting of [OCI standard annotations](https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys) for base images
- references consistent across Tasks and Pipelines
- manifest-list used
- an image based on UBI8 rather than RHEL8: (no redistribution allowed of RHEL according to EULA)
- published on registry.access.redhat.com (unauthenticated) instead of registry.redhat.io (authenticated) due to the above
Signed-off-by: Frederic Giloux <fgiloux@redhat.com>
> Bump of the buildah image referenced

- pipelines/devfile-build.yaml
- pipelines/docker-build.yaml
- pipelines/java-builder.yaml
- pipelines/nodejs-builder.yaml
- pipelines/prototype-build-compliance.yaml
- tasks/configure-build.yaml
- tasks/init.yaml
Fix of private repo cloning. Using feature of git-clone task directly.
No interaction with other steps.
> Set git-auth workspace only on git-clone task

- pipelines/java-builder.yaml
- pipelines/nodejs-builder.yaml
- tasks/s2i-java.yaml
- tasks/s2i-nodejs.yaml
Use the same way for s2i build as for buildah. Allow to define push
secret for each pipelinerun.
> Allow to use custom registry secret for s2i builds

- appstudio-utils/Dockerfile
- appstudio-utils/util-scripts/tekton-chains/_helpers.sh
- appstudio-utils/util-scripts/tekton-chains/check-pipelinerun.sh
- appstudio-utils/util-scripts/tekton-chains/check-taskrun.sh
- appstudio-utils/util-scripts/tekton-chains/cosign-verify-image-local.sh
- appstudio-utils/util-scripts/tekton-chains/cosign-verify-image-task.sh
- appstudio-utils/util-scripts/tekton-chains/kaniko-cosign-verify-local.sh
- appstudio-utils/util-scripts/tekton-chains/kaniko-cosign-verify-task.sh
- appstudio-utils/util-scripts/tekton-chains/rekor-verify-taskrun.sh
* Adds the rekor-cli to the appstudio-utils image
*  Moving chains utility scripts from infra-deployments to the appstudio-utils image
> utility scripts and binaries to test tekton-chains

- appstudio-utils/util-scripts/image-exists.sh
- tasks/sanity-label-check.yaml
By default, `skopeo inspect` will fetch a list of all the tags in the
repository. This can be an expensive operation if the repository has a
large amount of tags. A registry may paginate the results causing skopeo
to trigger an unbounded amount of queries to the registry.
Use the `--no-tags` parameter to avoid fetching the tags altogether
since they're not used.
> Avoid performance issues when inspecting repo

- .tekton/pull-request.yaml
- .tekton/push.yaml
This PR moves the CI previously defined in the [infra-deployments](https://github.com/redhat-appstudio/infra-deployments/blob/fd658a632b1c4cce67eaaafa6becc26260017ac9/components/build/.tekton/trigger-template.yaml) repository to this repository, while also adapting it to be run on top of Pipelines as Code.
> Add Pipelines as Code CI

- appstudio-utils/Dockerfile
* OPA cli tool: Used for for validating rego policies such
as the ones that will be used by the Enterprise Contract to
validate pipeline runs. Also verifies the checksum because
it seems like a good idea.
* Newer jq: Install it directly rather than with dnf. I was hitting
a weird jq problem when running the contract fetch scripts (see
upcoming commits) in the container and it went away when I
upgraded to jq-1.6. The dnf installed version was jq-1.5.
* Git: I want to use git to checkout rego policy files.
See also:
- https://github.com/open-policy-agent/opa/releases
- https://www.openpolicyagent.org/
- https://issues.redhat.com/browse/HACBS-233
- https://issues.redhat.com/browse/HACBS-235
> Add extra tools to utils image for contract

- appstudio-utils/util-scripts/lib/fetch/rekor.sh
This commit uses perl to parse a given URL and extract the desired
data in the log_index_from_url and rekor_host_from_url functions in the
rekor.sh script.
Signed-off-by: Rob Nester <rnester@redhat.com>
> HACBS-306: Better URL parsing in rekor fetch

- appstudio-utils/util-scripts/verify-attestation-with-policy.sh
- hack/build-and-push.sh
- hack/start-verify-ec-task.sh
- tasks/verify-enterprise-contract.yaml
Notable differences from the existing enterprise-contract.yaml task:
* The only data being validated is the image attestation. No data
data is fetched from the cluster.
* No support for inline public key. The parameter PUBLIC_KEY is used
as is. I didn't want to wrap cosign in a bash script just to support
this. Realistically, the key is going to be stored in the cluster
anyways, just use that. Do note that the Secret for the key does not
have to be the same one used by Chains. In fact, users of this
task are expected to create their own Secret containing just the
cosign.pub key in their own namespaces.
* The whole enterprise contract is verified by this task. This is the
same approach used by the existing enterprise-contract.yaml task,
but differs from the cosign-verify*.yaml tasks. …
> Add new task verify-enterprise-contract

- appstudio-utils/util-scripts/lib/fetch/cluster.sh
- test/fetch-ec-data_spec.sh
For the policy configuration, namely specifying what rules are
non-blocking we can now provide a ConfigMap named `ec-policy` in the
namespace the task is running in. From the ConfigMap a key with the name
`policy.json` needs to hold the JSON file with the policy configuration.
If the ConfigMap doesn't exist the current fixed value is used as a
fallback.
This will most likely be replaced with a EnterpriseContractPolicy custom
resource in the future.
Ref. https://issues.redhat.com/browse/HACBS-244
> Fetch policy configuration from ConfigMap

- appstudio-utils/util-scripts/fetch-test-data.sh
- appstudio-utils/util-scripts/lib/fetch.sh
If the pipeline run is missing or doesn't have the expected test
results, we get the following error and the task fails:
find: '/shared/ec-work-dir/data': No such file or directory
Actually `mkdir -p $DATA_DIR` alone would be enough to avoid the
error, but I thought it would be nice to write something to the data
dir.
JIRA: [HACBS-377](https://issues.redhat.com/browse/HACBS-377)
> Don't fail immediately if hacbs test results are missing

- hack/build-and-push.sh
- hack/test-build.sh
- hack/test-builds.sh
- pipelines/hacbs-core-service/csi-secret.yaml
- pipelines/hacbs-core-service/kustomization.yaml
- tasks/configure-build-csi-secret.yaml
- tasks/kustomization.yaml
Used in hacbs-core-service bundle to use shared secret for pushing into quay.io/redhat-appstudio/*
Dependency on https://github.com/redhat-appstudio/infra-deployments/pull/330
> Add configure-build-csi-secret to get sharedSecret

- pipelines/base/template-build/template-build.yaml
Without type it seems to default to `[]string` which leads to pipeline failing with:
```
Pipeline demo/nodejs-builder can't be Run; it has an invalid spec: "" type does not match default value's type: "string": finally.params[rebuild].default.type, finally.params[rebuild].type, tasks.params[rebuild].default.type, tasks.params[rebuild].type
invalid value: : finally.params[rebuild].type, tasks.params[rebuild].type
```
This sets the type to `string`.
This is how it the default value is interpreted without the type set:
```
$ tkn pipeline describe nodejs-builder
Name:        nodejs-builder
Namespace:   demo
⚓ Params
NAME             TYPE     DESCRIPTION              DEFAULT VALUE
∙ git-url        string   Source Repository U...   ---
∙ revision       string   Revision of the Sou...   main
∙ …
```
> Set type for the `rebuild` parameter

- appstudio-utils/util-scripts/lib/fetch/tekton.sh
It is entirely possible that the same task is used within the pipeline multiple times. For that reason we can't rely on the Task name from the definition of the task, but rather the name of the task in the Pipeline.
Ref. https://issues.redhat.com/browse/HACBS-414
> Use pipeline task name instead of task name

- tasks/hacbs-test-evaluation.yaml
- tasks/sanity-label-check.yaml
* Avoid overwriting task results by using different workingDir
* Add optional label check to hacbs-test-evaluation
> Add policy namespace to sanity label task workingDir

- appstudio-utils/Dockerfile
This commit updates the following tools to the specified versions:
- cosign updated to v1.8.0
- yq updated to v4.25.1
- opa updated to v0.40.0
Signed-off-by: Rob Nester <rnester@redhat.com>
> Update tool versions

- .tekton/push.yaml
- tasks/update-infra-deployments.yaml
Instead of creating a secret in each service namespace, a shared secret is defined. (https://github.com/redhat-appstudio/infra-deployments/pull/350)
this PR adds the shared secret config to update-infra-deployments task, which can be used to update infra-deployments.
> PLNSRVCE-255 - sharedSecret for infra-deployments update

- pipelines/base/template-build/template-build.yaml
In order to attest PipelineRuns, we are working towards a change in
Chains. The likely mechanism to determine which image needs the
attestation should be assocaited with is by producing the type hinting
results on the PipelineRun itself, instead of the TaskRun. Although this
mechanism is pending approval, making this change in the Pipeline
definitions now allows us to more easily experiment with it.
> Produce results for the build pipelines

- .tekton/pull-request.yaml
- README.md
- hack/build-and-push.sh
- hack/util-install-bundle.sh
https://issues.redhat.com/browse/PLNSRVCE-149
* updated PR pipeline to build & push bundles to `pull-request-builds` repo
* after bundles are pushed, configmap `build-pipelines-defaults` is updated to point to the pipeline bundle that was built
* E2E tests are triggered - pipeline used in E2E test should be extracted from the pipeline bundle ^
> PR E2E test

- test/fetch-test-data_spec.sh
I was getting this error locally with shellspec 0.28.1:
Unknown word 'exist' after should not verb
> Fix "Unknown word 'exist'" shellspec failure

- tasks/get-clair-scan.yaml
Since clair scan could take from 10 minutes to +5 hours then it does not
make sense to block pipelineRun by 5 minutes.
> Clair - do not wait for scan result

- pipelines/hacbs/hacbs-test.yaml
- tasks/hacbs-test-evaluation.yaml
- tasks/kustomization.yaml
- tasks/sast-go.yaml
- Test on a Go app: `./hack/test-build.sh https://github.com/redhat-appstudio/application-service docker-build`
- Test on a non-Go app: `./hack/test-build.sh https://github.com/jduimovich/single-container-app docker-build`
Both should pass, but `HACBS_TEST_OUTPUT` should only contain data for the Go app
> HACBS-223: Add task to run gosec

- tasks/update-infra-deployments.yaml
Update the infra-deployments script to allow all members of redhat-appstudio/infra-deployments with at least Write permission to update the PR created by appstudio-staging-ci.
> Update infra-deployments script

- pipelines/base/template-build/template-build.yaml
When Tekton Chains attests a PipelineRun, it looks for the presence of
either results, or parameters, named CHAINS-GIT_URL and
CHAINS-GIT_COMMIT. If found, this information is then propagated to the
.predicate.materials section of the SLSA Provenance attestation.
This commit makes the build pipelines produce this information in their
results. Although using parameters is also a possibility, it has a
stronger impact on the pipeline usability since users would have to
specify a different parameter for the git url and commit.
> Produce materials for the build pipelines

- pipelines/hacbs/hacbs-test.yaml
Running sast-java in paralel with build-container is causing race
condition which ends up in 'Permission denied'.
Details:
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project hacbs-classfile-tracker: Error while storing the mojo status: /work/classfile-tracker/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst (Permission denied) -> [Help 1]`
Based on [this thread](https://social.msdn.microsoft.com/Forums/vstudio/en-US/571135c6-7567-4606-94ba-1f48765ac4a9/error-while-storing-the-mojo-status-inputfileslst-access-is-denied?forum=tee) it is happening when there is `target` folder (in this case created by sast-java)
> sast-java: run after container is built

- tasks/buildah.yaml
During the merging of the generated SBOMs for a build, all identified components are sorted by name and version. But we found some specific scenarios (e.g. Golang builds) in which a component is reported without a version.
This fix will allow the merging to handle components even if the version information is missing.
> Fix build error when an SBOM component does not have a version

- tasks/sast-go.yaml
Building of jvm-build-service is failing on sast-go on OOMKilled.
> sast-go: increase memory limit to 4GB

- .tekton/pull-request.yaml
When pipelinerun fails on yamllint then the image for e2e-cleanup is not
created.
> e2e: use stable image for cleanup

- hack/build-and-push.sh
Provide newest tekton pipelines bundle under latest tag. First users can
consume directly newest pipelines.
> Build hacbs-templates-bundle:latest for first hacbs customers

- tasks/sast-go.yaml
4Gi is not enough to build KCP.
For container building 2Gi is enough but for building project like kcp we need more than 4 GB.
> sast-go: increase memory limit to 8Gi

- hack/verify_pipeline.sh
This commit adds a bash script that can be utilized to validate the
conformity of a given pipline json file to the enterprise-contract
policy.
Signed-off-by: Rob Nester <rnester@redhat.com>
> HACBS-375 Verify pipeline with policy

- hack/verify-pipeline.sh
There's a rego bug in ec-policies that means the future policy
violations are not handled correctly if data.config is missing
entirely.
This is a quick workaround for the demo. Hopefully the rego bug will
be fixed later properly and the workaround won't be needed.
> Tweak verify-pipeline so future violations work

- appstudio-utils/util-scripts/lib/fetch/cluster.sh
This fixes the e2e tests by allowing the fallback to be used if an ECP name was provided but does not exist which is now the case since `POLICY_CONFIGURATION` has a default value and is actually used in the bash scripts.
> Fix fallback when missing ECP resource

- pipelines/hacbs/hacbs-test.yaml
- tasks/kustomization.yaml
- tasks/sanity-inspect-image.yaml
- Checks the base image using `org.opencontainers.image.source`
- Add the check to `hacbs-test` pipeline
> [HACBS-426]: Integrate the deprecated base image check

- .tekton/pull-request.yaml
A follow-up on https://github.com/redhat-appstudio/e2e-tests/pull/105
Some new test specs (irrelevant to e2e build-definitions tests) were introduced to a build-service test suite that cannot be easily filtered out via `--ginkgo.focus` flag.
Using label filters is an elegant way to do it.
> fix: filter e2e tests to run using labels

- pipelines/base/template-build/template-build.yaml
- tasks/buildah.yaml
- tasks/s2i-java.yaml
Modifications:
- Do not force main branch, use repository default
- Increase opened files limit
- Increase memory for the build
Test:
./hack/test-build.sh https://github.com/Michkov/apicurio-registry java-builder
Only modification of the repo in fork is .s2i folder
> Improvements to allow build apicurio-registry

- tasks/sast-go.yaml
Gosec could return different return code than 0 which aborts
pipelinerun. Before there was 'tee' command used which hide this
problem.
> sast-go: ignore return code of gosec

- tasks/patches/add-sbom-and-push.yaml
Since we are injecting sbom files the base image annotation is changed
to new image. Overriding with the original value.
> Use original base image in annotation

- tasks/sast-java-sec-check.yaml
The SAST java check is failing with an OutOfMemory error for https://github.com/stuartwdouglas/code-with-quarkus
See more in the Slack conversation at https://coreos.slack.com/archives/C030SGP2VB9/p1657832614510839
> sast-java-sec-check: increase memory limit to 4Gi

- tasks/sast-java-sec-check.yaml
Follow up on https://coreos.slack.com/archives/C030SGP2VB9/p1657832614510839
> sast-java-sec-check: increase memory limit to 8Gi

- tasks/verify-enterprise-contract.yaml
This disables Rekor transparency log validation and Fulcio CA support
by setting the default value of `COSIGN_EXPERIMENTAL` to `0`, instead of
previous `1` - meaning enabled by default.
Seems that there was a change in how TUF is deployed at Sigstore so the
call to fetch the Fulcio CA certificate done by the code to verify
against the transparency log now results in a panic:
```
panic: error getting targets
goroutine 1 [running]:
github.com/sigstore/cosign/cmd/cosign/cli/fulcio/fulcioroots.Get.func1()
github.com/sigstore/cosign@v1.8.0/cmd/cosign/cli/fulcio/fulcioroots/fulcioroots.go:68 +0x74
sync.(*Once).doSlow(0xc00021be40, 0x1c)
sync/once.go:68 +0xd2
sync.(*Once).Do(...)
sync/once.go:59
github.com/sigstore/cosign/cmd/cosign/cli/fulcio/fulcioroots.Get() …
```
> Disable Cosign experimental features by default

- hack/start-verify-ec-task-v2.sh
- tasks/verify-enterprise-contract-v2.yaml
This change ensures the policy report is always displayed, regardless of its status.
It also fixes the STRICT parameter so it can be disabled.
https://issues.redhat.com/browse/HACBS-881
https://issues.redhat.com/browse/HACBS-882
> verify-ec-v2: fix display and strict

- pipelines/hacbs/e2e-ec.yaml
This was forgotten in #170, now the Pipeline used in the end to end
tests also disables Cosign experimental features by default.
> Disable Rekor lookup in e2e-ec Pipeline

- tasks/patches/add-sbom-and-push.yaml
This PR updates the `merge-sbom` step to generate a simple JSON that contains how many Java components were identified in the SBOM for each publisher, e.g.:
```
{
"central": 22,
"rebuilt": 3,
"gradle": 1
}
```
The goal is to make it simple to identify if a pipeline used community packages or not.
> PLNSRVCE-451: Adds Tekton result with couting of SBOM Java dependencies

- .tekton/push.yaml
- hack/build-and-push.sh
Changed hack/build-and-push.sh to record the Tekton bundles that it
produces. Then, use that output to call the "ec track" command.
This handles the case where the number of bundles changes unexpectedly.
> Dynamically determine built bundles

- appstudio-utils/util-scripts/lib/fetch/cluster.sh
- test/fetch-test-data_spec.sh
When the EnterpriseContractPolicy custom resource has `nonBlocking` key
at all the result of piping an empty string to `jq` renders empty string
and the `config.json` ends up being empty file.
This makes sure that in that case the `config.json` doesn't end up being
empty by setting `non_blocking_data` to `[]` when fetching the
configuration from the cluster.
> Fix fetching policy configuration

- pipelines/hacbs/e2e-ec.yaml
For `verify-enterprise-task` we need to pass `"1"` as `STRICT_POLICY`
PipelineRun parameter, and for `verify-enterprise-task-v2` we need to
pass `"true"` as `STRICT` PipelineRun parameter, for the enforcement to
be strict.
Likewise we can pass anything but `"1"` to as `STRICT_POLICY`, and
almost anything but `"true"` for `STRICT` parameter for the enforcement
not to be strict.
This makes it difficult to have a single PipelineRun parameter, so this
introduces a second parameter to cater to the V2 task.
Ref. https://issues.redhat.com/browse/HACBS-762
> Fix passing of `STRICT` parameter to VEC V2

- tasks/verify-enterprise-contract-v2.yaml
As recommended by https://access.redhat.com/solutions/6956010
This allows running the verify-enterprise-contract-v2 task with the
"restricted" scc (SecurityContextConstraint). This is the scc assigned
to ServiceAccounts by default, inluding the "default" ServiceAccount.
Since the release pipeline executes with a custom ServiceAccount, this
makes it easier to use the task in that environment.
https://issues.redhat.com/browse/HACBS-880
> Set HOME for verify-ec2 task

- tasks/patches/add-sbom-and-push.yaml
Same rationale as https://github.com/redhat-appstudio/jvm-build-service/pull/154
So yeah in production k8s clusters, the general convention is to not use Always for the image pull policy. That policy best serves inner loop development.
And sure enough, "stress testing", i.e. building service registry, I did instances of
`Failed to pull image .... pull QPS exceeded`
So a low hanging fruit improvement.
> PLNSRVCE-534: have sidecar image pull policy conform with production grade k8s conventions

- tasks/patches/add-sbom-and-push.yaml
had some good exchange with @fgiloux in https://coreos.slack.com/archives/C032EJ007C0/p1659512174591189
I think the consistent approach, given if not present is default, all are image refs are sha specific, and as the other steps in general for app studio do not set image pull policy, is just to remove the setting here.
I will be making a similar update in jvm-build-service as well
> PLNSRVCE-534: depend on IfNotPresent being default (consistent with other steps) and use of specific sha's

- tasks/clamav-scan.yaml
There is currently issue with attestation images causing errors during **oc image extract** command:
`error: unable to extract layer sha256:570dc024d08eb5044a0c29d41d4f777931b910ce30080b583e4aabdbc0eb43ff from quay.io/redhat-appstudio/user-workload:sha256-96aad71edef114ed6486116a66d9e2e1f6e469ca0f6e156ec0b062b3c98922a0.att: archive/tar: invalid tar header`
This change will be rolled-back after the attestation images are fixed.
In case of attestation image both clamav and parsing is skipped (exit 0)
> [HACBS-959]-skip clamav scan for attestation images

- tasks/patches/add-sbom-and-push.yaml
If I see it correctly we have not bumped the analyzer and sidecar in the bundle in 22 days since https://github.com/redhat-appstudio/build-definitions/pull/159
@psturc I've tagged this into PLNSRVCE-533 because I think you are going to need various fixes in these images when you test using a component that leverages the bundle.  In particluar, there were discussion in jvm build service PRs which indicated you would need https://github.com/redhat-appstudio/jvm-build-service/pull/155
I should also note though that as I open this PR @Michkov @stuartwdouglas https://github.com/redhat-appstudio/infra-deployments/pull/558 has not caught up yet and does not include the 27a8ba29a84a23b829afd7daee5f9ed91c802a02 from PR 155.  It is only up to PR 154 and commit …
> PLNSRVCE-533: bump jvm analyzer/sidecar with recent features/fixes

- tasks/clamav-scan.yaml
This prevents running clamscan on images that were unable to extract.
> feat[HACBS-959]-catch oc image extract output

- pipelines/hacbs/hacbs-java-builds.yaml
- pipelines/hacbs/kustomization.yaml
- tasks/init.yaml
- Ensure that jvm-build-config is created so cache service is deployed and can be used
- Ensure redhat-appstudio-registry-pull-secret is created so the build task will not be blocked in PaC workflow
> Create jvm build config and default secret for pull

- tasks/conftest-clair.yaml
- tasks/deprecated-image-check.yaml
- tasks/sanity-label-check.yaml
- tasks/sast-go.yaml
- tasks/sast-snyk-check.yaml
Tekton **result** capabilities are not sufficient for our use cases. We needed to avoid duplicities in gosec log.
> fix[HACBS-951]-result size limit

- tasks/sast-java-sec-check.yaml
* Fix the missing backlash
* Output the sast output to task log
> fix(HACBS-1002): Missing backslash and output in Java sast jq

- pipelines/hacbs/hacbs-test.yaml
- tasks/get-clair-scan.yaml
Adding solution to run clair scan on demand on customers image.
Runtimes on local crc:
**get-clair-db** : 1m 27s
**get-clair-results** : 1m 41s
example output of conftest-clair step:
```
STEP-CONFTEST-VULNERABILITIES
[
{
"filename": "/workspace/conftest-ws/clair-result.json",
"namespace": "required_checks",
"successes": 0,
"failures": [
{
"msg": "Found packages with critical vulnerabilities: binutils, binutils-common, binutils-x86-64-linux-gnu, curl, libaom0, libbinutils, libc-bin, libc-dev-bin, libc6, libc6-dev, libctf-nobfd0, libctf0, libcurl3-gnutls, libcurl4, libcurl4-openssl-dev, libdb5.3, libdb5.3-dev, libde265-0, libfreetype-dev, libfreetype6, libfreetype6-dev, libopenjp2-7, libopenjp2-7-dev, libpcre2-16-0, libpcre2-32-0, libpcre2-8-0, libpcre2-dev, libpcre2-posix2, …
```
> [HACBS-723] use clair-in-ci for getting image vulns

- tasks/buildah.yaml
- tasks/s2i-java.yaml
- tasks/s2i-nodejs.yaml
Buildah started to require full image names which breaks current image
builds.
Setting short-name-mode to disabled -> Use all unqualified-search registries without prompting.
> Automatically resolve short-names

- tasks/patches/add-sbom-and-push.yaml
- tasks/s2i-java.yaml
continuing running on 4.11 effort that @Michkov started recently (where he alerted me there were some items wrt java that still needed to be handled)
in testing on a 4.11 OCP cluster with boostrapped appstudio, I saw these problems when running @psturc new  component based e2e
```
[build-container : build] Error: error writing "0 0 4294967295\n" to /proc/23/uid_map: write /proc/23/uid_map: operation not permitted
[build-container : build] time="2022-08-23T00:24:44Z" level=error msg="error writing \"0 0 4294967295\\n\" to /proc/23/uid_map: write /proc/23/uid_map: operation not permitted"
[build-container : build] time="2022-08-23T00:24:44Z" level=error msg="(Unable to determine exit status)"
[build-container : inject-sbom-and-push] writing blob: initiating layer upload to …
```
> additional jvm related steps need runasuser 0 on 4.11

- pipelines/base/enterprise-contract.yaml
- pipelines/base/kustomization.yaml
- pipelines/hacbs/e2e-ec.yaml
- tasks/verify-enterprise-contract-v2.yaml
This pipeline is meant to be used by the integration controller to
provider faster feedback to users.
https://issues.redhat.com/browse/HACBS-1005
> feat: Add new enterprise-contract pipeline

- .tekton/pull-request.yaml
Recently I added a [health check](https://github.com/redhat-appstudio/e2e-tests/blob/dc56817d608a1a04cf0b98d2a66fc510e3e5b7b3/pkg/utils/has/controller.go#L68) to all e2e tests to make sure the component creation in the test doesn't start before the gitops resources for application CR are in place.
That change uncovered a bug hidden in the e2e task in this PR template: e2e tests were using a default github org for the health check, which should have been overridden by an env var in the build-definitions PR template. This PR fixes it.
> fix: e2e: use GITHUB_TOKEN

- tasks/patches/add-sbom-and-push.yaml
This config is only needed when doing dependency rebuilds, which don't
use this pipeline.
> Remove unneeded config from the sidecar

- tasks/patches/add-sbom-and-push.yaml
We are seeing intermittent failures in our image builds caused by sidecar memory issues. This temporarily raises the limit to avoid this and allow our images to complete.
I am going to investigate a sidecar-less design that just delegates all of the sidecars current responsibilities to the cache.
> Temporarily raise the sidecar memory limits

- appstudio-utils/Dockerfile
- hack/build-and-push.sh
For ease of consumption in development folk would like to utilize the newest versions of the pipeline bundle images with a fixed tag: `devel`.
This re-taggs the pipeline bundle images with the `devel` if `SKIP_DEVEL_TAG` environment variable is not empty and image push is directed to `redhat-appstudio` organization.
Fixes https://issues.redhat.com/browse/HACBS-1088
> Tag newest pipeline bundle images with `devel`

- tasks/update-infra-deployments.yaml
Change image for SCRIPT execution to ose-cli which provides oc and kubectl commands.
> Infra-deployment-updater: custom image for script

- hack/build-and-push.sh
The hacbs-templates-bundle contains the Tekton pipelines used for HACBS. This is what should be tracked in order to verify definitions via the Enterprise Contract.
https://issues.redhat.com/browse/HACBS-1224
> Track hacbs bundle instead of plain build bundle

- pipelines/hacbs/hacbs-test.yaml
We have made the decision to disable the SAST tasks (gosec and findsecbugs) temporarily becayse of infrastructure requirements. We will look into relying more on the Snyk task for the SAST functionality for the time being.
* Disable the sast-java-sec-check task in HACBS pipeline
* Disable the sast-go task in HACBS pipeline
> feat[HACBS-1072]: disable java and go SAST tasks

- .tekton/pull-request.yaml
follow-up on https://github.com/redhat-appstudio/e2e-tests/pull/219/files
https://quay.io/repository/redhat-appstudio/e2e-tests?tab=tags
> fix: e2e: use pre-kcp image tag

- .tekton/push.yaml
To avoid breaking change use docker-build pipeline in infra-deployments, it should be replaced by flexible solution in future.
> Set docker-build pipeline as default in infra-deployments

- hack/build-and-push.sh
`tkn bundle push' runs as the first command in the shell pipeline to push task and pipeline bundles. A few reason may fail the command and no bundle image information is got from the registry. So, fail the push pipeline immediately when something is wrong with the push operation.
> Set pipefail for build-and-push.sh

- pipelines/docker-build/patch.yaml
- pipelines/java-builder/patch.yaml
Previously, the patch was overwriting the results from the template-build pipeline. This change makes it so results are appended to the list of existing results.
Before this change:
```
🐚 oc kustomize pipelines | yq -P .spec.results
- name: JAVA_COMMUNITY_DEPENDENCIES
value: $(tasks.build-container.results.JAVA_COMMUNITY_DEPENDENCIES)
---
null
---
- name: REPORT
value: $(tasks.verify.results.REPORT)
---
- name: JAVA_COMMUNITY_DEPENDENCIES
value: $(tasks.build-container.results.JAVA_COMMUNITY_DEPENDENCIES)
---
- name: IMAGE_URL
value: $(tasks.build-container.results.IMAGE_URL)
- name: IMAGE_DIGEST
value: $(tasks.build-container.results.IMAGE_DIGEST)
- name: CHAINS-GIT_URL
value: $(tasks.clone-repository.results.url)
- name: CHAINS-GIT_COMMIT
value: $(tasks.clone-repository.results.commit) …
```
> Fix missing chains results

- task/buildah/0.1/buildah.yaml
- task/s2i-java/0.1/s2i-java.yaml
- task/s2i-nodejs/0.1/s2i-nodejs.yaml
I meet error as below in `sbom-json-check` task
```
failed to create task run pod "nodejs-builder-run-krzcv-sbom-json-check": Pod "nodejs-builder-run-krzcv-sbom-json-check-pod" is invalid: spec.containers[1].image: Invalid value: "quay.io/hongweiliu/single-nodejs-app:f623a43\n": must not have leading or trailing whitespace. Maybe missing or invalid Task default/sbom-json-check
```
This pr is to remove the  `\n` in `results.IMAGE_URL`.
> fix: remove \n from image_url generated by build job

- task/buildah/0.1/buildah.yaml
$(params.CONTEXT)/$(params.DOCKERFILE) can cover most cases that build context is current directory ".". However, it can't cover a special case that a context directory is different. For example, ./app is the build context directory, and ./dockerfiles/Dockerfile-app is the Dockerfile or even ./app/Dockerfile, that will cause the result of $(params.CONTEXT)/$(params.DOCKERFILE) is invalid.
> Fix Dockerfile resolve

- .tekton/push.yaml
- task/update-infra-deployments/0.1/update-infra-deployments.yaml
Since the task and pipeline bundle are built and pushed per one respectively, the task-bundle-list and pipeline-bundle-list may exceed the limit size of tekton task result.
> Pass task and pipeline bundles list via workspace

- .tekton/pull-request.yaml
- .tekton/push.yaml
- hack/build-and-push.sh
Tag tasks with last github git commit id which modified the file so they are persisted after update.
> Persist old sha256 of images which were overriden

- .tekton/pull-request.yaml
- pipelines/kustomization.yaml
Follow-up on https://github.com/redhat-appstudio/build-definitions/pull/242
Fixes an error seen in CI
```
Error: accumulating resources: accumulation err='accumulating resources from 'e2e-ec.yaml': evalsymlink failure on '/workspace/source/pipelines/e2e-ec.yaml' : lstat /workspace/source/pipelines/e2e-ec.yaml: no such file or directory': evalsymlink failure on '/workspace/source/pipelines/e2e-ec.yaml' : lstat /workspace/source/pipelines/e2e-ec.yaml: no such file or directory
```
> fix: CI: remove reference to e2e-ec pipeline

- pipelines/docker-build/patch.yaml
- pipelines/java-builder/patch.yaml
- pipelines/nodejs-builder/patch.yaml
- pipelines/template-build/template-build.yaml
- task/buildah/0.1/buildah.yaml
- task/git-clone/0.1/git-clone.yaml
- task/prefetch-dependencies/0.1/prefetch-dependencies.yaml
- task/prefetch-dependencies/OWNERS
Initital integration of Cachi2 into the pipelines to prefetch gomod dependencies and build the image with network isolation.
When a [cachi2-params](https://github.com/brunoapimentel/retrodep/commit/7e3edd8a0bcbf345e76ffc950ededa3c1b482282) file is found in the root of the target Git repository, the pipelineRun will:
- Execute the prefetch-dependencies task
- Apply the network isolation during the execution of `buildah bud` in the buildah task
- Mount the prefetched content at `/cachi2` during the execution of `buildah bud` in the buildah task
If the file is not present in the repository, the prefetch task will be skipped and the buildah bud command won't have the above mentioned changes.
In order to point the `go build` command to use the prefetched content, the Dockerfile needs to be …
> Add a prefetch step to the docker-container pipeline

- pipelines/template-build/template-build.yaml
- task/git-clone/0.1/git-clone.yaml
- task/sanity-inspect-image/0.1/sanity-inspect-image.yaml
[Make sure hermetic-build result is produced](https://github.com/redhat-appstudio/build-definitions/commit/dd729340099ee5440bc05f3a95d6a9088bd9f465)
If the Tekton Task result is not produced any when expression using that result will evaluate to `false`. The `hermetic-build` result of the `git-clone` Task would be set to `true` if and only if the `cachi2.params` exists in the workspace, if the file does not exist it will not be set.
The current default is that a when expression evaluating to false skips the task where the when expression is defined, but also all tasks that `runAfter` it. See[1],`scope-when-expressions-to-task` feature flag[2] and TEP-0059[3].
Without the `cachi2.params` file in the workspace, the when condition on the `prefetch-dependencies` would evaluate to false, and …
> Fix the build pipeline

- task/sanity-inspect-image/0.1/sanity-inspect-image.yaml
In `sanity-inspect-image` the `BASE_IMAGE` and `BASE_IMAGE_REPOSITORY` result is set and later on used in the `deprecated-image-check`.
Currently it contains a trailing newline. The trailing newline ends up being passed literally to `curl` used in the `deprecated-image-check` as the URL is quoted there. This leads to curl failing with status `000`.
The `deprecated-image-check` Task doesn't fail, but the `HACBS_TEST_OUTPUT` results in an error.
No matter how hard I tried see where the issue was and where the newline was emitted from for the `BASE_IMAGE_REPOSITORY` result, i.e. was it from jq, cut or tee, it seemed to originate from none of those. That's why I ended up rewriting that in a single jq invocation and analogous to `BASE_IMAGE` passed via variable and echo to tee. Seems to have …
> Remove trailing newline from BASE_IMAGE* results

- pipelines/template-build/template-build.yaml
This removes the resource dependency on the `build-container` task from the `show-summary` task. This way the `show-summary` task will be run regardless of the `build-container` task running, i.e. always.
Note that the resource dependency on the `clone-repository` task remains. Since `clone-repository` task will not be skipped, like the `build-container` task might, this is not an issue.
> Run the show-summary task always

- appstudio-utils/Dockerfile
'ec' command is not working on ubi8
> HACBS-1501: Bump ubi version of appstudio-utils

- task/prefetch-dependencies/0.1/prefetch-dependencies.yaml
The currently used cachi2 image has a bug ([cachi2#45](https://github.com/containerbuildsystem/cachi2/pull/45)) where it will never generate any environment variables for the build. That means the GOMODCACHE environment variable won't be set => the build will not use the pre-fetched dependencies and will instead (try to) download them again.
Update to a fixed version.
> Update cachi2 image to fix env vars used for build

- task/init/0.1/init.yaml
When multiple pipelineRuns are created at the same time it could happen that the secret will be created by another PipelineRun.
> init: Allow to fail creation of secret

- task/clamav-scan/0.1/clamav-scan.yaml
Skip check when the file does not exist.
> fix: clamav-scan - missing result file

- pipelines/fbc-builder/patch.yaml
- task/fbc-validation/0.1/fbc-validation.yaml
- task/fbc-validation/OWNERS
Signed-off-by: Jiri Sztuka <jsztuka@ovpn-194-168.brq.redhat.com>
This PR can be pushed only after https://github.com/redhat-appstudio/build-definitions/pull/249
Task is doing following:
- Checks existence of label: **operators.operatorframework.io.index.configs.v1** within a tested image
- Extracts binaries (opm, grpc_health_probe) together with configs folder found in previous step
- Checks binaries (opm version, existence of grpc_health_probe)
- Runs **opm validate** on configs folder
- Return report accordingly
> feat(HACBS-1423): add FBC validation task

- hack/util-install-bundle.sh
Since we've started using [build pipeline selector](https://github.com/redhat-appstudio/build-service/pull/84) instead of build-pipelines configmap, we need to update the logic in the pull request pipeline to install the custom build pipeline selector to `build-templates-e2e` namespace, where PR e2e tests are running.
Thanks to this we will be able to test changes to this repo per PR (again).
> fix: overriding pipeline bundle used in e2e

- .tekton/pull-request.yaml
the env var name for github org used for creating an application repo [has changed recently](https://github.com/redhat-appstudio/e2e-tests/blame/3148530edcd1b80f604490344d9852b18971ecf9/pkg/constants/constants.go#L9)
> fix: e2e: update github org env var

- task/git-clone/0.1/git-clone.yaml
Currently, other tasks in the pipeline assume that the source was cloned as root. Make sure the step will indeed run as root even if the default USER in the git-init image is non-root.
Otherwise, for example the prefetch-dependencies task (which runs as root) may fail to fetch git tags when processing Go modules:
cmdline: git fetch -v --force --tags origin
stderr: 'fatal: detected dubious ownership in repository at '/workspace/source''
> Run the git-clone task as root

- task/init/0.1/init.yaml
- task/summary/0.1/summary.yaml
- appstudio.redhat.com/updateComponentOnSuccess is not used now PLNSRVCE-982
- updated annotation with --overwrite
> PLNSRVCE-995: fix annotations for re-run

- task/clair-scan/0.1/clair-scan.yaml
As Title clarifies, preventing both clair steps from failing.
> fix(STONE-355): clair-scan must not fail the pipelinerun

- hack/test-build.sh
- pipelines/prototypes/noop.yaml
- pipelines/prototypes/prototype-build-compliance.yaml
- pipelines/template-build/template-build.yaml
- task/clair-scan/0.1/clair-scan.yaml
- task/clamav-scan/0.1/clamav-scan.yaml
- task/configure-build/0.1/configure-build.yaml
- task/init/0.1/init.yaml
Registry auth removal since the secrets should be linked to service account to be possible to use them by chains.
Updated secret merge logic to use tekton feature which creates ~/.docker/config.json file based on secrets attached to ServiceAccount  (which was done manually).
https://tekton.dev/vault/pipelines-v0.15.2/auth/#kubernetess-docker-registrys-secret
> PLNSRVCE-968: Remove registry-auth

- pipelines/docker-build/patch.yaml
- pipelines/template-build/template-build.yaml
- task/buildah/0.1/buildah.yaml
- task/git-clone/0.1/git-clone.yaml
- task/prefetch-dependencies/0.1/prefetch-dependencies.yaml
With the current integration, Cachi2 was limited to Go repositories that had the main module defined in the root of the repository. It was also dependent on the existence of a cachi2.params file that lived in the root of the repository.
Considering the addition of new package manager support to Cachi2 and the discouraging of having additional configuration files in the user's repository, this PR improves the current integration so that:
- The user can pass all configuration needed to Cachi2 using the `prefetch-input` pipeline parameter
- The preftech step no longer relies on the existence of a cachi2.params file
- The user can configure the network isolation using the `hermetic` parameter
```
tkn pipeline start docker-build \
-w name=workspace,volumeClaimTemplateFile=workspace-template.yam …
```
> Fully integrate Cachi2 into the build pipelines

- task/sast-snyk-check/0.1/sast-snyk-check.yaml
Fixing typo in filename "sast_snyk_check_out.json" which prevented to generate result.
Also create ERROR result before ito cover case when creating standard result fails
> fix(HACBS-1684): Fix sast_snyk_check results creation

- pipelines/fbc-builder/patch.yaml
- task/fbc-related-image-check/0.1/fbc-related-image-check.yaml
- task/fbc-related-image-check/OWNERS
- task/fbc-validation/0.1/fbc-validation.yaml
Adding related image check for FBC images:
Here is sample output:
```
Warning: the default reading order of registry auth file will be changed from "${HOME}/.docker/config.json" to podman registry config locations in the future version of oc. "${HOME}/.docker/config.json" is deprecated, but can still be used for storing credentials as a fallback. See https://github.com/containers/image/blob/main/docs/containers-auth.json.5.md for the order of podman registry config locations.
These are related images: 
gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
quay.io/joelanford/example-operator-bundle:0.1.0
quay.io/joelanford/example-operator:0.1.0
gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
quay.io/joelanford/example-operator-bundle:0.2.0
quay.io/joelanford/example-operator:0.2.0
{
"Name": …
```
> feat(HACBS-1509): Adding related image check

- task/fbc-validation/0.1/fbc-validation.yaml
We allow only one olm.package in a FBC fragment
The result is like below
```
!FAILURE! - more than one olm.packages are not permitted in a FBC fragment
{"result":"FAILURE","timestamp":"1675243411","note":"For more details please visit the logs in workspace of Tekton tasks.","namespace":"default","successes":3,"failures":1,"warnings":0}
```
> feat(HACBS-1510): add check to allow only one package in FBC fragment

- .tekton/pull-request.yaml
- .tekton/scripts/check-task-pipeline-bundle-repos.sh
- pipelines/kustomization.yaml
- pipelines/tekton-bundle-builder/kustomization.yaml
- task/tkn-bundle/0.1/.shellspec
- task/tkn-bundle/0.1/README.md
- task/tkn-bundle/0.1/TESTING.md
- task/tkn-bundle/0.1/spec/spec_helper.sh
- task/tkn-bundle/0.1/spec/support/jq_matcher.sh
- task/tkn-bundle/0.1/spec/support/task_run_subject.sh
- task/tkn-bundle/0.1/spec/test1.yaml
- task/tkn-bundle/0.1/spec/test2.yml
- task/tkn-bundle/0.1/spec/test3.yaml
- task/tkn-bundle/0.1/spec/tkn-bundle_spec.sh
- task/tkn-bundle/0.1/tkn-bundle.yaml
- task/tkn-bundle/OWNERS
This adds `tkn-bundle` Tekton Task that simply finds all *.yaml or *.yml files in the current `params.CONTEXT` directory and creates a Tekton Bundle by pushing it to `params.IMAGE`. The result of the task are `IMAGE_URL` image reference with digest (no tag) and `IMAGE_DIGEST` containing the image digest.
Also adds `tekton-bundle-builder` builder pipeline that uses the `tkn-bundle` task for the `build` step.
Tests are provided.
Ref. https://issues.redhat.com/browse/HACBS-1675
> Create Tekton task and Pipeline for Tekton bundles

- .tekton/pull-request.yaml
- .tekton/scripts/check-task-pipeline-bundle-repos.sh
During Pull-request check we should check production repositories so then we can reveal that some repository is missing before merging.
> fix: check prod repositories on pull-request

- .tekton/tasks/buildah.yaml
- hack/test-build.sh
- pipelines/docker-build/patch.yaml
- pipelines/fbc-builder/patch.yaml
- pipelines/java-builder/patch.yaml
- pipelines/nodejs-builder/patch.yaml
- task/buildah/0.1/buildah.yaml
- task/configure-build/0.1/configure-build.yaml
- task/s2i-java/0.1/s2i-java.yaml
- task/s2i-nodejs/0.1/s2i-nodejs.yaml
DOCKER_CONFIG env provides way how to globally set container registries auth - podman, buildah, docker, cosign are using it. For cosign it's only way how to configure auth. The auth file is composed in configure-build step which is taking secrets from serviceaccount and merge them with shared secret. So when shared secret will be removed we can just remove the task and use only secrets provided by serviceaccount (handled by tekton).
Instead of manual creation of sbom image use cosign to upload sbom - in future it could be function of tekton-chains. To receive the sbom `cosign download sbom $IMAGE` eg. `cosign download sbom quay.io/mkovarik/single-container-app:62c06bf`
> use DOCKER_CONFIG env for auth files and push sbom via cosign

- pipelines/tekton-bundle-builder/kustomization.yaml
- task/tkn-bundle/0.1/README.md
- task/tkn-bundle/0.1/spec/tkn-bundle_spec.sh
- task/tkn-bundle/0.1/tkn-bundle.yaml
This commit includes various small fixes that are essential for executing the tekton-bundle-builder pipeline:
1. Pass the pipeline path-context parameter to the CONTEXT parameter of the tkn-bundle task.
2. Pass the pipeline output-image parameter to the IMAGE parameter of the tkn-bundle task.
3. Remove certain tasks from the pipeline that assume the built image is binary. Tekton bundles are not.
4. Add new HOME parameter to the tkn-bundle task to avoid permission issues when mounting linked secrets. For details, see: https://access.redhat.com/solutions/6956010
5. Change the IMAGE_URL result from the tkn-bundle task to not include the digest. Other tasks, assume this value does not have a digest, and blindly add the IMAGE_DIGEST to it which creates an image reference that contains the …
> Fixes to the tekton-bundle-builder pipeline

- task/buildah/0.1/buildah.yaml
Dotnet component was failing on:
```
Unhandled exception. System.ComponentModel.Win32Exception (2):
Unable to retrieve the specified information about the process or thread.
It may have exited or may be privileged
```
Removing '-p/--pid' is fixing the problem.
> fix: avoid failing dotnet

- task/buildah/0.1/buildah.yaml
Improve sed to match 'short-name-mode = xxx' and also 'short-name-mode=xxx'
> STONEBLD-682: fix sed for new buildah image

- task/sbom-json-check/0.1/sbom-json-check.yaml
Running image as sidecar is insecure, an newly built image can contain malicious cp command. Also, image may not contain cp command at all.
Instead of mounting image content via sidecar, extract it directly via oc image extract
> fix(HACBS-1746, sbom-json-check): remove unsafe usage of sidecars

- .tekton/pull-request.yaml
- hack/util-install-bundle.sh
https://issues.redhat.com/browse/PLNSRVCE-830
* created [this repo](https://github.com/redhat-appstudio-qe/retrodep) for testing hermetic builds
* it uses [this simple test that checks network isolation](https://github.com/redhat-appstudio-qe/retrodep/blob/18f04edd59ba877f0d5a95eb894a772071c795bc/Dockerfile#L6)
* removed [deprecated ginkgo flag](https://github.com/onsi/ginkgo/blob/master/CHANGELOG.md#ginkgo-output-now-includes-a-timeline-view-of-the-spec)
> test: hermetic build

- pipelines/template-build/template-build.yaml
- task/sast-snyk-check/0.1/sast-snyk-check.yaml
* Add the snyk-secret parameter to build pipeline
* Skip the sast-snyk-check task if snyk-secret is empty
* Refactor the warning message in sast-snyk-check
> fix(HACBS-1778): Add the snyk-secret parameter

- .tekton/pull-request.yaml
- hack/util-install-bundle.sh
Use https://github.com/cachito-testing/pip-e2e-test for testing hermetic build with pip.
> STONEBLD-694: Add e2e test to verify cachi2 pip support

- pipelines/fbc-builder/patch.yaml
- task/prefetch-dependencies/0.1/prefetch-dependencies.yaml
Do not allow download external definitions in Dockerfile
> STONEBLD-31: restrict hermetic build for FBC

- .tekton/pull-request.yaml
- hack/build-and-push.sh
- hack/util-install-bundle.sh
* Added new test repo: https://github.com/redhat-appstudio-qe/fbc-sample-repo
* updated [util for installing bundle](https://github.com/redhat-appstudio/build-definitions/pull/317/files#diff-0cf40ce7cea04e5856c097541c8f9bd5b99c0e888ef7e78e43e37304ca9954b2) to support passing multiple pipeline bundles via arg (separated by a comma)
https://issues.redhat.com/browse/STONEBLD-39
> test: fbc build

- renovate.json
- task/clair-scan/0.1/clair-scan.yaml
- task/clamav-scan/0.1/clamav-scan.yaml
- task/deprecated-image-check/0.1/deprecated-image-check.yaml
- task/fbc-related-image-check/0.1/fbc-related-image-check.yaml
- task/fbc-validation/0.1/fbc-validation.yaml
- task/sanity-inspect-image/0.1/sanity-inspect-image.yaml
- task/sanity-label-check/0.1/sanity-label-check.yaml
- task/sast-snyk-check/0.1/sast-snyk-check.yaml
- task/sbom-json-check/0.1/sbom-json-check.yaml
Images should be pinned for stability
Last commit also contains configuration of renovate bot, which will be enabled after merging and do updates of images in tekton defintions
> Pin test team images

- task/fbc-validation/0.1/fbc-validation.yaml
- task/sanity-inspect-image/0.1/sanity-inspect-image.yaml
- task/sanity-label-check/0.1/sanity-label-check.yaml
* The exception in comamnd skopeo inspect should not break pipeline
* The error message in command skopeo will be logged out in task log and result HACBS_TEST_OUTPUT
> fix(HACBS-1786): handle exception in task sanity-inspect-image

- task/fbc-related-image-check/0.1/fbc-related-image-check.yaml
FBC-related image check was incorrectly setting result to **success** when catalog was not existing/ containing incorrect data. This changes fixes that issue.
> fix(HACBS-1787): report failures correctly

- task/sanity-label-check/0.1/sanity-label-check.yaml
Fix error 'line 6: [: too many arguments' in `[ ! -f ../sanity-inspect-image/image_inspect.json ] || [ -z $(cat ../sanity-inspect-image/image_inspect.json) ]`
> fix: fix syntax issue in sanity-label-check

- task/buildah/0.1/buildah.yaml
'source' command is bash build-in, so it's not working for images with sh only. '.' is more universal.
> hermetic: use . instead source

- task/clair-scan/0.1/clair-scan.yaml
* Save ERROR result to HACBS_TEST_OUTPUT only
* Add number of vulnerability critical/high/medium/low to a new result CLAIR_SCAN_RESULT
The content of CLAIR_SCAN_RESULT is like:
```
{
"vulnerabilities": {
"critical": 1,
"high": 0,
"medium": 1,
"low":0
}
```
> feat(HACBS-1670): change result format for clair scan

- task/fbc-validation/0.1/fbc-validation.yaml
Fixes vital checks for FBC fragment
- presence of opm binary
- presence of grpc_health_probe
- runs opm validate on catalog
- makes sure there is only one opm.package present
> fix(HACBS-1821): update fbc-validation to correctly validate fbc fragment

- task/buildah/0.1/buildah.yaml
- task/s2i-java/0.1/s2i-java.yaml
- task/s2i-nodejs/0.1/s2i-nodejs.yaml
UBI images are availble without authentication. This will allow renovatebot to track updates.
> chore(images): use no-auth registry for ubi images

- .tekton/pull-request.yaml
using older e2e-tests image which does not include https://github.com/redhat-appstudio/e2e-tests/blob/266c7898952a16e22471f0b928ddb3fed71ec0f8/pkg/framework/framework.go#L40
> Use older e2e-test image to fix e2e-tests issue

- task/fbc-related-image-check/0.1/fbc-related-image-check.yaml
- task/fbc-validation/0.1/fbc-validation.yaml
This will fix following errors in pipeline:
```
/tmp/image-content /workspace/workspace/hacbs/fbc-validation
Warning: the default reading order of registry auth file will be changed from "${HOME}/.docker/config.json" to podman registry config locations in the future version of oc. "${HOME}/.docker/config.json" is deprecated, but can still be used for storing credentials as a fallback. See https://github.com/containers/image/blob/main/docs/containers-auth.json.5.md for the order of podman registry config locations.
/tekton/scripts/script-0-xf56w: line 45: [: ./usr/bin/opm: unary operator expected
true
{"result":"SUCCESS","timestamp":"1677596444","note":"For more details please visit the logs in workspace of Tekton tasks.","namespace":"default","successes":4,"failures":0,"warnings":0} …
```
> fix(HACBS-1821-2):return confdir for rel-img-check

- task/buildah/0.1/buildah.yaml
- task/s2i-java/0.1/s2i-java.yaml
Fixing issue `invalid pipelineresults [JAVA_COMMUNITY_DEPENDENCIES], the referred results don't exist`
There is still issue with java pipelines with JVM build service enabled.
> STONEBLD-884: Quick fix for running on Openshift 1.9

- task/buildah/0.1/buildah.yaml
- task/s2i-java/0.1/s2i-java.yaml
The issue:  missmatched Types for these results, map[SBOM_JAVA_COMPONENTS_COUNT:[string]] Reported as SRVKP-2875, this is workaround
> STONEBLD-884: fix  missmatched Types on Openshift Pipelines 1.9

- .github/workflows/shellspec.yaml
- README.md
- hack/shellspec/github_formatter.sh
- hack/test-shellspec.sh
- task/tkn-bundle/0.1/spec/support/task_run_subject.sh
- task/tkn-bundle/0.1/spec/tkn-bundle_spec.sh
The test we have in `task/tkn-bundle/0.1/spec` is now exercised on
GitHub Actions by running `hack/test-shellspec.sh`. There is support for
GitHub reporting via annotations and incremental test runs -- i.e. skip
running change-unrelated tests.
Ref. https://issues.redhat.com/browse/HACBS-1740
> Run Shellspec tests via GitHub Actions

- .github/workflows/shellspec.yaml
- hack/test-shellspec.sh
The script no longer fetches into `main` but to a temp branch. This should fix the:
```
fatal: refusing to fetch into branch 'refs/heads/main' checked out at '/home/runner/work/build-definitions/build-definitions'
```
error.
The script now takes into account running on GitHub Actions and takes the relevant git change commit id and base from the available environment variables.
> Adapts the incremental support for GitHub

- .tekton/push.yaml
- task/update-infra-deployments/0.1/update-infra-deployments.yaml
Use new github app for updating infra-deployments.
https://github.com/apps/infra-deployments-updater
> STONEBLD-963: use infra-deployments-updater GitHub App

- renovate.json
Avoid creation of renovate dashoard which is creating issues which are synced to our Jira. PR in github is enough.
> STONEBLD-978: renovate - disable dashboard creation

- pipelines/template-build/template-build.yaml
- task/s2i-nodejs/0.1/s2i-nodejs.yaml
- task/summary/0.1/summary.yaml
Do not show generated image in summary when build-container task failed.
> STONEBLD-960: summary - do not show image if build failed

- .tekton/pull-request.yaml
https://issues.redhat.com/browse/STONEBLD-875
* updated e2e-tests to work in this repo (there were some breaking changes introduced to e2e-tests recently that caused e2e to fail, so we had to use the fixed e2e-tests image tag) ([link to related commit](https://github.com/redhat-appstudio/e2e-tests/pull/386/commits/a0f4c87fe35c3ba8ba3a315ec45359373770f23d))
* added ec-policy validation check to e2e ([link to related commit](https://github.com/redhat-appstudio/e2e-tests/pull/386/commits/10e0a0ea3369eb693bfc3fdfea538219493027f7))
> fix: use latest e2e-tests image for testing

- task/summary/0.1/summary.yaml
New parameter was added in #349 without default value which causes that renovate bot update breaks the pipelinerun. We have to always set default value for newly created tasks.
> Set default value on show-summary for build-task-status

- task/clair-scan/0.1/clair-scan.yaml
- task/clamav-scan/0.1/clamav-scan.yaml
- task/deprecated-image-check/0.1/deprecated-image-check.yaml
- task/fbc-related-image-check/0.1/fbc-related-image-check.yaml
- task/fbc-validation/0.1/fbc-validation.yaml
- task/sanity-inspect-image/0.1/sanity-inspect-image.yaml
- task/sanity-label-check/0.1/sanity-label-check.yaml
- task/sast-go/0.1/sast-go.yaml
- task/sast-java-sec-check/0.1/sast-java-sec-check.yaml
- task/sast-snyk-check/0.1/sast-snyk-check.yaml
- task/sbom-json-check/0.1/sbom-json-check.yaml
- Add more more meaningful note to HACBS_TEST_OUTPUT
- Add description to task
Example:
The note in clamav-scan task is like below when it meet error: 
`Task clamav-scan failed: Unable to get number of infected files from /tekton/home/clamscan-result.json. For details, check Tekton task log.`
`Task clamav-scan failed: /tekton/home/clamscan-result.json doesn't exist. For details, check Tekton task log.`
The note for the completed task: `Task clamav-scan completed: Check result for antivirus scan result.`
> feat(HACBS-1832): improve note in HACBS_TEST_OUTPUT

- task/clamav-scan/0.1/clamav-scan.yaml
It may be useful to users to know which version of ClamAV DB is used
> feat(clamav): print version of ClamAV DB

- task/prefetch-dependencies/0.1/prefetch-dependencies.yaml
The images in this respository are built using the RHTAP pipeline, and are now more compliant to the Enterprise Contract policies.
> Use Cachi2 image from Quay's redhat-appstudio org

- .tekton/pull-request.yaml
- .tekton/tasks/e2e-test.yaml
Added securityContext in e2e-test task for sbom check failure for hermatic builds
> fix: add securityContext in e2e-test task for sbom check failure

- task/init/0.1/init.yaml
Sometimes RH registry are having issue with pulling older images.
> STONEBUGS-109: bump ose-tools-rhel8 to newest version

- task/clair-scan/0.1/clair-scan.yaml
This behaviour was discussed and agreed on. We want to provide more explicit information to custommer regarding clair-scans. Thanks to this, they will be able to search for specific CVEs and how to fix them or version that fixes the CVEs.
> feat(clair-ci): provide clair output to logs

- pipelines/enterprise-contract.yaml
This will be used to identify it's the enterprise contract pipeline by the UI
https://issues.redhat.com/browse/HACBS-2062
> add label for enterprise contract pipeline

- task/buildah/0.1/buildah.yaml
If there is a .Dockerignore for a remote dockerfile then download it as well and replace the current file.
> STONEBLD-1120 Download corresponding .dockerignore

- .tekton/pull-request.yaml
- .tekton/tasks/ec-checks.yaml
- hack/ec-checks.sh
The purpose of this change is to create CI that validates the tasks in this repo against the policies in [ec-policies](https://github.com/enterprise-contract/ec-policies). There are two policies that will run. The first is [tasks](https://github.com/enterprise-contract/ec-policies/tree/main/policy/task). This policy will run against all tasks. The second policy is the [build tasks](https://github.com/enterprise-contract/ec-policies/tree/main/policy/build_task). This policy runs against just the build tasks. The build tasks are identified from the pipelines by the name `build-container`.
> ec policy check on all tasks 

- .tekton/pull-request.yaml
- README.md
- pipelines/template-build/template-build.yaml
- task/deprecated-image-check/0.2/MIGRATION.md
- task/deprecated-image-check/0.2/README.md
- task/deprecated-image-check/0.2/deprecated-image-check.yaml
- Start requiring new version when there is breaking change in the task -> when task update requires change of pipeline.
- Add check of existance of MIGRATION.md in new versions of tasks.
- Create version 0.2 of deprecated-image-check with MIGRATION.md - due to change from STONEINTG-233
> STONEBLD-1046: Require MIGRATION.md for new versions

- task/update-infra-deployments/0.1/update-infra-deployments.yaml
This is to fix a CI error `workspace binding "artifacts" does not match any declared workspace`
> artifacts workspace is referenced in push.yaml

- pipelines/enterprise-contract.yaml
A change was introduced to `ec-cli` that caused errors in the Security tab. The change has been reverted, and this new build should include the fix.
> Fix security tab regression from ec-cli

- task/update-infra-deployments/0.1/update-infra-deployments.yaml
Do not hardcode name of the git hub App. This allows to change GitHub app name without changing of code.
> update-infra-deployments: Remove dependency on bot name

- task/summary/0.1/summary.yaml
This annotation is not used by appstudio. Currently it was even broken due to switch to new Openshift Pipelines.
Modifying pipelineRun directly in pipelineRun could be also security issue.
> RHTAPBUGS-288: Remove annotation from summary step

- pipelines/core-services/snyk-secret.yaml
- #400 adds a parameter to the list of params before snyk-shared-secret,
but the replace patch is not updated to reflect the change.
https://github.com/redhat-appstudio/build-definitions/blob/c31f6ad4939f52b30b10331097a21a0d03ca1745/pipelines/core-services/snyk-secret.yaml#L2
- This causes wrong parameter to be replaced and the sync-secret remains
empty, causing the check to be skipped.
- This commit updates the patch to replace the correct parameter
- Fixes: PLNSRVCE-1315
- https://github.com/redhat-appstudio/build-definitions/blob/main/task/sast-snyk-check/0.1/sast-snyk-check.yaml#L46-L49
- [Before] https://console-openshift-console.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/k8s/ns/tekton-ci/tekton.dev~v1beta1~PipelineRun/release-service-on-push-kwgtp/yaml
- [After] …
> Update snyk-shared-secret replace patch

- task/inspect-image/0.1/inspect-image.yaml
Retry to get image metadata with skopeo to give time to succesfully show image in the registry.
Report failures in better way than just crashing bash commands
> fix(STONEINTG-418): inspect-image task should fail better

- pipelines/tekton-bundle-builder/kustomization.yaml
The build-container task moved from 4th to 3rd index.
> Fix the tkn-bundle pipeline

- task/buildah/0.1/buildah.yaml
- task/inspect-image/0.1/inspect-image.yaml
- task/s2i-java/0.1/s2i-java.yaml
- task/s2i-nodejs/0.1/s2i-nodejs.yaml
Remove digest from org.opencontainers.image.base.name annotation since there is already org.opencontainers.image.base.digest.
Fix typo in inspect image.
> RHTAPBUGS-332: Fix image inspect

- renovate.json
* Adding grouping per team and shared images.
* Reviewers will be assigned by renovatebot automatically.
* Shared images will be updated only twice a week to prevent too many updates in PR and noise
Note: it's not possible to add rule "*" to match everything else, that's why all images/prefixes are enumerated
Note: if there is no matching rule, a separate PR will be created
> chore(renovate): improve renovate experience

- task/buildah/0.1/buildah.yaml
We're hoping that by setting aside more cpu resources for buildah tasks, the scheduler will a) distribute them more evenly across nodes and b) auto-scale to more nodes sooner. The hope is that this would improve our ability to handle spikes of concurrent PipelineRuns by recruiting more compute resources.
> setting aside more resources for buildah

- pipelines/core-services/kustomization.yaml
- pipelines/core-services/slack-notification.yaml
- task/slack-webhook-notification/0.1/README.md
- task/slack-webhook-notification/0.1/slack-webhook-notification.yaml
- task/slack-webhook-notification/OWNERS
Add new task for sending messages via slack using webhooks. Integrate the task with core-services pipeline so that teams can be notified when their push pipelinerun failed.
> STONEBLD-29: add slack-webhook-notification

- pipelines/core-services/kustomization.yaml
- pipelines/core-services/update-repo.yaml
Create two new params 'update-repo-script' and 'update-repo-name' when defined then the 'update-repo-name' (eg. redhat-appstudio/build-service) is cloned, script 'update-repo-script' is executed and pull request is created.
> core-service: Allow to define additional repo to modify

- pipelines/docker-build/patch.yaml
- pipelines/fbc-builder/patch.yaml
- pipelines/java-builder/patch.yaml
- pipelines/nodejs-builder/patch.yaml
- task/buildah/0.1/buildah.yaml
- task/s2i-java/0.1/s2i-java.yaml
- task/s2i-nodejs/0.1/s2i-nodejs.yaml
This change affects docker-build pipeline only. Images built by nodejs and Java pipelines already have the requested labels.
> STONEBLD-894: inject labels into built image

- task/show-sbom/0.1/show-sbom.yaml
Print error message when show-sbom task failed.
> RHTAPBUGS-444: fix output of sbom in case of fail

- hack/build-and-push.sh
This PR updates the pipelines to use a resolver rather than specifying 'bundle'. I think this should help with the performance problems we are seeing.
> Use the bundle resolver

- task/slack-webhook-notification/0.1/slack-webhook-notification.yaml
There was a syntax error in the bash script.
Tested in https://github.com/containerbuildsystem/cachi2/pull/235 by inlining the fixed content of the task
> Fix slack-webhook-notification task

- pipelines/core-services/kustomization.yaml
- pipelines/core-services/snyk-secret.yaml
- pipelines/template-build/template-build.yaml
- task/sast-snyk-check/0.1/sast-snyk-check.yaml
* The name of the secret would always be `snyk-secret`
* The volume is set to 'optional: true' which means the absence of the `secret` wouldn't cause a failure ?
> Hardcode the default "snyk-secret"

- task/git-clone/0.1/README.md
- task/git-clone/0.1/git-clone.yaml
If the check is enabled and the cloned repository contains symlinks pointing outside of the repo, the build will fail.
[STONEBLD-1328](https://issues.redhat.com//browse/STONEBLD-1328)
> Add check for symlinks pointing outside of repo

- pipelines/fbc-builder/patch.yaml
- task/fbc-validation/0.1/README.md
- task/fbc-validation/0.1/fbc-validation.yaml
fbc-validation now checks for base image source.
If image is not in list of approved images, validation will fail.
> feat(STONEINTG-503): check for trusted OPM images

- task/buildah/0.1/buildah.yaml
Adds a new step to the buildah task that will insert the components reported by Cachi2 into the SBOM generated by Syft, while also performing deduplication.
See the [merge script](https://github.com/containerbuildsystem/cachi2/blob/main/utils/merge_syft_sbom.py) in the Cachi2 repo for more info.
[STONEBLD-1357](https://issues.redhat.com//browse/STONEBLD-1357)
> Merge Cachi2's SBOM components into the final SBOM

- hack/test-build.sh
- hack/test-builds.sh
There was a change from `pipeline` to `appstudio-pipeline`. Reflecting this change in hack script.
Without this change, custom secret is not linked to PLRs.
> fix(hack): link to right service account

- task/fbc-validation/0.1/fbc-validation.yaml
After verifying that the base image is trusted (see [STONEINTG-503](https://issues.redhat.com//browse/STONEINTG-503)) we need to use the opm binary from the base image to run fbc validation. Because Tekton tasks do not easily support running nested containers, this change extracts the base image and use the opm binary within it to validate the target image.
> feat(stoneintg-507): use base image opm binary for fbc validation

- renovate.json
- task/clamav-scan/0.1/clamav-scan.yaml
Using major version will allow us to do breaking changes in future without breaking user workflows.
Explicitly disable renovatebot from updating tags, we want to keep the same floating tag there.
Note: we also keep latest tag for compat reasons (but not forever)
> fix(STONEINTG-31): use versions with clamDB

- .tekton/push.yaml
This commit changes the push pipeline to run an additional script as part of the `update-ec-policies` TaskRun. This script ensure that if a previous CI run failed or was skipped, for whatever reason, then the next run should catch previous missed acceptable bundle images.
https://issues.redhat.com/browse/HACBS-2395
> Check acceptable bundles repo on push

- task/s2i-java/0.1/s2i-java.yaml
Unify version of the python image, other build scripts are using ubi9 this one is the only one for ubi8. This causes extra updates by renovate bot.
> fix(s2i-java): use ubi9 python

- .tekton/tasks/ec-checks.yaml
- pipelines/enterprise-contract-everything.yaml
- pipelines/enterprise-contract-redhat.yaml
- pipelines/enterprise-contract-slsa1.yaml
- pipelines/enterprise-contract-slsa2.yaml
- pipelines/enterprise-contract-slsa3.yaml
- pipelines/enterprise-contract.yaml
- renovate.json
This is to remove any reference of hacbs with regard to the enterprise contract.
https://issues.redhat.com/browse/HACBS-2047
> remove reference to hacbs-contract quay org

- pipelines/template-build/template-build.yaml
- task/deprecated-image-check/0.3/MIGRATION.md
- task/deprecated-image-check/0.3/README.md
- task/deprecated-image-check/0.3/deprecated-image-check.yaml
As the deprecated-image-check is not sharing any info between the different tasks and only using its own working directory, it doesn't seem to need any PVC to be used from the workspace. 
Hence, the workspace can be removed/replaced with the /tekton/home directory in the build-definitions deprecated-image-check task.
> change workspace to /tekton/home for deprecated-image-check

- .tekton/push.yaml
EC has the concept of acceptable tekton bundles. These are OCI image references that specify which tekton bundles are acceptable to build artifacts in RHTAP. Today, these are tracked in git. The push.yaml pipeline of this repo is responsible for making a pull request in the relevant EC repo update the list. However, this is subject to timing issues when the pull request is not merged fast enough, causing some of the references to be lost.
This commit introduces a new approach by tracking the list of acceptable tekton bundles in an OPA data bundle, which is just another type of OCI image. By doing this, the changes are deployed immediately, significantly lowering the risk of timing issues.
For now, the list is maintained in two places. This facilitate the transition. See the epic …
> Create OPA data bundle of acceptable tkn bundles

- .tekton/push.yaml
If there are no new task/pipeline tekton bundles to be added to the list of acceptable bundles, exit the build-acceptable-bundles task successfully.
This may happen if a commit is added that doesn't touch the task or pipeline definitions, e.g. update README.md.
> Handle no acceptable bundle changes

- task/deprecated-image-check/0.3/MIGRATION.md
Migration guide was written to udpate tasks, but users must update pipeline definitions in PRs created by bot, there is no task definition there and no updated to task should be done.
> fix(deprecated-image-check): migration guide to v0.3

- task/deprecated-image-check/0.2/deprecated-image-check.yaml
- task/deprecated-image-check/0.3/deprecated-image-check.yaml
New versions of the task didn't have updated version label values
> fix(deprecated-image-check): update versions to correct value

- task/buildah/0.1/buildah.yaml
Also updated to the newer v1.31.0.
This image is was copied from the community image in the same manner as the existing one, however all platforms were copied instead of just the amd64 platform.
> STONEBLD-1726 Move to multi-arch buildah image

- task/sast-snyk-check/0.1/sast-snyk-check.yaml
Fixing a bug when task is not returning skip result when snyk token is undefined
> fix(RHTAPBUGS-761): return TEST_OUTPUT when task skipped

- task/sast-snyk-check/0.1/sast-snyk-check.yaml
Instead of hiding how to enable snyk task in logs, show it to user in message which can be retrieved from summary and in web UI
> fix(RHTAPBUGS-761): show more explanatory message to users

- task/clair-scan/0.1/clair-scan.yaml
There is no need to separate these 2 checks, this will save uz one extra running container, as each step runs in separate container which are created in advance and parallel by tekton.
> feat(STONEINTG-438): clair - merge conftest and format-results step

- task/build-image-manifest/0.1/README.md
- task/build-image-manifest/0.1/build-image-manifest.yaml
- task/build-image-manifest/0.1/kustomization.yaml
- task/build-image-manifest/OWNERS
- task/buildah-remote/0.1/README.md
- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah-remote/0.1/kustomization.yaml
- task/buildah-remote/OWNERS
Note that this includes https://github.com/redhat-appstudio/build-definitions/pull/577 which moves to the multi-arch builder image
> STONEBLD-1667 Initial multi platform build tasks

- task/clair-scan/0.1/clair-scan.yaml
* Add the `unkown` field to clair-scan task output to catch vulnerabilities of Unkown severity level
Example vulnerability output for Unknown severity:
Example clair-scan task result:
> feat(STONEINTG-425): add unknown vulnerabilities for clair

- task/deprecated-image-check/0.1/deprecated-image-check.yaml
- task/deprecated-image-check/0.2/deprecated-image-check.yaml
- task/deprecated-image-check/0.3/deprecated-image-check.yaml
curl -k runs insecure connection to the server. This is a security issue to skip SSL certificate errors by adding -k or --insecure option in curl commands. 
This PR is to remove the -k option from the curl command of the deprecated-image-check
> fix(STONEINTG-603) remove insecure connection from curl

- .tekton/tasks/buildah.yaml
- task/buildah-10gb/0.1/patch.yaml
- task/buildah-6gb/0.1/patch.yaml
- task/buildah-8gb/0.1/patch.yaml
- task/buildah/0.1/buildah.yaml
- task/s2i-java/0.1/s2i-java.yaml
- task/s2i-nodejs/0.1/s2i-nodejs.yaml
- task/sbom-json-check/0.1/sbom-json-check.yaml
- task/update-infra-deployments/0.1/update-infra-deployments.yaml
@jhutar @pmacik @amfred @psuriset 
I've mentioned this in some of the WG calls.  We should compare the numbers from https://github.com/redhat-appstudio/build-definitions/pull/514 with this change
I'm curious how alleviating the use of aws storage for the sbom-json-check during the adv pipeline in particular has on overall disk IO
fwiw I don't see the use of the s2i-nodejs task in our runs
but ideally we pull the trigger on all our emptydirs at this point
> chore: update all emptyDirs to 'medium: Memory'

- task/buildah/0.1/buildah.yaml
Despite all the performance WG testing in PR #551, once the switch to memory for the build task /var/lib/containers landed; various builds started to fail because of memory issues.  Before we revert, we are bumping the default some more.
@mmorhun @arewm PTAL
if this does not suffice, we'll revert the change
> fix: bump default build task to 6gb

- .tekton/tasks/buildah.yaml
- task/buildah-10gb/0.1/patch.yaml
- task/buildah-6gb/0.1/patch.yaml
- task/buildah-8gb/0.1/patch.yaml
- task/buildah/0.1/buildah.yaml
- task/s2i-java/0.1/s2i-java.yaml
- task/s2i-nodejs/0.1/s2i-nodejs.yaml
- task/sbom-json-check/0.1/sbom-json-check.yaml
- task/update-infra-deployments/0.1/update-infra-deployments.yaml
This reverts commit f8c6a108b3be411b54075941b54142fb2b49fa5c.
this reverts https://github.com/redhat-appstudio/build-definitions/pull/551 in case https://github.com/redhat-appstudio/build-definitions/pull/611 does not work
@mmorhun @arewm
> Revert "update all emptyDirs to 'medium: Memory'"

- .tekton/push.yaml
Recently the CI has started to fail with the error: Error executing command: fork/exec ./hack/build-and-push.sh: no such file or directory
Presumably, this is due to a change in behavior in Tekton. This is an attempt to fix the error by removing `./` from the command path.
> Attempt to fix build-bundles step

- .tekton/push.yaml
A [previous change](https://github.com/redhat-appstudio/build-definitions/commit/0765369ae500ce4240f3a09dd0b9e8b5e20a9450) updated the git-clone task to clone repositories into a subdir which has the default value of `source`. The build-bundles task was missed during that update.
> Use /source subdir in build-bundles task

- task/deprecated-image-check/0.1/deprecated-image-check.yaml
- task/deprecated-image-check/0.2/deprecated-image-check.yaml
- task/deprecated-image-check/0.3/deprecated-image-check.yaml
Changing `bash` to `sh` in [PR](https://github.com/redhat-appstudio/build-definitions/commit/f18be5eb68f613e6168b0f7c8d666682b04baa47#diff-91bba1c97642720c1a3c3afd61f64b72f7b53bf70f5f10b6d9f5d095687159adR38) makes command `readarray -t IMAGE_ARRAY < <(echo -n "$BASE_IMAGES_DIGESTS" | sed 's/\\n/\'$'\n''/g')` fail with error as below
```
unexpected token `<'
Unexpected error: Script errored at command: trap 'handle_error' EXIT.
```
So let's rollback the change.
With the fix, it can pass like this:
```
step-query-pyxis
[registry.access.redhat.com] [ubi8/ubi:8.8-1067.1696517599@sha256:dd3ea588640fd91ea85f6324df14627b2f8ad52ac55ecd907ca3201cd78667e6]
Querying Pyxis for registry.access.redhat.com/ubi8/ubi:8.8-1067.1696517599@sha256:dd3ea588640fd91ea85f6324df14627b2f8ad52ac55ecd907ca3201cd78667e …
```
> fix: change sh back to bash in task deprecated-image-check

- pipelines/fbc-builder/patch.yaml
This change fixes the issue of the fbc-validate task running before the inspect-image task finishes.
> fix(STONEINTG-626): add runAfter to fbc-validate task

- task/fbc-validation/0.1/fbc-validation.yaml
* Remove usage of -f option and set image_inspect.json as the file parameter
Before the change, the jq command failed with this output in the task log:
After this change, the task is able to run correctly and validate the FBC image:
> fix(STONEINTG-662): fix jq command for config label in fbc-validate

- pipelines/template-build/template-build.yaml
* add runafter to task deprecated-base-image-check
> fix(STONEINTG-626): add runafter to deprecated-base-image-check

- task/git-clone/0.1/README.md
- task/git-clone/0.1/git-clone.yaml
ACS builds expect tags to be present in the checked out repository to set the version of the binary with commands like `git describe --tags`.
This PR adds a new parameter to the `git-clone` task to fetch the tags after the initial checkout. 
Because this is not a required parameter and provides a default value, a new version of the task is not needed.
We have tested this change with a custom build pipeline pointing to a self-bundled task with this change. 
Reviewers may find the compiled task bundle in `quay.io/tommartensen/rhtap-tasks@sha256:47190ad64bce76f1b8c50d66089fcd89a4afc80888372b5de61e33d89dd2fa91`. 
Example PipelineRun: https://console.redhat.com/preview/application-pipeline/workspaces/rh-acs/applications/acs/pipelineruns/roxctl-on-pull-request-t6674.
We fetched build logs as …
> feat(ROX-20233): add fetchTags option to git-clone task

- hack/test-build.sh
So that one can use the script to, for example, trigger a hermetic build
hack/test-build.sh \
https://github.com/cachito-testing/pip-e2e-test \
docker-build \
-p revision="1ecda839ba9ca55070d75c86c26a1bb07d777bba" \
-p hermetic=true \
-p prefetch-input=pip
> hack/test-build.sh: support passing params to tkn

- task/buildah/0.1/buildah.yaml
- task/s2i-java/0.1/s2i-java.yaml
- task/s2i-nodejs/0.1/s2i-nodejs.yaml
This changes the buildah, s2i-java, and s2i-nodejs tasks to emit a new task result, SBOM_BLOB_URL. This result includes an image reference by digest to the SBOM of the image.
By doing so, we establish a strong link between the image and the SBOM via the SLSA Provenance.
https://issues.redhat.com/browse/EC-175
> Emit SBOM_BLOB_URL result on build tasks

- task/source-build/0.1/source-build.yaml
Meanwhile, lower the resources.limits.memory.
Haven't noticed the revert PR https://github.com/redhat-appstudio/build-definitions/pull/612 during the review of https://github.com/redhat-appstudio/build-definitions/pull/621. Thanks for the reminding by @mmorhun
> Do not use in-memory emptyDir for source-build task

- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
- task/s2i-java/0.1/s2i-java.yaml
- task/s2i-nodejs/0.1/s2i-nodejs.yaml
In previous versions of syft, if the image did not contain any components, the field was empty list:
"components": []
But in newer versions, the field is omitted completely.
> Don't fail when image sbom does not contain components

- task/build-image-manifest/0.1/build-image-manifest.yaml
When creating manifest lists don't pull the images. The issue was that the docker image:tag@sha256:digest format requires buildah to pull the image. If we remove the tag section and just use the digest then the manifest list builds without needing to pull.
> STONEBLD-1758 don't pull the images

- README.md
- task/rpm-ostree/0.1/rpm-ostree.yaml
The `--initialize-mode` argument is only in newer releases; this ensures we work with current c9s.
> tasks/rpm-ostree: Support older rpm-ostree

- task/fbc-related-image-check/0.1/fbc-related-image-check.yaml
- Fix the message so user look in logs for more details instead of  TES_OUT. 
[STONEINTG-637](https://issues.redhat.com/browse/STONEINTG-637)
> Improve note when task succeeded 

- .tekton/push.yaml
We have noticed that some content is missing from the OPA bundle maintained by the `ec track bundle` command. This will help us debug what is going on.
Ref: [EC-230](https://issues.redhat.com//browse/EC-230)
> Add --debug to ec track command

- .tekton/push.yaml
- task/source-build/0.1/source-build.yaml
At some point, the git-clone Task was modified to clone repositories into the `/source` sub-directory. As part of that work, the `build-bundles` Task in the push PipelineRun started emitting the task-bundle-list and the pipeline-bundle-list files also under the `/source` sub-directory. However, the task build-acceptable-bundles was not updated with the new location. This caused that Task to never pick up new bundles. This went unperceived because the Task has functionality to query the registry for any bundles that it may have missed. This, of course, only works if the repo for the bundle is already in the list. New repos for new bundles were completely skipped.
This commit changes the build-acceptable-bundles to look for the expected bundle reference files in the updated location.
It …
> Fix EC task to get bundles from correct location

- .tekton/push.yaml
Without `--prune` the acceptable bundles data image only increases in
size.
Also builds on https://github.com/redhat-appstudio/build-definitions/pull/661 to ease merging.
Ref. https://issues.redhat.com/browse/EC-220
> Adds --prune to remove older entries

- hack/util-install-bundle.sh
Build-service supports the Tekton v1 pipelineRef style now. Switch to the new style so that build-service can drop support for the old style.
https://tekton.dev/docs/pipelines/pipelineruns/#tekton-bundles
> util-install-bundle.sh: use new selector syntax

- .tekton/tasks/buildah.yaml
- task/build-image-manifest/0.1/build-image-manifest.yaml
- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
- task/clamav-scan/0.1/clamav-scan.yaml
- task/fbc-related-image-check/0.1/fbc-related-image-check.yaml
- task/fbc-validation/0.1/fbc-validation.yaml
- task/rpm-ostree/0.1/rpm-ostree.yaml
- task/s2i-java/0.1/s2i-java.yaml
- task/s2i-nodejs/0.1/s2i-nodejs.yaml
- task/source-build/0.1/source-build.yaml
CPU `limits` are known as unhelpful and actually harmful as they cause throttling.
When containers have CPU `requests`, they should always get at least as much as requested. They can also get extra CPU cycles when available unless there are `limits` which prevent that.
This is well described in the following article: https://home.robusta.dev/blog/stop-using-cpu-limits
----
I simply searched for `cpu:` in all files of the repo and removed attributes that were in `limits:`. I feel some CPU `requests` can be tweaked but that's likely a job for separate PRs and requires more observations.
Initially, I created this PR observing that our build task gets throttled at 2 CPUs while it could get a speedup benefit if given more.
Testing: I haven't tested this change, and I hope it should work as …
> chore: Remove CPU limits from tasks

- .tekton/pull-request.yaml
- .tekton/push.yaml
- .tekton/tasks/buildah.yaml
- .tekton/tasks/e2e-test.yaml
- .tekton/tasks/ec-checks.yaml
- .tekton/tasks/yaml-lint.yaml
- task/build-image-manifest/0.1/build-image-manifest.yaml
- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
- task/clair-scan/0.1/clair-scan.yaml
- task/clamav-scan/0.1/clamav-scan.yaml
- task/deprecated-image-check/0.1/deprecated-image-check.yaml
- task/deprecated-image-check/0.2/deprecated-image-check.yaml
- task/deprecated-image-check/0.3/deprecated-image-check.yaml
- task/fbc-related-image-check/0.1/fbc-related-image-check.yaml
- task/fbc-validation/0.1/fbc-validation.yaml
- task/git-clone/0.1/git-clone.yaml
- task/init/0.1/init.yaml
- task/inspect-image/0.1/inspect-image.yaml
- task/prefetch-dependencies/0.1/prefetch-dependencies.yaml
- task/rpm-ostree/0.1/rpm-ostree.yaml
- task/s2i-java/0.1/s2i-java.yaml
- task/s2i-nodejs/0.1/s2i-nodejs.yaml
- task/sast-snyk-check/0.1/sast-snyk-check.yaml
- task/sbom-json-check/0.1/sbom-json-check.yaml
- task/show-sbom/0.1/show-sbom.yaml
- task/slack-webhook-notification/0.1/slack-webhook-notification.yaml
- task/source-build/0.1/source-build.yaml
- task/summary/0.1/summary.yaml
- task/update-infra-deployments/0.1/update-infra-deployments.yaml
QE has recently observed image pull throttling to the point of failed PipelineRuns during execution of the e2e's.  While QE is on a path to creating more quay.io robot accounts for their tests to increase their overall quota with the kubelet/quay.io access, this PR intend to both minimize the container level image pulling performed by the kubelet, as well as facilitate dependency updates via mechanisms like renovate and dependabot, by forcing use of image digests (but coulped with tags for human ease of use) and IfNotPreset pull poicy whenever possible.
See https://redhat-internal.slack.com/archives/C02CTEB3MMF/p1700747494517799
I've marked as reviewers those most active in discussing this with me.  But if you think I've missed important reviewers please advise.
Also, I will be creating …
> PLNSRVCE-1533: enforce use of image digests in all image tags

- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
This will append the '-s settings.xml' directly after the mvn command,
so that commands like 'mvn install && rm target' will still work.
Previously this would have appended the settings to the rm command.
> fix(STONEBUGS-124): settings.xml injection fix

- task/clamav-scan/0.1/clamav-scan.yaml
Add args to clamcan command line to scan more files, refer to https://docs.google.com/document/d/10KT44kmQeXFmbWtbqo3kVOsG3NFEbbS09S4fJGV_9dQ/edit#heading=h.655mtb2n05wb for more details
1. Add more clamscan parameters –max-* and alert-* in Tekton task params and set the value in task
2. Check alerts in clamscan-result.log when exceeding the limitations in clamscan command, we need parse clamscan-result.log and calculate the number of alert then add number to `warnings` and set result of TEST_OUTPUT to `WARNING` `{"result":"WARNING,"timestamp":"1701677631","note":"Task clamav-scan completed: Check result for antivirus scan result.","namespace":"default","successes":1,"failures":0,"warnings":4}`
3. Increase [requests.cpu](https://github.com/redhat-appstudio/build-definitions/blob/main/task/ …
> fix(STONEINTG-653): adjust args of clamscan command line

- hack/generate-buildah-remote.sh
- task/buildah-remote/0.1/buildah-remote.yaml
This will propagate docker credentials to the remote build agent. We now have tests to verify that these are cleaned up.
> STONEBLD-1779 propagate docker credentials

- task/clamav-scan/0.1/clamav-scan.yaml
In https://github.com/redhat-appstudio/build-definitions/pull/698/files, we increase requests.cpu to 1, but 1 cpu makes build PLR fail, see slack https://redhat-internal.slack.com/archives/C02FANRBZQD/p1703051386118509?thread_ts=1703049812.456129&cid=C02FANRBZQD
So we have to reduce requests.cpu back to 10m and then find way later
> fix: reduce request.cpu to 10m since 1 cpu make build PLR fail

- .tekton/pull-request.yaml
My theory is that pipelines 1.13 broke workingDir somehow.
> attempt to fix yamllint

- hack/generate-buildah-remote.sh
- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
> RHTAPBUGS-1061 BASE_IMAGE_DIGESTS for multi platform

- task/update-infra-deployments/0.1/update-infra-deployments.yaml
This PR addresses: [RHTAPBUGS-1043](https://issues.redhat.com/browse/RHTAPBUGS-1043)
> RHTAPBUGS-1043: Updated script image

- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
This avoids pulling the `scratch` image from remote registry.
Ref. https://issues.redhat.com/browse/RHTAPBUGS-1066
> Support `FROM scratch` image builds in buildah

- task/update-infra-deployments/0.1/update-infra-deployments.yaml
It will handle situation like closing the PR like [this one](https://github.com/redhat-appstudio/infra-deployments/pull/2976), when no files has been modified after running the SCRIPT parameter
> fix: Handles empty updated files gracefully

- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/README.md
- task/buildah/0.1/buildah.yaml
This change allows mounting repofiles inside the image being built so those can be used by the buildah build process.
The repofiles can be stored together with the code, or generated on-the-fly using the generate-odcs-compose task, similarly to what's done here:
https://github.com/redhat-appstudio/tekton-tools/pull/22/files
> chore(RHTAPWATCH-697): support mounting repofiles to buildah build

- .tekton/tasks/e2e-test.yaml
Running tests in verbose mode makes it nearly impossible to troubleshoot test failures. This disables it. Rationale: when running in verbose mode the test using the `GinkgoWriter` will cause immediate output to the stdout/log, for the build tests in particular this causes logging excessive amounts of Task logs from the SBOM task[1]. The difference when not running in verbose mode is that that output is buffered and only written to stdout/log IF the test fails[2]. Given that PipelineRuns are garbage collected almost immediately up on execution, the only resource available is to search for the CI logs through Splunk. This fails short because we can only page through the first 100 pages of logs, which in all certainty will not contain the test failure, just the excessive JSON output from the …
> Don't run e2e tests in verbose mode

- pipelines/template-build/template-build.yaml
- task/init/0.2/MIGRATION.md
- task/init/0.2/README.md
- task/init/0.2/init.yaml
The parameters skip-optional, pipelinerun-name and pipelinerun-uid are no longer used in init task and neither is the container-registry-secret result.
New version for init task was created together with the migration doc and the reference was updated in the pipeline
[STONEBLD-2000](https://issues.redhat.com//browse/STONEBLD-2000)
> Remove unused parameters and result

- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
- task/prefetch-dependencies/0.1/prefetch-dependencies.yaml
This change is done manually here since the combined PR created by renovate (#722) also bumps Syft's version, which would bring breaking changes from CycloneDX 1.5. Those will be handled in follow up patches.
> Update Cachi2 to 0.4.0

- task/clamav-scan/0.1/clamav-scan.yaml
* Remove --alert-broken from clamav scan args since this cause false positive alert
> fix: remove --alert-broken and --alert-broken-media from clamscan

- task/show-sbom/0.1/show-sbom.yaml
Addresses: https://issues.redhat.com/browse/STONEBLD-1936
> STONEBLD-1936: Added retry mechanism and don't fail the pipeline on show-sbom task failure

- task/deprecated-image-check/0.1/README.md
- task/deprecated-image-check/0.1/deprecated-image-check.yaml
- task/deprecated-image-check/0.2/README.md
- task/deprecated-image-check/0.2/deprecated-image-check.yaml
Task deprecated-base-image-check in versions 0.1 and 0.2 is deprecated and support for it will be removed in near future. Use the version 0.3+
> chore(STONEINTG-612): deprecate deprecated-base-image-check v0.1, v0.2

- .tekton/pull-request.yaml
As part of https://issues.redhat.com/browse/EC-356, a check was added to ensure Task steps use images from reputable registries. However, some existing Tasks do not meet this criteria. This will be addressed in https://issues.redhat.com/browse/KONFLUX-2034. This effort is being tracked by the Epic https://issues.redhat.com/browse/EC-332.
Also, the existing check uses `ec validate definition` which doesn't fully allow customization of which policies are executed. It just runs all of the ones from the "task" namespace.
Finally, the previous rules basically checks that a Task has the kind attribute set to "Task", which is not very valuable.
For now, let's disable the EC checks altogether. They will be properly re-enabled as part of the epic EC-332.
> Disable PR EC checks

- pipelines/docker-build-dance/patch.yaml
- task/buildah-rhtap/0.1/buildah-rhtap.yaml
- task/buildah-rhtap/OWNERS
This PR proposes a new simplified and improved buildah task to be used for the new RHTAP docker build  pipeline.
Compared to the current Konflux buildah task, this task:
- Removes all the Konflux-specific features that are not needed in RHTAP
- Uses a productized version of the buildah image
- Removes root access from all steps
- Sets the correct Syft catalogers when scanning the built image
- Pins the output CycloneDX version
- Avoids littering the source code workspace with temporary files
- Improves the SBOM merge algorithm (dedup by PURL)
- Add a the SBOM OCI artifact URL as a task result
- Changes the tags
> New buildah task for RHTAP

- .github/workflows/check-buildah-remote.yaml
- hack/test-shellspec.sh
- task/tkn-bundle/0.1/spec/test1.yaml
- task/tkn-bundle/0.1/spec/test2.yml
- task/tkn-bundle/0.1/spec/test3.yaml
- task/tkn-bundle/0.1/spec/tkn-bundle_spec.sh
- task/tkn-bundle/0.1/tkn-bundle.yaml
This change introduces a new parameter called STEPS_IMAGE, which allows you to include a custom image for each step in the bundled tasks. 
https://issues.redhat.com/browse/EC-35
> Support replacing the step image in task bundles

- .tekton/tasks/yaml-lint.yaml
- task/tkn-bundle/0.1/tkn-bundle.yaml
```
Ignore files without spec in yamllint
This commit modifies the `ensure-params-not-in-script` step of the
yaml-lint task to not emit an error when processing YAML files that do
not contain a `.spec` attribute.
The functionality is unchanged. The only change is that `yq` quits early
instead of failing.
```
```
Fix yaml lint violation on tkn-bundle task
The task was merged at the same time as the yaml lint checks were
enabled.
```
> Fix yamllint

- task/tkn-bundle/0.1/spec/tkn-bundle_spec.sh
- task/tkn-bundle/0.1/tkn-bundle.yaml
The `registry.access.redhat.com/ubi9/toolbox` image does not contain the `yq` binary, this changes the `modify-task-files` step's image to use `quay.io/redhat-appstudio/hacbs-test:latest` image instead.
The added test makes sure that the modification occurred by inspecting the image of the Tasks in the built bundle.
Resolves: https://issues.redhat.com/browse/EC-379
> Fix tkn-bundle task and add test

- .tekton/pull-request.yaml
- .tekton/push.yaml
- .tekton/tasks/ec-checks.yaml
- policies/build-tasks.yaml
Ref: https://issues.redhat.com/browse/EC-359
> Re-enable EC Task checks

- .tekton/push.yaml
Lately the "Red Hat Trusted App Pipeline /
build-definitions-bundle-push" has been timing out which causes the acceptable bundles data to go stale, which causes bogus EC failures out unacceptable tasks.
This is a quick fix to get the CI working again. It's likely the root causes still need to be addressed. See the following Jiras for details:
Ref: https://issues.redhat.com/browse/EC-236
Ref: https://issues.redhat.com/browse/EC-351
> Longer timeout for ec track bundle

- task/clamav-scan/0.1/clamav-scan.yaml
Update max-htmlnormalize max-scriptnormalize from clamav-scan task because they have not worked well.
They cause the issue in https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1706699932388599 and https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1704986484024359
I test scanning users's image quay.io/redhat-user-workloads/rh-acs-tenant/acs/scanner:on-pr-2554e4fa14648ce3dadfa75c7f15d105bf214f7f mentioned [here](https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1704986484024359) but it times out after 1 hour, and then it works if I remove these two args.
So let's remove these two args for now
> fix: update args max of htmlnormalize scriptnormalize  from clamac-scan task

- task/inspect-image/0.1/inspect-image.yaml
Task inspect-image would report index image (multiarch image) as "From scratch" image and consequently some checks would be skipped.
This patch adds support to image index to lookup for image manifest and parse correct data.
Currently amd64 platform si expected as that's the only platform current checks are supporting.
> fix(STONEINTG-25): support index image in image-inspect task

- task/clamav-scan/0.1/clamav-scan.yaml
A new policy `clamav/virus-check.rego` has been created which is able to parse results of clamav, detect heuristics checks and return only warnings for them
ec-cli is able to generate appstudio TEST_OUTPUT thus we don't need last 2 steps
> feat(STONEINTG-755): only warn about heurtistics in clamav

- task/git-clone/0.1/git-clone.yaml
Setting the verbose value to true causing the user private github tokens to be printed in the task run logs, changed it to be by default false
> RHTAPBUGS-1095: changed the default value of verbose param to false

- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
In RHACS, we have multiple "slim" containers that are the same as their non-slim counterparts with just few things absent. These are `collector-slim`-`collector`, `scanner-slim`-`scanner`, `scanner-db-slim`-`scanner-db`.
It is natural for these cases to have a single Dockerfile for both "slim" and non-slim containers done in the following way
```Dockerfile
FROM some-base AS slim
FROM slim AS full
```
Both `docker build` and `buildah build` support specifying target stage to build. This way, building something-slim would be
```bash
$ buildah build --target=slim ...
```
Building something non-slim would go simply without the `--target` argument because the Dockerfile is built entirely by default
```bash
$ buildah build ...
```
Not having an option to select target forces us to have two …
> Introduce `TARGET_STAGE` build parameter

- task/rpm-ostree/0.1/rpm-ostree.yaml
Required for https://github.com/CentOS/centos-bootc/pull/277
I am planning to potentially change to use bootc-image-builder for this, but it has a non-`bash` entrypoint.
> task/rpm-ostree: Use --entrypoint bash

- task/buildah-24gb/0.1/patch.yaml
The RHOAI team needs 10-20 CPUs to build their
component.
It also makes sense that if a build requires 24GB of RAM, it will also require a large amount of CPUs.
> RHTAPSRE-395: Add more cpus to buildah 24gb

- .tekton/tasks/ec-checks.yaml
By default OpenShift only fetches an image by a floating tag, e.g. `snapshot`, if the image is not yet available in the cluster. We can change this behaver with `imagePullPolicy: Always`. However, a better approach is to pin the image reference to a digest and let automation, i.e. renovate bot, bring in updates. This gives us more control over which code is actually executed in the CI.
I came across this when working on [EC-414](https://issues.redhat.com//browse/EC-414). The fix for that issue was not propagated as expected. Further investigation revealed that an older version of the EC CLI was still being executed.
This commit pins references to the EC CLI image to a digest.
Ref: https://issues.redhat.com/browse/EC-414
Look for any open pull requests in the repository with the title …
> Pin ec-cli image in ec-checks Task

- task/tkn-bundle/0.1/tkn-bundle.yaml
This resolves the "Unsuccessful cred copy" warning.
warning: unsuccessful cred copy: ".docker" from "/tekton/creds" to "/tekton/home": unable to open destination: open /tekton/home/.docker/config.json: permission denied
> Set runAsUser to 0 for bundle push step

- pipelines/rhtap/kustomization.yaml
This PR removes the pipelines referenced in the rhtap pipeline configuration to include only the docker-build-rhtap pipeline.
The other ones had been included as part of a PoC but are not planned for 1.0.
We need this to cleanup and remove unused components from the tssc-sample-pipelines
> remove the pipelines which are not included in 1.0

- .tekton/tasks/ec-checks.yaml
- policies/all-tasks.yaml
- task/git-clone/0.1/README.md
- task/git-clone/0.1/git-clone.yaml
This PR includes two commits:
1. Enable step_image_registries check for Tasks
> This commit effectively enables the step_image_registries[1] policy rules on the Task definitions in this repo.
> Since some Tasks do not yet comply with some of those policy rules, exceptions are added for those cases. 
> Enabling this check now should help prevent new violations from being introduced.
>
> Since the policy now includes a very specific exclusion list for this
> repo, the policy itself is now defined here.
> 
> Ref: https://issues.redhat.com/browse/EC-374
> 
> [1] https://enterprisecontract.dev/docs/ec-policies/task_policy.html#step_image_registries_package
2. Disable gitInitImage param from git-clone Task
> This was missed in [STONEBLD-2109](https://issues.redhat.com/browse/STONEBLD-2109).
> Enable step_image_registries check for Tasks

- task/update-deployment/0.1/update-deployment.yaml
This PR fixes an type in a string which is missing the end quote for the new update-deployment.yaml task
> fix typo, missing quoted string

- task/buildah-rhtap/0.1/buildah-rhtap.yaml
This Tekton result will contain the URL to the layer containing the SBOM, so it can be later be accessed by the EC. 
For future reference, the SBOM can be retrieved from a layer by using:
```
oras blob fetch quay.io/bpimente/test-images@sha256:509e7e73b03bb9c02f6e14a80acc81296396f538834dff09013f134f35a98591 --output -
```
> buildah-rhtap: emit the SBOM_BLOB_URL result

- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
Users can add the entitlement secret "etc-pki-entitlement" to their namespace in the cluster. This will be then available for installing rpms during container build.
[STONEBLD-1589](https://issues.redhat.com//browse/STONEBLD-1589)
> Add handling of entitlement secret

- task/buildah-rhtap/0.1/buildah-rhtap.yaml
The algorithm that is being used to strip the tag from the image will return an empty string in case the image already lacks the tag in the first place (i.e. quay.io/user/my-image).
This results in a SBOM_BLOB_RESULT that lacks the image name, and only contains the digest.
> buildah-rhtap: Fix SBOM_BLOB_RESULT for images that lack a tag

- task/fbc-validation/0.1/fbc-validation.yaml
A new version of ose-operator-registry based on rhel9 has been released, allow users to use it.
> fix(STONEINTG-821): allow ose-operator-registry-rhel9

- pipelines/docker-build-rhtap/patch.yaml
This PR adds the SCAN_OUTPUT to the PipelineRun results which enables the Tekton plugin to show the vulnerabilities in the Pipelines iew
> add ACS_SCAN_OUTPUT to pipeline run results

- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah-rhtap/0.1/buildah-rhtap.yaml
- task/buildah/0.1/buildah.yaml
- task/rpm-ostree/0.1/rpm-ostree.yaml
- task/s2i-java/0.1/s2i-java.yaml
- task/s2i-nodejs/0.1/s2i-nodejs.yaml
[STONEBLD-2095](https://issues.redhat.com//browse/STONEBLD-2095)
Syft makes many things configurable:
https://github.com/anchore/syft#configuration
For example, users can take advantage of this to get rid of false
positives. This will be useful for the Syft build itself:
https://github.com/redhat-appstudio/rh-syft/pull/21
Currently, our SBOM generation does not respect the user configuration.
Syft reads the config from the current working directory, not from the
target directory (https://github.com/anchore/syft/issues/2465).
Set the working directory to the root of the user's repository to ensure
we respect the configuration.
> Respect user configuration for Syft

- task/update-deployment/0.1/update-deployment.yaml
In case of push failure the task produces the following output:
```
step-patch-gitops
Cloning into 'testgo-gitops'...
[main 747a7b0] Update 'testgo' component image to: quay.io/user-org/rhdh-test:d719c735bdb7573482a9a24cee8442856885e36d@sha256:37607c61eec84d0ffefc8ec55dd859e688b10bb7391ec64a6f324e5e869eb7a9
1 file changed, 1 insertion(+), 1 deletion(-)
Failed to push update to gitops repository: https://github.com/user-org/testgo-gitops
Do you have correct git credentials configured?
```
> Control git push command output

- pipelines/docker-build-rhtap/patch.yaml
- task/update-deployment/0.1/update-deployment.yaml
Prevents running update deployment task if pipeline was trigerred by pull_request event.
Also, fixes some formatting.
https://github.com/redhat-appstudio/tssc-sample-pipelines/pull/24 adds `event-type` parameter to the RHTAP pipeline run.
> Do not run update-deployment task on pull request

- pipelines/docker-build-rhtap/patch.yaml
- task/show-sbom-rhdh/0.1/README.md
- task/show-sbom-rhdh/0.1/show-sbom-rhdh.yaml
- task/show-sbom-rhdh/OWNERS
Previous title: emit the LINK_TO_SBOM result
~This result contains the URL to the OCI artifact that stores the SBOM. It is meant primarily to be consumed by [RHDH](https://github.com/janus-idp/backstage-plugins/issues/988) and [ODC](https://github.com/openshift/console/pull/13314). The URl follows the format:~
~registry.io/user/image:sha256-hash.sbom~
~Note that this URL is not meant to be used with cosign, as it automatically resolves it when performing a "cosign download sbom registry.io/user/image:actual-tag".~
This PR was changed based on the comments on this [thread](https://github.com/redhat-appstudio/build-definitions/pull/876#discussion_r1522576564). We need to annotate the `show-sbom` task instead of `buildah-rhtap`. But since Pipelines as Code will clear the annotations, they …
> docker-build-rhtap: create a new show-sbom task compatible with RHDH

- task/show-sbom-rhdh/0.1/show-sbom-rhdh.yaml
The current shebang (/busybox/sh) does not exist in the RHTAS image, and will cause the taskRun to fail.
> Change the shebang in the show-sbom-rhdh task

- pipelines/gitops-pull-request-rhtap/gitops-pull-request.yaml
- task/gather-deploy-images/0.1/README.md
- task/gather-deploy-images/0.1/gather-deploy-images.yaml
The pipeline will only check images that changed in the pull request
> gitops-pull-request: check only changed images

- task/update-deployment/0.1/update-deployment.yaml
Changes `update-deployment` task to get component name within gitops repository from `application.yaml` instead of gitops repository name.
> Read component name from application.yaml in update-deployment task

- task/source-build/0.1/source-build.yaml
- This fix is needed for the builds performed by the rpm-ostree task otherwise, we can see this error:
"fatal: detected dubious ownership in repository at '/workspace/workspace/source'"
> fix issue with source build when rpm-ostree is used

- task/acs-deploy-check/0.1/acs-deploy-check.yaml
Changes acs-deply-check task to get component name within gitops repository from application.yaml instead of gitops repository name.
Related to https://github.com/redhat-appstudio/build-definitions/pull/894
> Read component name from application.yaml in acs-deploy-check task

- task/summary/0.2/summary.yaml
This PR removes last usage of `quay.io/redhat-appstudio/task-toolset` image by replacing it with `uay.io/redhat-appstudio/appstudio-utils` image that has needed tools installed and already used in other tasks, so we reduce number of used images by 1.
> Remove usage of task-toolset image

- .tekton/pull-request.yaml
- .tekton/tasks/e2e-test.yaml
* This change increases the default timeout (60mins) of the PR-type PLR and the 'e2e-tests' Task to 90 mins.
* This is a temporary change, please see: https://github.com/redhat-appstudio/e2e-tests/pull/1091
* Since the chains controller is overwhelmed, we had to increase the test timeout value to 90mins.
* So this current PR increases the timeout values for PLR and a Task to the same timeout value used by test, 90m.
> fix(STONEBLD-2265): increase the default timeout of pull-request-type PLR & e2e-tests Task to 2hrs

- .tekton/tasks/e2e-test.yaml
Names of the test repos created in tha past match the cleanup rule
defined in e2e-tests, which causes those repos were removed from
redhat-appstudio-qe organization. As of this update, the test repos have
been recovered with new names already.
> Update test repos for source container build

- .tekton/tasks/e2e-test.yaml
In d07462a6068ca7f6f086c2b734c2cdfb97e902e5, the timeout for the test
pipelineRun was increased to 2 hours (see the commit message for
reasoning.)
However, ginkgo has its own timeout which defaults to 1 hour. Increase
to 2 hours correspondingly.
> e2e-test: Set ginkgo timeout to 2 hours

- .tekton/push.yaml
- .tekton/scripts/build-acceptable-bundles.sh
After a merge, collect any changed task files then add them to a data bundle for policy evaluation.
https://issues.redhat.com/browse/EC-387
> Get changed task files for git resolvers

- pipelines/docker-build-rhtap/patch.yaml
- defaults remain the same so existing installer will work with github
This change is to allow the RHTAP templates to pass a different secret for gitlab vs github
> add secret param to pipeline to allow gitlab/github

- .tekton/tasks/e2e-test.yaml
[STONEBLD-1832](https://issues.redhat.com//browse/STONEBLD-1832)
Pull secret is required to be available for the e2e tests in order to
fetch image data from registry.redhat.io. The task needs the capability
in order to write the registry authentication credential into auth file.
> Give write permission to e2e-tests task

- task/verify-enterprise-contract/0.1/verify-enterprise-contract.yaml
> Clarify ec task usage in this repo

- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
This steps uses a python script for creating the sbom
https://github.com/redhat-appstudio/build-tasks-dockerfiles/tree/main/base-images-sbom-script
It expects 3 arguments:
1. path to the sbom file that will be updated in place with base images data
2. path to a file containing base images as taken from from the dockerfile (with preserved order)
3. path to a file containing base images with digests, generated from the output of buildah images --format '{{ .Name }}:{{ .Tag }}@{{ .Digest }}'.
The dockerfile order must be preserved as well
For more information, please read the script README
[STONEBLD-2042](https://issues.redhat.com//browse/STONEBLD-2042)
> Add a buildah task step that generates base images sbom

- pipelines/docker-build-rhtap/patch.yaml
Update deployment task should be skipped in pull request pipeline.
Pipelines as Code has different name of the event for GitHub and GitLab. Take both into account.
> Properly handle GitLab merge request event in RHTAP pipeline

- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
The reason is that this was failing in buildah remote task because the line
echo "$BASE_IMAGES" > /workspace/base_images_from_dockerfile
was executed on a VM via SSH and it was not restored afterwards. However, /workspaces/source is actually restored via
rsync -ra "$SSH_HOST:$BUILD_DIR/workspaces/source/" "$(workspaces.source.path)/" 
https://github.com/redhat-appstudio/build-definitions/blob/main/task/buildah-remote/0.1/buildah-remote.yaml#L326
So storing it in /workspaces/source should make it available in the end.
> Save base_images_from_dockerfile to /workspaces/source

- task/sbom-json-check/0.1/sbom-json-check.yaml
Refers to CVP-4048. With multi-arch builds, the sbom-json-check task is able to identify and consume an Image Index as input and check all Image Manifests in the Image Index.
> feat: Add multi-arch support in sbom-json-check task

- task/verify-enterprise-contract/0.1/verify-enterprise-contract.yaml
This should not be merged until *after*
[EC-518](https://issues.redhat.com/browse/EC-518) is resolved, since right now there are not v0.2 images of ec pushed out to registry.redhat.io. (Long story.)
It's expected this will resolve the root cause of
[RHTAPBUGS-1212](https://issues.redhat.com/browse/RHTAPBUGS-1212)
I'm aware of the dire warning at the top of this file, but IIUC this PR to change ref does indeed belong here.
> Use a newer version of ec in task definition

- task/rpm-ostree/0.1/rpm-ostree.yaml
This changes the rpm-ostree task to emit a new task result, SBOM_BLOB_URL. This result includes an image reference by digest to the SBOM of the image.
Context https://issues.redhat.com/browse/STONEBLD-2269
> Emit SBOM_BLOB_URL result on rpm-ostree task

- .tekton/pull-request.yaml
This change will make it such that our PR pipeline builds in response to merge queue events.
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
> ci(STONEBLD-2225): Build in response to merge queue events

- task/clair-scan/0.1/clair-scan.yaml
* Add unpatched_vulnerabilities field to leverage the updated clair policies that differentiate between fixable and unpatched vulnerabilities
> feat(STONEINTG-877): add unpatched_vulnerabilities field to clair-scan

- task/clamav-scan/0.1/clamav-scan.yaml
[CVP-4040] clamav scan should identify an image index, get all the image manifests in it and scan each one of them.
> Add multi-arch support for clamav scan

- task/fbc-validation/0.1/fbc-validation.yaml
* Add brew.registry.redhat.io/rh-osbs/openshift-ose-operator-registry-rhel9 base image to the list of allowed base images in the fbc-validation check task
> feat(STONEINTG-875): allow brew.registry.redhat.io in fbc-validation

- .tekton/pull-request.yaml
- .tekton/tasks/e2e-test.yaml
The pipeline used to pass APP_SUFFIX={{ pull_request_number }} to e2e tests. When a pull request enters the merge queue, it does so via a push event, not a pull request event. Pipelines as Code therefore does not expand the {{ pull_request_number }} placeholder, causing e2e tests to create Kubernetes objects with invalid names:
"test-app-{{ pull_request_number }}" is invalid: metadata.name: ...
The pull request number in the APP_SUFFIX is also used by e2e test code to determine the source url and revision for the pull request [1].
To fix the issues:
- use the {{ revision }} instead of the {{ pull_request_number }} for the suffix
- pass the source url and revision to the e2e tests directly instead of relying on the APP_SUFFIX [2]
- use ref-{{ revision }} as the suffix to make absolutely …
> Fix pull-request pipeline for the GH merge queue

- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
[STONEBLD-2280](https://issues.redhat.com//browse/STONEBLD-2280)
When the prefetch task prefetches RPMs for the correct architecture (the architecture of the machine which runs the buildah task), inject the generated cachi2.repo into the build.
Use the existing YUM_REPO_D_FETCHED mechanism for this, so that the cachi2 prefetch can hypothetically be compatible with other prefetch mechanisms.
> buildah: support prefetched RPMs

- task/rpm-ostree/0.1/rpm-ostree.yaml
[STONEBLD-2281](https://issues.redhat.com//browse/STONEBLD-2281)
If the prefetch task has generated an SBOM, merge it with the one
generated by Syft.
Copy-paste the step from the buildah task, just modify the condition:
check the existence of the SBOM file rather than checking the
PREFETCH_INPUT param (the rpm-ostree task doesn't have it).
> rpm-ostree: merge Cachi2 SBOM with Syft SBOM

- task/show-sbom/0.1/README.md
- task/show-sbom/0.1/show-sbom.yaml
- if IMAGE_URL is a multi-arch one, print out sbom
for each arch present
> fix(KFLUXBUGS-1152): add support for multi-arch

- pipelines/template-build/template-build.yaml
- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
buildah task
[KONFLUX-268](https://issues.redhat.com//browse/KONFLUX-268)
> new build-args-file parameter which allows to pass build arguments to

- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
- quotes within variable are not handled very well
by ssh command and it impacts the buildah-remote task
(which is based on this task)
we only need to know if prefetch was used, not the actual
input. Therefore, we inspect whether cachi2 has been called.
> fix(KFLUXBUGS-1215): fix use of PREFETCH_INPUT

- task/deprecated-image-check/0.1/README.md
- task/deprecated-image-check/0.1/deprecated-image-check.yaml
- task/deprecated-image-check/0.2/README.md
- task/deprecated-image-check/0.2/deprecated-image-check.yaml
v1 and v2 of deprecated-image-check are deprecated (for real now) and after deprecation date EC will start failing build verifications.
> chore(STONEINTG-758): deprecate old ver of deprecated-image-check

- pipelines/template-build/template-build.yaml
- task/prefetch-dependencies/0.1/README.md
- task/prefetch-dependencies/0.1/prefetch-dependencies.yaml
[KFLUXBUGS-1215](https://issues.redhat.com//browse/KFLUXBUGS-1215)
Cachi2 may fetch git tags from the source repository and/or clone other git repositories. Those may be private. Give the user a way to authenticate.
The basic-auth mechanism is copy-pasted from the git-clone task.
---
To fully replace #944, also
**prefetch-dependencies: expose log-level option**
> prefetch-dependencies: enable basic git auth

- task/init/0.2/init.yaml
We noticed that the `oc image info` call was executed regardless of whether the following conditions (REBUILD, SKIP_CHECKS) were set to echo `true` into the result.
This PR changes the order of evaluation so that the command execution is skipped if one of the other two parts already evaluates to true. 
This issue became apparent, when we changed the `image-url` to not include the tag part. `oc image info` will then return all images in the repository, e.g. all built images, all sbom and att images, which we'd like to avoid for sake of API server health & time. 
> # Before you complete this pull request ...
> Look for any open pull requests in the repository with the title "e2e-tests update" and 
#959 is …
> fix: reorder conditions in init task to avoid kube API calls

- task/verify-enterprise-contract/0.1/verify-enterprise-contract.yaml
_NOTE: As noted mentioned in the comments in the of the file, this change has no impact on Konflux since Konflux uses the upstream task definition, not this one._
Since EC has been declared GA, it's now able to push to the normal repo rather than the tech preview repo. So let's update the image reference in the verify-enterprise-contract task accordingly.
There's a similar change in the related task definition in the tssc-sample-pipelines repo, see https://github.com/redhat-appstudio/tssc-sample-pipelines/pull/39 .
Ref: [EC-571](https://issues.redhat.com/browse/EC-571)
Before you complete this pull request: Look for any open pull requests in the repository with the title "e2e-tests update" and  see if there are recent e2e-tests updates that will be applicable to your change.
> Use GA repo for the EC task ref used by RHTAP

- task/ecosystem-cert-preflight-checks/0.1/ecosystem-cert-preflight-checks.yaml
The ecosystem-cert-preflight-checks Task started reporting failure in the `TEST_OUTPUT` result for checks that fully passed. This is due to the incorrect declaration of the `SUPPORTED_ARCHES` array leading to the path to the `results.json` file containing the comma `,`, e.g. `artifacts/arm64,/results.json`.
In addition to this there are several other issues with the embedded script in the Task:
* Error handling is not turned on
* Variables are not quoted (see https://www.shellcheck.net/wiki/SC2086)
* Unnecessary `cat | jq` usage, jq can read the file directly
* Use of `expr` when `$((...))` expression can be used (see https://www.shellcheck.net/wiki/SC2003)
* Use of `>` for number comparison (see https://www.shellcheck.net/wiki/SC2071)
* Incorrect logic in the forming of the note text, if …
> Fix the script in ecosystem-cert-preflight-checks

- pipelines/template-build/template-build.yaml
- task/deprecated-image-check/0.4/MIGRATION.md
- task/deprecated-image-check/0.4/README.md
- task/deprecated-image-check/0.4/deprecated-image-check.yaml
Task `deprecated-image-check` will fetch data about base images also from SBOM.
This requires incompatible change, because users must update PLR definition with new parameters.
In future, konflux will stop provide BASE_IMAGES_DIGESTS via parameter, thus this param is optional now (we cannot remove it yet)
> feat(STONEINTG-887): get base images from SBOM

- .tekton/push.yaml
The `hack/build-and-push.sh` script if `OUTPUT_TASK_BUNDLE_LIST` and `OUTPUT_PIPELINE_BUNDLE_LIST` variables are not defined default to generating the list of Task and Pipeline bundles pushed relative to `SCRIPTDIR` which is the base directory where `build-and-push.sh` script resides, i.e. `$(workspaces.source.path)/source/hack`. This is in contrast to what the `build-acceptable-bundles` Task expects, i.e. that files with the list of Task and Pipeline bundles pushed is in `$(workspaces.artifacts.path)/source/`.
This leads to missing new versions of the Tasks and Pipelines in the `quay.io/redhat-appstudio-tekton-catalog/data-acceptable-bundles` image, and EC policy violations with code
`attestation_task_bundle.task_ref_bundles_trusted`, and error messages such as:
```
Pipeline task …
```
> Fix recording of pushed bundles

- .tekton/push.yaml
- .tekton/scripts/build-acceptable-bundles.sh
Passing arrays via environment variables (i.e. using `export`) is not supported, this leads to the `BUNDLES` variable to be undefined in the `build-acceptable-bundles.sh` script.
This also adds error handling and prefers to use `mapfile` instead of `awk` to generate command line parameters.
> Fix acceptable bundles build

- .tekton/push.yaml
The environment variables used in `hack/build-and-push.sh` start with `OUTPUT_`, this fixes the wrong variable names.
> Environment variables for `hack/build-and-push.sh`

- task/deprecated-image-check/0.4/deprecated-image-check.yaml
We need this change to get in so the Task bundle for 0.4 gets built and the new bundle is tracked by `ec track bundle` to get the 0.4 version of the Task in acceptable bundles
> Dummy change to get the new Task bundle built

- .tekton/push.yaml
Reverts redhat-appstudio/build-definitions#978
The change was on the wrong Task, in fact the variables were originally typed correctly. It has been a long day.
> Revert "Environment variables for `hack/build-and-push.sh`"

- task/deprecated-image-check/0.4/deprecated-image-check.yaml
Reverts redhat-appstudio/build-definitions#980
We need the `hack/build-and-push.sh` script to pass the Task bundle OCI reference via the `task-bundle-list` file to the `build-acceptable-bundles`, and it will not do this unless a new tag is generated for the Task, for `deprecated-image-check` the git commit id of the file will be used as it is not built using Kustomize. So this forces this to happen.
> Revert "Dummy change to get the new Task bundle built"

- task/deprecated-image-check/0.4/deprecated-image-check.yaml
This is to get the the rebuild of the Task bundle so that the acceptable bundles are updated with this and previous versions.
> Dummy change to the deprecated-image-check 0.4

- renovate.json
- task/clair-scan/0.1/README.md
- task/clair-scan/0.1/clair-scan.yaml
- task/clamav-scan/0.1/README.md
- task/clamav-scan/0.1/clamav-scan.yaml
- task/deprecated-image-check/0.1/README.md
- task/deprecated-image-check/0.1/deprecated-image-check.yaml
- task/deprecated-image-check/0.2/README.md
- task/deprecated-image-check/0.2/deprecated-image-check.yaml
- task/deprecated-image-check/0.3/README.md
- task/deprecated-image-check/0.3/deprecated-image-check.yaml
- task/deprecated-image-check/0.4/README.md
- task/deprecated-image-check/0.4/deprecated-image-check.yaml
- task/fbc-related-image-check/0.1/README.md
- task/fbc-related-image-check/0.1/fbc-related-image-check.yaml
- task/fbc-validation/0.1/README.md
- task/fbc-validation/0.1/fbc-validation.yaml
- task/inspect-image/0.1/README.md
- task/inspect-image/0.1/inspect-image.yaml
- task/sast-snyk-check/0.1/README.md
- task/sast-snyk-check/0.1/sast-snyk-check.yaml
- task/sbom-json-check/0.1/README.md
- task/sbom-json-check/0.1/sbom-json-check.yaml
- task/tkn-bundle/0.1/tkn-bundle.yaml
- task/verify-signed-rpms/0.1/verify-signed-rpms.yaml
hacbs-test repo has been migrated under konflux-ci org. It was also renamed to konflux-test.
Old images under hacbs-test repo have been kept for BW compatibility of tasks.
> feat(STONEINTG-839): hacbs-test migration

- pipelines/template-build/template-build.yaml
- task/prefetch-dependencies/0.1/prefetch-dependencies.yaml
The prefetch-dependencies task has some value even without hermetic builds. It provides dependency sources for the source container that would otherwise be missing, and AIUI it lets the SBOM generator know more details about the dependencies. (I'm speaking about go module prefetching, but I expect it's probably similar for other types of dependencies supported by cachi2.)
Currently prefetch-dependency task is includes whenever the `hermetic` param is set to "true". In this patch the logic is changed to include the prefetch-dependency task whenever a non-blank the prefetch-input param is provided.
This makes it easier for users to enable the prefetch-dependencies task even if they're not ready for hermetic builds.
This also better supports the use case for hermetic builds that don't …
> Allow prefetch to run without hermetic option

- hack/build-and-push.sh
Fixes several issues with the `hack/build-and-push.sh` script. See individual commits for details.
> Cleanup hack/build-and-push.sh

- .tekton/pull-request.yaml
To reduce the load on the prod cluster, let's skip running CI when the PR is WIP (draft)
* It is still possible to trigger CI test by commenting `/test` or `/retest` even when PR is WIP
* Since [PaC currently does not support event](https://pipelinesascode.com/docs/guide/authoringprs/#advanced-event-matching) `ready_for_review`, after converting a PR to "Ready for review" it's required to add a `test` comment (as mentioned above) to trigger CI
> feat: skip CI when the PR is in draft

- task/buildah-oci-ta/0.1/README.md
- task/buildah-oci-ta/0.1/buildah-oci-ta.yaml
- task/buildah-oci-ta/0.1/kustomization.yaml
- task/buildah-oci-ta/OWNERS
This pull request introduces a new Tekton Task, `buildah-oci-ta`. This is a variation of the `0.1/builah` Task. The main difference is that instead of expecting the application source code and the prefetched dependencies to come from a workspace, this Task consumes those as Trusted Artifacts from an OCI registry.
The Taks is not currently used in any of the default Pipelines. This will happen later on.
I tested this Task on a kind cluster like this:
```
🐚 oc -n default apply -f task/buildah-oci-ta/0.1/buildah-oci-ta.yaml 
task.tekton.dev/buildah-oci-ta configured
🐚 tkn -n default task start buildah-oci-ta --showlog \
--param IMAGE=quay.io/lucarval/ec-551:buildah  \
--param SOURCE_ARTIFACT=oci:quay.io/lucarval/ec-551@sha256:450d6a50de35262296c79860dcc3369a25eec205a39ac4d6921c13763412f103 \ …
```
> Add the new buildah-oci-ta Task

- task/prefetch-dependencies-oci-ta/0.1/README.md
- task/prefetch-dependencies-oci-ta/0.1/prefetch-dependencies-oci-ta.yaml
- task/prefetch-dependencies-oci-ta/OWNERS
This pull request introduces a new Tekton Task, `prefetch-dependencies-oci-task`. This is a variation of the `0.1/prefetch-dependencies` Task. The main difference is that instead of using a workspace, this Task stores the modified application source and the fetched dependencies as Trusted Artifacts in an OCI registry.
The Task is not currently used in any of the default Pipelines. This will happen later on.
I tested this Task on a kind cluster by first taking the Trusted Artifact generated by `git-clone-oci-ta` (https://github.com/redhat-appstudio/build-definitions/pull/1005), then starting the `prefetch-dependencies-oci-ta` Task like this:
```
$ tkn -n default task start prefetch-dependencies-oci-ta --showlog     --param input=gomod     --param …
```
> Add the new prefetch-dependencies-oci-ta Task

- task/sast-snyk-check-oci-ta/0.1/README.md
- task/sast-snyk-check-oci-ta/0.1/sast-snyk-check-oci-ta.yaml
- task/sast-snyk-check-oci-ta/OWNERS
This pull request introduces a new Tekton Task, `sast-snyk-check-oci-ta`. This is a variation of the `0.1/sast-snyk-check` Task. The main different is that instead of expecting the application source code to come from a workspace, this Task consumes the source code as a Trusted Artifact from an OCI registry.
The Task is not currently used in any of the default Pipelines. This will happen later on.
I tested this Task on a kind cluster like this:
```
🐚 oc -n default apply -f task/sast-snyk-check-oci-ta/0.1/sast-snyk-check-oci-ta.yaml
🐚 tkn -n default task start sast-snyk-check-oci-ta --showlog \
--param SOURCE_ARTIFACT=oci:quay.io/lucarval/ec-551@sha256:450d6a50de35262296c79860dcc3369a25eec205a39ac4d6921c13763412f103 \
--use-param-defaults
TaskRun started: sast-snyk-check-oci-ta-run-fsb7w …
```
> Add the new sast-snyk-check-oci-ta Task

- hack/trusted-tasks-update.sh
This script can be run if there is a CI failure and trusted tasks bundle has not been updated with the newest revisions (digest bumps) or versions (new versions of Tasks).
By default it will update both git and oci references, resolving the Tasks from the local git repository and from the remote quay.io repository (quay.io/redhat-appstudio-tekton-catalog by default).
Since there is no resolver that supports `kustomize`, the Task definitions that rely on it will not be included.
Fixes: https://issues.redhat.com/browse/EC-545
> Script to manually update trusted tasks

- task/source-build-oci-ta/0.1/README.md
- task/source-build-oci-ta/0.1/source-build-oci-ta.yaml
- task/source-build-oci-ta/OWNERS
This pull request introduces a new Tekton Task, `source-build-oci-ta`. This is a variation of the `0.1/source-build` Task. The main difference is that instead of expecting the application source code and the prefetched dependencies to come from a workspace, this Task consumes those as Trusted Artifacts from an OCI registry.
The Task is not currently used in any of the default Pipelines. This will happen later on.
I tested this Task on a kind cluster like this:
```
$ oc apply -f task/source-build-oci-ta/0.1/source-build-oci-ta.yaml
$ tkn -n default task start source-build-oci-ta --showlog \
--param BINARY_IMAGE=quay.io/lucarval/ec-551:buildah \
--param BASE_IMAGES='docker.io/library/golang:1.21@sha256:b58705289f65009af963d7704eee0473270a3a61a4c5b6e1379d9434cf9cb9cf …
```
> Add the new source-build-oci-ta Task

- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
I found that the syft step may take a non-negligble amount of time in my builds. Currently, it emits nothing to stdout, so it can feel like your build is stuck doing nothing.
By printing here, the user will get a clue as to what is happening.
> fix: log during syft step

- .tekton/pull-request.yaml
- .tekton/push.yaml
- .tekton/tasks/buildah.yaml
- .tekton/tasks/ec-checks.yaml
- .tekton/tasks/yaml-lint.yaml
- task/build-image-manifest/0.1/build-image-manifest.yaml
- task/clair-scan/0.1/clair-scan.yaml
- task/clamav-scan/0.1/clamav-scan.yaml
- task/deprecated-image-check/0.1/deprecated-image-check.yaml
- task/deprecated-image-check/0.2/deprecated-image-check.yaml
- task/deprecated-image-check/0.3/deprecated-image-check.yaml
- task/deprecated-image-check/0.4/deprecated-image-check.yaml
- task/fbc-related-image-check/0.1/fbc-related-image-check.yaml
- task/fbc-validation/0.1/fbc-validation.yaml
- task/git-clone/0.1/git-clone.yaml
- task/init/0.1/init.yaml
- task/inspect-image/0.1/inspect-image.yaml
- task/prefetch-dependencies/0.1/prefetch-dependencies.yaml
- task/rpm-ostree/0.1/rpm-ostree.yaml
- task/s2i-java/0.1/s2i-java.yaml
- task/s2i-nodejs/0.1/s2i-nodejs.yaml
- task/sast-snyk-check/0.1/sast-snyk-check.yaml
- task/sbom-json-check/0.1/sbom-json-check.yaml
- task/show-sbom/0.1/show-sbom.yaml
- task/slack-webhook-notification/0.1/slack-webhook-notification.yaml
- task/source-build/0.1/source-build.yaml
- task/summary/0.1/summary.yaml
- task/summary/0.2/summary.yaml
- task/update-infra-deployments/0.1/update-infra-deployments.yaml
This comment is getting copied everywhere everytime we add a new step or task.
It's true I asked for this to be put in place, but it takes on a life of its own when it lives as a comment in the task definitions like this.
> chore: drop comments explaining the tag+digest combination

- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
In certain cases, having a context set could change the meaning of a Containerfile. See:
https://github.com/containers/buildah/issues/5529
For details of a situation affecting Flatpaks and bootc images. This applies to both to any context from the CONTEXT parameter, and the implicit context from SOURCE_CODE_DIR. To avoid any possible problems, just change to the context directory and use a context argument of .
[edited to fix a wrong link]
> buildah: always use a context of .

- .tekton/tasks/e2e-test.yaml
The tkn-bundle tests need to push a bundle to quay. This change export the token from a secret.
https://issues.redhat.com/browse/EC-624
> export the quay token to push bundles during e2e tests

- task/git-clone-oci-ta/0.1/git-clone-oci-ta.yaml
- task/prefetch-dependencies-oci-ta/0.1/prefetch-dependencies-oci-ta.yaml
We should be consistent in our naming, makes for easier manipulation via tools.
> Use consistent naming for -oci-ta Tasks

- hack/generate-pipelines-readme.py
- hack/generate-readme.sh
- pipelines/docker-build-rhtap/README.md
- pipelines/docker-build-rhtap/patch.yaml
- pipelines/docker-build/README.md
- pipelines/docker-build/patch.yaml
- pipelines/fbc-builder/README.md
- pipelines/java-builder/README.md
- pipelines/nodejs-builder/README.md
- pipelines/tekton-bundle-builder/README.md
- task/buildah-oci-ta/0.1/README.md
- task/buildah-oci-ta/0.1/buildah-oci-ta.yaml
- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah-rhtap/0.1/buildah-rhtap.yaml
- task/buildah/0.1/README.md
- task/buildah/0.1/buildah.yaml
[STONEBLD-2462](https://issues.redhat.com//browse/STONEBLD-2462)
Add a BUILD_ARGS array parameter to allow users to pass build args
directly, not just via BUILD_ARGS_FILE.
This provides greater flexibility. Those who just need static build args
can commit a file into their repo and use BUILD_ARGS_FILE. Those who
need dynamic values can create a custom task and incorporate its return
value into the BUILD_ARGS array.
---
Also:
* generate-readme: handle array param defaults
* buildah: re-generate README
> buildah*: add BUILD_ARGS param

- task/buildah-oci-ta/0.1/buildah-oci-ta.yaml
- task/git-clone-oci-ta/0.1/git-clone-oci-ta.yaml
- task/prefetch-dependencies-oci-ta/0.1/prefetch-dependencies-oci-ta.yaml
- task/sast-snyk-check-oci-ta/0.1/sast-snyk-check-oci-ta.yaml
- task/source-build-oci-ta/0.1/source-build-oci-ta.yaml
More details in the comments. This will allow the tool in https://github.com/enterprise-contract/hacks/pull/82 to generate the equivalent TA variants to the human generated ones. Also helps that descriptions and volume usage is consistent, at least with this convention new TA Tasks would not diverge much.
> Consistency and automation indulgement 

- pipelines/enterprise-contract-everything.yaml
- pipelines/enterprise-contract-redhat-no-hermetic.yaml
- pipelines/enterprise-contract-redhat.yaml
- pipelines/enterprise-contract-slsa3.yaml
- pipelines/enterprise-contract.yaml
Allow to mention the path to the public key in the enterprise-contract pipelines. This is needed when running on non OCP k8s cluster.
> Configurable public key path for EC pipelines

- appstudio-utils/Dockerfile
Will be using this image in prepare-e2e-tasks task in integration tests of build-task-dockerfiles repo
Part of the story: https://issues.redhat.com/browse/STONEBLD-2353
> fix: add golang in the image

- pipelines/docker-build-oci-ta/README.md
- pipelines/docker-build-oci-ta/kustomization.yaml
- pipelines/docker-build-oci-ta/patch.yaml
- pipelines/kustomization.yaml
This Pipeline, based on the docker-build Pipeline, uses Trusted Artifacts stored in an OCI registry to share data between Tasks. No PVC is needed.
Ref: [EC-555](https://issues.redhat.com//browse/EC-555)
> Add docker-build-oci-ta Pipeline

- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
Replicates https://github.com/redhat-appstudio/build-definitions/pull/942, but for build task
Slack [convo](https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1715889582174049?thread_ts=1715795662.148729&cid=C04PZ7H0VA8)
> Custom CA bundle for build-task

- task/init/0.2/init.yaml
The init task is using an image hosted in registry.redhat.io in order to make use of the oc command. This change, instead, makes it use skopeo which can be found on an image in registry.access.redhat.com which does not require login.
> chore: convert init to use a public image

- task/git-clone/0.1/git-clone.yaml
A git-clone image built by Konflux to be used in the git-clone task.
> Use Konflux git-clone image

- policies/all-tasks.yaml
This enables the policy rules from the newly added `trusted_artifacts`[1] policy package to ensure the Tasks in this repo that use Trusted Artifacts follow the expects parameter and result naming convention.
[1] https://enterprisecontract.dev/docs/ec-policies/task_policy.html#trusted_artifacts_package
Ref: [EC-371](https://issues.redhat.com//browse/EC-371)
> Enable trusted_artifacts policy package for Tasks

- .tekton/pull-request.yaml
- .tekton/push.yaml
- .tekton/scripts/build-acceptable-bundles.sh
- .tekton/scripts/check-task-pipeline-bundle-repos.sh
- .tekton/tasks/e2e-test.yaml
- README.md
- appstudio-utils/README.md
- hack/build-and-push.sh
- hack/check-partner-tasks.sh
- hack/test-build.sh
- hack/trusted-tasks-update.sh
[STONEBLD-2339](https://issues.redhat.com//browse/STONEBLD-2339)
All the images published from this repo will now be pushed to `quay.io/konflux-ci/*`. Some will continue getting pushed to their old location.
| Old (continues getting updates?) | New |
| --- | --- |
| ✅ `redhat-appstudio-tekton-catalog/task-*` | `konflux-ci/tekton-catalog/task-*` |
| ✅ `redhat-appstudio-tekton-catalog/pipeline-*` | `konflux-ci/tekton-catalog/pipeline-*` |
| ✅ `redhat-appstudio-tekton-catalog/data-acceptable-bundles` | `konflux-ci/tekton-catalog/data-acceptable-bundles` |
| ❌ `redhat-appstudio-tekton-catalog/pull-request-builds` | `konflux-ci/pull-request-builds:(task\|pipeline)-*` |
| ❌ `redhat-appstudio/appstudio-utils` | `konflux-ci/appstudio-utils` |
| ❌ …
> Start pushing all images to quay.io/konflux-ci

- .tekton/tasks/ec-checks.yaml
- .tekton/tasks/yaml-lint.yaml
- policies/all-tasks.yaml
- renovate.json
- task/acs-deploy-check/0.1/acs-deploy-check.yaml
- task/download-sbom-from-url-in-attestation/0.1/download-sbom-from-url-in-attestation.yaml
- task/ecosystem-cert-preflight-checks/0.1/ecosystem-cert-preflight-checks.yaml
- task/gather-deploy-images/0.1/gather-deploy-images.yaml
- task/show-sbom/0.1/show-sbom.yaml
- task/summary/0.2/summary.yaml
- task/update-deployment/0.1/update-deployment.yaml
- task/upload-sbom-to-trustification/0.1/upload-sbom-to-trustification.yaml
[STONEBLD-2339](https://issues.redhat.com//browse/STONEBLD-2339)
All the images built in build-definitions CI now get released to the
quay.io/konflux-ci organization.
Replace the relevant redhat-appstudio[-tekton-catalog] references in
this repo with konflux-ci[/tekton-catalog] references.
> Migrate build-definitions redhat-appstudio images

- policies/all-tasks.yaml
The `trusted_artifacts` package now has a new polcy rule, `workspace`[1]` that aims to restrict the workspaces used by Tasks that implement the Trusted Artifacts pattern. By default, it does not allow any. This commit adds a list of allow workspaces which are meant for providing authentication details.
Ref: [EC-258](https://issues.redhat.com/browse/EC-258)
[1] https://enterprisecontract.dev/docs/ec-policies/task_policy.html#trusted_artifacts__workspace
> Allow certain workspaces in TA tasks

- .github/workflows/check-ta.yaml
- hack/generate-ta-tasks.sh
- task/buildah-oci-ta/0.1/README.md
- task/buildah-oci-ta/0.1/buildah-oci-ta.yaml
- task/buildah-oci-ta/0.1/recipe.yaml
- task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml
- task/git-clone-oci-ta/0.1/README.md
- task/git-clone-oci-ta/0.1/git-clone-oci-ta.yaml
- task/git-clone-oci-ta/0.1/recipe.yaml
- task/prefetch-dependencies-oci-ta/0.1/README.md
- task/prefetch-dependencies-oci-ta/0.1/prefetch-dependencies-oci-ta.yaml
- task/prefetch-dependencies-oci-ta/0.1/recipe.yaml
- task/sast-snyk-check-oci-ta/0.1/README.md
- task/sast-snyk-check-oci-ta/0.1/recipe.yaml
- task/sast-snyk-check-oci-ta/0.1/sast-snyk-check-oci-ta.yaml
- task/source-build-oci-ta/0.1/README.md
- task/source-build-oci-ta/0.1/recipe.yaml
- task/source-build-oci-ta/0.1/source-build-oci-ta.yaml
This includes the tool to generate the Trusted Artifacts Task variants in the `hack/build-and-push.sh` script, now if the task has a `recipe.yaml` file within its directory the tool will be used to regenerate the Trusted Artifact Task from the base Task.
Fixes https://issues.redhat.com/browse/EC-650
> Include tash in the Task bundle build

- task/prefetch-dependencies-oci-ta/0.1/prefetch-dependencies-oci-ta.yaml
- task/prefetch-dependencies-oci-ta/0.1/recipe.yaml
When prefetch-dependencies will not do anything we don't need to restore or create Trusted Artifacts, so this adds a step before those to create a marker file so that TA will not do anything. This optimizes the no-op case of prefetch-dependencies.
Reference: https://issues.redhat.com/browse/EC-480
> Create a skip markerfile in no-op case

- task/git-clone-oci-ta/0.1/README.md
- task/git-clone-oci-ta/0.1/git-clone-oci-ta.yaml
- task/git-clone/0.1/git-clone.yaml
Emit the commit timestamp as a result, this allows for subsequent tasks to consume it to get better reproducability.
> KONFLUX-3386 emit the commit timestamp

- task/eaas-provision-space/0.1/README.md
- task/eaas-provision-space/0.1/eaas-provision-space.yaml
- task/eaas-provision-space/OWNERS
This task is meant to be used before all other EaaS tasks/stepactions in a pipeline (such as #1058).
> Add eaas-provision-space task

- task/oci-copy-oci-ta/0.1/README.md
- task/oci-copy-oci-ta/0.1/oci-copy-oci-ta.yaml
- task/oci-copy-oci-ta/OWNERS
- task/oci-copy/0.1/README.md
- task/oci-copy/0.1/oci-copy.yaml
- task/oci-copy/OWNERS
The task is an alternative to our buildah task.
It should generally be disallowed by policy because there is not much that can be done to provide high quality provenance for the artifacts.
We'll allow it in limited cases, like in https://issues.redhat.com/browse/KONFLUX-3284
> Add an oci-copy task

- task/buildah-oci-ta/0.1/README.md
- task/buildah-oci-ta/0.1/buildah-oci-ta.yaml
- task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml
- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
This is a rebase of https://github.com/konflux-ci/build-definitions/pull/1017.
> buildah: Add an ADD_CAPABILITIES paramter

- pipelines/template-build/template-build.yaml
- task/clamav-scan/0.1/clamav-scan.yaml
- task/sast-snyk-check-oci-ta/0.1/README.md
- task/sast-snyk-check-oci-ta/0.1/sast-snyk-check-oci-ta.yaml
- task/sast-snyk-check/0.1/sast-snyk-check.yaml
For https://issues.redhat.com/browse/KONFLUX-2742
Will post example output
> feat(KONFLUX-2742): upload test results to quay as OCI artifacts

- task/oci-copy-oci-ta/0.1/README.md
- task/oci-copy-oci-ta/0.1/oci-copy-oci-ta.yaml
- task/oci-copy/0.1/README.md
- task/oci-copy/0.1/oci-copy.yaml
See https://github.com/enterprise-contract/ec-cli/issues/1698
ec expects to validate a signature for every image manifest referred to
in a image index. By exposing this additional result, we induce chains
to sign each one.
> fix: expose image manifest digest of all copied artifacts

- task/oci-copy-oci-ta/0.1/recipe.yaml
I didn't understand how the recipe worked before.
I figured this out in the course of working on https://github.com/konflux-ci/build-definitions/pull/1086, but I split this out to a separate PR.
> Add forgotten recipe for oci-copy task

- task/oci-copy-oci-ta/0.1/README.md
- task/oci-copy-oci-ta/0.1/oci-copy-oci-ta.yaml
- task/oci-copy-oci-ta/0.1/recipe.yaml
- task/oci-copy/0.1/README.md
- task/oci-copy/0.1/oci-copy.yaml
Update this to produce a single OCI artifact with a layer for each file, rather than an image index with an OCI artifact for each file.
> Refactor oci-copy task

- task/clamav-scan/0.1/clamav-scan.yaml
Recent version of the bundle resolver does a stricter validation and it is failing on the case sensitivity of `emptydir` (should be `emptyDir`).
> Fix clamav-scan task

- task/clair-scan/0.1/clair-scan.yaml
- task/clamav-scan/0.1/clamav-scan.yaml
- task/deprecated-image-check/0.1/deprecated-image-check.yaml
- task/deprecated-image-check/0.2/deprecated-image-check.yaml
- task/deprecated-image-check/0.3/deprecated-image-check.yaml
- task/deprecated-image-check/0.4/deprecated-image-check.yaml
- task/fbc-related-image-check/0.1/fbc-related-image-check.yaml
- task/fbc-validation/0.1/fbc-validation.yaml
- task/inspect-image/0.1/inspect-image.yaml
- task/sast-snyk-check-oci-ta/0.1/sast-snyk-check-oci-ta.yaml
- task/sast-snyk-check/0.1/sast-snyk-check.yaml
- task/sbom-json-check/0.1/sbom-json-check.yaml
- task/verify-signed-rpms/0.1/verify-signed-rpms.yaml
Update the `konflux-test` image to the newest [v1.4.3 release](https://github.com/konflux-ci/konflux-test/releases/tag/v1.4.3).
> chore: update konflux-test image references to v1.4.3

- pipelines/template-build/template-build.yaml
- task/buildah-oci-ta/0.1/buildah-oci-ta.yaml
- task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml
- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
- task/prefetch-dependencies-oci-ta/0.1/README.md
- task/prefetch-dependencies-oci-ta/0.1/prefetch-dependencies-oci-ta.yaml
- task/prefetch-dependencies/0.1/README.md
- task/prefetch-dependencies/0.1/prefetch-dependencies.yaml
[STONEBLD-2506](https://issues.redhat.com//browse/STONEBLD-2506)
* Update to cachi2 0.8.0 (among other things, introduces .netrc support and --index-url support for pip)
* Allow user to supply a workspace containing a .netrc file. Cachi2 will authenticate https requests using the credentials in this file.
> Support netrc auth for prefetch-dependencies

- task/git-clone-oci-ta/0.1/git-clone-oci-ta.yaml
- task/git-clone/0.1/git-clone.yaml
Previously, we were using the -f option for the readlink command. This means that if the symlink was broken (pointing to nonexistent file), the file path was not evaluated and the readlink command failed which meant that the git clone task failed as well.
By using the -m option, the symlink path will be evaluated every time. This means that we will not break builds that contain broken symlinks pointing to nonexistent files within the directory. However, if the symlink is pointing to nonexistent file OUTSIDE of the repo, we will fail the task, as expected to avoid security concerns.
[STONEBLD-2492](https://issues.redhat.com//browse/STONEBLD-2492)
> Check broken symlinks and don't fail on them unnecessarily

- task/buildah-oci-ta/0.1/README.md
- task/buildah-oci-ta/0.1/buildah-oci-ta.yaml
- task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml
- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/README.md
- task/buildah/0.1/buildah.yaml
We've got a particular need for this in the instructlab image, which must be squashed so that it can later be embedded in another container image (a bootc image).
> Add squash option for buildah task

- task/buildah-oci-ta/0.1/README.md
- task/buildah-oci-ta/0.1/buildah-oci-ta.yaml
- task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml
- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/README.md
- task/buildah/0.1/buildah.yaml
The secret is made available only to RUN lines that are invoked with `--mount`, like this:
```
RUN --mount=type=secret,id={secret-name} cat /run/secrets/{secret-name}
```
See https://docs.podman.io/en/latest/markdown/podman-build.1.html#secret-id-id-src-path
> feat: add buildah param to inject secrets into the build

- task/buildah-oci-ta/0.1/README.md
- task/buildah-oci-ta/0.1/buildah-oci-ta.yaml
- task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml
- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/README.md
- task/buildah/0.1/buildah.yaml
I got confused before in https://github.com/konflux-ci/build-definitions/pull/1107
`podman build` has both a `--squash` and a `--squash-all` option.
`buildah build` has only a `--squash` option which behaves like the `--squash-all` option from `podman build`.
We _just_ added this param earlier this morning. Hopefully we can remove it here without needing a task version bump.
> Remove the squash_all parameter

- task/buildah-oci-ta/0.1/buildah-oci-ta.yaml
- task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml
- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
This was omitted by accident in
https://github.com/konflux-ci/build-definitions/pull/1107
> fix: squash also the sbom layer

- task/buildah-oci-ta/0.1/buildah-oci-ta.yaml
- task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml
- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
Two bugs are fixed here.
First, the buildah `--secret` arg expects a *file*, not a directory, so every key/value pair in the kubernetes secrets mounted in needs to be supplied as a separate argument to buildah.
Second, buildah won't accept symlinks and all of the individual files in the mounted directory are symlinks. The `-L` option to `cp` addresses that by de-referencing them.
> Iterate over additional secret keys, making all available

- .gitignore
This gets generated as a side-effect when you run hack/build-and-push.sh
Is there any value in *not* ignoring it?
> Ignore bundle_values.env

- .tekton/tasks/e2e-test.yaml
E2e tests repo was onboarded in Konflux and now is using user workloads to save quay images
> Change e2e image to konflux workloads

- .tekton/push.yaml
Seems that scheduling Task pods often runs into issues, most likely the inability to mount persistent volumes caused by "volume node affinity conflict". To minimize this issue three separate bundle build Tasks are now combined into a single Tasks as three Steps instead.
Reference: https://issues.redhat.com/browse/EC-705
> Combine three bundle build tasks into one

- task/oci-copy-oci-ta/0.1/README.md
- task/oci-copy-oci-ta/0.1/oci-copy-oci-ta.yaml
- task/oci-copy/0.1/README.md
- task/oci-copy/0.1/oci-copy.yaml
The use case for this is copying artifacts into the OCI registry from locations that require some authentication, in particular https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1
> Incorporate auth param for oci-copy task

- .tekton/push.yaml
Follow up to #1112, let's not confuse folk by printing:
```
cat: /workspace/source/task-bundle-list-konflux-ci: No such file or directory
cat: /workspace/source/task-bundle-list-appstudio: No such file or directory
```
In the TaskRun logs. Those files do not exist if no Tasks were changed.
Reference: https://issues.redhat.com/browse/EC-705
> Skip bundle list files that have not been created

- task/oci-copy-oci-ta/0.1/oci-copy-oci-ta.yaml
- task/oci-copy/0.1/oci-copy.yaml
Originally, this task would download all artifacts requested in the input file, check them all, and then upload them all to the registry in one invocation of "oras push".
This had two problems. First, if "oras push" flaked out part way through and the user needed to retry their pipeline, the entire download section would need to be run again needlessly. Second, for extremely large artifacts with lots of medium-sized files, an enormous PVC would be needed to hold all of them between download and push to the registry.
The change here addresses both problems.
First, files are downloaded, checked, pushed to the registry and then deleted from local storage - one at a time. This obviates the need for a large volume to store all files at once, since only enough storage is needed to store one …
> Refactor oci-copy to be more efficient

- task/build-image-manifest/0.1/build-image-manifest.yaml
This means the task can also take manifest lists as an input, which is useful when dealing with OCI artifacts.
> Pass --all when building manifests

- hack/generate-ta-tasks.sh
This allows us to read the existing `-oci-ta.yaml` file without the redirection truncating the file first.
> Buffer output from `tash`

- renovate.json
- task/build-image-manifest/0.1/build-image-manifest.yaml
- task/buildah-oci-ta/0.1/buildah-oci-ta.yaml
- task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml
- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
Some changes:
* The image is built from https://github.com/konflux-ci/buildah-container
* The image is now built and released from Konflux so now we can easily track the provenance of the image
* The buildah image will just update the floating latest tag
* Buildah is now multi-arch
* Buildah has been updated to a recent commit and is therefore a newer verison
> Switch to a new buildah image source

- task/build-vm-image/0.1/build-vm-image.yaml
- task/build-vm-image/OWNERS
This is a duplicate of https://github.com/konflux-ci/build-definitions/pull/1059. I'm picking that up since stuart is on PTO.
I tried to address @mmorhun's first round of feedback there, here.
I'll close that one so we can focus on this one (although https://github.com/konflux-ci/build-definitions/pull/1042 is still valid).
> bootc build VM task

- pipelines/enterprise-contract.yaml
Depends on https://github.com/enterprise-contract/ec-cli/pull/1754
Reference: https://issues.redhat.com/browse/EC-735
Reference: https://issues.redhat.com/browse/EC-722
> Add timeout parameter to ec validation pipeline

- task/build-vm-image/0.1/build-vm-image.yaml
The way this previously worked was that each build-vm-image task would produce an image index (index1), which was later fed into a the build-image-index task to produce a second image index (index2), which (by use of the --all option) would throwaway the vm image's original index image (index1), keeping only its image manifest.
The problem this caused was that the vm image's original index image (index1) was exposed as a result, and not the image manifest. This meant that tekton chains would not see the image manifest, would not generate an attestation for it, and would not sign it.
Later, when trying to validate the aggregate index image (index2), policy checks would fail since the index image (index2) was signed, but non of the image manifests were signed.
The change here modifies …
> fix: expose image manifest from build-vm-image task                       

- task/build-image-manifest/0.1/build-image-manifest.yaml
- task/build-vm-image/0.1/build-vm-image.yaml
- task/buildah-oci-ta/0.1/README.md
- task/buildah-oci-ta/0.1/buildah-oci-ta.yaml
- task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml
- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah-rhtap/0.1/buildah-rhtap.yaml
- task/buildah/0.1/buildah.yaml
- task/s2i-java/0.1/s2i-java.yaml
- task/s2i-nodejs/0.1/s2i-nodejs.yaml
Some builds on remote VMs will fail if the storage driver is not set to the default of overlay. In order to enable this customization, I am exposing it as a parameter to allow it to be set on the PipelineRun instead of trying to configure the task generation to modify this property.
> Convert STORAGE_DRIVER to a buildah parameter

- .tekton/push.yaml
The build-bundles step uses the image built by the build-container step.
Without the runAfter relation, the step would start before the image has been built and eventually give up on trying to pull the not-yet-existing image.
> .tekton/push: add missing runAfter relation

- task/source-build-oci-ta/0.1/README.md
- task/source-build-oci-ta/0.1/source-build-oci-ta.yaml
- task/source-build/0.1/README.md
- task/source-build/0.1/source-build.yaml
[STONEBLD-2607](https://issues.redhat.com//browse/STONEBLD-2607)
When the BASE_IMAGES param is empty, fall back to reading the base image from the SBOM of the BINARY_IMAGE.
This removes the source-build task's dependency on the BASE_IMAGES_DIGESTS result, finally allowing us to stop returning this result from build tasks.
> source-build: read base image from SBOM

- .gitignore
- pipelines/docker-build-oci-ta/patch.yaml
- pipelines/docker-build-rhtap/patch.yaml
- pipelines/template-build/template-build.yaml
- task/push-dockerfile-oci-ta/0.1/README.md
- task/push-dockerfile-oci-ta/0.1/push-dockerfile-oci-ta.yaml
- task/push-dockerfile-oci-ta/0.1/recipe.yaml
- task/push-dockerfile-oci-ta/OWNERS
- task/push-dockerfile/0.1/README.md
- task/push-dockerfile/0.1/push-dockerfile.yaml
- task/push-dockerfile/OWNERS
[STONEBLD-2522](https://issues.redhat.com//browse/STONEBLD-2522)
Add a new task push-dockerfile to push Dockerfile to registry as an OCI
artifact.
Task is configurable to accept varaints of Dockerfile with different
names, like Containerfile.
Use `oras pull' to get the image.
This new task is added to docker-build pipeline and enabled by default.
Trusted Artifacts version of push-dockerfile is created accordingly and
updated into the docker-build-oci-ta pipeline.
> feat: push Dockerfile to registry

- renovate.json
We have a bunch of Go linters enabled, one of them checks that go.mod and go.sum are tidy. Renovate updates for Go modules fail this check almost every time. Try to fix the situation by making Renovate run go mod tidy.
https://docs.renovatebot.com/configuration-options/#postupdateoptions
> renovate: run go mod tidy

- task/buildah-oci-ta/0.1/buildah-oci-ta.yaml
- task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml
- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
In certain cases, we might have a FROM line which is from an archive exported by a pevious build stage; when we are pre-pulling images for a hermetic build, skip these images.
(Even if the oci-archive wasn't generated during the build, there's no point in pre-pulling a local URL.)
> buildah: Don't include oci-archive: FROM lines in BASE_IMAGES

- task/buildah-oci-ta/0.1/README.md
- task/buildah-oci-ta/0.1/buildah-oci-ta.yaml
- task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml
- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
Expose the --skip-unused-stages argument to Buildah as a parameter. This is needed to handle certain Containerfiles where stages have hidden side-effects like writing things to the context directory.
See https://github.com/containers/buildah/issues/5529 for details.
> Buildah: Add SKIP_UNUSED_STAGES parameter

- task/buildah-oci-ta/0.1/buildah-oci-ta.yaml
- task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml
- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
When the Syft SBOM didn't have the components property, the output was generated incorrectly because - the default empty list needed to be added back to image_sbom.
> buildah: Handle missing components property in syft-generated SBOM

- task/source-build-oci-ta/0.1/source-build-oci-ta.yaml
The oci-ta variant of the task doesn't have the /var/source-build volume
mount
> source-build-oci-ta: fix non-existent filepath

- pipelines/template-build/template-build.yaml
Someone may be confused when processing the build pipeline template YAML by kustomize directly and does not easily know what is the purpose of having fields, e.g. version, that are not valid field of tekton taskRef.
> Comment out how template-build is intended to be processed

- task-generator/remote/main.go
- task/buildah-oci-ta/0.1/README.md
- task/buildah-oci-ta/0.1/buildah-oci-ta.yaml
- task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml
- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
… tasks, including buildah-remoate-oci-ta. It also disables podman subscription-manager integration on all remote builders so that subscription-manager commands can be used to configure which repos are enabled.  
i had recently had a couple interactions with people smart about subscription mgmt and they all said that using certs the way we are is wrong and eventually will lead to random build failures due to revoked certs. Activation keys solves that problems, and it solves the problem that Camilla was having in this thread, so I just went ahead and did it.
ref slack thread https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1721226430548109
> add support for subscription activation keys to trusted artifacts

- task/buildah-oci-ta/0.1/buildah-oci-ta.yaml
- task/buildah-oci-ta/0.2/buildah-oci-ta.yaml
- task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml
- task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml
- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah-remote/0.2/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
- task/buildah/0.2/buildah.yaml
If you have a Dockerfile like:
```
RUN --mount=type=bind,from=somedir,to=/mnt/somewhere \
do-something /mnt/somewhere
```
then that will get mangled for a prefetch enabled build to:
```
RUN . /cachi2/cachi2.env && --mount=type=bind,from=somedir,to=/mnt/somewhere \
do-something /mnt/somewhere
```
Which is of course invalid. This patch uses a more complicated sed invocation to add the cache2.env after any leading options, and handling line continuations.
> buildah: add 'cachi2.env' after any mount options to RUN

- task/prefetch-dependencies-oci-ta/0.1/README.md
- task/prefetch-dependencies-oci-ta/0.1/prefetch-dependencies-oci-ta.yaml
- task/prefetch-dependencies/0.1/README.md
- task/prefetch-dependencies/0.1/prefetch-dependencies.yaml
Allow consumers to pass a cachi2 config to the tool in the prefetch task.
> Support cachi2 config passing in prefetch-dependencies

- task/build-vm-image/0.1/build-vm-image.yaml
This removes the default configuration (which also removes a default user and password from being injected into all images), instead deferring to the config.toml which is present in the source repository.
> Enable users to be able to provide their own config.toml

- task/buildah-oci-ta/0.2/README.md
- task/buildah-oci-ta/0.2/buildah-oci-ta.yaml
- task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml
- task/buildah-remote/0.2/README.md
- task/buildah-remote/0.2/buildah-remote.yaml
- task/buildah/0.2/buildah.yaml
- task/oci-copy-oci-ta/0.1/README.md
- task/oci-copy-oci-ta/0.1/oci-copy-oci-ta.yaml
- task/oci-copy/0.1/README.md
- task/oci-copy/0.1/oci-copy.yaml
- task/rpm-ostree/0.1/README.md
- task/rpm-ostree/0.1/rpm-ostree.yaml
- task/s2i-java/0.1/README.md
- task/s2i-java/0.1/s2i-java.yaml
- task/s2i-nodejs/0.1/README.md
- task/s2i-nodejs/0.1/s2i-nodejs.yaml
- task/source-build-oci-ta/0.1/README.md
- task/source-build-oci-ta/0.1/source-build-oci-ta.yaml
- task/source-build/0.1/README.md
- task/source-build/0.1/source-build.yaml
- task/tkn-bundle/0.1/README.md
- task/tkn-bundle/0.1/tkn-bundle.yaml
This helps in the reuse of the results when using matrix feature of Tekton. Given that the concatenation of two results from matrix-spawned Tasks is not supported, e.g.
$(tasks.build-container-multiarch.results.IMAGE_URL[*])@$(tasks.build-container-multiarch.results.IMAGE_DIGEST[*])
will not expand correctly.
This produces the image reference in full in the `IMAGE_REF` result, so the result from the matrix-spawned Tasks can be referenced using:
$(tasks.build-container-multiarch.results.IMAGE_REF[*])
Reference: https://issues.redhat.com/browse/EC-654
> `IMAGE_REF` result from image building Tasks

- .github/workflows/checkton.yaml
- hack/checkton-local.sh
Checkton is a GitHub action that runs ShellCheck on scripts embedded in YAML files (https://github.com/chmeliik/checkton)
> Add Checkton workflow

- .tekton/tasks/yaml-lint.yaml
Previously, the yaml-lint task (the custom script that checks for $(params.*) usage) would flag false positives such as
echo "set params.SOME_PARAM to do X"
Make the regex match actual param usage more closely
> CI: avoid false-positive $(params.*) detection

- .tekton/pull-request.yaml
STONEBLD-2339
The build-definitions repo has moved to the konflux-ci org. The
https://github.com/apps/rh-tap-build-team app had to be reinstalled in
the new org, thus changing the installation ID.
Update the installation ID for the create-comment task, which may try to
comment on build-definitions pull requests.
NOTE: do not update the default installation ID in the
update-infra-deployments task - infra-deployments is staying in the
redhat-appstudio org.
> Fix GH app installation ID for commenting on PRs

- pipelines/docker-build-oci-ta/README.md
- pipelines/docker-build/README.md
- task/buildah-oci-ta/0.2/buildah-oci-ta.yaml
- task/buildah-remote-oci-ta/0.2/README.md
- task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml
- task/buildah-remote/0.2/README.md
- task/buildah-remote/0.2/buildah-remote.yaml
- task/buildah/0.2/README.md
- task/buildah/0.2/buildah.yaml
Now that the BASE_IMAGE_DIGESTS result has been removed, there should be enough room for us to re-add the SBOM_BLOB_URL. This will enable EC verification of the SBOM based on the digest which is recorded in the provenenance. It will prevent supply-chain attacks which are driven by modifying the floating tag of the uploaded SBOM.
Even with the referrer's API, the digest can be used to identify which SBOM should be the one built from Konflux.
This was added in #645 and then removed in #654 due to the limitation of Tekton results' size.
> Create the SBOM_BLOB_URL for v0.2 buildah tasks

- task/buildah-oci-ta/0.2/buildah-oci-ta.yaml
- task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml
- task/buildah-remote/0.2/buildah-remote.yaml
- task/buildah/0.2/buildah.yaml
When there are no base images (i.e. it is FROM scratch), we need to make sure that the base_images_digests file exists.
> Ensure that /shared/base_images_digests exists

- pipelines/docker-build-rhtap/README.md
- pipelines/docker-build-rhtap/patch.yaml
As usual, the docker-build-rhtap pipeline has inherited unnecessary things from template-build.yaml because the approach of using kustomization to strip out tasks is fragile.
* Remove unnecessary tasks: apply-tags, push-dockerfile
* Remove unused workspace: netrc
> docker-build-rhtap: drop unnecessary things

- pipelines/gitops-pull-request-rhtap/gitops-pull-request.yaml
When the 'gather-deploy-images' task doesn't find any images that changed between the current ref and the base branch, it returns an empty string.
Skip the verify-ec and download-sbom -> upload-sbom tasks when this happens. Otherwise, those tasks would run unnecessarily and/or fail.
> gitops-pull-request: add missing when conditions

- task/operator-sdk-generate-bundle/0.1/README.md
- task/operator-sdk-generate-bundle/0.1/operator-sdk-generate-bundle.yaml
- task/operator-sdk-generate-bundle/OWNERS
Add a new custom task to generate the OLM bundle from the provided input
directory. This generates the on-disk representation of an operator (a
bundle) including the CSV, CRDs, manifests, additional metadata and the
Dockerfile to be built. Once built, it can be submitted to a catalog and
deployed to a cluster.
```
$ operator-sdk generate bundle \
--overwrite \
--version 4.16.265-f15333d \
--input-dir deploy/ \
--package osd-example-operator-bundle
Generating bundle version 4.16.265-f15333d
Generating bundle manifests
Building a ClusterServiceVersion without an existing base
Bundle manifests generated successfully in bundle
Generating bundle metadata
INFO[0000] Creating bundle.Dockerfile
INFO[0000] Creating bundle/metadata/annotations.yaml
INFO[0000] Bundle metadata generated successfully …
```
> SDCICD-1337: custom task to generate an olm bundle

- task/prefetch-dependencies-oci-ta/0.1/README.md
- task/prefetch-dependencies-oci-ta/0.1/prefetch-dependencies-oci-ta.yaml
- task/prefetch-dependencies-oci-ta/0.1/recipe.yaml
- task/prefetch-dependencies/0.1/README.md
- task/prefetch-dependencies/0.1/prefetch-dependencies.yaml
Add example how config file should be used
> Readme: prefetch-deps: example of usage of configfile

- task/oci-copy-oci-ta/0.1/README.md
- task/oci-copy-oci-ta/0.1/oci-copy-oci-ta.yaml
- task/oci-copy/0.1/README.md
- task/oci-copy/0.1/oci-copy.yaml
The existing bearer token auth is not sufficient for pulling from an S3 bucket. This enables just that: pulling content from an s3 bucket.
Policy mechanisms (already in place and merged) prevent redistributing content from buckets that are not explicitly allowed.
> Add S3 bucket authentication to oci-copy

- task/buildah-oci-ta/0.1/buildah-oci-ta.yaml
- task/buildah-oci-ta/0.2/buildah-oci-ta.yaml
- task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml
- task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml
- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah-remote/0.2/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
- task/buildah/0.2/buildah.yaml
only allow 1 method for subscription certs at a time; ensure certificates are not included in final image 
this commit updates activation-keys work to mount a temporary directory to /etc/pki/entitlement during the build. **This ensure that any certificates generated by "subscription-manager register" are not included in the final build.**
The subscription manager team has raised that new processes will revoke generated client subscriptions. On a normal machine using subscription-manager or insights, there is a regeneration process that runs and this is not an issue. In Konflux, when certificates stored as secrets are revoked nothing will regenerate them and it will result in a broken build.
For this reason, they asked us to push people to using activation-keys. This change will prefer …
> Use tmpfs for pki entitlements

- .gitignore
This is produced by local checkton runs.
> Ignore .checkton.sarif

- task/rpm-ostree/0.2/MIGRATION.md
- task/rpm-ostree/0.2/rpm-ostree.yaml
[STONEBLD-2326](https://issues.redhat.com//browse/STONEBLD-2326)
For consistency with the buildah tasks, don't return BASE_IMAGES_DIGESTS from rpm-ostree either.
> rpm-ostree: drop BASE_IMAGES_DIGESTS result

- pipelines/gitops-pull-request-rhtap/README.md
- pipelines/gitops-pull-request-rhtap/gitops-pull-request.yaml
Expose the FAIL_IF_TRUSTIFICATION_NOT_CONFIGURED param of the upload-sbom-to-trustification task as a pipeline param.
This allows the caller of the pipeline to decide if missing configuration should cause the pipeline to fail.
> gitops-pull-request: allow ignoring missing config

- task/opm-render-bundles/0.1/README.md
- task/opm-render-bundles/0.1/opm-render-bundles.yaml
- task/opm-render-bundles/OWNERS
Add a new custom task to generate the OLM catalog based on a bundle image. This creates the Dockerfile and generates the catalog contents by adding a single bundle and a single channel entry for that bundle to the catalog with a skip range to the latest version. OLM can then be treated in such a way that it will always upgrade to the latest version available in the catalog.
following the documentation[1] for creating raw FBCs
[1]: https://olm.operatorframework.io/docs/tasks/creating-a-catalog/#catalog-creation-with-raw-file-based-catalogs
PR #1153 will be used to generate the bundle that is fed into this task as a parameter. SRE-P operators are maintained without actively versioning or managing upgrade graphs; the latest version is always the version that should be running.
<details> …
> SDCICD-1338: custom task to generate OLM catalog

- .github/workflows/check-ta.yaml
- hack/generate-ta-tasks.sh
When the workflow fails it should attach a patch that folk can apply to get the needed changes on their PR.
Reference: https://issues.redhat.com/browse/EC-769
> Attach a patch for needed updates to the TA Tasks

- task/slack-webhook-notification/0.1/README.md
- task/slack-webhook-notification/0.1/slack-webhook-notification.yaml
For RHEL-AI, each time there is a new build, I'm receiving requests to explain what is in and what's not.
I figure out that adding some configuration file content that is relevant to the build + some git history about upstream repo (a submodule) + some links most people are able to work. So I created a custom slack notification task for that, an inline task.
Since it's inline, it's not trusted and make the release pipeline fail. After some iteration with @ralphbean, he convinces me that it would be better to remove that custom task rather than adding an exception.
This is my humble attempt to make my task generic so that it can be reused by other
> feat(task): Add capability to the slack task to dump file content and submodule git log

- task/oci-copy-oci-ta/0.1/oci-copy-oci-ta.yaml
- task/oci-copy/0.1/oci-copy.yaml
The aws v2 auth mechanism is deprecated.
Plus, for reasons I can't explain, the v2 auth doesn't work with _one_ set of files I'm trying to pull.
> chore: port oci-copy task to aws v4 auth

- pipelines/docker-build-oci-ta/README.md
- pipelines/docker-build/README.md
- pipelines/fbc-builder/README.md
- pipelines/java-builder/README.md
- pipelines/nodejs-builder/README.md
- task/show-sbom/0.1/README.md
- task/show-sbom/0.1/show-sbom.yaml
Support mounting a custom ca-bundle to allow the show-sbom task to use a registry with a self-signed certificate.
> feat(RHTAPWATCH-1019): support custom certificate in show-sbom

- task/buildah-oci-ta/0.2/buildah-oci-ta.yaml
- task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml
- task/buildah-remote/0.2/buildah-remote.yaml
- task/buildah/0.2/buildah.yaml
The build step already included support for mounting custom ca-bundle. This change introduces similar capabilities also to steps inject-sbom-and-push and upload-sbom.
> feat(RHTAPWATCH-1011): support custom certificate in buildah

- task/gather-deploy-images/0.1/gather-deploy-images.yaml
Short explanation: Clean up the code a little by using a variable.
Long explanation: This task gets converted to a bash script and wrapped by a Jenkins shared library in the brand new RHTAP Jenkins pipeline sample templates. When testing the RHTAP Jenkins pipeline I found the default Jenkins user could not write to `/tmp/`, so I wanted to change the location of the file. This refactor makes that just a single line change, rather than having to change the path in three places.
See also
https://github.com/redhat-appstudio/tssc-sample-jenkins/pull/1/ where this PR was suggested by @mmorhun, and also
https://github.com/jduimovich/tssc-jenkins/pull/2 where the cosign, Enterprise Contract, and promote pipeline support was being added to the RHTAP Jenkins templates.
> Use a var for the images file path in the RHTAP gather-deploy-images task

- task/push-dockerfile-oci-ta/0.1/push-dockerfile-oci-ta.yaml
- task/push-dockerfile-oci-ta/0.1/recipe.yaml
> fix: add missing stepTemplate for volume mounts

- task/build-image-manifest/0.1/build-image-manifest.yaml
- task/buildah-oci-ta/0.1/buildah-oci-ta.yaml
- task/buildah-oci-ta/0.2/buildah-oci-ta.yaml
- task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml
- task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml
- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah-remote/0.2/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
- task/buildah/0.2/buildah.yaml
This is a replacement for the PR
https://github.com/konflux-ci/build-definitions/pull/1262 as that did not include the necessary changes to the remote task definitions.
This includes a fix for KFLUXBUGS-1506.
> Update buildah to latest version

- stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/README.md
- stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/eaas-create-ephemeral-cluster-hypershift-aws.yaml
The default is increased to 30m to add more buffer for unforeseen performance issues.
> User configurable timeout for EaaS cluster provisioning

- task/opm-get-bundle-version/0.1/README.md
- task/opm-get-bundle-version/0.1/opm-get-bundle-version.yaml
- task/opm-get-bundle-version/OWNERS
this is needed to string together the dynamic bundle generation task to
the catalog generation task. The bundle ref is stored as a param in the
catalog pipeline (nudged), we need to fetch the version that was put in
the bundle to add an entry into the catalog with it.
```
❯ opm render ${BUNDLE_IMAGE}
{
"schema": "olm.bundle",
"name": "osd-example-operator.v4.16.0-28f1940",
"package": "osd-example-operator",
"image": "quay.io/redhat-user-workloads/oeo-cicada-tenant/osd-example-operator/bundle@sha256:5485652c17ab8ac5cf44452f67e15ed06dc9d2d7d67a7f079e76248878d5370e",
"properties": [
{
"type": "olm.gvk",
"value": {
"group": "managed.openshift.io",
"kind": "Example",
"version": "v1alpha1"
}
},
{
"type": "olm.package",
"value": {
"packageName": "osd-example-operator",
"version": …
```
> SDCICD-1358: custom task to get OLM bundle version

- pipelines/docker-build-oci-ta/patch.yaml
The way the docker-build-oci-ta Pipeline is defined, the prefetch-dependencies Task must always execute. In some cases this becomes a no-op operation and the provided source artifact is passed through to its result.
This change removes the `when` clause from the Task in the docker-build-oci-ta Pipeline. Without this, all Tasks are skipped after the prefetch-dependencies Task.
Ref: [KFLUXBUGS-1516](https://issues.redhat.com//browse/KFLUXBUGS-1516)
> Run prefetch-deps Task unconditionally in TA

- task/buildah-oci-ta/0.1/buildah-oci-ta.yaml
- task/buildah-oci-ta/0.2/buildah-oci-ta.yaml
- task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml
- task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml
- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah-remote/0.2/buildah-remote.yaml
- task/buildah/0.1/buildah.yaml
- task/buildah/0.2/buildah.yaml
closes https://github.com/konflux-ci/build-definitions/issues/1249 
When an activation key secret is not provided, Kubernetes still mounts a volume. This volume is also not truly empty but contains some symlinks in it. To ensure that the fallback to mounted certificates works for backwards compatibility, activation keys will only be mounted now if the 'org' key is present in the key/value secret. This is tested by checking for a file-like-object (-e) in the dir where the secret is mounted.
> issue-1249: entitlements cert not working using buildah task with support for activation keys

- hack/generate-buildah-remote.sh
- task-generator/remote/main.go
- task/buildah-oci-ta/0.2/buildah-oci-ta.yaml
- task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml
- task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml
- task/buildah-remote/0.1/buildah-remote.yaml
- task/buildah-remote/0.2/buildah-remote.yaml
- task/buildah/0.2/buildah.yaml
In order to reduce the likelihood of users accidentally forgetting to specify unique tags for each architecture, we can add a suffix to the pushed image
> Add an architecture suffix to images pushed for multi-platform if missing

- task/push-dockerfile-oci-ta/0.1/push-dockerfile-oci-ta.yaml
- task/push-dockerfile/0.1/push-dockerfile.yaml
By specifying the tag explicitly, the oras image gets update along with others in other tasks. Otherwise, two separate pull requests are created, one for tasks that reference oras image with tag latest and digest, and another one for this task.
> fix: specify tag for oras image

- renovate.json
[STONEBLD-2661](https://issues.redhat.com//browse/STONEBLD-2661)
buildah image is also specified in the .spec.stepTemplate.env. This custom manager updates the buildah image there.
> feat: add renovate customManager to update buildah image

- task/buildah-oci-ta/0.2/buildah-oci-ta.yaml
- task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml
- task/buildah-remote/0.2/buildah-remote.yaml
- task/buildah/0.2/buildah.yaml
- task/clair-scan/0.1/clair-scan.yaml
- task/clamav-scan/0.1/clamav-scan.yaml
IMO this needs to happen before https://github.com/redhat-appstudio/infra-deployments/pull/4275
Some support for these values: https://docs.google.com/document/d/1SvR7AP1UCU67bV0UvYhn6b8U30LCoPu9zcD5Wd1uAxk/edit?pli=1#heading=h.7kx4nf5n5g
> feat(KONFLUX-1503): Set some requests and limits so pods can spread across cluster nodes
