konflux-ci/build-definitions

task/download-sbom-from-url-in-attestation/0.1/download-sbom-from-url-in-attestation.yaml
[RHTAPBUGS-1289](https://issues.redhat.com//browse/RHTAPBUGS-1289)
Curl versions lower than 7.83.0 do not support the %header{...} syntax.
Write out all the headers and pick out the one we need using sed.
=> download-sbom: make auth work with curl < 7.83.0

task-generator/remote/main.go, task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.1/buildah-remote.yaml, task/buildah-remote/0.2/buildah-remote.yaml
It is reported some ssh conection interruptions during the long running remote build tasks. It is not yet 100% clear what causes it, but sending those keepalives might help to keep the channel up, or understood which side is closing the connections.
See https://issues.redhat.com/browse/KFLUXBUGS-1523 for more details
=> Add ssh keepalives into buildah-remote to prevent (or at least debug) the ssh conection interruptions

pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/fbc-builder/README.md, pipelines/java-builder/README.md, pipelines/nodejs-builder/README.md, pipelines/tekton-bundle-builder/README.md, task/sbom-json-check/0.1/README.md, task/sbom-json-check/0.1/sbom-json-check.yaml
Support mounting a custom ca-bundle to allow the sbom-json-check task to use a registry with a self-signed certificate.
=> feat(RHTAPWATCH-1177): support custom certificate in sbom-json-check

pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/java-builder/README.md, pipelines/nodejs-builder/README.md, pipelines/tekton-bundle-builder/README.md, task/clair-scan/0.1/README.md, task/clair-scan/0.1/clair-scan.yaml
Support mounting a custom ca-bundle to allow the clair-scan task to use a registry with a self-signed certificate.
=> feat(RHTAPWATCH-1171): support custom cert in clair-scan

task/operator-sdk-generate-bundle/0.1/README.md, task/operator-sdk-generate-bundle/0.1/operator-sdk-generate-bundle.yaml
allow setting `--kustomize-dir` flag when generating the bundle. This works for generating using a base CSV. If the string is empty (default), it will build without an existing base and generate the default CSV.
=> task/operator-sdk-generate-bundle: kustomize-dir param

task/operator-sdk-generate-bundle/0.1/README.md, task/operator-sdk-generate-bundle/0.1/operator-sdk-generate-bundle.yaml
allow for passing the `--extra-service-accounts` operator-sdk flag in to configure additional cluster permissions in the CSV
```
❯ operator-sdk generate bundle --overwrite \
--version 4.16.265-f15333d --input-dir deploy \
--package osd-example-operator --channels stable \
--kustomize-dir config/manifests/ --extra-service-accounts osd-example-admin
❯ cat bundle/manifests/osd-example-operator.clusterserviceversion.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
...
name: osd-example-operator.v4.16.265-f15333d
namespace: openshift-osd-example-operator
spec:
...
install:
spec:
clusterPermissions:
- rules:
- apiGroups:
- '*'
resources:
- '*'
verbs:
- '*'
- nonResourceURLs:
- '*'
verbs:
- '*'
serviceAccountName: osd-example-admin
...
```
=> task/operator-sdk-generate-bundle: --extra-service-accounts

renovate.json, task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.2/buildah.yaml, task/rpm-ostree/0.2/rpm-ostree.yaml
The steps merge-syft-sboms, merge-cachi2-sbom, create-purl-sbom, create-base-images-sbom were merged into single "prepare-sboms" step. This is done because the tekton results size for a task depends on the number of steps. By reducing the number of the steps we increase the limit.
The scripts from the individual steps were moved to the build-tasks-dockerfiles repo that also contains the Dockerfile for the sbom-utility-scripts image.
[STONEBLD-2608](https://issues.redhat.com//browse/STONEBLD-2608)
=> Merge sbom manipulation steps

pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/fbc-builder/README.md, pipelines/java-builder/README.md, pipelines/nodejs-builder/README.md, task/deprecated-image-check/0.4/README.md, task/deprecated-image-check/0.4/deprecated-image-check.yaml
Support mounting a custom ca-bundle to allow the deprecated-image-check task to use a registry with a self-signed certificate.
=> feat(RHTAPWATCH-1172): support custom cert in deprecated-image-check

task-generator/remote/main.go, task/build-image-manifest/0.1/build-image-manifest.yaml, task/buildah-oci-ta/0.1/buildah-oci-ta.yaml, task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.1/buildah-remote.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.1/buildah.yaml, task/buildah/0.2/buildah.yaml
By default, we should run builds matching the local architecture in-cluster to reduce the overhead of provisioning platforms. This will enable a fully matrixed build for all images using only the remote builds. This change will require the multi-platform controller to set the /ssh/host to localhost in order for the builds to run in-cluster.
In a change from the prior behavior of auto-appending the architecture to the tag, we will now append a sanitized version of the entire PLATFORM to the image tag upon request. This behavior is now needs to be explicitly requested which fixes a bug where users cannot specify the specific tag desired when using a remote build.
NOTE: There are not currently any local platforms configured. These need to be added before this PR have an effect in production.
=> Enable remote tasks to be run in cluster

pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/java-builder/README.md, pipelines/nodejs-builder/README.md, pipelines/tekton-bundle-builder/README.md, task/ecosystem-cert-preflight-checks/0.1/README.md, task/ecosystem-cert-preflight-checks/0.1/ecosystem-cert-preflight-checks.yaml
Support mounting a custom ca-bundle to allow the
ecosystem-cert-preflight-check task to use a registry with a self-signed certificate.
=> feat(RHTAPWATCH-1179): custom cert in ecosystem-cert-preflight-check

pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/fbc-builder/README.md, pipelines/java-builder/README.md, pipelines/nodejs-builder/README.md, pipelines/tekton-bundle-builder/README.md, task/apply-tags/0.1/README.md, task/apply-tags/0.1/apply-tags.yaml
Support mounting a custom ca-bundle to allow the apply-tags task to use a registry with a self-signed certificate.
=> feat(RHTAPWATCH-1178): support custom certificate in apply-tags

pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/java-builder/README.md, pipelines/nodejs-builder/README.md, task/clamav-scan/0.1/README.md, task/clamav-scan/0.1/clamav-scan.yaml
Support mounting a custom ca-bundle to allow the clamav-scan task to use a registry with a self-signed certificate.
=> feat(RHTAPWATCH-1180): support custom certificate in clamav-scan

.github/workflows/check-task-owners.yaml, hack/check-task-owners.sh, task/acs-deploy-check/OWNERS, task/acs-image-check/OWNERS, task/acs-image-scan/OWNERS, task/buildah-remote-oci-ta/OWNERS, task/download-sbom-from-url-in-attestation/OWNERS, task/gather-deploy-images/OWNERS, task/rpm-ostree/OWNERS, task/upload-sbom-to-trustification/OWNERS
- This PR adds a github workflow to check task owners file is present and having atleast  1 approver and 1 reviewer 
- Also adds missing owners file
=> STONEBLD-2649: add github action workflow to check task owners

renovate.json
We previously enabled a customManager for the buildah image used in buildah-remote (in e49a405ee38019dfa39abe66b2d85684efe881c0).
Since then, the name of the buildah image has changed to 'buildah-task', so the updates stopped working. Make the regex more general.
=> renovate: fix regex pattern for buildah image

task/sbom-json-check/0.1/README.md, task/sbom-json-check/0.1/sbom-json-check.yaml
We want to completely remove sbom-json-check task from build-definitions in future,
for now, we just want to inform customers about such fact.
=> feat(STONEINTG-931): adding deprecation warning for sbom-json-check task

task/build-vm-image/0.1/build-vm-image.yaml, task/prefetch-dependencies-oci-ta/0.1/prefetch-dependencies-oci-ta.yaml, task/prefetch-dependencies/0.1/prefetch-dependencies.yaml
Previously, some of the quay.io/konflux-ci/yq pullspecs included the tag and some did not. This made Renovate open two PRs to update yq instead of one.
=> Use :latest tag for yq image consistently

renovate.json
#1316 wasn't enough, the file pattern was broken too
Tested in https://github.com/chmeliik/build-definitions/pull/18
=> renovate: fix fileMatch pattern for regex manager

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-multi-platform-oci-ta/patch.yaml, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build-rhtap/patch.yaml, pipelines/docker-build/README.md, pipelines/docker-build/patch.yaml, pipelines/fbc-builder/README.md, pipelines/java-builder/README.md, pipelines/nodejs-builder/README.md, pipelines/tekton-bundle-builder/README.md, pipelines/template-build/template-build.yaml
This does not remove any of the java task dependencies but it will reduce a potential migration for new users that onboard. By removing the result, any users that onboard will have an easier migration.
=> Remove java references from pipelines

task/reduce-snapshot-to-single-component/0.1/README.md, task/reduce-snapshot-to-single-component/0.1/reduce-snapshot-to-single-component.yaml, task/reduce-snapshot-to-single-component/OWNERS
- This task, reduce-snapshot-to-single-component does nothing by default.
- If turned on, it will create a new single component Snapshot based on which component caused the Snapshot to be built.
=> feat(KONFLUX-4136): new reduce-snapshot task

renovate.json, task-generator/remote/main.go, task/buildah-oci-ta/0.1/buildah-oci-ta.yaml, task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.1/buildah-remote.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.1/buildah.yaml, task/buildah/0.2/buildah.yaml, task/rpm-ostree/0.1/rpm-ostree.yaml, task/rpm-ostree/0.2/rpm-ostree.yaml, task/s2i-java/0.1/s2i-java.yaml, task/s2i-nodejs/0.1/s2i-nodejs.yaml
[STONEBLD-2715](https://issues.redhat.com//browse/STONEBLD-2715)
Switch from quay.io/redhat-appstudio/syft to
registry.access.redhat.com/rh-syft-tech-preview/syft-rhel9.
The latter is built and released via Konflux (from
https://github.com/redhat-appstudio/rh-syft/) and is a bit more up to
date.
=> Use Konflux-built Syft image

task/fbc-validation/0.1/fbc-validation.yaml
* It is now allowed to have more than one olm.package within the FBC fragment
* The only remaining requirement is to have at least one olm.package entry
=> fix(KFLUXBUGS-1554): check if there are 0 FBC packages

task/build-image-index/0.1/build-image-index.yaml
This task was never added to the trusted tasks.
=> Trigger an update to the build-image-index task

.tekton/scripts/check-task-pipeline-bundle-repos.sh
The script had a bug (after 1a9375b67745b15eda6eee8bdf17713ac63a7600) that made it check only the "core-services" pipelines.
=> repo existence check: check all pipelines

renovate.json, ta-generator/golden/buildah/base.yaml, ta-generator/golden/buildah/ta.yaml, task/buildah-oci-ta/0.1/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml, task/buildah-remote/0.1/buildah-remote.yaml, task/buildah/0.1/buildah.yaml, task/oci-copy-oci-ta/0.1/oci-copy-oci-ta.yaml, task/oci-copy/0.1/oci-copy.yaml, task/rpm-ostree/0.1/rpm-ostree.yaml, task/rpm-ostree/0.2/rpm-ostree.yaml, task/s2i-java/0.1/s2i-java.yaml, task/s2i-nodejs/0.1/s2i-nodejs.yaml
Jira: [STONEBLD-2717](https://issues.redhat.com/browse/STONEBLD-2717)
Replace current uses of `redhat-appstudio/cosign` image with `konflux-ci/appstudio-utils` due to deprecation
of `redhat-appstudio` quay org and migration to `konflux-ci` org
=> remove redhat-appstudio/cosign image

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-multi-platform-oci-ta/patch.yaml, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build-oci-ta/patch.yaml, pipelines/docker-build-rhtap/patch.yaml, pipelines/docker-build/README.md, pipelines/docker-build/patch.yaml, pipelines/fbc-builder/README.md, pipelines/fbc-builder/patch.yaml, pipelines/java-builder/README.md, pipelines/nodejs-builder/README.md, pipelines/tekton-bundle-builder/README.md, pipelines/tekton-bundle-builder/kustomization.yaml, pipelines/template-build/template-build.yaml, task/sbom-json-check/0.2/MIGRATION.md, task/sbom-json-check/0.2/README.md, task/sbom-json-check/0.2/sbom-json-check.yaml
This change should help customers to remove sbom-json-check themselves from the pipeline.
=> STONEINTG-931: sbom-json-check deprecation

task/build-vm-image/0.1/build-vm-image.yaml, task/rpm-ostree/0.1/rpm-ostree.yaml, task/rpm-ostree/0.2/rpm-ostree.yaml
Part of the story: https://issues.redhat.com/browse/STONEBLD-2716
migrating away from `redhat-appstudio` quay org to `konflux-ci` org and use a similar existing image
=> chore: replace multi-platform-runner image with buildah-task image

task/build-vm-image/0.1/build-vm-image.yaml, task/rpm-ostree/0.1/rpm-ostree.yaml, task/rpm-ostree/0.2/rpm-ostree.yaml
This reverts commit 79b11ef741cec77d707f5670315f7d7b68322d9c. (#1348)
This change broke the ostree tasks due to the updated buildah version. This updated version includes
https://github.com/containers/common/commit/08fc0b450 which prevents the task from being able to use an OCI archive as desired.
=> Revert "replace multi-platform-runner image with buildah"

renovate.json, ta-generator/golden/buildah/base.yaml, ta-generator/golden/buildah/ta.yaml, task/buildah-oci-ta/0.1/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml, task/buildah-remote/0.1/buildah-remote.yaml, task/buildah/0.1/buildah.yaml, task/oci-copy-oci-ta/0.1/oci-copy-oci-ta.yaml, task/oci-copy/0.1/oci-copy.yaml, task/rpm-ostree/0.1/rpm-ostree.yaml, task/rpm-ostree/0.2/rpm-ostree.yaml, task/s2i-java/0.1/s2i-java.yaml, task/s2i-nodejs/0.1/s2i-nodejs.yaml
This reverts commit b26d80895ab291d635381d583379f66889df49aa. as introduced in #1344.
This change was causing issues with the sbom upload build steps. The task was using cosign image which allowed the arguments to be passed directly in the task args. The new image does not use cosign as the entrypoint so the image update breaks the builds.
=> Revert "remove redhat-appstudio/cosign image"

pipelines/docker-build-rhtap/README.md, pipelines/docker-build-rhtap/patch.yaml, task/acs-deploy-check/0.1/acs-deploy-check.yaml, task/update-deployment/0.1/update-deployment.yaml
update-deployment was using empty variable ${hostname} and it also wasn't setting up the ~/.gitconfig properly.
In acs-deploy-check, no credentials were being used whatsoever, so the gitops repo clone failed which caused failure of that task.
=> fix RHTAPBUGS-1305 setup git credential helper for private repos

task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.2/buildah.yaml
This is more reliable and allow us to fix bugs where base images were loaded incorrectly.
For example, previously this part in Dockerfile:
LABEL description="this is a build \
from single-arch"
Would return "single-arch" as a base image.
Using dockerfile-json also solves the problem of omitting "scratch" from the results.
Another advantage is that when we have something such as:
FROM registry.access.redhat.com/ubi9/ubi:latest as builder ...
FROM builder AS build1
then only the original image
"registry.access.redhat.com/ubi9/ubi:latest" will be reported.
[KFLUXBUGS-1269](https://issues.redhat.com//browse/KFLUXBUGS-1269)
=> Replace grep base images parsing with dockerfile-json

policies/all-tasks.yaml
Since certain EC policy rules rely on the existence of certain Task results, e.g. CLAIR_SCAN_RESULT, let's verify that these are defined during CI.
Ref: https://issues.redhat.com/browse/EC-794
=> Enable Task results check via EC

task/fbc-validation/0.1/README.md, task/fbc-validation/0.1/TROUBLESHOOTING.md, task/fbc-validation/0.1/USAGE.md, task/fbc-validation/0.1/fbc-validation.yaml
This update augments the fbc-validation task to enforce bundle metadata formats for incoming fragments based on the destination catalog's OCP release.
For OCP releases before 4.17, this will ensure that all bundles use only the `olm.bundle.object` object.  
For OCP releases at/after 4.17, this will ensure that all bundles use only the `olm.csv.metadata` object.
=> OPRUN-3458,OPRUN-3459: add policy enforcement for bundle metadata format based on OCP versions

task/fbc-validation/0.1/fbc-validation.yaml
OCP major version extraction was failing for base images with reference like `registry.redhat.io/openshift4/ose-operator-registry-rhel9@sha256:56e5c57b9d94bcadad6ff0cd47d157d35affc4bfd2c23a2ac948eee1cac3b8a3`. 
This changes behavior to test the OCP version major/minor elements which were extracted from the BASE_IMAGE supplied to the task.  If those elements are not numeric, then it will print a warning, e.g. 
```
!WARNING! - unable to assess bundle metadata alignment with OCP version because we cannot extract version info from BASE_IMAGE: brew.registry.redhat.io/rh-osbs/openshift-ose-operator-registry-rhel9@sha256:a3314d6dab5509fdd445ec81fb430eba7453fb56d674566fc6ef9354bc31bb3a
```
=> fix ocp major version extraction from base image tag

task-generator/remote/main.go, task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.1/buildah-remote.yaml, task/buildah-remote/0.2/buildah-remote.yaml
1. Create a source repo that builds an image that consumes build args
```
FROM alpine
ARG ARG1="test1"
ARG ARG2="test2"
RUN echo "arg1=${ARG1}" && echo "${ARG1}" > /arg1.txt
RUN echo "arg2=${ARG2}" && echo "${ARG2}" > /arg2.txt
```
2. Onboard a component with multi platform build.
3. Add `build-args` pipeline param:
```yaml
spec:
params:
- name: build-args
value: ["ARG1=val1", "ARG2=val2"]
```
5. Wait build finished and check the resulting arm image
=> Pass buildah build arguments to remote VM

hack/build-and-push.sh
Tagging with latest so applications can use this image with a floating tag. Using a floating tag ensures the latest utilities are used without updating the image.
https://issues.redhat.com/browse/EC-865
=> Tag appstudio-utils with latest

task/oci-copy-oci-ta/0.1/oci-copy-oci-ta.yaml, task/oci-copy/0.1/oci-copy.yaml
This is another take on https://github.com/konflux-ci/build-definitions/pull/1091, but it starts by modifying the oci-copy task first and then running hack/generate-ta-tasks.sh.
=> fix: drop use of /var/workdir in oci-copy task

task/build-image-index/0.1/build-image-index.yaml
Since we are passing --all to the buildah manifest add command, we enable all manifests referenced by an image index to be added to this index. If that happens, then we will only expose the digest of the image index and not all image manifests.
By post-processing the image index to identify all manifests, we can ensure that we have identified all image manifests referenced.
=> Ensure that we know all image mainfests added to the index

.tekton/push.yaml
Using a floating tag so applications can use the latest utilities without updating the image tag.
https://issues.redhat.com/browse/EC-865
=> Tagging appstudio-utils with latest

.tekton/push.yaml
The IMAGE_REF result is not supported in this version. Using IMAGE_URL instead. This will fix the CI issue on push.
=> The buildah task does not support IMAGE_REF

task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.2/buildah.yaml
It is possible to use a build arg to specify the base image for a stage:
ARG BASE_IMAGE=foo
FROM $BASE_IMAGE
...
Pass --build-arg values to dockerfile-json to make sure we resolve the
base images properly.
=> buildah: resolve BUILD_ARGS in base images

task/operator-sdk-generate-bundle/0.1/README.md, task/operator-sdk-generate-bundle/0.1/operator-sdk-generate-bundle.yaml
in order to comply with the required labels check, the generated dockerfile needs to have labels amended to it. By providing an additional file with this data, it can be appended in order to pass the compliance check.
```
❯ cat -p config/metadata/additional-labels.txt
LABEL com.redhat.component="openshift-osd-example-operator" \
description="A sample operator used for testing SREP tooling" \
distribution-scope="public" \
io.k8s.description="A sample operator used for testing SREP tooling" \
name="openshift/osd-example-operator" \
release="v0.0.0" \
url="https://github.com/openshift/osd-example-operator" \
vendor="Red Hat" \
version="v0.0.0"
```
Below is the summarized output of running the task locally
```
...
[generate-bundle : operator-sdk-generate-bundle] + operator-sdk generate bundle …
```
=> task/operator-sdk-generate-bundle: allow for supplying additional labels

.tekton/pull-request.yaml, .tekton/tasks/e2e-test.yaml, hack/build-and-push.sh
This commit passes new environment variables to the e2e tests containing references to the oci-ta build Pipelines. This allows us to test those Pipelines.
Ref: [EC-715](https://issues.redhat.com//browse/EC-715)
=> Propagate oci-ta Pipelines to e2e-tests

hack/build-and-push.sh
Due to https://github.com/tektoncd/cli/issues/2402, annotation values that contain commas or double-quotes currently break 'tkn bundle push'.
Escape such annotation values in a way that's compatible with the pflag.StringSlice [1] parser that 'tkn bundle push' uses to parse CLI arguments.
https://pkg.go.dev/github.com/spf13/pflag#FlagSet.StringSlice
=> build-and-push: escape annotation values

task/oci-copy-oci-ta/0.1/oci-copy-oci-ta.yaml, task/oci-copy/0.1/oci-copy.yaml
There is no volumeMount for workdir in the oci-copy task, and it's presence in the volumes causes duplicate volumes in the oci-copy-oci-ta Task.
This could also be resolved by making the generator aware of duplicate volumes and volumeMounts. Let's do that if it indeed does become an issue.
=> Removes unused workdir volume form oci-copy Task

.tekton/pull-request.yaml, .tekton/push.yaml
The PR pipeline already runs Snyk, but doesn't upload the results
anywhere. Run Snyk in the push pipeline as well and upload the results
to snyk.io.
Note: we should not upload to Snyk from the PR pipeline. Each PR would
overwrite the Snyk results from other PRs. By uploading only in the push
pipeline, the results will at least always reflect the state in 'main'.
The results can be found in the 'konflux-ci/build-definitions' project
in the Snyk organization associated with the Snyk token used by the
pipeline (currently the 'developer-red-hat-trusted-application-pipeline'
organization).
=> Upload Snyk report to snyk.io on push

.tekton/pull-request.yaml
Fail the pipeline when build-and-push.sh fails, don't proceed to the e2e-tests (which would fail anyway)
=> CI: don't ignore build-and-push failures

task/clair-scan/0.1/clair-scan.yaml, task/clamav-scan/0.1/clamav-scan.yaml, task/deprecated-image-check/0.4/deprecated-image-check.yaml, task/sbom-json-check/0.1/sbom-json-check.yaml, task/sbom-json-check/0.2/sbom-json-check.yaml
In order to fix KFLUXBUGS-1616, we need to ensure the digest of the Image Index is also included in the list of PROCESSED_IMAGES. This will allow EC to verify the Image Index directly as well as the Image Manifests.
=> Include Image Index digest in PROCESSED_IMAGES

renovate.json, task/oci-copy-oci-ta/0.1/oci-copy-oci-ta.yaml, task/oci-copy/0.1/oci-copy.yaml, task/rpm-ostree/0.1/rpm-ostree.yaml, task/rpm-ostree/0.2/rpm-ostree.yaml, task/s2i-java/0.1/s2i-java.yaml, task/s2i-nodejs/0.1/s2i-nodejs.yaml
redhat-appstudio/cosign image is getting deprecated due to migration to konflux-ci, replace with konflux-ci/appstudio-utils image
[STONEBLD-2717](https://issues.redhat.com/browse/STONEBLD-2717), related previous reverted attempt https://github.com/konflux-ci/build-definitions/pull/1344
This PR has been tested by running `./hack/test-builds.sh` locally and checking that pipelines pass and SBOMs are pushed to the Quay namespace.
=> replace cosign image with appstudio-utils

renovate.json, task/update-infra-deployments/0.1/update-infra-deployments.yaml
[STONEBLD-2718](https://issues.redhat.com/browse/STONEBLD-2718)
The quay.io/redhat-appstudio/github-app-token image is highly suspect.
- It is a copy of quay.io/chmouel/github-app-token - an image in a
personal namespace with unclear origins and content.
- It has not been updated for 4 years.
- It has 175 critical vlunerabilities according to quay.io.
Update the update-infra-deployments task to no longer depend on anything this
image provides and replace it with a generic python image.
=> Stop using the github-app-token image

stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
- Add admin username and password in the credentials volume
- Add `APIserverURL` and `ConsoleURL` status field values from the CTI in the results
=> chore(RHTAPWATCH-1248): Provide admin user/pwd combo for ephemeral clusters

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/fbc-builder/README.md, pipelines/java-builder/README.md, pipelines/nodejs-builder/README.md, pipelines/tekton-bundle-builder/README.md, task/build-image-index/0.1/README.md, task/build-image-index/0.1/build-image-index.yaml
In order to have consistency between all image build tasks, we should also set the IMAGE_REF result when building the image index.
=> Add the IMAGE_REF parameter to the image index task

policies/all-tasks.yaml
Because some EC policy rules rely on the existence of the RPMS_DATA result, this commit adds a check to ensure future modifications of the `rpms-signature-scan` Task continues to define the result.
Ref: https://issues.redhat.com/browse/EC-846
=> Ensure rpms-signature-scan emits expected result

pipelines/docker-build-rhtap/patch.yaml
[RHTAPBUGS-1307](https://issues.redhat.com//browse/RHTAPBUGS-1307)
The update-deployment task is supposed to run on push, but has been
reported to run for MR comments as well. To fix this, rather than
excluding the task for "pull_request" and "Merge Request" event types,
run the task only for "push" and "Push" event types.
---
Based on the pipelines-as-code codebase [1], mainly
pkg/provider/*/parse_payload.go, the possible events and their
corresponding event_type values are:
|                | anything except gitlab            | gitlab
|----------------|-----------------------------------|---------------
| PR             | pull_request                      | Merge Request
| PR comment     | pull_request*                     | pull_request**
| push           | push …
=> rhtap: fix update-deployment condition

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build-rhtap/README.md, pipelines/docker-build/README.md, pipelines/fbc-builder/README.md, pipelines/gitops-pull-request-rhtap/README.md, pipelines/java-builder/README.md, pipelines/nodejs-builder/README.md, pipelines/tekton-bundle-builder/README.md, task/git-clone-oci-ta/0.1/README.md, task/git-clone-oci-ta/0.1/git-clone-oci-ta.yaml, task/git-clone/0.1/README.md, task/git-clone/0.1/git-clone.yaml
It's helpful to have a short commit SHA for use in other tasks, such as `apply-tags`. The length of `short-commit` is also configurable, giving greater flexibility to the pipeline author.
=> git-clone: Add configurable `short-commit` result

task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.2/buildah.yaml
Commit f12435b933 (Replace grep base images parsing with dockerfile-json) accidentally reverted fdc3d9c57cc (buildah: Don't include oci-archive: FROM lines in BASE_IMAGES)
Original commit message:
In certain cases, we might have a FROM line which is from an archive
exported by a pevious build stage; when we are pre-pulling images
for a hermetic build, skip these images.
(Even if the oci-archive wasn't generated during the build, there's
no point in pre-pulling a local URL.)
See https://github.com/konflux-ci/build-definitions/pull/1158
=> buildah: restore exclusion of "FROM oci-archive:"

.github/workflows/check-buildah-remote.yaml, .github/workflows/checkton.yaml, .github/workflows/go-ci.yaml, .github/workflows/yaml-lint.yaml, .tekton/pull-request.yaml, .tekton/tasks/task-lint.yaml, partners/README.md
[STONEBLD-2791](https://issues.redhat.com/browse/STONEBLD-2791)
- Container image used in yaml-lint task is outdated and using it causes rate-limiting issues with docker.io
- Remove the yaml-lint task to task-lint and remove yamllint part
- Create a GitHub Action that runs yamllint
- Fix yamllint warnings
- Double quote the `on` keyword
`on` -> `"on"`
- Fix comment indentation
Tested locally by using `act`. Added random things to random YAMLs in order to make the lint fail and it indeed failed.
=> ci: migrate yamllint to GitHub Actions

task/clamav-scan/0.1/clamav-scan.yaml
=> fix(STONEINTG-1054):add wait for clamav db files to exist

task/fbc-validation/0.1/fbc-validation.yaml
* The BASE_IMAGE result from the inspect-image task is supposed to be referenced by digest and is supposed to be used as such in other checks within the fbc-validation task
* Switch to extracting the base image name from the org.opencontainers.image.base.name for the needs of getting the base image tag and deriving the OCP version from it
=> fix(KFLUXBUGS-1601): use the base image name label to get its tag

.tekton/push.yaml, .tekton/scripts/check-task-pipeline-bundle-repos.sh, hack/build-and-push.sh
[STONEBLD-2720](https://issues.redhat.com//browse/STONEBLD-2720)
* Stop pushing task bundles for new tasks (those that didn't exist before this PR got merged)
* Stop pushing pipeline bundles
* Related PRs:
* https://github.com/konflux-ci/ci-helper-app/pull/55
* https://github.com/konflux-ci/quality-dashboard/pull/340
* https://github.com/redhat-appstudio/managed-gitops/pull/812
* https://github.com/containerbuildsystem/cachi2/pull/661
* https://github.com/openshift-pipelines/pipeline-service-exporter/pull/73
* https://github.com/konflux-ci/docs/pull/137
* These don't need to be merged before this PR gets merged. If they're not merged, the worst that can happen is that the affected services will use an outdated build pipeline.
* Stop pushing data-acceptable-bundles
* one related MR in an …
=> Don't push unnecessary things to redhat-appstudio-tekton-catalog

task/fbc-validation/0.1/fbc-validation.yaml
=> fix(KFLUXBUGS-1601): move fbc base image label check

pipelines/fbc-builder/README.md, pipelines/fbc-builder/patch.yaml
Fixes https://github.com/konflux-ci/build-definitions/issues/1426
Remove hardcoded `HERMETIC="true"` in `build-container` task for the FBC pipeline.
=> Use `hermetic` param in FBC builder pipeline to configure `build-container` task

task/buildah-oci-ta/0.1/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml, task/buildah-remote/0.1/buildah-remote.yaml, task/buildah/0.1/buildah.yaml, task/rpm-ostree/0.1/rpm-ostree.yaml, task/s2i-java/0.1/s2i-java.yaml, task/s2i-nodejs/0.1/s2i-nodejs.yaml
[STONEBLD-2747](https://issues.redhat.com/browse/STONEBLD-2747)
- Results with BASE_IMAGES_DIGESTS are too large and cause builds to hit the Tekton result size
limit
- Deprecate all tasks using the result so they will be unsupported after 2024-11-13T00:00:00Z
=> deprecate images using BASE_IMAGES_DIGESTS result

task/apply-tags/0.1/apply-tags.yaml
When copying an image manifest, `skopeo` by default only copies the image matching the architecture of the system running `skopeo`. It does not copy the image manifest as expected.
In my testing, adding the `--multi-arch all` flag on single architecture images works without error.
=> apply-tags: Tag multi-arch images as expected

task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.2/buildah.yaml
When generating the SBOM, we do not constrain the source analysis to the build context. This can result in many additional dependencies being included than should be.
=> fix(KFLUXBUGS-1666): Only analyze build context for dependencies

task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.2/buildah.yaml
[STONEBLD-2795](https://issues.redhat.com//browse/STONEBLD-2795)
Instead, make a copy outside the repo and modify the copy. This is to
avoid dirtying the repo.
For example, when combined with the push-dockerfile task, the pipeline
will now push the original dockerfile instead of pushing the modified
one.
=> buildah: don't modify Dockerfile in place

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build-rhtap/README.md, pipelines/docker-build/README.md, pipelines/fbc-builder/README.md, pipelines/java-builder/README.md, pipelines/nodejs-builder/README.md, pipelines/tekton-bundle-builder/README.md, pipelines/template-build/template-build.yaml
=> chore(RHTAPWATCH-1297): Add rpms-signature-scan to template

task/buildah-10gb/0.1/patch.yaml, task/buildah-10gb/0.2/patch.yaml, task/buildah-20gb/0.1/patch.yaml, task/buildah-20gb/0.2/patch.yaml, task/buildah-24gb/0.1/patch.yaml, task/buildah-24gb/0.2/patch.yaml, task/buildah-6gb/0.1/patch.yaml, task/buildah-6gb/0.2/patch.yaml, task/buildah-8gb/0.1/patch.yaml, task/buildah-8gb/0.2/patch.yaml
Since it's possible to set task resources from pipeline run in Konflux ([docs](https://konflux-ci.dev/docs/how-tos/configuring/overriding-compute-resources/)), we are deprecation `buildah-*gb` tasks.
=> Deprecate buildah task resource variations

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/java-builder/README.md, pipelines/nodejs-builder/README.md, pipelines/tekton-bundle-builder/README.md, task/clair-scan/0.2/README.md, task/clair-scan/0.2/clair-scan.yaml, task/clair-scan/0.2/spec/clair_scan_spec.sh
This attaches the "clair"-formatted output of the `clair-action` command to the scanned image. Contrary to the `sast-snyk-check` Task only a single variant of attachment method is supported, based on the registry support. For quay.io OCI Distribution 1.1. Referrers API will be used.
The `clair-action` needs to be run twice as the Rego rules executed in the `conftest-vulnerabilities` require the "quay" format, which does not include any date information, whereas the (future) EC policy Rego rules require the "clair" format, which does.
Resolves: https://issues.redhat.com/browse/EC-837
Notes for reviewers:
- should this be uploading both OCI 1.1 distribution referrers tag and API variants, analogous to the sast-snyk-check Task?
- is there a better MIME type other than …
=> OCI-attach reports from `clair-scan` 0.2 Task

task/oci-copy-oci-ta/0.1/oci-copy-oci-ta.yaml, task/oci-copy/0.1/oci-copy.yaml
Some build is failing because of this.
I think the problem is that set -u is set after the function definition but *before* the function is called
EDIT: I'm talking about this set: https://github.com/konflux-ci/build-definitions/blob/main/task/oci-copy/0.1/oci-copy.yaml#L186
Build is failing because of 
> /tekton/scripts/script-1-qxwgg: line 11: AWS_ACCESS_KEY_ID: unbound variable
When I'm not providing AWS creds
=> fix: oci-copy task triggers unbounded var error when not using AWS creds

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build-rhtap/README.md, pipelines/docker-build/README.md, pipelines/fbc-builder/README.md, pipelines/java-builder/README.md, pipelines/nodejs-builder/README.md, pipelines/tekton-bundle-builder/README.md, pipelines/template-build/template-build.yaml, task/rpms-signature-scan/0.2/MIGRATION.md, task/rpms-signature-scan/0.2/README.md, task/rpms-signature-scan/0.2/rpms-signature-scan.yaml
The fail-unsigned parameter was removed from the task.
The task will only fail if the scanner fails, otherwise it will end successfully providing the RPMS_DATA result with the signature keys and the number of unsigned RPMs.
EC will process the result and determine whether it should pass or fail.
- Bumping to v0.2
- Update task
- Add MIGRATION.md
- Update template version
=> fix(KFLUXBUGS-1693): remove fail-unsigned param from task

task/rpm-ostree/0.2/rpm-ostree.yaml
Related to https://gitlab.com/redhat/centos-stream/containers/bootc/-/merge_requests/248
Basically a while ago the rpm-ostree task was forked from the buildah task and we didn't inherit the later change to use `set -e` (as we should) on the inner shell script, meaning we had the default "blindly stumble forward when we hit an error" which is never what we want.
This would have helped focus the problem on cachi2, not selinux.
=> tasks: Use set -e in rpm-ostree task

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build-rhtap/README.md, pipelines/docker-build/README.md, pipelines/fbc-builder/README.md, pipelines/tekton-bundle-builder/README.md, pipelines/template-build/template-build.yaml
=> make rpm-signature-scan depend on image index

task/clair-scan/0.2/clair-scan.yaml
This was missed when the v0.2 version of the clair-scan Task was introduced.
Ref: https://issues.redhat.com/browse/EC-906
=> Include image index digest in clair-scan Task

.tekton/pull-request.yaml, task/sast-unicode-check/0.1/README.md, task/sast-unicode-check/0.1/sast-unicode-check.yaml, task/sast-unicode-check/OWNERS
=> sast: Add sast-unicode-check task for testing

.tekton/scripts/check-task-pipeline-bundle-repos.sh
- Message in the check-task-pipeline-bundle-repos script says to contact `#forum-stonesoup-build`
- This channel was renamed to `#forum-konflux-build`
=> update outdated konflux build slack channel

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/fbc-builder/README.md, task/buildah-oci-ta/0.2/README.md, task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.2/buildah.yaml, task/generate-labels/0.1/README.md, task/generate-labels/0.1/generate-labels.yaml, task/generate-labels/OWNERS
For https://issues.redhat.com/browse/KONFLUX-4274. Turns out people really do use those labels (see linked issues).
This can have a future connection with https://github.com/konflux-ci/build-definitions/issues/1268 once we do that. I.e., use the commit timestamp for the release label and build-date, rather than the real world date. But, that's for another day...
=> A new task to generate labels

.tekton/scripts/check-task-pipeline-bundle-repos.sh
The script no longer checks the redhat-appstudio-tekton-catalog org (it's no longer necessary to create repos there).
=> check-repos: fix error message

task/push-dockerfile-oci-ta/0.1/push-dockerfile-oci-ta.yaml, task/push-dockerfile/0.1/push-dockerfile.yaml
To have consistency in `.dockerfile` oci artifact of the built image, always create it under `Dockerfile` name
=> Always name attached file Dockerfile in push-dockerfile task

hack/build-and-push.sh
[STONEBLD-2821](https://issues.redhat.com//browse/STONEBLD-2821)
=> Annotate task bundles with version

.tekton/tasks/ec-checks.yaml, pipelines/enterprise-contract.yaml
Reverts konflux-ci/build-definitions#1460
=> Revert "chore(deps): update ec"

task/rpm-ostree-oci-ta/0.2/README.md, task/rpm-ostree-oci-ta/0.2/recipe.yaml, task/rpm-ostree-oci-ta/0.2/rpm-ostree-oci-ta.yaml, task/rpm-ostree-oci-ta/OWNERS, task/rpm-ostree/0.2/rpm-ostree.yaml
Generated for version 0.2 only.
Reference: https://issues.redhat.com/browse/EC-924
=> Add rpm-ostree OCI-TA Task variant

task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.2/buildah.yaml
This work was triggered by KFLUXBUGS-1285.
User was trying to use dockerfile from an url, but it was failing for a
uknown reason and there was not any information as to why it might be
failing. It only showed the last successful log:
"Fetch Dockerfile from <URL>".
The true reason behind that failure is that the user was trying to fetch
the Dockerfile from an internal gitlab. That instance is accessible only
from internal network and with a certificate issued by Red Hat is needed.
Dockerfile failed "violently", without returning any error msg and did not return any http code.
Also we are using "set -e" which means, we exit on failure.
The reason we did not have any error message from the curl is the "-s"
(silent) option. However, adding -S (show error) means that we will be
outputting …
=> Add show error option to curl

task/build-vm-image/0.1/build-vm-image.yaml
Add support for VHD format in build-vm-image task.
Original support from BIB was made in this PR https://github.com/osbuild/bootc-image-builder/pull/634
=> feat: Add support for vhd format for build-vm-image task

task/build-vm-image/0.1/build-vm-image.yaml
Add supporty for specific GCP disk image format in build-vm-image task
Original support from BIB was made in this PR: https://github.com/osbuild/bootc-image-builder/pull/646
Edit: I also checked the release pipeline, it should be ok to have a .tgz: https://github.com/hacbs-release/app-interface-deployments/blob/main/internal-services/catalog/pulp-push-disk-images-task.yaml#L180-L182
=> feat: Add support for specific GCP format for build-vm-image task

task/rpm-ostree-oci-ta/0.2/recipe.yaml, task/rpm-ostree-oci-ta/0.2/rpm-ostree-oci-ta.yaml
Workdir replacement changed from `/var/workdir/source` to `/var/workdir` as the `source` directory is assumed and appended by the step scripts.
This prevents the script from using `/var/workdir/source/source` paths.
Reference: https://issues.redhat.com/browse/EC-924
=> Fix workdir for rpm-ostree OCI-TA Task

task/rpm-ostree-oci-ta/0.2/README.md, task/rpm-ostree-oci-ta/0.2/recipe.yaml, task/rpm-ostree-oci-ta/0.2/rpm-ostree-oci-ta.yaml
We also need to restore the cachi2 TA artifact.
Reference: https://issues.redhat.com/browse/EC-924
=> Add cachi2 artifact to rpm-ostree OCI-TA Task

pipelines/docker-build-rhtap/README.md, pipelines/docker-build-rhtap/patch.yaml, pipelines/fbc-builder/README.md, pipelines/fbc-builder/patch.yaml, pipelines/tekton-bundle-builder/README.md, pipelines/tekton-bundle-builder/kustomization.yaml, pipelines/tekton-bundle-builder/patch.yaml
In #1480, we added the rpms-signature-scan task to the pipeline template. This resulted in the task being added to multiple pipelines unnecessarily.
Also removed additional unnecessary tasks from the tekton bundle builder pipeline.
=> Remove unnecessary pipeline tasks

task/show-sbom-rhdh/0.1/README.md, task/show-sbom-rhdh/0.1/show-sbom-rhdh.yaml, task/show-sbom/0.1/README.md, task/show-sbom/0.1/show-sbom.yaml
SPDX format will be supported by build-definitions later. Update description of show-sbom tasks so that they are not limited to CycloneDX.
=> feat(CLOUDDST-24366) Update description of show-sbom

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-multi-platform-oci-ta/patch.yaml
Now that we can support a matrix of size one out of the box, changing the default configuraiton for multi-platform builds to only run in-cluster.
=> Change the default build-platforms to only build locallly

task/clamav-scan/0.1/clamav-scan.yaml
This should resolve the intermittent issue that users are experiencing with their build pipelines.
=> fix(STONEINTG-1073): increase db copy timeout

.tekton/pull-request.yaml, .tekton/push.yaml
The original name build-container does not reflect what the task does.
=> Rename CI task that builds appstudio-utils image

.github/workflows/check-ta.yaml, hack/missing-ta-tasks.sh, policies/all-tasks.yaml
A script and a GitHub workflow change to check if a new Task was added that uses a PVC-backed workspace without a Trusted Artifacts Task variant.
Reference: https://issues.redhat.com/browse/EC-934
=> CI check for missing TA Task variants

appstudio-utils/Dockerfile
We will create a new build pipeline to create OCI-artifact for maven zip files, which will be used to release maven artifacts in RedHat Maven repository (maven.repository.redhat.com). It needs zip tool to create zip files, so add zip installation in this image for later use.
=> appstudio-utils: install zip

README.md, task-generator/trusted-artifacts/README.md
Adds the documentation for the trusted-artifacts Task generator.
Reference: https://issues.redhat.com/browse/EC-933
=> Document trusted-artifacts Task generator

task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.2/buildah.yaml
Bazel uses a client server architecture to execute even when performing network isolated builds.It works fine as long as there is any adapter, even a loopback addapter. The default unshare env has a loopback device [lo] but it is DOWN by default. This PR brings lo UP in the unshare environment so that hermetic Bazel builds will work.
It is dependent on  the 'ip' command being present in the buildah image so another PR is open for that:
https://github.com/konflux-ci/buildah-container/pull/90
=> enable loopback adapter in hermetic unshare namespace

task/sast-snyk-check-oci-ta/0.3/MIGRATION.md, task/sast-snyk-check-oci-ta/0.3/README.md, task/sast-snyk-check-oci-ta/0.3/recipe.yaml, task/sast-snyk-check-oci-ta/0.3/sast-snyk-check-oci-ta.yaml, task/sast-snyk-check/0.3/MIGRATION.md, task/sast-snyk-check/0.3/README.md, task/sast-snyk-check/0.3/sast-snyk-check.yaml
Resolves: https://issues.redhat.com/browse/OSH-737
In this version, the severity-threshold argument is introduced and enabled by default to high and the results are parsed with csgrep to be uploaded with the fingerprint. This MR needs to be merged after this one: https://github.com/konflux-ci/konflux-test/pull/292
All changes have been discussed in the provided Jira tracker.
@konflux-team , we created this as a draft PR in order to gather feedback from you. Would this be acceptable? Is something else needed? ...
=> sast-snyk-check: increased version to 0.3

task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.2/buildah.yaml
This add support for pre-registering with subscription-manager in the buildah tasks (0.2 only). When activation keys are provided the buildah-task container will register and then provide certs to the buildah env via volume mounts so that users do not need to add subscription-manager register commands to the Containerfiles. This makes downstreaming somewhat easier and addresses negative user feedback.
=> subscription-manager pre-registration

task/sast-snyk-check-oci-ta/0.3/sast-snyk-check-oci-ta.yaml, task/sast-snyk-check/0.3/sast-snyk-check.yaml
In order to avoid unnecesary processing if no files are supported by Snyk, we check the Snyk status first.
Pipeline tests:
- Results: https://konflux.apps.stone-prod-p02.hjvn.p1.openshiftapps.com/application-pipeline/workspaces/jperezde/applications/test-coverity/pipelineruns/osh-cli-container-konflux-test-2-on-pull-request-n68fb
- No supported files: https://konflux.apps.stone-prod-p02.hjvn.p1.openshiftapps.com/application-pipeline/workspaces/jperezde/applications/test-no-files-ec/pipelineruns/golden-container-on-pull-request-mnjw6
=> sast-snyk-check: added checks before parsing

task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.2/buildah.yaml
We need to modify buildah task in order to be able to create SAST scanning tasks that has identical build logic with the original buildah task, but also have ability to:
- override the image used for the build step
- override the computeResources requirements for the task
- modify Dockerfile prior to running the buildah build
- specify additional volume mounts for the buildah build
- process the captured data after the container build
- prevent the resulting image from being used as the task result
Also
- The instrumented build-container SAST task will be provided with the same inputs as the original build-container task
- The instrumented build-container SAST task will be able to upload the SAST scanning results to image registry
SAST scan tasks can be created using the following …
=> Modify buildah task to allow creating SAST scan tasks via kustomize

stepactions/eaas-get-latest-openshift-version-by-prefix/0.1/eaas-get-latest-openshift-version-by-prefix.yaml
When getting latest version use the openshift CI multi-arch API instead of amd64 specific API.
Jira-Url: https://issues.redhat.com/browse/KFLUXVNGD-30
=> chore(KFLUXVNGD-30): Use Openshift CI multi-arch API

task/buildah-oci-ta/0.1/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml, task/buildah-remote/0.1/buildah-remote.yaml, task/buildah/0.1/buildah.yaml
Renovate bot has ignored v0.12.0 for some reason and it didn't open an update to v0.13.0 either. Bump it manually.
=> chore(deps): update quay.io/redhat-appstudio/cachi2 docker to v0.13.0

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/fbc-builder/README.md, pipelines/tekton-bundle-builder/README.md, task/build-image-index/0.1/README.md, task/build-image-index/0.1/build-image-index.yaml
This PR is related with two JIRA Issues:
https://issues.redhat.com/browse/ISV-5221
https://issues.redhat.com/browse/ISV-5222
=> [ISV-5221][ISV-5222] Add a new step into the “build-index-image” to build and push index sbom.

task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.2/buildah.yaml
[KFLUXBUGS-1539](https://issues.redhat.com/browse/KFLUXBUGS-1539)
- Built image in buildah task is pushed to a location specified in the `IMAGE` param
- This location does not have to be unique when running multiple PipelineRuns on the
same revision
- A race condition can occur resulting in a failure
- Besides pushing to `IMAGE`, push to a tag named after the TaskRun name which
should be unique
=> push to a unique tag in buildah tasks

task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.2/buildah.yaml
=> always unregister system from red hat subscription manager

task/source-build-oci-ta/0.1/source-build-oci-ta.yaml, task/source-build/0.1/source-build.yaml
Renovate PRs for this image are not created, the debug message says
DEBUG: Dependency quay.io/konflux-ci/source-container-build has unsupported/unversioned value 9ad131acf5154d2f280b7b46a1abc543952d325c (versioning=docker)
Replacing the hash tag with latest might work, as successfull PRs are created for images in this format, e.g.
https://github.com/konflux-ci/build-definitions/pull/1478/
=> Replace the hash tag with latest

task/clamav-scan/0.1/clamav-scan.yaml
Daily DB could cycle between daily.cld and daily.cvd
Freshclam tries to fetch daily.cvd, but in case that it's outdated, it
will fetch diffs and construct daily.cld instead.
```
Properly loaded 2067774 signatures from /var/lib/clamav/tmp.76d8729fde/clamav-306c76ad22d1f1bb9c4a6f49e1bedaf1.tmp-daily.cvd
Database test passed.
daily.cvd updated (version: 27455, sigs: 2067774, f-level: 90, builder: raynman)
Received an older daily CVD than was advertised. We'll retry so the incremental update will ensure we're up-to-date.
```
Make sure both files are checked.
=> fix(clamav): detection of daily DB

appstudio-utils/Dockerfile
TAS 1.1 requires cosign 2.2.0 or greater.
=> feat: Update cosign to 2.4.1

renovate.json, task/clamav-scan/0.1/clamav-scan.yaml
=> redirect task to the new quay repo konflux-ci

task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.2/buildah.yaml
[KFLUXBUGS-1681](https://issues.redhat.com/browse/KFLUXBUGS-1681)
- Failure of dockerfile-json parsing is not handled and buildah attempts to build
the image, leading to confusing errors
- Fail the build immediately if an error in a pipeline occurs
Previously
After the change
=> set strict mode for buildah build step

pipelines/gitops-pull-request-rhtap/README.md, pipelines/gitops-pull-request-rhtap/gitops-pull-request.yaml, task/update-infra-deployments/0.1/update-infra-deployments.yaml
fix for [RHTAPINST-182](https://issues.redhat.com/browse/RHTAPINST-182).
=> fix: correct 'enteprise' to 'enterprise'

.tekton/pull-request.yaml, .tekton/tasks/task-switchboard.yaml, appstudio-utils/Dockerfile
The new Task in `.tekton/tasks/changed-dirs.yaml` produces a list of changed directories for a particular pull request as an array result. Given this result guards can be done, e.g. using CEL expressions to limit when a Task on the Pipeline needs to run.
This way we can skip expensive Tasks that are unrelated to the change done in the pull request.
Similar to work in #1188 and #524, with the distinction that the PipelineRun is executed, only potentially not in full.
=> Guard Task execution via changed files

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/fbc-builder/README.md, task-generator/remote/main.go, task/buildah-oci-ta/0.2/README.md, task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.1/buildah-remote.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.2/buildah.yaml
Resolve https://issues.redhat.com/browse/BIFROST-475
To build bootc case image with buildah, we need additional options to be supported.
xref: https://gitlab.com/fedora/bootc/base-images/-/blob/main/Containerfile?ref_type=heads#L6
=> Add PRIVILEGED_NESTED to the buildah tasks

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/fbc-builder/README.md, task-generator/remote/main.go, task/buildah-oci-ta/0.2/README.md, task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.1/buildah-remote.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.2/buildah.yaml
This reverts commit 54b1217b28328ffbf4ad9cd1c3681b8b37449fe1.
The raw size of the buildah-remote-oci-ta task definition became too large, causing the bundle resolver to fail.
https://github.com/tektoncd/pipeline/issues/8388
=> Revert "Add PRIVILEGED_NESTED to the buildah task"

policies/all-tasks.yaml
Since [KFLUXBUGS-1111](https://issues.redhat.com//browse/KFLUXBUGS-1111) and [KFLUXBUGS-1110](https://issues.redhat.com//browse/KFLUXBUGS-1110) have been resolved an exception for the EC `step_image_registries.step_images_permitted` policy rules is no longer needed.
=> Remove exceptions for step images

.tekton/pull-request.yaml
We moved the stale application pruning to closer to the timeout of the PLR. In order to reduce unexpected errors when increasing the timeout, we should add a comment for the behavior.
=> Add link between e2e timeout and resource pruning

task/sast-snyk-check-oci-ta/0.3/README.md, task/sast-snyk-check-oci-ta/0.3/sast-snyk-check-oci-ta.yaml, task/sast-snyk-check/0.3/README.md, task/sast-snyk-check/0.3/sast-snyk-check.yaml
=> Update doc link for using snyk in task sast-snyk-check

appstudio-utils/Dockerfile
This adds support for `[oc|kubectl] wait --for=jsonpath=...` syntax.
=> Upgrade appstudio-utils oc client to v4.10

task/sast-unicode-check/OWNERS
As suggested by the Konflux team, updated the OWNERS file to add members from the SAST scanning.
=> sast-unicode: added SME to the OWNERS file

task/sast-snyk-check/OWNERS
As suggested by the Konflux team, updated the OWNERS file to add members from the SAST scanning.
=> sast-snyk: added SME to the OWNERS file

stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/README.md, stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/eaas-create-ephemeral-cluster-hypershift-aws.yaml
The user may choose to pass the value as a quoted string with explicit newlines ("\n") or by using the "|" operator, among other options. A tool like `yq` is therefore necessary since basic variable expansion within a heredoc isn't adequate at preventing issues with malformed yaml.
As a result. the container image was changed to one which provides both the `yq` and `kubectl` binaries. This is a more upstream friendly image since it's publicly pullable.
=> Add imageContentSources to eaas-create-ephemeral-cluster-hypershift-aws

policies/all-tasks.yaml
The rule checks that Task step image is accessible.
Reference: https://issues.redhat.com/browse/EC-912
=> Add new `step_images` rule to policy

task/build-vm-image/0.1/build-vm-image.yaml
We encountered transient 502 errors from quay today.
Add retries here to avoid task failure when we encounter flakiness.
=> Add retries to registry operations in build-vm-image

task-generator/remote/main.go, task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.1/buildah-remote.yaml, task/buildah-remote/0.2/buildah-remote.yaml
Added Nvidia GPU support to the buildah-remote task
=> Added Nvidia GPU support to the buildah-remote task

stepactions/eaas-get-ephemeral-cluster-credentials/0.1/README.md, stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
=> OLS-1232 - Adding consoleURL to results of get credentials 

task/oci-copy-oci-ta/0.1/oci-copy-oci-ta.yaml, task/oci-copy/0.1/oci-copy.yaml
It turns out that IBM Cloud and AWS s3 bucket urls are constructed differently, and the region is in a different place in the string.
Add a conditional here to catch AWS-style urls.
=> fix: extract region from aws s3 urls

task-generator/remote/main.go, task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.1/buildah-remote.yaml, task/buildah-remote/0.2/buildah-remote.yaml
Added in #1529 due to https://github.com/tektoncd/pipeline/issues/8388 as this is not yet deployed in the cluster.
This reverts commit 51cb7249f1a48a92d0098560aa418bb2025c1659.
=> Revert "Nvidia GPU support in the buildah-remote task"

.github/workflows/temp-block-buildah.yaml
If they increase the file size
(https://github.com/tektoncd/pipeline/issues/8388)
=> Temporarily block buildah-remote-oci-ta PRs

pipelines/enterprise-contract.yaml
Allow modifying `STRICT`. This allows to mark an EC as informative and not gate changes on it.
This is useful for us while we iterate to fix all the violations without gating yet the pull requests
=> Make EC strict mode configurable

stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
when getting ephemeral cluster credentials the kubeconfig file was assigned to the KUBECONFIG env var which is deleted before the script ends.
This change removes that assignment and instead explicitly mentions the kubeconfig path when it's used.
=> fix: delete propagated kubeconfig

.github/workflows/temp-block-buildah.yaml
The previous check wouldn't reward us for decreasing the file size - any PR that increased the size compared to the current 'main' would fail the check.
Instead, check the current size against largest known-safe size.
=> Improve buildah-remote-oci-ta size check

OWNERS_ALIASES, task/build-maven-zip-oci-ta/0.1/README.md, task/build-maven-zip-oci-ta/0.1/build-maven-zip-oci-ta.yaml, task/build-maven-zip-oci-ta/0.1/kustomization.yaml, task/build-maven-zip-oci-ta/0.1/recipe.yaml, task/build-maven-zip-oci-ta/OWNERS, task/build-maven-zip/0.1/README.md, task/build-maven-zip/0.1/build-maven-zip.yaml, task/build-maven-zip/0.1/kustomization.yaml, task/build-maven-zip/OWNERS
This task will be used in the new Konflux MRRC maven build pipeline. It is responsible for these work:
* Consume cachi2 prefetched aritfacts of "generic-fetcher" package type
* Generate checksums(md5, sha1, sha256) for all artifacts
* Bundle the artifacts and checksums into maven zip 
* Upload the maven zip to quay.io as OCI-artifact
* Attach sbom generated by cachi2 to the OCI-artifact
* Store these results into IMAGE_DIGEST, IMAGE_URL and SBOM_BLOB_URL
It also includes the oci-ta version.
BTW, we've added a new owner alias to put our team members in, and also mark the owners of this task as our team for future update.
=> feat(MMENG-4237): add build-maven-zip task

task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.2/README.md, task/buildah/0.2/buildah.yaml
The SBOM generated by the buildah task now contains the reference to the image itself. The new script supports both spdx and cyclonedx format.
In order to inject the image reference to the SBOM steps were rearanged to push first and then generate SBOM. The code that stored the sbom into image itself was removed as not used anymore.
JIRA: [ISV-5411](https://issues.redhat.com//browse/ISV-5411)
=> Add image reference to SBOM

.tekton/pull-request.yaml, .tekton/tasks/task-switchboard.yaml
It seems that the `pull_request_number` might not be defined when running checks on a PR in merge queue. So if the value is empty we can try looking up the pull request number by searching for the commit that contained it.
=> Use revision when pull_request_number is missing

task/buildah-min/0.2/patch.yaml
Due to recent step changes with [PR](https://github.com/konflux-ci/build-definitions/pull/1629/) in the `Buildah` task, our buildah-min task fails with `OOMKilled`, this PR will help address this issue
=> fix: adjust the cpu/mem values as per the step changed

.github/actions/install-tkn/action.yaml, .github/resources/workspace-template.yaml, .github/scripts/test_tekton_tasks.sh, .github/workflows/run-task-tests.yaml, README.md, renovate.json, task/git-clone/0.1/tests/test-git-clone-fail-for-wrong-url.yaml, task/git-clone/0.1/tests/test-git-clone-run-with-tag.yaml, task/git-clone/0.1/tests/test-git-clone-run-without-args.yaml
This PR implements the task validation in CI.
And took inspiration from the approach taken in [release-service-catalog repo](https://github.com/konflux-ci/release-service-catalog/blob/development/CONTRIBUTING.md#tekton-task-testing).
Part of the story: https://issues.redhat.com/browse/STONEBLD-2910
=> feat: add task validation in CI

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build-oci-ta/patch.yaml, pipelines/docker-build-rhtap/README.md, pipelines/docker-build/README.md, pipelines/fbc-builder/README.md, pipelines/fbc-builder/patch.yaml, pipelines/tekton-bundle-builder/README.md, pipelines/template-build/template-build.yaml, task/coverity-availability-check-oci-ta/0.1/README.md, task/coverity-availability-check-oci-ta/0.1/coverity-availability-check-oci-ta.yaml, task/coverity-availability-check-oci-ta/0.1/recipe.yaml, task/coverity-availability-check-oci-ta/OWNERS, task/coverity-availability-check/0.1/README.md, task/coverity-availability-check/0.1/coverity-availability-check.yaml, task/coverity-availability-check/OWNERS, task/sast-coverity-check-oci-ta/0.1/README.md, task/sast-coverity-check-oci-ta/0.1/recipe.yaml, task/sast-coverity-check-oci-ta/0.1/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check-oci-ta/OWNERS, task/sast-coverity-check/0.1/README.md, task/sast-coverity-check/0.1/sast-coverity-check.yaml, task/sast-coverity-check/OWNERS
Initial version of the Coverity Buildless task. The code will be scanned using coverity buildless mode, then the results are processuing using csgrep and the results are later filtered using csfilter-kfp.
This is a draft request and **this can not be merged** in this repository. It will be merged in a newly created repository.
Things pending to do:
Apart from that, the MR can be reviewed as the funcionality will remain the same
=> sast: initial task for Coverity Buildless

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build-oci-ta/patch.yaml, pipelines/docker-build-rhtap/README.md, pipelines/docker-build/README.md, pipelines/docker-build/patch.yaml, pipelines/fbc-builder/README.md, pipelines/fbc-builder/patch.yaml, pipelines/tekton-bundle-builder/README.md, pipelines/template-build/template-build.yaml
Solves: https://issues.redhat.com/browse/OSH-781
Adding sast-unicode-check and sast-shell-check tasks to to the template-build.yaml file so these tasks are added to every pipeline by default. Also updated sast-snyk-check version from 0.2 to 0.3 version
=> template-build: updated sast tasks

.tekton/tasks/e2e-test.yaml, hack/missing-ta-tasks.sh, pipelines/fbc-builder/README.md, pipelines/fbc-builder/patch.yaml, task/fbc-related-image-check/0.1/fbc-related-image-check.yaml, task/fbc-related-image-check/0.1/kustomization.yaml, task/fbc-related-image-check/0.2/MIGRATION.md, task/fbc-related-image-check/0.2/README.md, task/fbc-related-image-check/0.2/kustomization.yaml, task/fbc-validation/0.1/fbc-validation.yaml, task/fbc-validation/0.1/kustomization.yaml, task/fbc-validation/0.2/MIGRATION.md, task/fbc-validation/0.2/README.md, task/fbc-validation/0.2/kustomization.yaml, task/inspect-image/0.1/inspect-image.yaml, task/inspect-image/0.1/kustomization.yaml, task/inspect-image/0.2/MIGRATION.md, task/inspect-image/0.2/README.md, task/inspect-image/0.2/kustomization.yaml, task/validate-fbc/0.1/README.md, task/validate-fbc/0.1/TROUBLESHOOTING.md, task/validate-fbc/0.1/USAGE.md, task/validate-fbc/0.1/validate-fbc.yaml, task/validate-fbc/OWNERS
This change combines the inspect-image, fbc-validate, and fbc-related-image-check into a single task. ~It depends on functionality that needs to be added to EC to parse the produced trusted artifact in order to assess whether the related images are valid.~
All of the old tasks will be deprecated and the required tasks need to be updated to require only
```
- [fbc-related-image-check, validate-fbc]
```
This will ensure that users can still be guaranteed to have a valid FBC fragment and appropriate related images.
EDIT: In order to merge this PR quicker, the functionality for moving the related image check was backed out. In a future PR, we can update the task to output the list of related images and have EC check them for validity.
EDIT: This PR has sat around long enough so that I was …
=> feat(STONEINTG-1078): Combine all FBC validation tasks into one

pipelines/maven-zip-build-oci-ta/README.md, pipelines/maven-zip-build/README.md
Seems the pipeline readme is generated by tools. If not they will fail the ci checks. This PR fixed the issue.
=> fix: maven-zip-build pipelines README failed the ci checks

.tekton/scripts/build-acceptable-bundles.sh
We ended up with revision 3b215506e4ecc70c287785eeda9dbf8a4350b2fe for several Tasks in the acceptable bundles, seems that the `git log` method was also listing the files that were brought in by merging the main branch onto the pull request branch.
This switches to using GitHub CLI to search for a merged pull request that contains the top commit (`$REVISION`), and then lists the changed files in that pull request.
This should contain only the list of files that were changed in the pull request and not any changed files in a merge commit.
Reference: https://issues.redhat.com/browse/EC-1015
=> Improve listing changed files in a commit

.tekton/pull-request.yaml, pipelines/fbc-builder/README.md, pipelines/fbc-builder/kustomization.yaml, pipelines/fbc-builder/patch.yaml
This also changes the FBC pipeline to be multi-arch enabled by default.
=> feat(KONFLUX-5480): Convert FBC pipeline to use trusted artifacts

.tekton/scripts/build-acceptable-bundles.sh
Reverts konflux-ci/build-definitions#1654
`gh` CLI won't work without a token, see https://github.com/konflux-ci/build-definitions/runs/33966336258
=> Revert "Improve listing changed files in a commit"

task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.2/buildah.yaml
- Retries were achieved by writing a loop around the buildah command
- buildah actually has a `--retry` option
- Use the built-in option in order to simplify the code
=> refactor: use built-in buildah --retry

task/buildah-rhtap/0.1/buildah-rhtap.yaml
- buildah currently pushes to a tag based on revision
- if multiple pipelineruns are ran on the same revision, race conditions may happen
- push to a unique tag based on the unique taskrun name
=> push to a unique tag in buildah-rhtap

pipelines/kustomization.yaml
This is a missing part of maven-zip-build pipelines. They should be added to main kustomization.yaml to trigger the bundle build. Just added in this PR.
=> chore: add maven-zip-build/ta to main kustomization.yaml

.tekton/pull-request.yaml, OWNERS_ALIASES, task/prefetch-dependencies-oci-ta/OWNERS, task/prefetch-dependencies/OWNERS
They generally don't maintain anything in the build pipeline except for
the prefetch task.
Also: Don't run e2e-tests just for OWNERS changes (note that the e2e-tests _will_ trigger on this PR because it changes a file in `.tekton`)
=> Move prefetch devs out of the larger build team

.github/workflows/check-task-owners.yaml, CODEOWNERS, hack/check-task-owners.sh, hack/update_renovate_json_based_on_codeowners.py, renovate.json, task/provision-env-with-ephemeral-namespace/OWNERS
CODEOWNERS will allow us to make the ownership of individual tasks
actually mean something.
We will have to give every owner write permissions, but we will be able
to set up branch protection rules to block PRs from getting merged if
they don't have approvals from the owners.
This will allow the CODEOWNERS of tasks and stepactions to fully
self-service their PRs without giving them the ability to mess with
other parts of the repository.
=> Setup CODEOWNERS

task/operator-sdk-generate-bundle/OWNERS, task/opm-get-bundle-version/OWNERS, task/opm-render-bundles/OWNERS
=> Remove opm tasks' OWNERS files

task/build-maven-zip-oci-ta/OWNERS, task/build-maven-zip/OWNERS
=> Remove maven tasks' OWNERS files

stepactions/eaas-copy-secrets-to-ephemeral-cluster/OWNERS, stepactions/eaas-create-ephemeral-cluster-hypershift-aws/OWNERS, stepactions/eaas-get-ephemeral-cluster-credentials/OWNERS, stepactions/eaas-get-latest-openshift-version-by-prefix/OWNERS, stepactions/eaas-get-supported-ephemeral-cluster-versions/OWNERS, task/eaas-provision-space/OWNERS, task/provision-env-with-ephemeral-namespace/OWNERS
=> Remove eaas tasks' OWNERS files

task/build-vm-image/OWNERS
=> Remove build-vm-image tasks' OWNERS files

task/clair-scan/OWNERS, task/clamav-scan/OWNERS, task/coverity-availability-check-oci-ta/OWNERS, task/coverity-availability-check/OWNERS, task/deprecated-image-check/OWNERS, task/fbc-related-image-check/OWNERS, task/fbc-validation/OWNERS, task/inspect-image/OWNERS, task/sast-coverity-check-oci-ta/OWNERS, task/sast-coverity-check/OWNERS, task/sast-shell-check-oci-ta/OWNERS, task/sast-shell-check/OWNERS, task/sast-snyk-check-oci-ta/OWNERS, task/sast-snyk-check/OWNERS, task/sast-unicode-check-oci-ta/OWNERS, task/sast-unicode-check/OWNERS, task/sbom-json-check/OWNERS, task/validate-fbc/OWNERS
=> Remove integration tasks' OWNERS files

task/generate-odcs-compose/OWNERS, task/rpms-signature-scan/OWNERS, task/verify-signed-rpms/OWNERS
=> Remove rpm-related tasks' OWNERS files

pipelines/maven-zip-build-oci-ta/README.md, pipelines/maven-zip-build-oci-ta/patch.yaml, pipelines/maven-zip-build/README.md, pipelines/maven-zip-build/patch.yaml
The template-build has added several sast tasks, which breaks the maven-zip-build pipelines. This PR has fixed the pipelines  accordingly. It kept the following tasks which are added recently in template-build:
* sast-coverity-check
* coverity-availability-check
* sast-shell-check
* sast-unicode-check
=> fix: update maven-zip-build pipelines with recent template-build change

.github/workflows/run-task-tests.yaml
Fixes the task validation CI which was skipped with [PR](https://github.com/konflux-ci/build-definitions/pull/1685)
=> fix: task validation CI

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/tekton-bundle-builder/README.md, pipelines/template-build/template-build.yaml
... and coverity-availability-check to make the template work with multiarch builds.
Fixes: https://github.com/konflux-ci/build-definitions/pull/1411
Resolves: https://issues.redhat.com/browse/OSH-790
Resolves: https://issues.redhat.com/browse/KFLUXSPRT-847
=> template-build: fix parmeters of sast-coverity-check

renovate.json
See the individual commits for more details
=> Tweak Renovate config

task/tkn-bundle-oci-ta/OWNERS, task/tkn-bundle/OWNERS, task/verify-enterprise-contract/OWNERS
=> Remove ec-owned tasks' OWNERS files

task/sast-snyk-check-oci-ta/0.3/sast-snyk-check-oci-ta.yaml, task/sast-snyk-check/0.3/MIGRATION.md, task/sast-snyk-check/0.3/sast-snyk-check.yaml
Solves: https://issues.redhat.com/browse/OSH-769
Adding the stats to snyk scans in the result's SARIF file of successful scans.
Example of successful pipeline: https://konflux.apps.stone-prod-p02.hjvn.p1.openshiftapps.com/application-pipeline/workspaces/jperezde/applications/test-coverity/pipelineruns/osh-cli-container-konflux-test-2-on-pull-request-znx98
=> snyk-sast: added stats for Snyk scans

task/build-image-index/0.1/build-image-index.yaml, task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.2/buildah.yaml
most functional changes are in the related PR that updates the
base_images_sbom_script.py
https://github.com/konflux-ci/build-tasks-dockerfiles/pull/191
Here, we are just updating on how we generate the inputs for this
script.
We are now passing the whole parsed Dockerfile in json format to that
script, which allows us to better parse/detect base images.
Also, the format of the /shared/base_images_digests file was changed.
Previously we could rely on the order of the image references with the
digests in the file. Now we need to provide a mapping from an image
reference as it was used in the Dockerfile to the full image reference
with digests that was used during build and generated by buildah.
The mapping is done as:
<image-reference-used-in-dockerfile> <full-image-reference-with-digest> …
=> Improve generation of base images SBOMs

task/apply-tags/0.1/apply-tags.yaml, task/init/0.2/init.yaml
By default, skopeo inspect will try to fetch all of the tags for a remote repository. This can take a lot of time if there are many present. Therefore, unless we need tags, we should use one of
* `skopeo inspect --raw`
* `skopeo inspect --no-tags`
as both of these will not try to list all tags.
=> fix(KONFLUX-6028): Stop fetching tags with skopeo inspect

hack/build-and-push.sh
Each commit in this PR has detailed information about the changes.
=> Small updates to hack/build-and-push.sh

task/sast-coverity-check-oci-ta/0.1/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.1/README.md, task/sast-coverity-check/0.1/sast-coverity-check.yaml
Solves: https://issues.redhat.com/browse/OSH-769
Adding the stats to Coverity scans in the result's SARIF file of successful scans.
=> sast-coverity-check: added stats for Coverity scans

task/opm-render-bundles/0.1/opm-render-bundles.yaml
the entry should have a v in the name according to the skiprange docs
https://olm.operatorframework.io/docs/concepts/olm-architecture/operator-catalog/creating-an-update-graph/#skiprange
=> task/opm-render-bundles: add v to entry name

pipelines/fbc-builder/README.md, task/validate-fbc/0.1/README.md, task/validate-fbc/0.1/validate-fbc.yaml
While the FBC builder pipeline has been changed to be multi-arch aware, the validate-fbc task will cause EC failures since it does not report that the results are valid for all of the OCI image manifest digests. Even if we are not performing additional verification on the architecture specific images, we need to set the IMAGES_PROCESSED result so that EC will pass.
=> feat: enable multi-arch fbc verification

task/rpm-ostree-oci-ta/0.2/rpm-ostree-oci-ta.yaml, task/rpm-ostree/0.2/rpm-ostree.yaml
Set SBOM name for rpm-ostree generated images to `registry/repository@digest`of the pushed image.
JIRA: [ISV-5322](https://issues.redhat.com//browse/ISV-5322)
=> Set useful SBOM name for rpm-ostree generated images

renovate.json
https://docs.renovatebot.com/configuration-options/#packagerules
> If multiple matchers are included in one package rule, *all of them*
> must match.
Remove the extraneous matchers that are breaking the groupings
Tested with
$ podman run --rm -ti -v "$PWD:$PWD:z" -w "$PWD" --user=0 \
-e LOG_LEVEL=debug \
-e RENOVATE_PLATFORM=local \
ghcr.io/renovatebot/renovate |
grep 'Returning .* branch'
DEBUG: Returning 15 branch(es) (repository=local)
In main, this returns 24 branches instead.
=> Fix renovate.json groupings

task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.2/buildah.yaml
=> disable red hat subsciption logic when build is in hermetic mode

CODEOWNERS, renovate.json
The tasks that are maintained in tekton-tools are tracked by mintmaker there and have additional specific test cases there.
We should let mintmaker update them rather than have renovate update them here. The updated tasks are then automatically mirrored to this repo.
=> chore(KFLUXVNGD-140): renovate to ignore tekton-tools tasks

task/oci-copy-oci-ta/0.1/oci-copy-oci-ta.yaml, task/oci-copy/0.1/oci-copy.yaml
This enhances the name for the oci-copy produced SBOM, to be `registry/repository@digest `
JIRA: [ISV-5323](https://issues.redhat.com//browse/ISV-5323)
=> oci-copy produced SBOM has a better name

renovate.json
The task-generator/trusted-artifacts tools uses recipe.yaml files to generate tasks. These files may include an 'additionalSteps' attribute, which is a list of full Tekton step definitions.
These definitions include pinned image references. This clashes with Renovate updates - when Renovate updates the image reference in an *-oci-ta.yaml task, the TA generator reverts it back to the reference in recipe.yaml.
Fix by adding a custom regexManager for recipe.yaml files.
=> renovate: update images in recipe.yaml

CODEOWNERS, renovate.json, task/build-paketo-builder-oci-ta/0.1/README.md, task/build-paketo-builder-oci-ta/0.1/build-paketo-builder-oci-ta.yaml
- New build task: paketo builder
- The `build-paketo-ubi-builder` task builds the [ubi builder image](https://github.com/paketo-community/builder-ubi-base) for paketo using as input the [builder.toml](https://buildpacks.io/docs/reference/config/builder-config/) file. The image is build using the pack tool packaged part of the [paketo-container](https://github.com/konflux-ci/paketo-container/) image.
The task also produces the SBOM which is signed and added to the image.
Build succeeded part of this PR: https://console.redhat.com/application-pipeline/workspaces/cmoullia/applications/buildpack-remote/pipelineruns/builder-ubi-base-l2q8r
=> New build task : paketo builder

.tekton/scripts/create-task-pipeline-bundle-repos.sh
The version of `curl` (7.76.1) we currently use in quay.io/konflux-ci/appstudio-utils does not support the `--json` parameter, so this reverts to using lengthier `--data-binary` and setting the Content-Type and Accept headers.
=> `--json` not supported in version of curl in use

task/buildah-min/0.2/patch.yaml, task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.2/buildah.yaml
For backwards compatibility with image scanners that still expect https://raw.githubusercontent.com/containerbuildsystem/atomic-reactor/master/atomic_reactor/schemas/content_manifest.json
Looking forward, clair and other scanners are going to adapt to start reading the content sets from the dnf database and later from our sboms - but they're not ready for that yet. Add this file to support them while they migrate.
See also https://github.com/containerbuildsystem/atomic-reactor/pull/2140
https://issues.redhat.com/browse/KONFLUX-6200
=> feat: introduce content manifest with content sets

task-generator/trusted-artifacts/go.mod, task-generator/trusted-artifacts/golden/git-clone/ta.yaml, task-generator/trusted-artifacts/golden/prefetch-dependencies/ta.yaml, task-generator/trusted-artifacts/ta.go, task/git-clone-oci-ta/0.1/git-clone-oci-ta.yaml, task/prefetch-dependencies-oci-ta/0.1/prefetch-dependencies-oci-ta.yaml, task/prefetch-dependencies/0.1/prefetch-dependencies.yaml
OK, I was trying to reproduce the issue [KONFLUX-5951](https://issues.redhat.com//browse/KONFLUX-5951) and was able to do so with Gomod Cachi2 configured. I do not know what caused that issue, but noticed that for me all of 50 concurrent prefetch-dependencies pods were running on the same node!
I have picked 1 CPU and 3 GiB of memory as a `request` (and in an effort to slowly migrate to model where we have requests == limits), used the same for `limits`. This is why I used these numbers (graphs from _stone-prd-rh01_):
... looks like steps `step-prefetch-dependencies` and `step-create-trusted-artifact` can take about 2 GB (including cache and so)
... RSS memory is of-course smaller
... regarding CPU it takes about 1 CPU across all containers
... again, only containers …
=> feat(KONFLUX-5670): Define computeResources for prefetch-dependencies and create-trusted-artifact steps

task/oci-copy-oci-ta/OWNERS, task/oci-copy/OWNERS
=> Remove oci-copy tasks' OWNERS files

task-generator/remote/main.go, task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.2/buildah.yaml
The new 'icm' step was broken because it didn't take into account the
IMAGE modifications done in every other step. To fix it, switch the step
from "command-style" to "script-style" to make the task-generator tool
notice that it has to do its thing.
Also fix the task-generator because it wasn't handling things very well
=> Fix buildah remote

appstudio-utils/Dockerfile
The latest release of ec-cli is missing the executables. 
This makes it fail build of the appstudio-utils image. 
Fix the version of ec-cli to the latest working release
=> chore: fix ec-cli version to v0.6.150

hack/generate-buildah-remote.sh, pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/docker-build/patch.yaml, pipelines/fbc-builder/README.md, task/buildah-oci-ta/0.3/MIGRATION.md, task/buildah-oci-ta/0.3/README.md, task/buildah-oci-ta/0.3/buildah-oci-ta.yaml, task/buildah-oci-ta/0.3/recipe.yaml, task/buildah-remote-oci-ta/0.3/MIGRATION.md, task/buildah-remote-oci-ta/0.3/README.md, task/buildah-remote-oci-ta/0.3/buildah-remote-oci-ta.yaml, task/buildah-remote/0.3/MIGRATION.md, task/buildah-remote/0.3/README.md, task/buildah-remote/0.3/buildah-remote.yaml, task/buildah/0.3/MIGRATION.md, task/buildah/0.3/README.md, task/buildah/0.3/buildah.yaml, task/buildah/0.3/kustomization.yaml
- jvm-build-service is not used by anyone and will get reworked
- buildah task contains references to jvm-build-service
- Removal of the references is a breaking change
* Remove `analyse-dependencies-java-sbom` step
* Remove `SBOM_JAVA_COMPONENTS_COUNT` result
* Remove `JAVA_COMMUNITY_DEPENDENCIES` result
- Release buildah version 0.3
- Upgrade buildah version in docker-build pipelines to 0.3
~~**Note for reviewers:**~~
~~I haven't found an easy way to compare different files in GitHub, I would probably checkout the branch locally and do something like:~~
```
diff task/buildah/0.2/buildah.yaml task/buildah/0.3/buildah.yaml
```
~~(I welcome different ideas)~~
=> remove references to jvm-build-service

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/fbc-builder/README.md, task-generator/remote/main.go, task/buildah-oci-ta/0.2/README.md, task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-oci-ta/0.3/README.md, task/buildah-oci-ta/0.3/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote-oci-ta/0.3/buildah-remote-oci-ta.yaml, task/buildah-remote/0.1/buildah-remote.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah-remote/0.3/buildah-remote.yaml, task/buildah/0.2/buildah.yaml, task/buildah/0.3/buildah.yaml
This reverts commit ca880a9e47d12f534e0dbde30369cdf0ccb9d7e2.
The bundle size limitation issue has been solved and deployed on production clusters, so reapply this PR.
https://issues.redhat.com/browse/KONFLUX-5706
=> Reapply "Add PRIVILEGED_NESTED to the buildah task"

task/buildah-oci-ta/0.3/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.3/buildah-remote-oci-ta.yaml, task/buildah-remote/0.3/buildah-remote.yaml, task/buildah/0.3/buildah.yaml
See 2ac6602697a28ed44f63b0d58c9275c3b5a1a2d6.
The fix got lost while creating the 0.3 version of buildah.
=> buildah*/0.3: port icm fix from buildah/0.2

task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-oci-ta/0.3/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote-oci-ta/0.3/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah-remote/0.3/buildah-remote.yaml, task/buildah/0.2/buildah.yaml, task/buildah/0.3/buildah.yaml
The purpose is just to help users debug failures in the future. I have one such failure now where a later step complains that these base image digest lines are malformed. I'm just trying to get visibility on that.
=> Log activity when recording base image digests

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/fbc-builder/README.md, task/buildah-oci-ta/0.2/README.md, task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-oci-ta/0.3/README.md, task/buildah-oci-ta/0.3/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/README.md, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote-oci-ta/0.3/README.md, task/buildah-remote-oci-ta/0.3/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/README.md, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah-remote/0.3/README.md, task/buildah-remote/0.3/buildah-remote.yaml, task/buildah/0.2/README.md, task/buildah/0.2/buildah.yaml, task/buildah/0.3/README.md, task/buildah/0.3/buildah.yaml
Since we can require SBOMs to be present with EC policies, we can enable
users to optionally speed up their builds by not analyzing repositories
to generate build-time SBOMs.
While we may have a partial SBOM from the prefetched data, we should
just not upload an SBOM at all in order to simplify decisions (i.e.
removing the need to decide if the SBOM is full or partial).
=> Optionally skip SBOM generation

task/build-vm-image/0.1/build-vm-image.yaml
Part of the story: https://issues.redhat.com/browse/STONEBLD-2716
=> chore: replace multi-platform-runner image with buildah-task

task/buildah-oci-ta/0.3/MIGRATION.md, task/buildah-remote-oci-ta/0.3/MIGRATION.md, task/buildah-remote/0.3/MIGRATION.md, task/buildah/0.3/MIGRATION.md
- Some users have encountered problems when migrating buildah tasks from 0.2 to 0.3 when using older PipelineRun definitions which still include the results that are being removed in buildah 0.3
- Mention in the Migration files that users should check if their PipelineRun contains the removed results and that they should be removed
=> improve buildah 0.3 migration files

task/build-image-index/0.1/build-image-index.yaml, task/build-paketo-builder-oci-ta/0.1/build-paketo-builder-oci-ta.yaml, task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-oci-ta/0.3/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote-oci-ta/0.3/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah-remote/0.3/buildah-remote.yaml, task/buildah/0.2/buildah.yaml, task/buildah/0.3/buildah.yaml, task/rpm-ostree-oci-ta/0.2/rpm-ostree-oci-ta.yaml, task/rpm-ostree/0.2/rpm-ostree.yaml
- `quay.io/redhat-appstudio/sbom-utility-scripts-image` got renamed and moved, so it's now `konflux-ci/sbom-utility-scripts`
- This is a part of the effort to decomission redhat-appstudio Quay org
- Change the image references to the new location
=> change sbom-utility-scripts refs to new location

task-generator/trusted-artifacts/golden/buildah/base.yaml, task-generator/trusted-artifacts/golden/buildah/ta.yaml, task-generator/trusted-artifacts/golden/prefetch-dependencies/base.yaml, task-generator/trusted-artifacts/golden/prefetch-dependencies/ta.yaml, task/buildah-oci-ta/0.1/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml, task/buildah-remote/0.1/buildah-remote.yaml, task/buildah/0.1/buildah.yaml, task/prefetch-dependencies-oci-ta/0.1/prefetch-dependencies-oci-ta.yaml, task/prefetch-dependencies/0.1/prefetch-dependencies.yaml
cachi2 has been moved to konflux-ci quay namespace -> update manually all references with latest cachi2 image tag
0.17.0 tag:
https://quay.io/repository/konflux-ci/cachi2/tag/0.17.0
=> chore(deps): update build / prefetch

.github/workflows/check-task-migration.yaml, hack/validate-migration.sh
[STONEBLD-2827](https://issues.redhat.com//browse/STONEBLD-2827)
=> Validate added migration file

task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-oci-ta/0.3/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote-oci-ta/0.3/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah-remote/0.3/buildah-remote.yaml, task/buildah/0.2/buildah.yaml, task/buildah/0.3/buildah.yaml
With a recent update of the Syft image, we accidentally bumped the CycloneDX version of our SBOMs from 1.5 to 1.6 (Syft v1.8 [1] added support for CDX 1.6 and also bumped the default).
Explicitly specify the CDX version to avoid problems like this in the future.
[1]: https://github.com/anchore/syft/releases/tag/v1.8.0
=> buildah: pin CycloneDX version to 1.5

pipelines/enterprise-contract.yaml
Since the default timeout for tasks is hardcoded to 1h/2h, this change sets the timeout to a higher value to
support users who run bigger sets of images through the verify task.
It is still possible to limit the duration of the check on the pipeline or pipelineRun level, depending on usage.
=> fix: add 4h task timeout in the ec pipeline

task/clair-scan/0.1/clair-scan.yaml, task/clair-scan/0.2/clair-scan.yaml
Update references to redhat-appstudio quay org to reflect move to konflux-ci.
=> feat(STONEINTG-948): migrate redhat-appstudio/clair-in-ci

task/deprecated-image-check/0.4/deprecated-image-check.yaml, task/source-build-oci-ta/0.1/source-build-oci-ta.yaml, task/source-build/0.1/source-build.yaml
Support extracting the base/builder images from both CycloneDX SBOMs
and SPDX SBOMs.
Tested in https://github.com/redhat-appstudio/rh-syft/pull/105
source-build:
```
Found SBOM of media type: text/spdx+json
Looking for base image in SBOM (a package with a {"name": "konflux:container:is_base_image"} JSON-encoded annotation)
registry.access.redhat.com/ubi9/ubi-micro@sha256:7f376b75faf8ea546f28f8529c37d24adcde33dca4103f4897ae19a43d58192b
```
deprecated-image-check:
```
Found SBOM of media type: text/spdx+json
Detected base images from amd64 SBOM:
brew.registry.redhat.io/rh-osbs/openshift-golang-builder
registry.access.redhat.com/ubi9/ubi-micro
Images to be checked:
brew.registry.redhat.io/rh-osbs/openshift-golang-builder
registry.access.redhat.com/ubi9/ubi-micro
```
=> source-build, deprecated-image-check: support reading base images from SPDX SBOMs

appstudio-utils/Dockerfile
Since there's not an easy way to update ec use the rolling release.
https://issues.redhat.com/browse/EC-1066
=> Using rolling release of EC

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/fbc-builder/README.md, pipelines/maven-zip-build-oci-ta/README.md, pipelines/maven-zip-build/README.md, pipelines/tekton-bundle-builder/README.md, task/prefetch-dependencies-oci-ta/0.1/README.md, task/prefetch-dependencies-oci-ta/0.1/prefetch-dependencies-oci-ta.yaml, task/prefetch-dependencies/0.1/README.md, task/prefetch-dependencies/0.1/prefetch-dependencies.yaml
Add sbom-type param to allow choosing the SBOM format cachi2 should generate. Defaults to cyclonedx for now.
=> prefetch-dependencies: support SPDX

task/rpm-ostree-oci-ta/OWNERS, task/rpm-ostree/OWNERS
=> Remove rpm-ostree tasks' OWNERS files

task/build-paketo-builder-oci-ta/0.1/README.md, task/build-paketo-builder-oci-ta/0.1/build-paketo-builder-oci-ta.yaml
- Remove the command using the script create_purl_sbom.py as script is deprecated
- Improve the code to generate the SBOM of the paketo build image
- Remove non used parameters
=> Remove the command using create_purl_sbom.py

task/oci-copy-oci-ta/0.1/README.md, task/oci-copy-oci-ta/0.1/oci-copy-oci-ta.yaml, task/oci-copy/0.1/README.md, task/oci-copy/0.1/oci-copy.yaml
Depends on https://github.com/konflux-ci/build-tasks-dockerfiles/pull/226
=> oci-copy: rework SBOM generation, support SPDX

task/sast-coverity-check-oci-ta/0.1/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.1/sast-coverity-check.yaml
Related: https://issues.redhat.com/browse/OSH-801
The missing character prevented the filtered files to be correctly generated and uploaded
Tested pipeline: https://konflux.apps.stone-prod-p02.hjvn.p1.openshiftapps.com/application-pipeline/workspaces/jperezde/applications/test-coverity/pipelineruns/automation-hub-web-container-on-pull-request-cpsfd
=> sast-coverity-check: Fix error while creating filtered file

task-generator/trusted-artifacts/README.md, task-generator/trusted-artifacts/recipe.go, task-generator/trusted-artifacts/ta.go, task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-oci-ta/0.2/recipe.yaml, task/buildah-oci-ta/0.3/buildah-oci-ta.yaml, task/buildah-oci-ta/0.3/recipe.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote-oci-ta/0.3/buildah-remote-oci-ta.yaml, task/git-clone-oci-ta/0.1/git-clone-oci-ta.yaml, task/git-clone-oci-ta/0.1/recipe.yaml
Add param to support the custom certificate support for git-clone-oci-ta and
buildah-oci-ta tasks to connect to internal registry. For this we have updated
the use-trusted-artifact/create-trusted-artifact steps, which download/upload
the artifact from/to a registry.
Jira-Url: https://issues.redhat.com/browse/KFLUXVNGD-155
=> chore(KFLUXVNGD-155): Add custom certificate support for git clone and buildah task

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/maven-zip-build-oci-ta/README.md, pipelines/maven-zip-build/README.md, task/sast-snyk-check-oci-ta/0.3/README.md, task/sast-snyk-check-oci-ta/0.3/sast-snyk-check-oci-ta.yaml, task/sast-snyk-check/0.3/sast-snyk-check.yaml
feat([STONEINTG-1098](https://issues.redhat.com//browse/STONEINTG-1098)): setting default KFP_GIT_URL for snyk check
* setting default KFP_GIT_URL to
https://gitlab.cee.redhat.com/osh/known-false-positives.git
for task running in internal Konflux instance
* setting default KFP_GIT_URL to empty string for task running
in external Konflux instance
Signed-off-by: Kamil Dudka <kdudka@redhat.com>
=> feat(STONEINTG-1098): setting default KFP_GIT_URL for sast-snyk-check

CODEOWNERS, renovate.json, task/sealights-go/0.1/README.md, task/sealights-go/0.1/sealights-go.yaml, task/sealights-python/0.1/README.md, task/sealights-python/0.1/sealights-python.yaml
I open this Pull Request to migrate the current Sealights tasks that are living currently in [tekton-integration-catalog](https://github.com/konflux-ci/tekton-integration-catalog/tree/main/tasks/sealights). The reason of migration is that we cannot use the tasks from catalog due to EC violations during builds. For now this migration is temporary until Konflux support https://issues.redhat.com/browse/KONFLUX-4530.
@ascerra @Dannyb48 @psturc @arewm @lcarva @konflux-ci/build-maintainers   FYI
=> feat(): Migrate sealights tasks from integration catalog to build-definitions

.tekton/push.yaml, .tekton/scripts/create-task-pipeline-bundle-repos.sh
* The script wasn't adding the "task-" or "pipeline-" prefix to repositories
* Ignore strange "Repository already exists" errors
* Run build-bundles _after_ create-repositories-if-missing
=> Fix repository creation in push pipeline

.tekton/push.yaml
Don't use the pull-request appstudio-utils image
=> push pipeline: fix appstudio-utils image ref

task-generator/remote/main.go, task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote-oci-ta/0.3/buildah-remote-oci-ta.yaml, task/buildah-remote/0.1/buildah-remote.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah-remote/0.3/buildah-remote.yaml
It's hard to determine if the issue happened on remote host or in container.
=> fix(buildah-remote): logs when build on remote host started/finished

.tekton/pull-request.yaml, .tekton/tasks/e2e-test.yaml
This PR will enable archiving e2e-tests logs to an oci image and add the link to the image in the PR comments (when there is test failures).
Part of the story: https://issues.redhat.com/browse/STONEBLD-3025
=> feat: capturing e2e-tests logs of CI in an oci artifact 

task/prefetch-dependencies-oci-ta/0.1/prefetch-dependencies-oci-ta.yaml, task/prefetch-dependencies/0.1/prefetch-dependencies.yaml
~**Depends on:**  https://github.com/containerbuildsystem/cachi2/pull/792~
Opening as an RFC draft since this solution currently relies on a custom-built cachi2 image which the task was tested with in a private Konflux deployment. Once the dependent PR is merged AND this solution is accepted I will lift the Draft status. Pasting a (publishable) snippet from the pipelines log:
```
prefetch
=======
Registering with Red Hat subscription manager.
The system has been registered with ID: cc44f731-1d42-44f2-9993-56454f63faa4
The registered system name is: konflux-test-repo-on-pull-rdc2a0834b9fb80d8cdb850c8f3586779-pod
2025-01-22 17:02:50,177 INFO Fetching the gomod dependencies at subpath hello
2025-01-22 17:02:50,186 INFO go.mod reported versions: '1.20'[go], '-'[toolchain]
2025-01-22 …
```
=> task: prefetch: Condense the RHSM entitlement RPM repositories logic to a single step

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build-oci-ta/patch.yaml
There was a copy-paste mistake in `pipelines/docker-build-oci-ta/patch.yaml` causing the `sast-shell-check` bundle to be used instead of `sast-unicode-check`.
Related: https://issues.redhat.com/browse/OSH-763
Related: https://issues.redhat.com/browse/OSH-805
=> docker-build-oci-ta: fix a copy-paste mistake in the patch

pipelines/docker-build-rhtap/README.md, pipelines/docker-build-rhtap/patch.yaml
This changes removes various Tasks that have been added to template-build and thus automatically added to the docker-build-rhtap pipeline.
NOTE: At this point, it is probably not worth using kustomize to generate the docker-build-rhtap pipeline -- only three of the 20 tasks are reused. It probably also makes sense to remove this pipeline and all other RHTAP specific tasks out of this repository.
=> Remove unnecessary tasks from the RHTAP build

task/build-paketo-builder-oci-ta/0.1/README.md, task/build-paketo-builder-oci-ta/0.1/build-paketo-builder-oci-ta.yaml
@cmoulliard context for this:
We'll be switching the default SBOM type to SPDX by the end of the month (i.e. this week).
I believe that a typical paketo-builder pipeline doesn't enable dependency prefetching via the `prefetch-dependencies` task, so this switch probably shouldn't break the users of this task. Otherwise, the prefetch-dependencies task and the build task (in this case paketo-builder) would have to switch to SPDX at the same time.
TLDR - it would be good to get this merged fairly soon, but we won't consider this a blocker to switch the other tasks to SPDX
=> paketo: support generating SPDX SBOMs

task/fbc-fips-check-oci-ta/0.1/fbc-fips-check-oci-ta.yaml, task/fbc-fips-check/0.1/fbc-fips-check.yaml, task/fips-operator-bundle-check-oci-ta/0.1/fips-operator-bundle-check-oci-ta.yaml, task/fips-operator-bundle-check/0.1/fips-operator-bundle-check.yaml
Because the stepaction doesn't exist in the workspaces, the task image fails to run. Use the git resolver to fetch the stepaction in the task.
Refers to [KFLUXSPRT-1555](https://issues.redhat.com//browse/KFLUXSPRT-1555)
=> use git resolver for fips task stepaction

CODEOWNERS, pipelines/fbc-builder/README.md, pipelines/fbc-builder/patch.yaml, renovate.json, task/fbc-target-index-pruning-check/0.1/README.md, task/fbc-target-index-pruning-check/0.1/fbc-target-index-pruning-check.yaml, task/validate-fbc/0.1/README.md, task/validate-fbc/0.1/validate-fbc.yaml
Adds a new task to the fbc-builder pipeline to check if the incoming FBC fragment would remove channels or channel entries already present in the target index.
=> feat(KONFLUX-3935) Add pruning check to FBC pipeline

task/build-maven-zip-oci-ta/0.1/build-maven-zip-oci-ta.yaml, task/build-maven-zip/0.1/build-maven-zip.yaml
Detect the format of the SBOM coming from the prefetch task. Use the right '--type' argument for 'cosign attach' based on the format.
=> build-maven-zip: support SPDX

task/fbc-fips-check-oci-ta/0.1/fbc-fips-check-oci-ta.yaml, task/fbc-fips-check/0.1/fbc-fips-check.yaml, task/fips-operator-bundle-check-oci-ta/0.1/fips-operator-bundle-check-oci-ta.yaml, task/fips-operator-bundle-check/0.1/fips-operator-bundle-check.yaml
previously, the FIPS compliance tasks checked image labels to identify if an operator bundle claims to be fips compliant. Not all product teams include it as labels. A more robust way is to check the CSV annotations. This commit implements that fix.
Refers to [KONFLUX-6664](https://issues.redhat.com//browse/KONFLUX-6664)
=> fix: use CSV annotations for fips compliance of a bundle

task/ecosystem-cert-preflight-checks/0.2/MIGRATION.md, task/ecosystem-cert-preflight-checks/0.2/README.md, task/ecosystem-cert-preflight-checks/0.2/ecosystem-cert-preflight-checks.yaml
Related to KFLUXBUGS-1638- This pull request modifies the ecosystem check such that it should no longer fail (or need to be worked around) if the built image is an operator bundle.
~The original scope for this issue was to detect the image was a bundle and then _skip the remaining checks_. I went ahead and added a bundle validation call just because it seemed within reach  (see [KONFLUX-178](https://issues.redhat.com//browse/KONFLUX-178)). If this implementation is not desirable, I'm happy to return to the original scope (i.e. detect the image is a bundle, then skip the ecosystem application image checks).~
Before:
- User builds a bundle image
- This task throws a failure (shows up as a :warning:) because Preflight (`check container`) can't find what it's expecting.
Now:
- The image's …
=> Introspect image type and skip for bundle images

.tekton/pull-request.yaml
Since we are getting rid of images from `quay.io/redhat-appstudio` , using python based image in the CI
=> fix: replace quay.io/redhat-appstudio/github-app-token image with ubi

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, task/source-build-oci-ta/0.2/README.md, task/source-build-oci-ta/0.2/source-build-oci-ta.yaml, task/source-build/0.2/README.md, task/source-build/0.2/source-build.yaml
Needed to add the task to the data-acceptable-bundles image.
When merging https://github.com/konflux-ci/build-definitions/pull/1865, the build-acceptable-bundles failed. This meant the new versions of all tasks updated in that PR were missing from data-acceptable-bundles.
Due to the way the push pipeline is set up, making a change to the affected tasks is the only way to add them to data-acceptable-bundles.
=> source-build/0.2: arbitrary change

task/deprecated-image-check/0.5/deprecated-image-check.yaml
Needed to add the task to the data-acceptable-bundles image.
When merging https://github.com/konflux-ci/build-definitions/pull/1865, the build-acceptable-bundles failed. This meant the new versions of all tasks updated in that PR were missing from data-acceptable-bundles.
Due to the way the push pipeline is set up, making a change to the affected tasks is the only way to add them to data-acceptable-bundles.
=> deprecated-image-check/0.5: arbitrary change

policies/all-tasks.yaml, policies/step-actions.yaml
Two images require auth and another two are parametized and EC is unable to handle these two cases.
https://issues.redhat.com/browse/EC-1038
=> Exclude step images

task/buildah-oci-ta/0.3/buildah-oci-ta.yaml, task/buildah-oci-ta/0.4/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.3/buildah-remote-oci-ta.yaml, task/buildah-remote-oci-ta/0.4/buildah-remote-oci-ta.yaml, task/buildah-remote/0.3/buildah-remote.yaml, task/buildah-remote/0.4/buildah-remote.yaml, task/buildah/0.3/buildah.yaml, task/buildah/0.4/buildah.yaml, task/sast-coverity-check-oci-ta/0.2/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.2/sast-coverity-check.yaml
https://issues.redhat.com/browse/KONFLUX-5915
The previous solution only worked if the entire base image was quoted:
jq -n -r --arg pullspec '"registry.com/foo:v1"' \
'$pullspec | sub("\"?(?<image>[^\"]*)\"?" ; .image)'
registry.com/foo:v1
But didn't work if the quotes were inside the base image, e.g.
jq -n -r --arg pullspec 'registry.com/foo:"v1"' \
'$pullspec | sub("\"?(?<image>[^\"]*)\"?" ; .image)'
registry.com/foo:v1"
This can happen for Containerfiles like this one:
ARG version="v1"
FROM registry.com/foo:$version
Simplify the code to just strip all double-quotes from the base image pullspecs, and add handling for single-quotes as well.
see if there are recent e2e-tests updates that will be …
=> buildah: remove quotes from BASE_IMAGES, again

CODEOWNERS
... as code owners of the `sast-*-check` tasks.  They are going to be the primary maintainers of these task definitions.
Related: https://issues.redhat.com/browse/PSSECAUT-943
=> CODEOWNERS: add Jeremy Choi and Sam Fowler

CODEOWNERS
this commit makes the operator-foundry team owners of FBC tasks and FIPS tasks.
=> add operator-foundry to CODEOWNERS

appstudio-utils/Dockerfile
This should resolve a race condition seen in
`stepactions/eaas-create-ephemeral-cluster-hypershift-aws` when waiting for resource status which doesn't yet exist.
See https://github.com/kubernetes/kubectl/issues/1236
=> Upgrade kubectl in appstudio-utils to v1.26

policies/all-tasks.yaml, policies/step-actions.yaml, task/coverity-availability-check-oci-ta/0.2/MIGRATION.md, task/coverity-availability-check-oci-ta/0.2/coverity-availability-check-oci-ta.yaml, task/coverity-availability-check-oci-ta/0.2/kustomization.yaml, task/coverity-availability-check/0.2/kustomization.yaml
Previously, coverity-availability-check-oci-ta.yaml was just a symlink to coverity-availability-check.yaml. Which means .metadata.name was 'coverity-availability-check'. This caused pipelines referencing coverity-availability-check-oci-ta:0.2 to fail with
Couldn't retrieve Task ...
could not find object in image with kind: task and name: coverity-availability-check-oci-ta
Generate coverity-availability-check-oci-ta.yaml from coverity-availability-check.yaml via kustomize, set the .metadata.name to the expected name.
Add kustomization.yaml to coverity-availability-check as well, otherwise coverity-availability-check-oci-ta wouldn't be able to use it as a base.
Explain how to switch from coverity-availability-check-oci-ta to
coverity-availability-check
=> coverity-availability-check-oci-ta/0.2: fix name, improve migration doc

stepactions/eaas-copy-secrets-to-ephemeral-cluster/0.1/eaas-copy-secrets-to-ephemeral-cluster.yaml, stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/eaas-create-ephemeral-cluster-hypershift-aws.yaml, stepactions/eaas-get-latest-openshift-version-by-prefix/0.1/eaas-get-latest-openshift-version-by-prefix.yaml, stepactions/eaas-get-supported-ephemeral-cluster-versions/0.1/eaas-get-supported-ephemeral-cluster-versions.yaml
This is a followup to #1918.
Commit tags are removed from the pull specs so renovate can identify newer versions.
=> Upgrade appstudio-utils image in EaaS stepactions

task/tkn-bundle-oci-ta/0.1/tkn-bundle-oci-ta.yaml, task/tkn-bundle/0.1/tkn-bundle.yaml
Add retry to tkn bundle push command
The tkn bundle push command fails from time to time, but succeeds when rerun.
Adding retries might reduce the errors we are seeing.
=> chore(KFLUXVNGD-183): add retries to tkn bundle push

CODEOWNERS, hack/build-and-push.sh, renovate.json, task/git-clone-oci-ta/0.1/git-clone-oci-ta.yaml, task/git-clone-oci-ta/0.1/kustomization.yaml, task/git-clone/0.1/git-clone.yaml, task/pnc-prebuild-git-clone-oci-ta/0.1/README.md, task/pnc-prebuild-git-clone-oci-ta/0.1/kustomization.yaml, task/pnc-prebuild-git-clone-oci-ta/0.1/patch.yaml, task/pnc-prebuild-git-clone-oci-ta/0.1/pnc-prebuild-git-clone-oci-ta.yaml
As middleware (PNC) need to preprocess the source in order to prepare it for building within a container an extra step is required for the PNC custom pipeline
=> Add PNC prebuild task based upon git-clone-oci-ta

task/prefetch-dependencies-oci-ta/0.1/prefetch-dependencies-oci-ta.yaml, task/prefetch-dependencies-oci-ta/0.2/prefetch-dependencies-oci-ta.yaml, task/prefetch-dependencies/0.1/prefetch-dependencies.yaml, task/prefetch-dependencies/0.2/prefetch-dependencies.yaml
prefetch-dependencies has been changed recently and is currently failing on a jq syntax error
Allowing if without else-branch in jq seems to not be implemented in jq 1.6, which is used in the cachi2 image used in the prefetch-dependencies tasks
Add an else branch with '.' (identity) to fix the syntax error
This has been tested manually in the [base image used in the cachi2 image](https://github.com/hermetoproject/cachi2/blob/2235854bfc5cb76ea168cb04d50be16efce9fa0a/Dockerfile#L1)
=> Fix jq syntax error in prefetch-dependencies tasks

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/maven-zip-build-oci-ta/README.md, pipelines/maven-zip-build/README.md, pipelines/tekton-bundle-builder/README.md, task/buildah-min/0.2/buildah-min.yaml, task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-oci-ta/0.3/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote-oci-ta/0.3/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah-remote/0.3/buildah-remote.yaml, task/buildah/0.2/buildah.yaml, task/buildah/0.3/buildah.yaml, task/sast-coverity-check-oci-ta/0.2/README.md, task/sast-coverity-check-oci-ta/0.2/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.2/kustomization.yaml, task/sast-coverity-check/0.2/patch.yaml, task/sast-coverity-check/0.2/sast-coverity-check.yaml
Deprecate buildah/0.2 on 1st March 2025
Deprecate buildah/0.3 on 31st March 2025
This mainly to "motivate" users to update to the version that switched the default SBOM type to SPDX
Also update the sast-coverity-check task to be based on buildah 0.4 rather than 0.3, to avoid inheriting the deprecation annotation. And fix the version label in the task.
=> Deprecate old buildah tasks

pipelines/tekton-bundle-builder/README.md, pipelines/tekton-bundle-builder/patch.yaml, pipelines/tekton-bundle-builder/tekton-bundle-builder.yaml
Align tasks in `tekton-bundle-builder` pipeline:
- Remove `rpm-signature-scan` task
- Remove `push-dockerfile` task
- Add `coverity-availability-check` task
- Add `sast-shell-check` task
- Update Pipeline
- Update README
=> chore(KFLUXVNGD-194): Align tasks in tekton-bundle-builder pipeline

.tekton/pull-request.yaml, .tekton/scripts/determine-if-e2e-execution-needed.py, .tekton/tasks/task-switchboard.yaml
PR adds a logic to determine when the e2e-tests needs to be executed. E2e tests will be executed only for the pipelines/tasks/files changes for which coverage is there and for unrelated changes, it will skip e2e-tests execution task.
This is part of the story: https://issues.redhat.com/browse/STONEBLD-3161
=> feat: execute e2e-tests only when needed

task/acs-image-check/0.1/acs-image-check.yaml
Failure during roxctl-image-check currently does not cause the
acs-image-check task to fail, resulting in a false negative.
Make rox-image-check step exit with non-zero code in case of a failure,
but continue with rest of the TaskRun in order to create a successful
report in the next report step.
Add a new step which fails if rox-image-check step failed so the whole
TaskRun ends with a failure
=> Fail acs-image-check task when image check fails

task/sast-shell-check/0.1/tests/test-sast-shell-check.yaml, task/sast-unicode-check/0.1/tests/test-sast-unicode-check.yaml
=> SAST tests: Creation of tests for SAST tasks

task/sealights-go-oci-ta/0.1/README.md, task/sealights-go-oci-ta/0.1/sealights-go-oci-ta.yaml
* use dedicated image from quay.io/konflux-ci/tekton-integration-catalog/sealights-go that already contains those binaries
* also use the latest go toolset image by default
=> fix: do not download Sealights Go binaries

task-generator/remote/main.go, task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote-oci-ta/0.3/buildah-remote-oci-ta.yaml, task/buildah-remote-oci-ta/0.4/buildah-remote-oci-ta.yaml, task/buildah-remote/0.1/buildah-remote.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah-remote/0.3/buildah-remote.yaml, task/buildah-remote/0.4/buildah-remote.yaml
Re-enable Nvidia GPU support in the buildah-remote tasks
It was initially introduced in #1529 and reverted in #1638
=> Revert the revert of "Nvidia GPU support in the buildah-remote task"

pipelines/enterprise-contract.yaml
This should mean it works as expected for users who set it to "pipeline_intention=release" in their IntegrationTestScenario params list.
Ref: [KONFLUX-6809](https://issues.redhat.com/browse/KONFLUX-6809)
=> Expose EXTRA_RULE_DATA ec param at pipeline level

task/validate-fbc/0.1/validate-fbc.yaml
The computation of differential related images has been improved by removing jq operations which require large arrays to be loaded.
related: https://github.com/konflux-ci/konflux-test/pull/364
* Check to make sure that a valid base image tag is found
* Properly catch failure to retrieve differential base iamges
resolves: [KONFLUX-6943](https://issues.redhat.com//browse/KONFLUX-6943)
=> Improve the performance and validation of validate-fbc task

task/sealights-nodejs-oci-ta/0.1/README.md, task/sealights-nodejs-oci-ta/0.1/sealights-nodejs-oci-ta.yaml, task/sealights-python-oci-ta/0.1/README.md, task/sealights-python-oci-ta/0.1/sealights-python-oci-ta.yaml
* use dedicated images from quay.io/konflux-ci/tekton-integration-catalog/sealights-python and quay.io/konflux-ci/tekton-integration-catalog/sealights-nodejs that already contain those binaries
* also use the latest ubi9 images by default (hence no need to specify python-version and nodejs-version)
=> fix: avoid downloading Sealights Agents binaries

task/sast-snyk-check/0.3/tests/test-sast-snyk-check-no-token.yaml
Because we can't do a real run of snyk in tests due to the secret token requirement, this test just ensures the snyk check is skipped in the expected fashion. A test source code repository is not cloned for this test, as it would not change the behaviour of the skipped snyk check task.
Supports [PSSECAUT-954](https://issues.redhat.com//browse/PSSECAUT-954)
=> Add test-sast-snyk-check-no-token.yaml

policies/all-tasks.yaml, policies/step-actions.yaml, task/sast-coverity-check-oci-ta/0.2/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.2/patch.yaml, task/sast-coverity-check/0.2/sast-coverity-check.yaml
- do not change CWD while instrumenting RUN lines
- use shell form of RUN instructions while instrumenting `Containerfile` because the exec form is not supported by the `cachi2` instrumentation implemented in the `build-container` task, which `sast-coverity-check` is derived from.
Resolves: https://issues.redhat.com/browse/OSH-813
Resolves: https://issues.redhat.com/browse/OSH-809
Related: https://issues.redhat.com/browse/KONFLUX-6806
=> sast-coverity-check: eliminate scan failures reported by users

task/coverity-availability-check-oci-ta/0.2/coverity-availability-check-oci-ta.yaml, task/coverity-availability-check-oci-ta/0.2/kustomization.yaml
... to make sure that users migrate off the deprecated task so that it does not need to be maintained forever.
Resolves: https://issues.redhat.com/browse/OSH-810
=> coverity-availability-check: deprecate the -oci-ta copy

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/fbc-builder/README.md, pipelines/maven-zip-build-oci-ta/README.md, pipelines/maven-zip-build/README.md, pipelines/tekton-bundle-builder/README.md, task/build-image-index/0.1/README.md, task/build-image-index/0.1/build-image-index.yaml, task/build-image-manifest/0.1/build-image-manifest.yaml, task/buildah-min/0.4/buildah-min.yaml, task/buildah-oci-ta/0.4/README.md, task/buildah-oci-ta/0.4/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.4/buildah-remote-oci-ta.yaml, task/buildah-remote/0.4/README.md, task/buildah-remote/0.4/buildah-remote.yaml, task/buildah/0.4/README.md, task/buildah/0.4/buildah.yaml, task/sast-coverity-check-oci-ta/0.2/README.md, task/sast-coverity-check-oci-ta/0.2/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.2/sast-coverity-check.yaml, task/show-sbom/0.1/show-sbom.yaml
While we still produce images with an OCI mediaType by default, some users may need to generate docker mediaTypes in order to remain compatible with older functionality. This change lets that setting be configured.
We are not exposing it as a pipeline parameter by default to encourage the continued use of OCI mediaTypes.
=> feat(KONFLUX-6858): add support for generating docker mediaType

task/coverity-availability-check/0.2/tests/test-coverity-availability-check.yaml
Adds a test for the expected behaviour for `coverity-availability-check` when the expected secrets are not available.
Related, I'm not sure if it's intended that `coverity-availability-check` currently does not write anything to `TEST_OUTPUT`, if these secrets are not available. Because of this, this test currently does not verify anything in `TEST_OUTPUT`.
=> Add test-coverity-availability-check.yaml

task/sast-coverity-check-oci-ta/0.2/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.2/patch.yaml, task/sast-coverity-check/0.2/sast-coverity-check.yaml, task/sast-shell-check-oci-ta/0.1/sast-shell-check-oci-ta.yaml, task/sast-shell-check/0.1/sast-shell-check.yaml, task/sast-snyk-check-oci-ta/0.3/sast-snyk-check-oci-ta.yaml, task/sast-snyk-check/0.3/sast-snyk-check.yaml, task/sast-unicode-check-oci-ta/0.1/sast-unicode-check-oci-ta.yaml, task/sast-unicode-check/0.1/sast-unicode-check.yaml
... when `KFP_GIT_URL` is set to `SITE_DEFAULT`, which is the default value.  This way we do not need to hardcode the list of internal Konflux clusters, as initially implemented in #1848 and #1883.
Related: https://issues.redhat.com/browse/KONFLUX-4530
Related: https://issues.redhat.com/browse/OSH-763
Resolves: https://issues.redhat.com/browse/OSH-814
=> sast-*-check: check connectivity to CEE GitLab

hack/build-and-push.sh
This change can benefit other scripts that want to reuse this script to build bundles at a differet location rather than from inside build-definitions repo. It may be for testing purpose without writing custom code to repeat the logic of build-and-push process. For example of a use case: https://github.com/konflux-ci/pipeline-migration-tool/pull/10
=> Allow specifying startup directory

task/validate-fbc/0.1/validate-fbc.yaml
There is often a lot of text output when validating the related images. In order to enable better troubleshooting, we will augment the normal output to add additional details.
=> fix(KONFLUX-6999): improve logging output for FBC validation

CODEOWNERS, renovate.json
The task is generated from the git-clone task => changes to the git-clone task will always require corresponding changes to the PNC task.
Add build team to the CODEOWNERS of this task to avoid git-clone changes being blocked on reviews from the PNC team.
Also move this task to the same Renovate group as git-clone. Otherwise Renovate PRs would fail CI because they would only update the git-clone task and not the PNC task.
=> pnc-prebuild-git-clone: add build team to owners

task/git-clone-oci-ta/0.1/git-clone-oci-ta.yaml, task/git-clone/0.1/git-clone.yaml, task/pnc-prebuild-git-clone-oci-ta/0.1/pnc-prebuild-git-clone-oci-ta.yaml
Git fetch tags currently fail, when a repo has submodules. 
Fetching for the second time works as a workaround.
=> fix: retry git fetch --tags on fail

.tekton/scripts/determine-if-e2e-execution-needed.py, .tekton/tasks/task-switchboard.yaml
Comparing with main branch of the origin to find changed files in the PR, when running in the merge queue it will help detecting the changes and execute CI accordingly.
This is part of the story: https://issues.redhat.com/browse/STONEBLD-3270
=> fix: CI execution in the merge queue

task/acs-image-check/0.1/acs-image-check.yaml
acs-image-check task currently fails when there are Critical or High policy violations detected
The task should pass if it succeeds in creating a report and let users handle the policy violations separately themselves
=> Let acs-image-check task pass with policy violations

task/verify-signed-rpms/0.1/README.md, task/verify-signed-rpms/0.1/verify-signed-rpms.yaml
The task was renamed and the task under the old name is not maintained anymore and should not be used.
=> chore(KFLUXVNGD-221): deprecate task verify-signed-rpms

task/fbc-fips-check-oci-ta/0.1/fbc-fips-check-oci-ta.yaml, task/fbc-fips-check/0.1/fbc-fips-check.yaml, task/fips-operator-bundle-check-oci-ta/0.1/fips-operator-bundle-check-oci-ta.yaml, task/fips-operator-bundle-check/0.1/fips-operator-bundle-check.yaml
This commit updates konflux-test version to 1.4.18 and stepaction revision to the latest commit for FIPS tasks
Refers to [CLOUDDST-26028](https://issues.redhat.com//browse/CLOUDDST-26028)
=> update refs for FIPS tasks

.tekton/pull-request.yaml
When we push the changes to merge queue, durin final merge event two pipelineruns were created one for push pipelinerun and another pr pipelinerun. This change will avoid that  unnecessary trigger of pr pipeline run.
=> fix: avoid triggering duplicate pipelinerun during final merge

task/verify-signed-rpms/0.1/verify-signed-rpms.yaml
A fixup for commit 5a8e618dc2656f2a52bfd352bc4a9fe1fb19c87e which added the keys at the wrong level.
Split out from #2011 for early merge.
=> Fix expires-on in verify-signed-rpms task

task/validate-fbc/0.1/validate-fbc.yaml
With EC-965, we created a policy which can verify a set of related images that have been idenified by this task and attached to the FBC image. Since we can check validity with Conforma, we no longer need to check validity here.
This enables users to produce a FBC catalog while ignoring unreleased related images until it actually matters (i.e. until the fragment is about to be pushed to production).
=> feat: stop checking related image accessibility in validate-fbc

stepactions/fips-operator-check-step-action/0.1/fips-operator-check-step-action.yaml
currently, the stepaction directly tries to access the mirror from IDMS, if present. This commit fixes that behavior by accessing the original pullspec first and resorting to the mirror only if required. It also allows users to provide more than one mirrors for their images.
=> fix(KONFLUX-7202): access IDMS only if original pullspec is unavailable

task/fbc-fips-check-oci-ta/0.1/fbc-fips-check-oci-ta.yaml, task/fbc-fips-check/0.1/fbc-fips-check.yaml, task/fips-operator-bundle-check-oci-ta/0.1/fips-operator-bundle-check-oci-ta.yaml, task/fips-operator-bundle-check/0.1/fips-operator-bundle-check.yaml
like the stepaction, the tasks also used IDMS directly instead of
attempting to access the original pullspec. This commit fixes that
behavior and uses the updated stepaction. It also allows users to
provide more than one mirrors
Refers to [KONFLUX-7202](https://issues.redhat.com//browse/KONFLUX-7202) and [KONFLUX-7203](https://issues.redhat.com//browse/KONFLUX-7203)
=> access IDMS in FIPS tasks only if required

task/sast-coverity-check-oci-ta/0.2/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.2/patch.yaml, task/sast-coverity-check/0.2/sast-coverity-check.yaml
... so that `coverity capture` does not wait for them to finish.
The behavior of `sast-coverity-check` needs to be compatible with the behavior of `build-container`, which does not wait for the background processes to finish.  Otherwise a container image that takes 6 minutes to build natively, takes 2 hours to timeout with `sast-coverity-check`.
Resolves: https://issues.redhat.com/browse/KFLUXSPRT-2157
=> sast-coverity-check: kill orphan background processes

.github/workflows/check-buildah-remote.yaml, .github/workflows/check-kustomize-build.yaml, .github/workflows/check-readmes.yaml, .github/workflows/check-ta.yaml, .github/workflows/check-task-migration.yaml, .github/workflows/check-task-owners.yaml, .github/workflows/checkton.yaml, .github/workflows/go-ci.yaml, .github/workflows/run-task-tests.yaml, .github/workflows/yaml-lint.yaml
Execute all the github actions CI inside merge queue, to validate the correctness of the checks again
=> fix: execute github actions CI inside merge_queue

task/buildah-min/0.4/buildah-min.yaml, task/sast-coverity-check-oci-ta/0.2/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.2/patch.yaml, task/sast-coverity-check/0.2/sast-coverity-check.yaml
... in the post-process step, too, and do not set any limit on CPUs.
The increased resources are needed in the `post-process` step, too, because Coverity runs there in case the buildful capture fails.  We have reports about Coverity being OOM killed in the step.  I wish we could ask for more memory and CPUs but then the `sast-coverit-check` task is not started at all.
Related: https://github.com/konflux-ci/build-definitions/pull/1821
Related: https://issues.redhat.com/browse/KFLUXSPRT-2167
Related: https://issues.redhat.com/browse/KFLUXSPRT-2181
=> sast-coverity-check: request 4 GiB of RAM

task/coverity-availability-check-oci-ta/0.2/coverity-availability-check-oci-ta.yaml, task/coverity-availability-check/0.2/coverity-availability-check.yaml, task/coverity-availability-check/0.2/tests/test-coverity-availability-check.yaml
The intention of this change is the coverity-availability-check task should report failure status to users, to indicate that action is needed (add coverity secrets), but it should NOT cause the pipeline to fail.
=> coverity-availability-check: result status ERROR -> FAILURE

CODEOWNERS, renovate.json, task/build-helm-chart-oci-ta/0.1/README.md, task/build-helm-chart-oci-ta/0.1/build-helm-chart-oci-ta.yaml, task/build-helm-chart-oci-ta/0.1/recipe.yaml, task/build-helm-chart-oci-ta/OWNERS, task/build-helm-chart/0.1/README.md, task/build-helm-chart/0.1/build-helm-chart.yaml, task/build-helm-chart/OWNERS
The task can be used in order to package and push a Helm chart to an OCI repository.
=> feat(KFLUXVNGD-185): add task for building helm charts

task/sealights-go-oci-ta/0.1/sealights-go-oci-ta.yaml, task/sealights-nodejs-oci-ta/0.1/sealights-nodejs-oci-ta.yaml, task/sealights-python-oci-ta/0.1/sealights-python-oci-ta.yaml
https://issues.redhat.com/browse/KFLUXDP-208
* store agent/cli versions in Tekton Results - related to https://issues.redhat.com/browse/KFLUXDP-208
* [stop using npx](https://github.com/konflux-ci/build-definitions/pull/2024/commits/bd0328bf08580c932987f34117285f7166f5a98d), because npx uses the package (in this case `slnodejs`) from a remote location, if it's not installed locally - this caused an issue that the Node.js instrumentation Task was using a different version of `slnodejs` package than it was installed in the container image. The local version of the package was not found, because the installed package was overwritten by a mounted directory used for trusted artifact. Due to that I had to [change the working directory used for the trusted …
=> feat: store Sealights agent/cli version in Results

pipelines/maven-zip-build-oci-ta/README.md, pipelines/maven-zip-build-oci-ta/maven-zip-build-oci-ta.yaml, pipelines/maven-zip-build-oci-ta/patch.yaml
This is a follow-up to the fix in #1884, which was incomplete.
The mistake was discovered by Kasem Alem while working on #2018.
Related: https://issues.redhat.com//browse/KONFLUX-6914
=> maven-zip-build-oci-ta: fix a copy-paste mistake in the patch

task/sealights-go-oci-ta/0.1/README.md, task/sealights-go-oci-ta/0.1/sealights-go-oci-ta.yaml
https://issues.redhat.com/browse/KFLUXDP-180
By default we encourage users to use private images for Sealights TA and container images, because it will contain the Sealights token, which we don't want to expose in a public repo.
However Sealights CLI provides an option to disable the saving of the token and the application can be successfully deployed if it will be provided the `SEALIGHTS_TOKEN` environment variable during deployment. We will use this approach for konflux-ci component repositories.
=> feat: add possibility to skip saving the SL token

hack/build-and-push.sh
[STONEBLD-3353](https://issues.redhat.com//browse/STONEBLD-3353)
The problem is:
* commit 1 includes a migration, which is attached to the task bundle built from commit 1.
* then, commit 2 includes updates to the same task without bumping the version in label '.metadata.labels."app.kubernetes.io/version'.
* as a result, the migration is attached to the last bundle.
=> fix: avoid attaching migration to irrelevant task bundle

task/ecosystem-cert-preflight-checks/0.2/ecosystem-cert-preflight-checks.yaml
Distill the auth down to the entry necessary for pulling an image before passing to preflight.
=> fix(KONFLUX-6666) Select auth properly for preflight task

README.md
Add some additional information about specific changes needed to update a build-definition task along with
possible e2e test changes.
A follow on to #1978 
=> feat(STONEINTG-1069): add additional task version change guidance

task/ecosystem-cert-preflight-checks/0.1/ecosystem-cert-preflight-checks.yaml, task/ecosystem-cert-preflight-checks/0.2/ecosystem-cert-preflight-checks.yaml
This PR updates resource limits and requests for the task **ecosystem-cert-preflight-checks** as part of this effort - [KONFLUX-7127](https://issues.redhat.com/browse/KONFLUX-7127). 
The new request/limit values have been defined taking into account usages observed historically (tracked in this [spreadsheet](https://docs.google.com/spreadsheets/d/1d4Tn7PYkY2EVgpNyT29xL7y62akZNPIjy18VTzw54iQ/edit?gid=1735880927#gid=1735880927)) in the **stone-prd-rh01** cluster.
=> feat(KONFLUX-7127): Setup limits and resource for ecosystem-cert-preflight-checks task

README.md
[STONEBLD-2829](https://issues.redhat.com//browse/STONEBLD-2829)
=> Add document for using task migrations

hack/build-and-push.sh
The push failed due to Bad Gateway:
```
Copying blob sha256:6f0a4413f0e0eac0199d0ccade8d781a577fb7d6c43619a9b21a0549c3809374
error pushing image "quay.io/konflux-ci/pull-request-builds:appstudio-utils-b4525f6fcf9bfdf026717af3f868bcc83a0462db" to "docker://quay.io/konflux-ci/pull-request-builds:appstudio-utils-b4525f6fcf9bfdf026717af3f868bcc83a0462db": writing blob: initiating layer upload to /v2/konflux-ci/pull-request-builds/blobs/uploads/ in quay.io: received unexpected HTTP status: 502 Bad Gateway
time="2025-03-21T08:36:37Z" level=error msg="exit status 125"
```
Re-ran passed.
=> Retry push for appstudio-utils image

renovate.json
[STONEBLD-3351](https://issues.redhat.com//browse/STONEBLD-3351)
The customeManager for recipe.yaml is extended to work for patch.yaml files under task/ directory.
The regex is rewritten since the original for reciple.yaml does not work for images which do not include tag. For example, for given image app@sha256:1234, the matched depName is app@sha256.
=> fix: update konflux-tooling image in patch.yaml

task/clamav-scan/0.2/clamav-scan.yaml
The upload step required a fix to test this. It was silently failing to find any logs because the `find` command isn't present in the oras image.
=> Add support for self-signed OCI registries to clamav-scan task

pipelines/fbc-builder/README.md, pipelines/fbc-builder/fbc-builder.yaml, pipelines/fbc-builder/patch.yaml, task/sast-snyk-check-oci-ta/0.3/README.md, task/sast-snyk-check-oci-ta/0.3/sast-snyk-check-oci-ta.yaml, task/sast-snyk-check/0.3/README.md, task/sast-snyk-check/0.3/sast-snyk-check.yaml
https://github.com/konflux-ci/docs/pull/258 flattened the directory structure for some of the documentation pages. This broke some of the pages being linked to.
=> fix: updating the documentation links

stepactions/fips-operator-check-step-action/0.1/fips-operator-check-step-action.yaml, task/fbc-fips-check-oci-ta/0.1/fbc-fips-check-oci-ta.yaml, task/fbc-fips-check/0.1/fbc-fips-check.yaml
In FIPS tasks, fixed the way lists of IDMS mirrors are populated into bash arrays.
=> fix(KFLUXSPRT-2387) Fix mirrors array population in FIPS tasks

task/buildah-min/0.4/buildah-min.yaml, task/buildah-oci-ta/0.4/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.4/buildah-remote-oci-ta.yaml, task/buildah-remote/0.4/buildah-remote.yaml, task/buildah/0.4/buildah.yaml, task/sast-coverity-check-oci-ta/0.2/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.2/sast-coverity-check.yaml
This fixes a bug in the coverity-check task. When builds are run with prefetched rpms, the cachi2.repo file is first copied by the original buildah task. Later when coverity-check repeats the build, the cachi2.repo file is already there, so `cp --no-clobber` exits with an error.
Fix tested here: https://github.com/openshift-kni/dpdk-base/pull/17
=> fix(KONFLUX-7346): buildah: check if cachi2.repo file exists

task/clamav-scan/0.2/clamav-scan.yaml
This change makes it possible to extract image even on kind cluster, the behaviour of scan itself remains the same.
=> fix(KONFLUX-5907): make clamav work on kind cluster

.github/workflows/check-task-migration.yaml
The current output is informative enough. When check CI job logs from GitHub, verbose mode makes the logs too long to focus on the necessary messages output from the script itself.
=> Disable verbose output during migration validation

task/prefetch-dependencies-oci-ta/0.2/prefetch-dependencies-oci-ta.yaml, task/prefetch-dependencies/0.2/prefetch-dependencies.yaml
Some repos with go submodules would fail during prefetch dependencies task. 
Cachi2 would fail and this serves as a workaround, since we didn't find the root cause.
=> Force fetching git tags on some projects with go submodule

task/prefetch-dependencies-oci-ta/0.2/prefetch-dependencies-oci-ta.yaml, task/prefetch-dependencies/0.2/prefetch-dependencies.yaml
Move to quay.io/konflux-ci/hermeto since I see 0.23.0 is only pushed to the new repo instead of quay.io/konflux-ci/cachi2
=> [prefetch] Switch the cachi2 image to the new name hermeto

hack/trusted-tasks-update.sh
* Fix a bug related to default env var quoting
* Remove possibility of ec track bundle timing out
* Support specifying just the task that needs to update, since updating them all takes a really long time.
All these changes were either necessary or useful for [EC-1199](https://issues.redhat.com/browse/EC-1199) where I needed to get one missing task added to the acceptable bundles data.
=> Several fixes & improvements for hack/trusted-tasks-update

task/tkn-bundle-oci-ta/0.1/tkn-bundle-oci-ta.yaml, task/tkn-bundle/0.1/tkn-bundle.yaml
When using a file as CONTEXT in the task, the task fails for not finding the file.
It happens because in the task's script we are adding only the file without the workspace and source.
Update the task to add the workspace and source dir to the file
=> fix(KFLUXVNGD-267): tkn-bundle task fails when the context is a file

CODEOWNERS, renovate.json, task/modelcar-oci-ta/0.1/README.md, task/modelcar-oci-ta/0.1/modelcar-oci-ta.yaml
Add a ModelCar task to build images in Konflux
This depends on https://github.com/konflux-ci/build-tasks-dockerfiles/pull/252 for the SBOM script
- closes [AIPCC-632](https://issues.redhat.com//browse/AIPCC-632)
=> AIPCC-632: Add ModelCar OCI TA task

task/run-script-oci-ta/0.1/run-script-oci-ta.yaml
The .metadata.name in run-script-oci-ta.yaml doesn't match the filename. Because of that, the CI gets confused:
- The create-task-pipeline-bundle-repos.sh script reads the name from the yaml, creates quay.io/konflux-ci/tekton-catalog/task-run-script
- The build-and-push.sh script takes the name from the file name, pushes to quay.io/konflux-ci/tekton-catalog/task-run-script-oci-ta. Pushing to a non-existent repo creates it as private. The script then fails to read from the private repo.
Fix the run-script-oci-ta task name in the YAML metadata, to make sure both the scripts will use the same name.
=> run-script-oci-ta: fix .metadata.name

task/modelcar-oci-ta/0.1/modelcar-oci-ta.yaml
This is used by conforma to look up what tasks should be required for the given pipeline. The tasks required of a modelcar build will be different from those required of a normal docker build - primarily, the "buildah" task is not required.
Related:
* https://github.com/konflux-ci/build-definitions/pull/2171
* https://github.com/release-engineering/rhtap-ec-policy/pull/138
=> Specify modelcar build_type is modelcar

task/oci-copy-oci-ta/0.2/oci-copy-oci-ta.yaml, task/oci-copy/0.2/oci-copy.yaml
We can only declare one list of required tasks per "build_type" in the conforma rule data and "oci-artifact" was a little too generic.
By making this more specific, we can create a list of tasks required for "oci-copy" build pipelines that includes the oci-copy task.
Related:
* https://github.com/konflux-ci/build-definitions/pull/2170
* https://github.com/release-engineering/rhtap-ec-policy/pull/138
=> Rename the oci-copy build type

pipelines/core-services/kustomization.yaml, pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-multi-platform-oci-ta/docker-build-multi-platform-oci-ta.yaml, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build-oci-ta/docker-build-oci-ta.yaml, pipelines/docker-build/README.md, pipelines/docker-build/docker-build.yaml, pipelines/docker-build/patch.yaml, pipelines/fbc-builder/patch.yaml
Add the `privileged-nested` parameter to the single and multiplatform build pipelines
=> chore: add privileged-nested parameter to build pipelines

pipelines/tekton-bundle-builder-oci-ta/README.md, pipelines/tekton-bundle-builder-oci-ta/patch.yaml, pipelines/tekton-bundle-builder-oci-ta/tekton-bundle-builder-oci-ta.yaml
workspace was removed from the pipeline when creating tekton-bundle-builder-oci-ta pipeline.
workspace is optional for task summary, so this removal just works.
This issue is found during review on #2018. That makes migration validation fails.
=> Remove workspace from show-summary task

task-generator/remote/main.go, task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote-oci-ta/0.3/buildah-remote-oci-ta.yaml, task/buildah-remote-oci-ta/0.4/buildah-remote-oci-ta.yaml, task/buildah-remote/0.1/buildah-remote.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah-remote/0.3/buildah-remote.yaml, task/buildah-remote/0.4/buildah-remote.yaml
When passing a variable to SSH, it gets evaluated by two shells: the shell that's currently running and the shell on the remote server. What does this mean?
If you run this example locally:
message='hello there'
printf '%s.' $message
The message breaks into two arguments, because it's not properly quoted. Fix by adding quotes:
message='hello there'
printf '%s.' "$message"
But then, when you add ssh into the mix:
message='hello there'
ssh "$some_host" printf '%s.' "$message"
The message broke again. That's because ssh received a list of arguments already expanded by your shell and concatenated them together, resulting in a command that may look something like this:
printf %s. hello there
When passing arbitrary strings to ssh, they need two layers of quoting. The result of variable …
=> buildah-remote: fix ssh shell quoting

hack/generate-everything.sh, pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build-rhtap/README.md, pipelines/docker-build/README.md, pipelines/fbc-builder/README.md, pipelines/gitops-pull-request-rhtap/README.md, pipelines/maven-zip-build-oci-ta/README.md, pipelines/maven-zip-build/README.md, pipelines/tekton-bundle-builder-oci-ta/README.md, pipelines/tekton-bundle-builder/README.md, task/git-clone-oci-ta/0.1/README.md, task/git-clone-oci-ta/0.1/git-clone-oci-ta.yaml, task/git-clone/0.1/README.md, task/git-clone/0.1/git-clone.yaml, task/pnc-prebuild-git-clone-oci-ta/0.1/pnc-prebuild-git-clone-oci-ta.yaml
This pull request introduces new functionality to the `git-clone` task to optionally merge a target branch into the checked-out revision. The changes
include:
- **Introduced `mergeTargetBranch` parameter:** Allows enabling the merge of a target branch.
- **Added `targetBranch` parameter:** Specifies the branch to be merged (defaults to `main`).
- **Included new result `merged_sha`:** Outputs the commit SHA after a successful merge.
- **Updated `spec` and `steps` sections:** Added parameters and logic to handle the merge process.
1. **Added `mergeTargetBranch` parameter:** This parameter, when set to `"true"`, enables the merge of the specified target branch.
2. **Added `targetBranch` parameter:** Specifies the branch to be merged (defaults to `main`).
3. **Added `merged_sha` result:** …
=> feat: git-clone: Add optional targetBranch merging

hack/build-manifests.sh, task/buildah-min/0.4/buildah-min.yaml, task/buildah-min/0.4/patch.yaml, task/buildah-oci-ta/0.4/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.4/buildah-remote-oci-ta.yaml, task/buildah-remote/0.4/buildah-remote.yaml, task/buildah/0.4/buildah.yaml, task/sast-coverity-check-oci-ta/0.2/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.2/patch.yaml, task/sast-coverity-check/0.2/sast-coverity-check.yaml
When we were injecting the image content manifests after the image build, we were adding a new layer since it is not possible to just ammend the previously added layer locally. We have moved the script into the buildah-task image and modified it to COPY the `content-sets.json` into the container. This allows buildah's default behavior of only creating _one_ new layer to be respected.
resolves: [KONFLUX-7507](https://issues.redhat.com//browse/KONFLUX-7507)
=> fix(KONFLUX-7507): inject image content manifests via Containerfile

task/buildah-min/0.4/buildah-min.yaml, task/buildah-oci-ta/0.4/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.4/buildah-remote-oci-ta.yaml, task/buildah-remote/0.4/buildah-remote.yaml, task/buildah/0.4/buildah.yaml, task/sast-coverity-check-oci-ta/0.2/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.2/sast-coverity-check.yaml
As a user, I have often wanted to know what architecture a build is running on at the start as well as what the actual buildah command used was. We can easily output both of these to the log.
=> Improve log-based buildah debugging

task/init/0.1/init.yaml, task/init/0.2/init.yaml
This PR updates resource limits and requests for the task init as part of this effort - [KONFLUX-7127](https://issues.redhat.com/browse/KONFLUX-7127).
The new request/limit values have been defined taking into account usages observed historically (tracked in this [spreadsheet](https://docs.google.com/spreadsheets/d/1d4Tn7PYkY2EVgpNyT29xL7y62akZNPIjy18VTzw54iQ/edit?gid=1735880927#gid=1735880927)) in the stone-prd-rh01 cluster.
=> feat(KONFLUX-7127): Set limits/resources for task init

stepactions/fips-operator-check-step-action/0.1/fips-operator-check-step-action.yaml
Updated to make fips scan log slightly easier to read and determine which images had errors and were unable to be scanned. Also updated to use retries when calling `skopeo copy` and `umoci`.
=> fix(KONFLUX-7459): update logging and use retries for fips step action

pipelines/tekton-bundle-builder-oci-ta/README.md, pipelines/tekton-bundle-builder-oci-ta/tekton-bundle-builder-oci-ta.yaml, pipelines/tekton-bundle-builder/README.md, pipelines/tekton-bundle-builder/patch.yaml, pipelines/tekton-bundle-builder/tekton-bundle-builder.yaml, task/tkn-bundle-oci-ta/0.2/MIGRATION.md, task/tkn-bundle-oci-ta/0.2/README.md, task/tkn-bundle-oci-ta/0.2/recipe.yaml, task/tkn-bundle-oci-ta/0.2/tkn-bundle-oci-ta.yaml, task/tkn-bundle/0.2/MIGRATION.md, task/tkn-bundle/0.2/README.md, task/tkn-bundle/0.2/tkn-bundle.yaml
- Adding annotations to tasks created as bundles
- Migrating to v0.2 because of parameters addition
This PR is for adding annotations to the tasks being built as bundles using the `tkn-bundle` task.
There are 2 new parameters we need for the annotations:
URL - Source Code Git URL
REVISION - Revision of the Source Repository
And therefor a migration to v0.2 is needed.
=> chore(KFLUXVNGD-212): add annotations to bundles

task/inspect-image/0.1/inspect-image.yaml, task/inspect-image/0.2/inspect-image.yaml
This PR updates resource limits and requests for the task inspect-image as part of this effort - [KONFLUX-7127](https://issues.redhat.com/browse/KONFLUX-7127).
The new request/limit values have been defined taking into account usages observed historically (tracked in this [spreadsheet](https://docs.google.com/spreadsheets/d/1d4Tn7PYkY2EVgpNyT29xL7y62akZNPIjy18VTzw54iQ/edit?gid=1735880927#gid=1735880927)) in the stone-prd-rh01 cluster.
=> Set limits/resources for task inspect-image

task/fbc-fips-check-oci-ta/0.1/fbc-fips-check-oci-ta.yaml, task/fbc-fips-check/0.1/fbc-fips-check.yaml, task/fips-operator-bundle-check-oci-ta/0.1/fips-operator-bundle-check-oci-ta.yaml, task/fips-operator-bundle-check/0.1/fips-operator-bundle-check.yaml
Updated fips tasks refs to use the latest fips stepaction with logging and resiliency improvements.
=> fix(KONFLUX-7549): update refs for fips tasks

task/build-vm-image/0.1/build-vm-image.yaml
Some products need to build multi-arch disk images.
In order to do that, a matrix is used in the Pipeline definition for some parameters.
This commit introduces:
- support for those parameters as `matrix`.
- sanitizing the PLATFORM string, as tags don't not accept `_` chars.
- new result IMAGE_REFERENCE: see comment in the code for more details on why this is needed.
=> AIPCC-779(feat): build multi-arch disk images

task/fbc-target-index-pruning-check/0.1/fbc-target-index-pruning-check.yaml
Increased memory for fbc-target-index-pruning-check.
=> fix(KONFLUX-7841): Increase memory for fbc pruning check

task/tkn-bundle-oci-ta/0.2/tkn-bundle-oci-ta.yaml, task/tkn-bundle/0.2/README.md, task/tkn-bundle/0.2/tkn-bundle.yaml
Updating FILES[@] to FILES[0] to only pick the first element. 
All elements are referencing to the same task dir.
=> fix(KFLUXVNGD-212): update reference to FILES array

stepactions/fips-operator-check-step-action/0.1/fips-operator-check-step-action.yaml
Fixed the way the fips stepaction parses `unique_related_images.txt`.
=> fix(KONFLUX-7846): fix parsing of related imgs in fips stepaction

task/tkn-bundle-oci-ta/0.2/tkn-bundle-oci-ta.yaml, task/tkn-bundle/0.2/README.md, task/tkn-bundle/0.2/tkn-bundle.yaml
Add support to kustomization file.
In case a `kustomiztion.yaml` file is located in `CONTEXT` it will be used to generate the task definition and all other files in `CONTEXT` will be ignored
=> chore(KFLUXVNGD-242): add kustomization support to tkn-bundle

task/ecosystem-cert-preflight-checks/0.2/ecosystem-cert-preflight-checks.yaml
When `preflight` added the Red Hat Trademark tests, we were unable to update the `preflight` check in konflux, otherwise all Red Hat pipelines would fail the check. We then introduced the `PFLT_KONFLUX` in `preflight` which when enabled runs a konflux specific policy, with the Trademark tests removed. The below linked PR has those related changes.
- Relates: redhat-openshift-ecosystem/openshift-preflight#1247
Enable the flag in the latest `preflight` task and update to the `stable` release tag for the container image.
Using the test cluster, I built a new `tkn` bundle and created a `PipelineRun` to run against the `simple-demo-operator` container. The output below shows that the all checks passed, and the Trademark tests never ran.
```
[test-preflight : app-check] …
```
=> updating preflight task to use PFLT_KONFLUX env

pipelines/core-services/core-services.yaml, pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-multi-platform-oci-ta/docker-build-multi-platform-oci-ta.yaml, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build-oci-ta/docker-build-oci-ta.yaml, pipelines/docker-build/README.md, pipelines/docker-build/docker-build.yaml, pipelines/template-build/template-build.yaml
The pipeline docker-build-oci-ta can be used to build bundle images for operators. However, version v0.2 of ecosystem-cert-preflight-check is needed to make the test succeed with operator bundle images, too.
Blocks https://github.com/openshift/multiarch-tuning-operator/pull/572
=> Update task ecosystem-cert-preflight-check to v0.2

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, task/source-build-oci-ta/0.2/README.md, task/source-build-oci-ta/0.2/source-build-oci-ta.yaml, task/source-build/0.2/source-build.yaml
Enable users to pass IGNORE_MISSING_SIGNATURES parameter. 
When "true" source_build.py won't fail when source image has missing signatures
This is the implementation of the original [PR](https://github.com/konflux-ci/build-tasks-dockerfiles/pull/240) in build-tasks-dockerfiles and the parameter is passed to the source_build.py
This PR works hand in hand with: https://github.com/konflux-ci/build-tasks-dockerfiles/pull/257
=> Added source build task parameter

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/fbc-builder/README.md, pipelines/maven-zip-build-oci-ta/README.md, pipelines/maven-zip-build/README.md, task/buildah-min/0.4/buildah-min.yaml, task/buildah-oci-ta/0.4/README.md, task/buildah-oci-ta/0.4/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.4/buildah-remote-oci-ta.yaml, task/buildah-remote/0.4/buildah-remote.yaml, task/buildah/0.4/buildah.yaml, task/sast-coverity-check-oci-ta/0.2/README.md, task/sast-coverity-check-oci-ta/0.2/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check-oci-ta/0.3/README.md, task/sast-coverity-check-oci-ta/0.3/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.2/sast-coverity-check.yaml, task/sast-coverity-check/0.3/sast-coverity-check.yaml
This change will allow users of this task to specify a path to a file
containing annotations for their build.
This is especially useful in scenarios where the annotation value is dynamically generated by another task and the resulting value exceeds the limit set by Tekton task results.
Users can have a basic `annotations.txt` file in their repo with contents such as the following:
```
test.annotation.a=abc123
test.annotation.b=def456
```
And specify the param in the following format:
```
- name: ANNOTATIONS_FILE
value: "annotations.txt"
```
Or dynamically generate and export the annotation file in a script using the `run-script-oci-ta` task.
=> feat: Add support for ANNOTATIONS_FILE

task/build-helm-chart-oci-ta/0.1/build-helm-chart-oci-ta.yaml, task/build-helm-chart/0.1/build-helm-chart.yaml
Helm is unable to select the correct auth when pushing to OCI registries, so need to help it select the right one.
=> chore(KFLUXVNGD-283): use scoped auth for helm push

task/ecosystem-cert-preflight-checks/0.2/ecosystem-cert-preflight-checks.yaml
`ecosystem-cert-preflight-checks` is skipped for operator bundles. However, conforma checks fail if the result of it is not `SUCCESS`. This commit changes the task code to return `SUCCESS` when skipping due to the image under test being an operator bundle.
Originally-implemented-by: Dale Haiducek <19750917+dhaiducek@users.noreply.github.com>
Fixes #1931
=> Set preflight to SUCCESS for operator bundles

renovate.json
Currently, we have 3 separate PRs open for `.tekton/pull-request.yaml`:
* https://github.com/konflux-ci/build-definitions/pull/2187
* https://github.com/konflux-ci/build-definitions/pull/2076
* https://github.com/konflux-ci/build-definitions/pull/2060
Let's group updates like this into a single PR
=> renovate: group .tekton/* updates

appstudio-utils/Dockerfile, appstudio-utils/util-scripts/select-oci-auth.sh
This script is already installed in the 'oras' and 'build-trusted-artifacts' container images to work around oras not supporting containers-auth.json properly [1].
Add the script to the appstudio-utils image as well, which will enable us to also use this workaround for cosign. Cosign uses the go-containerregistry module for authentication, which works a bit better than oras, but still not well enough [2].
The script was copied from the build-trusted-artifacts repo [3].
[1]: https://github.com/oras-project/oras-go/issues/840
[2]: https://github.com/google/go-containerregistry/pull/1966
[3]: https://github.com/konflux-ci/build-trusted-artifacts/blob/ddb050d092df562860fe2522d4de234ed49dabd3/select-oci-auth.sh
=> appstudio-utils: add select-oci-auth script

.github/workflows/checkton.yaml, .github/workflows/go-ci.yaml, .github/workflows/run-task-tests.yaml
Some GHA checks fails while running on merge queue, there is [an issue ](https://issues.redhat.com/browse/STONEBLD-3354) open for it, till that issue is fixed, skip them for now
=> chore: skip GHA checks on merge queue till they are fixed

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/fbc-builder/README.md, pipelines/maven-zip-build-oci-ta/README.md, pipelines/maven-zip-build/README.md, task-generator/remote/main.go, task/buildah-min/0.4/buildah-min.yaml, task/buildah-oci-ta/0.4/README.md, task/buildah-oci-ta/0.4/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.4/buildah-remote-oci-ta.yaml, task/buildah-remote/0.4/buildah-remote.yaml, task/buildah/0.4/buildah.yaml, task/sast-coverity-check-oci-ta/0.2/README.md, task/sast-coverity-check-oci-ta/0.2/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check-oci-ta/0.3/README.md, task/sast-coverity-check-oci-ta/0.3/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.2/sast-coverity-check.yaml, task/sast-coverity-check/0.3/sast-coverity-check.yaml
It aims to make it able to build image with overlay2 storage driver.
As of right now, buildah-remote-oci-it can only build images using the VFS storage driver. We'd like it's able to support overlay2 as well, because overlay2 performs better than VFS in performance. We did a performance test to compare both (see https://issues.redhat.com/browse/KONFLUX-6577).
Arches | Duration - vfs | Duration overlay2 | % Change
-- | -- | -- | --
linux/amd64 | 0:00:34 | 0:00:20 | -41.52%
linux/arm64 | 0:01:57 | 0:01:12 | -38.30%
linux/ppc64le | 0:09:05 | 0:05:59 | -34.18%
Above result shows, compared to vfs storage drivers, duration of building image with overlay2 is reduced by around 30% to 40%.
**Note that the PR is not completed yet**.  It requires "buildah-task" modification [1], which makes buildah …
=> feat(KONFLUX-7125): Change buildah task to use overlay2 storage driver

task/init/0.1/init.yaml, task/prefetch-dependencies-oci-ta/0.1/prefetch-dependencies-oci-ta.yaml, task/prefetch-dependencies/0.1/prefetch-dependencies.yaml, task/source-build-oci-ta/0.1/source-build-oci-ta.yaml, task/source-build/0.1/source-build.yaml, task/summary/0.1/summary.yaml
Expiry date is set to the 31st of May.
After the deprecation period, they should be removed.
=> deprecate old tasks owned by the build team

task/upload-sbom-to-trustification/0.1/upload-sbom-to-trustification.yaml
SBOMs are getting uploaded to Red Hat Trusted Profile Analyzer in the GitOps pipeline.
Expose the link to the uploaded SBOM and wrap it around `TPA_SBOM_EYECATCHER` so that it can be used in UI.
Example output:
```
TPA_SBOM_URL_EYECATCHER_BEGIN
{
"TPA_SBOM_URL": "<url>"
}
```
=> Expose the link to an uploaded SBOM in TPA

.tekton/tasks/ec-checks.yaml, appstudio-utils/Dockerfile, pipelines/enterprise-contract.yaml
We're now building a main branch Conforma image and related Tekton task bundle in Konflux. These new Konflux-built images are pushed to a different repo than the equivalent GitHub built images.
The goal is to use the Konflux builds instead of the GitHub builds. In this PR the image refs are updated in a few different places.
(See commit messages for further details.)
Ref: https://issues.redhat.com/browse/EC-913
=> Use new Konflux-built Conforma/EC images

task/oci-copy-oci-ta/0.2/oci-copy-oci-ta.yaml, task/oci-copy/0.2/oci-copy.yaml
Cosign uses the go-containerregistry module for authentication. This
module doesn't implement containers-auth.json handling properly [1].
In particular, the keys in the auth file must either be full image
names or just hostnames:
quay.io/my-org/my-image
quay.io
Partial paths are not supported:
quay.io/my-org
Use the select-oci-auth script [1] as a workaround to make cosign work
for partial paths in the auth file.
[1]: https://github.com/konflux-ci/build-definitions/blob/main/appstudio-utils/util-scripts/select-oci-auth.sh
=> oci-copy: work around broken cosign auth

task/modelcar-oci-ta/0.1/modelcar-oci-ta.yaml
Cosign uses the go-containerregistry module for authentication. This
module doesn't implement containers-auth.json handling properly [1].
In particular, the keys in the auth file must either be full image
names or just hostnames:
quay.io/my-org/my-image
quay.io
Partial paths are not supported:
quay.io/my-org
Use the select-oci-auth script [1] as a workaround to make cosign work
for partial paths in the auth file.
[1]: https://github.com/konflux-ci/build-definitions/blob/main/appstudio-utils/util-scripts/select-oci-auth.sh
=> modelcar: work around broken cosign auth

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/fbc-builder/README.md, pipelines/maven-zip-build-oci-ta/README.md, pipelines/maven-zip-build/README.md, task/buildah-min/0.4/buildah-min.yaml, task/buildah-oci-ta/0.4/README.md, task/buildah-oci-ta/0.4/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.4/buildah-remote-oci-ta.yaml, task/buildah-remote/0.4/buildah-remote.yaml, task/buildah/0.4/README.md, task/buildah/0.4/buildah.yaml, task/sast-coverity-check-oci-ta/0.2/README.md, task/sast-coverity-check-oci-ta/0.2/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check-oci-ta/0.3/README.md, task/sast-coverity-check-oci-ta/0.3/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.2/sast-coverity-check.yaml, task/sast-coverity-check/0.3/sast-coverity-check.yaml
Allows to mount the current working directory into the build using
--volume $PWD:/$WORKINGDIR_MOUNT. Note that the $PWD will be the context
directory for the build, because we set the workdir to the context dir
before calling 'buildah build'.
The primary use case for this parameter is for builds that need to write
some outputs into a shared directory and reference the output in a later
FROM instruction, e.g.
FROM oci-archive:./out.ociarchive
See https://github.com/konflux-ci/buildah-container/issues/134 for more details.
=> buildah: add WORKINGDIR_MOUNT parameter

task/run-script-oci-ta/0.1/run-script-oci-ta.yaml
some build would fail, because cachi2 directory doesn't exist in the image
=> fix: check cachi2 dir existence/PREFETCH_ARTIFACT being non-empty

pipelines/core-services/core-services.yaml, pipelines/docker-build-oci-ta/patch.yaml, pipelines/docker-build/docker-build.yaml, pipelines/maven-zip-build-oci-ta/patch.yaml, pipelines/maven-zip-build/maven-zip-build.yaml, pipelines/tekton-bundle-builder-oci-ta/patch.yaml, pipelines/tekton-bundle-builder/tekton-bundle-builder.yaml, pipelines/template-build/template-build.yaml, task/prefetch-dependencies-oci-ta/0.2/prefetch-dependencies-oci-ta.yaml, task/prefetch-dependencies/0.2/prefetch-dependencies.yaml
I think it may be confusing users that if they pass `""` then the task is skipped (which may cause conforma to fail with "no skipped tasks"), even when they have no _real_ content that they want to prefetch, say for a data container like a bundle or something that just contains basic shell scripts.
With this, the prefetch task will run, but with the input of `""`, it will exit early with exit code 0.
Related: https://github.com/release-engineering/rhtap-ec-policy/pull/128
=> Don't skip prefetch by default

hack/generate-readme.sh
The behavior of empty array streaming changed in v4.45.2 [1]
Before:
$ echo '[]' | yq.4.45.1 '.[] | .a + "hi"'
<no output>
After:
$ echo '[]' | yq.4.45.2 '.[] | .a + "hi"'
hi
This broke the logic in the README generator script. It is now trying to add sections that have no content, e.g. a Workspaces section for tasks that have no workspaces.
Refactor to work with the new yq version.
[1]: https://github.com/mikefarah/yq/issues/2325#issuecomment-2851357108
=> generate-readme: work around bug in yq v4.45.2

task/modelcar-oci-ta/0.1/modelcar-oci-ta.yaml
Adding a parameter for olot to be able to pass `--remove-originals`.
Also adjusting permissions on the model files so that they can actually
be remove. Also updating olot version to support this new param.
=> task/modelcar-oci-ta: Parametrize olot --remove-originals param

task/modelcar-oci-ta/0.1/modelcar-oci-ta.yaml
The update in dec4145e607b0e4f5d92c806adbcad544a374cdc was incorrect, the current image does not include the select-oci-auth script. Update to the correct image.
=> modelcar: fix appstudio-utils image version

task/buildah-min/0.4/buildah-min.yaml, task/buildah-oci-ta/0.4/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.4/buildah-remote-oci-ta.yaml, task/buildah-remote/0.4/buildah-remote.yaml, task/buildah/0.4/buildah.yaml, task/sast-coverity-check-oci-ta/0.2/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check-oci-ta/0.3/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.2/sast-coverity-check.yaml, task/sast-coverity-check/0.3/sast-coverity-check.yaml
Syft refuses to extract a large blob from an oci-archive. It fails with:
[0001] ERROR could not determine source:
an error occurred attempting to resolve 'big-image.tar':
oci-archive: failed to visit tar entry="blobs/sha256/..." :
zip read limit hit (potential decompression bomb attack):
copied 2147483648, limit 2147483648
Syft has no such reservations about processing an equally large blob in an oci-dir.
=> buildah etc.: run syft on oci-dir, not oci-archive

appstudio-utils/Dockerfile
Add `HOME` environment variable to appstudio-utils
When using appstudio-utils to run `ec track` command it fails for authorization.
The solution is to add HOME environment variable to the task that uses this image.
We can simply add `HOME` to the dockerfile and avoid updating the tasks that uses it.
Example taken from release service:
https://github.com/konflux-ci/release-service-utils/blob/main/Dockerfile#L97
=> chore: add HOME var to appstudio-utils

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/maven-zip-build-oci-ta/README.md, pipelines/maven-zip-build/README.md, task/sast-coverity-check-oci-ta/0.3/README.md, task/sast-coverity-check-oci-ta/0.3/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.3/patch.yaml, task/sast-coverity-check/0.3/sast-coverity-check.yaml
Users were confused about the IMAGE parameter of the sast-coverity-check task. Explain that the parameter is mostly irrelevant.
=> sast-coverity-check: fix IMAGE param description

pipelines/gitops-pull-request-rhtap/README.md, pipelines/gitops-pull-request-rhtap/gitops-pull-request.yaml, pipelines/rhtap/rhtap.yaml
This PR is related to the resources deployed by the installer. Another PR will be needed to remove other mentions of RHTAP in the repo.
rh-pre-commit.version: 2.3.2
rh-pre-commit.check-secrets: ENABLED
=> feat: rename RHTAP resources to TSSC

task/generate-labels/0.1/README.md, task/generate-labels/0.1/generate-labels.yaml
If we want to achieve parity between tags and labels for a monotonically increasing "release" number, the only recourse we currently have is the git commit timestamp. While this produces a reproducible integer, if the commit is rebuilt, the tag will move to a new digest. In order to improve uniqueness, users may want to base the release off of the actual timestsamp. Exposing the time of this task enables easier parity between tags and labels without having to add the desired tags as a konflux.additional-tags label.
relates to: https://github.com/konflux-ci/docs/pull/330
=> Expose the actual time for the generate-labels task

task/clair-scan/0.1/clair-scan.yaml, task/clair-scan/0.2/clair-scan.yaml, task/clamav-scan/0.1/clamav-scan.yaml, task/clamav-scan/0.2/clamav-scan.yaml, task/deprecated-image-check/0.4/deprecated-image-check.yaml, task/deprecated-image-check/0.5/deprecated-image-check.yaml, task/sbom-json-check/0.1/sbom-json-check.yaml, task/sbom-json-check/0.2/sbom-json-check.yaml
* retry command which meet integmittent issue as below get_image_manifests, clair-action, c image extract
* echo message to TEST_OUTPUT and mark result as ERROR when command fails
igned-off-by: Hongwei Liu <hongliu@redhat.com>
=> feat(STONEINTG-1195): add retry to command meeting intermittent issue

.tekton/push.yaml
In 0e7654818966eb2f929ccdcc0cf9f81a1ae17597, the HOME in the appstudio-utils image changed to /tekton/home. Update the mount path of the redhat-appstudio-tekton-catalog secret accordingly.
=> .tekton/push: fix docker auth mount path

task/push-dockerfile-oci-ta/0.1/push-dockerfile-oci-ta.yaml, task/push-dockerfile/0.1/push-dockerfile.yaml
We conducted a CPU and memory resource usage analysis for the push-dockerfile task to determine appropriate Kubernetes resource requests and limits. The following PromQL queries were executed against 3 weeks of metrics data. 
PEAK MEMORY
95 PERCENTILE MEMORY
PEAK CPU
95 PERCENTILE CPU
The spreadsheet has been updated with the resulting values to guide tuning of resource requests and limits
https://docs.google.com/spreadsheets/d/1d4Tn7PYkY2EVgpNyT29xL7y62akZNPIjy18VTzw54iQ/edit?pli=1&gid=1735880927#gid=1735880927
=> Adding request and limits for CPU and Memory for push-dockerfile task

task/sast-coverity-check-oci-ta/0.3/MIGRATION.md, task/sast-coverity-check-oci-ta/0.3/migrations/0.3.sh, task/sast-coverity-check/0.3/MIGRATION.md
* add 0.3 migration script to sast-coverity-check-oci-ta folder since they need to run in pipeline-migration-tool separately.
Refer to [slack thread](https://redhat-internal.slack.com/archives/C02CTEB3MMF/p1745996501575899) for details
=> fix(STONEINTG-1192): add migration script to sast-coverity-check-oci-ta

task/fbc-target-index-pruning-check/0.1/README.md, task/fbc-target-index-pruning-check/0.1/fbc-target-index-pruning-check.yaml
This PR modifies the fbc-target-index-pruning-check Tekton task to allow pruning in channels that start with dev-preview, pre-ga, or candidate.
=> feat(CLOUDDST-27064): Allow pruning in specific channels

stepactions/fips-operator-check-step-action/0.1/fips-operator-check-step-action.yaml
1. Fix retrieval of the version label to extract only the label that starts with the word version. Currently, it matches multiple labels that contain the word version:
* io.buildah.version
* upstream-version
* version
2. Sanitize the component, version, and release labels by removing newlines and whitespace.
=> fix: remove new lines from local storage dir names

task/sast-coverity-check/0.3/README.md, task/sast-shell-check/0.1/README.md, task/sast-snyk-check/0.4/README.md, task/sast-unicode-check/0.2/README.md
Supports https://issues.redhat.com/browse/PSSECAUT-1147 but I also intend to update other docs.
Note sure if I missed something, but I assumed that if I just updated the sast non-trusted-artifact tasks the `hack/generate-everything.sh` script would update the -oci-ta tasks for me. That didn't seem to occur, so I updated the -oci-ta tasks manually.
I also did some light markdown linting, like wrapping bare URLs in `<>` and whitespace tidy.
=> Add note to sast tasks about KFP directory names

task/apply-tags/0.1/apply-tags.yaml
This PR updates resource limits and requests for the task **apply-tags** as part of this effort - [KONFLUX-7127](https://issues.redhat.com/browse/KONFLUX-7127). 
The new request/limit values have been defined taking into account usages observed historically (tracked in this [spreadsheet](https://docs.google.com/spreadsheets/d/1d4Tn7PYkY2EVgpNyT29xL7y62akZNPIjy18VTzw54iQ/edit?gid=1735880927#gid=1735880927)) in the **stone-prd-rh01** cluster.
=> feat(KONFLUX-7127): Setup limits and resource for apply-tags

task/sast-snyk-check-oci-ta/0.1/sast-snyk-check-oci-ta.yaml, task/sast-snyk-check-oci-ta/0.2/sast-snyk-check-oci-ta.yaml, task/sast-snyk-check-oci-ta/0.3/sast-snyk-check-oci-ta.yaml, task/sast-snyk-check-oci-ta/0.4/sast-snyk-check-oci-ta.yaml, task/sast-snyk-check/0.1/sast-snyk-check.yaml, task/sast-snyk-check/0.2/sast-snyk-check.yaml, task/sast-snyk-check/0.3/sast-snyk-check.yaml, task/sast-snyk-check/0.3/tests/pre-apply-task-hook.sh, task/sast-snyk-check/0.4/sast-snyk-check.yaml, task/sast-snyk-check/0.4/tests/pre-apply-task-hook.sh
This PR updates resource limits and requests for the task **sast-snyk-check** as part of this effort - [KONFLUX-7331](https://issues.redhat.com/browse/KONFLUX-7331). 
The new request/limit values have been defined taking into account usages observed historically (tracked in this [spreadsheet](https://docs.google.com/spreadsheets/d/1d4Tn7PYkY2EVgpNyT29xL7y62akZNPIjy18VTzw54iQ/edit?gid=1735880927#gid=1735880927)) in the **stone-prd-rh01** cluster. 
The memory usage is increased to 6Gi for sast-snyk-check task based on the discussion in this PR: https://www.google.com/url?q=https://github.com/konflux-ci/build-definitions/pull/2051%23discussion_r1992927271&sa=D&source=editors&ust=1744272213794567&usg=AOvVaw0au9JdXyoKZfsQ7o3oXeAq
=> feat(KONFLUX-7331): Setup limits and resource for sast-snyk-check

task/upload-sbom-to-trustification/0.1/upload-sbom-to-trustification.yaml
rh-pre-commit.version: 2.3.2
rh-pre-commit.check-secrets: ENABLED
=> feat: bump API version for TPA 2.x

task/build-image-index/0.1/build-image-index.yaml, task/build-image-manifest/0.1/build-image-manifest.yaml
The Mobster tool is generic SBOM content generate that will be used to generate Konflux SBOMs. This commit is one of the first that switches SBOM generation to use Mobster. Index image SBOMs are now fully handled by the tool.
Mobster source code is available here: https://github.com/konflux-ci/mobster
JIRA: [ISV-5868](https://issues.redhat.com//browse/ISV-5868)
=> feat(ISV-5868): Use Mobster to generate index image sboms

task/ecosystem-cert-preflight-checks/0.2/ecosystem-cert-preflight-checks.yaml
During introspection, check if the provided image is a multi-arch image. If so, explicitly override the arch/os during the subsequent inspect step to the first image/manifest in the list.
skopeo will fail to inspect a multi-arch image if the image does not cover the host system where skopeo is running, unless an explicit arch/os override is specified.
---
Some of this logic could probably be improved/simplified if there is progress on https://github.com/containers/skopeo/issues/1283.
=> fix(EET-4670): override arch/os in ecosystem-cert-preflight-checks

.github/scripts/check_task_and_pipeline_yamls.sh, .github/workflows/check-task-and-pipeline-yamls.yaml, pipelines/gitops-pull-request-rhtap/README.md, pipelines/gitops-pull-request-rhtap/gitops-pull-request.yaml, pipelines/rhtap/rhtap.yaml
At the moment, errors in task and pipeline YAMLs only surface after the full CI run completes. This PR adds a GitHub Actions workflow that pre-validates task and pipeline YAMLs so that we can catch apply failures immediately.
This PR addresses [STONEBLD-3431](https://issues.redhat.com//browse/STONEBLD-3431) by adding a workflow to validate the tasks and pipelines YAMLs and whether they can be applied.
* Added a bash script to generate & apply tasks and pipelines via kubectl
* Added a GH Actions workflow to prepare a cluster via kind, and invoke the script
* Modified the gitops-pull-request.yaml so that it can be applied on its own (by defining the workspaces it uses)
=> feat(STONEBLD-3431): Validate tasks and pipelines YAMLs

task/sast-unicode-check-oci-ta/0.2/sast-unicode-check-oci-ta.yaml, task/sast-unicode-check/0.2/sast-unicode-check.yaml
This PR updates resource limits and requests for the task sast-unicode-check as part of this effort - KONFLUX-7127.
The new request/limit values have been defined taking into account usages observed historically (tracked in this [spreadsheet](https://docs.google.com/spreadsheets/d/1d4Tn7PYkY2EVgpNyT29xL7y62akZNPIjy18VTzw54iQ/edit?gid=1735880927#gid=1735880927)) in the stone-prd-rh01 cluster.
=> feat(CLOUDDST-27468): set limits/resources for task sast-unicode-check

hack/validate-migration.sh
The bug was that the script was checking for migration files for oci-ta variants, even when a particular task does not have an oci-ta variant.
=> Fix a bug in validate-migration script

task/modelcar-oci-ta/0.1/modelcar-oci-ta.yaml
A Mobster tool is now used to generate consistent SBOMs for modelcar. The logic of the old script was ported to the Mobster and Mobster now generates same content but with consistent quality that is shared between all other SBOMs content type.
Reference to Mobster doc:
https://github.com/konflux-ci/mobster/blob/main/docs/sboms/modelcar_sbom.md
JIRA: [ISV-5869](https://issues.redhat.com//browse/ISV-5869)
=> feat(ISV-5859): Use Mobster to generate modelcar SBOMs

task/git-clone-oci-ta/0.1/git-clone-oci-ta.yaml, task/git-clone/0.1/git-clone.yaml, task/pnc-prebuild-git-clone-oci-ta/0.1/pnc-prebuild-git-clone-oci-ta.yaml
When attempting to merge a target branch by using the 'mergeTargetBranch' and 'targetBranch' params, the git-clone tasks would sometimes fail even if no merge conflict happened. This is because when trying to commit without any diff in the staging area, the 'git commit' commands exits with a code 1, which makes the whole task fail.
This patches changes this behavior to only commit if a diff is found.
=> git-clone: Fix error when merging target branch and there is no diff

policies/step-actions.yaml, task/verify-enterprise-contract/0.1/verify-enterprise-contract.yaml
Conforma policies were moved to a new location, so let's update the urls accordlingly.
Ref: https://issues.redhat.com/browse/EC-1113
=> Update Conforma policy git urls

README.md, pipelines/core-services/core-services.yaml, pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-multi-platform-oci-ta/docker-build-multi-platform-oci-ta.yaml, pipelines/docker-build-multi-platform-oci-ta/patch.yaml, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build-oci-ta/docker-build-oci-ta.yaml, pipelines/docker-build-oci-ta/patch.yaml, pipelines/docker-build/README.md, pipelines/docker-build/docker-build.yaml, pipelines/docker-build/patch.yaml
Some of the pipeline descriptions include a link to the trusted tasks Conforma policy. Fix that link.
The link changed because the policy docs were split up into one page per package.
Ref: https://issues.redhat.com/browse/EC-984
=> Fix Conforma policy links in pipeline descriptions

task/build-maven-zip-oci-ta/0.1/build-maven-zip-oci-ta.yaml, task/build-maven-zip/0.1/build-maven-zip.yaml, task/clair-scan/0.2/clair-scan.yaml, task/clamav-scan/0.1/clamav-scan.yaml, task/clamav-scan/0.2/clamav-scan.yaml, task/fbc-target-index-pruning-check/0.1/fbc-target-index-pruning-check.yaml, task/oci-copy-oci-ta/0.1/oci-copy-oci-ta.yaml, task/oci-copy-oci-ta/0.2/oci-copy-oci-ta.yaml, task/oci-copy/0.1/oci-copy.yaml, task/oci-copy/0.2/oci-copy.yaml, task/push-dockerfile-oci-ta/0.1/push-dockerfile-oci-ta.yaml, task/push-dockerfile/0.1/push-dockerfile.yaml, task/sast-coverity-check-oci-ta/0.1/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.1/sast-coverity-check.yaml, task/sast-shell-check-oci-ta/0.1/sast-shell-check-oci-ta.yaml, task/sast-shell-check/0.1/sast-shell-check.yaml, task/sast-snyk-check-oci-ta/0.1/sast-snyk-check-oci-ta.yaml, task/sast-snyk-check-oci-ta/0.2/sast-snyk-check-oci-ta.yaml, task/sast-snyk-check-oci-ta/0.3/sast-snyk-check-oci-ta.yaml, task/sast-snyk-check-oci-ta/0.4/sast-snyk-check-oci-ta.yaml, task/sast-snyk-check/0.1/sast-snyk-check.yaml, task/sast-snyk-check/0.2/sast-snyk-check.yaml, task/sast-snyk-check/0.3/sast-snyk-check.yaml, task/sast-snyk-check/0.4/sast-snyk-check.yaml, task/sast-unicode-check-oci-ta/0.1/sast-unicode-check-oci-ta.yaml, task/sast-unicode-check-oci-ta/0.2/sast-unicode-check-oci-ta.yaml, task/sast-unicode-check/0.1/sast-unicode-check.yaml, task/sast-unicode-check/0.2/sast-unicode-check.yaml, task/validate-fbc/0.1/validate-fbc.yaml
contains common retry script /usr/bin/retry
[STONEBLD-3488](https://issues.redhat.com//browse/STONEBLD-3488)
=> update quay.io/konflux-ci/oras image to version which

task/git-clone-oci-ta/0.1/git-clone-oci-ta.yaml, task/git-clone/0.1/git-clone.yaml, task/pnc-prebuild-git-clone-oci-ta/0.1/pnc-prebuild-git-clone-oci-ta.yaml
When the user sets the mergeTargetBranch param to true, this task will fetch the branch and perform a git merge that ultimately skips the commit part. It also leaves any change that will be commited in Git's staging area.
A previous commit (3f84d17) included a check that would only apply a git merge command if any diff was found in the staging area. Unfortunately, the command used to check if there's any staged changes returns an exit code 1, which makes the whole task fail. This patch changes the way the check is made to avoid the issue.
=> git-clone: Fix merge target branch workflow

task/deprecated-image-check/0.1/deprecated-image-check.yaml, task/deprecated-image-check/0.2/deprecated-image-check.yaml, task/deprecated-image-check/0.3/deprecated-image-check.yaml, task/deprecated-image-check/0.4/deprecated-image-check.yaml, task/deprecated-image-check/0.5/deprecated-image-check.yaml
This is to fix the issue with deprecated-image-check failing for the below error:
`"Unauthorized: access to the requested resource is not authorized" in latest deprecated-base-image-check`
=> fix: update deprecated image to use new konflux-test version

task/acs-deploy-check/0.1/acs-deploy-check.yaml, task/acs-image-check/0.1/acs-image-check.yaml, task/acs-image-scan/0.1/acs-image-scan.yaml, task/build-helm-chart-oci-ta/0.1/build-helm-chart-oci-ta.yaml, task/build-helm-chart/0.1/build-helm-chart.yaml, task/download-sbom-from-url-in-attestation/0.1/download-sbom-from-url-in-attestation.yaml, task/eaas-provision-space/0.1/eaas-provision-space.yaml, task/ecosystem-cert-preflight-checks/0.1/ecosystem-cert-preflight-checks.yaml, task/ecosystem-cert-preflight-checks/0.2/ecosystem-cert-preflight-checks.yaml, task/gather-deploy-images/0.1/gather-deploy-images.yaml, task/operator-sdk-generate-bundle/0.1/operator-sdk-generate-bundle.yaml, task/opm-get-bundle-version/0.1/opm-get-bundle-version.yaml, task/opm-render-bundles/0.1/opm-render-bundles.yaml, task/sbom-json-check/0.1/sbom-json-check.yaml, task/sbom-json-check/0.2/sbom-json-check.yaml, task/update-deployment/0.1/update-deployment.yaml, task/upload-sbom-to-trustification/0.1/upload-sbom-to-trustification.yaml, task/verify-signed-rpms/0.1/verify-signed-rpms.yaml
With the help of `hack/check-task-version-labels.sh` from #2127 I added an `app.kubernetes.io/version` label to all the tasks that don't have it.
(This one should be low risk, and hence easy to merge.)
=> Add missing task version labels

.github/workflows/check-task-owners.yaml, hack/check-task-version-labels.sh
PRs #2129 and #2128 added some missing or mismatched task version labels. This change adds some CI that should prevent future missing or mismatched task version labels.
I added it as a step in an existing workflow rather than creating a whole new workflow. Let me know if you have a preference for putting it somewhere else.
=> Add CI check for task version labels

task/sast-shell-check/0.1/README.md
Oops. Should already be correct everywhere else.
=> sast-shell-check: fix param name typo in README

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/fbc-builder/README.md, pipelines/maven-zip-build-oci-ta/README.md, pipelines/maven-zip-build/README.md, task/buildah-min/0.4/buildah-min.yaml, task/buildah-oci-ta/0.4/README.md, task/buildah-oci-ta/0.4/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.4/README.md, task/buildah-remote-oci-ta/0.4/buildah-remote-oci-ta.yaml, task/buildah-remote/0.4/README.md, task/buildah-remote/0.4/buildah-remote.yaml, task/buildah/0.4/README.md, task/buildah/0.4/buildah.yaml, task/sast-coverity-check-oci-ta/0.2/README.md, task/sast-coverity-check-oci-ta/0.2/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check-oci-ta/0.3/README.md, task/sast-coverity-check-oci-ta/0.3/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.2/sast-coverity-check.yaml, task/sast-coverity-check/0.3/sast-coverity-check.yaml
This can be used by users to disable the inheritace of labels from the base/parent image.
The default behaviour is that the labels are inherited.
Resolves [STONEBLD-3455](https://issues.redhat.com//browse/STONEBLD-3455)
=> Add INHERIT_BASE_IMAGE_LABELS parameter to buildah task

task/sast-unicode-check-oci-ta/0.2/sast-unicode-check-oci-ta.yaml, task/sast-unicode-check-oci-ta/0.3/MIGRATION.md, task/sast-unicode-check-oci-ta/0.3/README.md, task/sast-unicode-check-oci-ta/0.3/migrations/0.3.sh, task/sast-unicode-check-oci-ta/0.3/recipe.yaml, task/sast-unicode-check-oci-ta/0.3/sast-unicode-check-oci-ta.yaml, task/sast-unicode-check/0.2/sast-unicode-check.yaml, task/sast-unicode-check/0.3/MIGRATION.md, task/sast-unicode-check/0.3/README.md, task/sast-unicode-check/0.3/migrations/0.3.sh, task/sast-unicode-check/0.3/sast-unicode-check.yaml, task/sast-unicode-check/0.3/tests/test-sast-unicode-check.yaml
[PSSECAUT-1203](https://issues.redhat.com/browse/PSSECAUT-1203)
It seems as though in https://github.com/konflux-ci/build-definitions/pull/2018 the `image-digest` param was not made required for sast-unicode-check and had a default value of `""`. This caused upload to fail for pipelines that did not have image-digest set for this task.
There is also a small bugfix due to incorrect var name `UPLOAD_FILE` vs `UPLOAD_FILES`.
To fix I've creaated a new version, 0.3, and migration scripts. Also related to https://issues.redhat.com/browse/STONEINTG-1208
=> sast-unicode: add 0.3 with required image-digest

CODEOWNERS, renovate.json, task/slack-webhook-notification-oci-ta/0.1/README.md, task/slack-webhook-notification-oci-ta/0.1/recipe.yaml, task/slack-webhook-notification-oci-ta/0.1/slack-webhook-notification-oci-ta.yaml
Adding the equivalent of https://github.com/konflux-ci/build-definitions/tree/main/task/slack-webhook-notification/0.1 for trusted artifact pipelines
This allows users to send a slack notification when a merge build pipeline fails, or when a new artifact is available for example.
T̶h̶i̶s̶ ̶t̶a̶s̶k̶ ̶w̶a̶s̶ ̶c̶r̶e̶a̶t̶e̶d̶ ̶m̶a̶n̶u̶a̶l̶l̶y̶ ̶b̶y̶ ̶a̶d̶a̶p̶t̶i̶n̶g̶ ̶t̶h̶e̶ ̶n̶o̶n̶-̶o̶c̶i̶-̶t̶a̶ ̶e̶q̶u̶i̶v̶a̶l̶e̶n̶t̶.̶
This task was genered with a recipe from the non-oci-ta equivalent.
I had no idea who should be the CODEOWNER so I mimic-ed slack-webhook-notification
=> feat: Add slack-webhook-notification-oci-ta task

stepactions/fips-operator-check-step-action/0.1/fips-operator-check-step-action.yaml
Updated fips stepaction to latest konflux-test image containing check-payload 0.3.8.
=> Update fips stepaction to use check-payload 0.3.8

hack/build-manifests.sh
This reverts commit dfc3b54a3321937468c5f0b36f50ccc61d36b61f.
This actually caused more bad than good, so let's drop it. Specifically with tasks, once a task makes it to archived-tasks then such task should no longer be considered to be used for anything and especially not by any generators/validators.
**Depends on: https://github.com/konflux-ci/build-definitions/pull/2497**
=> Revert "hack: build-manifest: Tell find to follow symbolic links"

README.md, external-task/rpms-signature-scan/0.2/rpms-signature-scan.yaml, hack/build-and-push.sh, renovate.json
This is a POC for running build-definitions' CI with tasks that are built externally (in other repositories).
Using an external-task folder with the format of `task` folder (task-name -> task-version -> definition file).
`The build-and-push.sh` script will first inject the tasks in the `external-task` folder by getting their structure and fetching the task_bundle from its definition file.
After injecting all the external tasks, the script will proceed to the task folder and inject only the tasks that has no definition in the external tasks folder, so that the priority will be for external tasks in case of duplication.
The external task definition will contain a single yaml file (it can be other format) which will hold the url of the task_bundle (this task was built externally to build- …
=> chore(KFLUXVNGD-315): external-tasks support

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/maven-zip-build-oci-ta/README.md, pipelines/maven-zip-build/README.md, task/sast-coverity-check-oci-ta/0.3/README.md, task/sast-coverity-check-oci-ta/0.3/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.3/README.md, task/sast-coverity-check/0.3/patch.yaml, task/sast-coverity-check/0.3/sast-coverity-check.yaml
[PSSECAUT-1198](https://issues.redhat.com/browse/PSSECAUT-1198)
Tested https://konflux-ui.apps.stone-prod-p02.hjvn.p1.openshiftapps.com/ns/sfowler-tenant/applications/snr-0-9/pipelineruns/snr-bundle-0-9-on-pull-request-cs2bc
~This test seemed to reveal another issue, but I don't think it's related to this change:~
```
+ /opt/coverity/bin/cov-analyze '--enable HARDCODED_CREDENTIALS --security --concurrency --spotbugs-max-mem=4096' --dir=/tmp/idir
[COMMAND LINE ERROR] Undefined option 'enable HARDCODED_CREDENTIALS --security --concurrency --spotbugs-max-mem'
Did you mean to pass '--enable', 'HARDCODED_CREDENTIALS', '--security', '--concurrency' and '--spotbugs-max-mem=4096' as separate arguments?
Check your shell quoting rules, and note that response files allow only one argument per line. …
```
=> sast-coverity: add TARGET_DIRS parameter

stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/README.md, stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/eaas-create-ephemeral-cluster-hypershift-aws.yaml
- Introduce 'fips' parameter to enable or disable FIPS mode during cluster provisioning
- Pass 'fips' as an environment variable and include it in ClusterTemplateInstance parameters in the provisioning script
- Update README to document the new parameter and correct its default value
This allows users to provision clusters with FIPS mode enabled as needed.
Relevant pr in the helm chart to support this: https://github.com/konflux-ci/cluster-template-charts/pull/25
=> feat: add FIPS mode support to AWS cluster

renovate.json
The only Go code in this repo is for CI - the buildah-remote generator and the trusted task generator. Automerging Go modules if CI passes should be safe.
Also run Go module updates only on sundays, same as GH action updates.
=> renovate: group and automerge Go module updates

hack/build-manifests.sh
`$ find task/*/*/*.yaml -maxdept 0`
is only stable until symlinks are added to the equation. Everything is fine as long as one wants the symlinks to be included, however, since we gave find a fully resolved list of files based on the glob (which isn't capable of skipping symlinks) and limited its max descend level to 0 (which is questionable since we gave it a list of resolved paths to individual YAML files) it won't apply any further filtering options specified on the command line.
In our case, we don't intend to provide updates to tasks that have been moved to the 'archived-tasks' directory which happen to be symlinked to the 'task' directory.
Therefore, manifests would continue to be built AND verified for archived tasks as well. To prevent that, let's use filtering native to find to …
=> hack: build-manifests: Replace pattern glob for native options in find

task/sast-shell-check-oci-ta/0.1/sast-shell-check-oci-ta.yaml, task/sast-shell-check/0.1/README.md, task/sast-shell-check/0.1/sast-shell-check.yaml
- [PSSECAUT-1196](https://issues.redhat.com//browse/PSSECAUT-1196)
- set sast-shell-check default CPU limit to 8
- set SC_JOBS equal to CPU limit (rounded up) based on cgroups v2 max
- fix issue with IFS=, affecting word splitting (which impacted `read -r quota period < /sys/fs/cgroup/cpu.max`)
~Marked as draft for now~, as it requires an updated version of the quay.io/konflux-ci/konflux-test image with a new epel9 release of csmock-plugins-shellcheck-core with this [change](https://github.com/csutils/csmock/pull/205).
EDIT: konflux-test image has been updated, ready for merge
=> sast-shell-check: set ShellCheck jobs based on cgroup v2 CPU limits

archived-tasks/sast-coverity-check/0.2/sast-coverity-check.yaml, task/buildah-min/0.4/buildah-min.yaml, task/buildah-oci-ta/0.4/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.4/buildah-remote-oci-ta.yaml, task/buildah-remote/0.4/buildah-remote.yaml, task/buildah/0.4/buildah.yaml, task/sast-coverity-check-oci-ta/0.3/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.3/sast-coverity-check.yaml
[STONEBLD-3488](https://issues.redhat.com//browse/STONEBLD-3488)
=> retry subscription-manager register in case of failure

task/buildah-min/0.4/buildah-min.yaml, task/buildah-oci-ta/0.4/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.4/buildah-remote-oci-ta.yaml, task/buildah-remote/0.4/buildah-remote.yaml, task/buildah/0.4/buildah.yaml, task/deprecated-image-check/0.5/deprecated-image-check.yaml, task/sast-coverity-check-oci-ta/0.3/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.3/sast-coverity-check.yaml, task/source-build-oci-ta/0.3/source-build-oci-ta.yaml, task/source-build/0.3/source-build.yaml
A Mobster is a unified tool for generating SBOMs in Konflux. The oci image is another content type that is being ported to use Mobster.
A Mobster handles a logic of previously defined scripts and unifies the output across all SBOMs produced by the SBOM.
The oci-image generator executes following steps internally:
- merge syft and hermeto outputs
- add reference to the image and updates relationship
- add base images used to build an image
- add additional base images
- validate a format of the spdx or cyclonedx schema
JIRA: [ISV-5866](https://issues.redhat.com//browse/ISV-5866)
=> feat(ISV-5866): Use Mobster to generate oci image SBOMs

task/build-helm-chart-oci-ta/0.1/build-helm-chart-oci-ta.yaml, task/build-helm-chart-oci-ta/0.2/MIGRATION.md, task/build-helm-chart-oci-ta/0.2/README.md, task/build-helm-chart-oci-ta/0.2/build-helm-chart-oci-ta.yaml, task/build-helm-chart/0.1/README.md, task/build-helm-chart/0.1/build-helm-chart.yaml
The build-helm-chart task relied on the images in the chart to be updated prior for the chart running, requiring that the update of the image that the charts deploys and the chart itself are not changed at part of the same commit.
This change introduces version 0.2 in which the image and chart are expected to be built at the same time, for which the task for building the chart needs to substitute the images within the chart with values per what is being built at the same time.
Assisted by Cursor
=> feat: add image substitution to build-helm-chart

.github/workflows/check-task-and-pipeline-yamls.yaml, .github/workflows/check-task-migration.yaml
GitHub Actions using the setup-tektoncd step have recently started intermittently failing with a somewhat cryptic error message `jq: error (at <stdin>:1): Cannot iterate over null (null)`
Upstream issue for setup-tektoncd has been filed at https://github.com/tektoncd/actions/issues/9
Until the issue is fixed in upstream, inform users that the issue is known, link it and tell them that they should re-run the workflow.
=> Describe why setup-tektoncd fails in GH Actions

task/fbc-fips-check-oci-ta/0.1/fbc-fips-check-oci-ta.yaml, task/fbc-fips-check/0.1/fbc-fips-check.yaml
Fixed to print user-friendly message when no mirror entries found in image mirror map. Also modified to print the entries in images-mirror-set only once at the top.
=> fix(KONFLUX-8786): make jq error user friendly

CODEOWNERS, pipelines/fbc-builder/README.md, pipelines/fbc-builder/fbc-builder.yaml, pipelines/fbc-builder/patch.yaml, renovate.json, task/run-opm-command-oci-ta/0.1/README.md, task/run-opm-command-oci-ta/0.1/run-opm-command-oci-ta.yaml
Adding non mandatory task for running `opm` command which can be used to render catalog from catalog template. Pullspecs of related images can be replaced when ImageDigestMirrorSet file is provided. 
[KONFLUX-5311]
[CLOUDDST-26462]
=> New task: run-opm-command-oci-ta

task/sast-unicode-check-oci-ta/0.3/MIGRATION.md, task/sast-unicode-check/0.3/MIGRATION.md
MIGRATION.md didn't mention the change to `image-url` parameter.
=> Update sast-unicode-check 0.3 MIGRATION.md

pipelines/core-services/core-services.yaml, pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-multi-platform-oci-ta/docker-build-multi-platform-oci-ta.yaml, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build-oci-ta/docker-build-oci-ta.yaml, pipelines/docker-build/README.md, pipelines/docker-build/docker-build.yaml, pipelines/maven-zip-build-oci-ta/README.md, pipelines/maven-zip-build-oci-ta/maven-zip-build-oci-ta.yaml, pipelines/maven-zip-build/README.md, pipelines/maven-zip-build/maven-zip-build.yaml, pipelines/tekton-bundle-builder-oci-ta/README.md, pipelines/tekton-bundle-builder-oci-ta/tekton-bundle-builder-oci-ta.yaml, pipelines/tekton-bundle-builder/README.md, pipelines/tekton-bundle-builder/tekton-bundle-builder.yaml, pipelines/template-build/template-build.yaml, renovate.json
Upgrade `sast-unicode-check` version from 0.2 to 0.3 in template-build.yaml.
All other changes are generated by `hack/generate-everything.sh`.
=> Upgrade sast-unicode-check version in template build

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/fbc-builder/README.md, pipelines/maven-zip-build-oci-ta/README.md, pipelines/maven-zip-build/README.md, task/buildah-min/0.4/buildah-min.yaml, task/buildah-oci-ta/0.4/README.md, task/buildah-oci-ta/0.4/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.4/buildah-remote-oci-ta.yaml, task/buildah-remote/0.4/buildah-remote.yaml, task/buildah/0.4/buildah.yaml, task/sast-coverity-check-oci-ta/0.3/README.md, task/sast-coverity-check-oci-ta/0.3/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.3/sast-coverity-check.yaml
If specified, the proxy is only configured for buildah pull or build operations to prevent unintentional use by other processes.
Assisted-by: cursor (claude-3.5-sonnet)
=> Add proxy support to buildah tasks

pipelines/fbc-builder/README.md, task/run-opm-command-oci-ta/0.1/README.md, task/run-opm-command-oci-ta/0.1/run-opm-command-oci-ta.yaml
Fixing bug in run-opm-command-oci-ta. We need to replace pull spec in catalog-template before we run `opm alpha render-template`.
[CLOUDDST-28855]
[KONFLUX-5311]
Assisted-by: Gemini
=> fix(KONFLUX-5311): Run replace pullspec before opm 

task/sast-coverity-check/0.3/kustomization.yaml
This is to reduce churn so that changes to buildah task don't require updating the coverity task at the same time. This should prioritize stability for the coverity task, and prevent cases when buildah task updates introduces changes that rely on recent buildah image versions, that may not yet also be in the coverity image.
=> sast-coverity: pin base buildah task dep to specific commit

.tekton/push.yaml
* The latest tag of data-acceptable-bundles is manually set to a known working SHA
* We want to prevent the push pipeline from overwriting the latest tag upon merge
* Until we fix the root cause, tracked by [KFLUXSPRT-4746](https://issues.redhat.com//browse/KFLUXSPRT-4746).
resolves: [KFLUXSPRT-4746](https://issues.redhat.com//browse/KFLUXSPRT-4746)
=> Temporarily prevent data-acceptable-bundles overwrite on push event

.tekton/push.yaml
* I'm now re-enabling the push pipeline to update
data-acceptable-bundles repo on every merge.
* I've tested that it correctly picks up the
content from the latest tag of repo and pushes
a new tag to it, with correct data format and content
* But I tested this behaviour when no task was
changed, so I'll keep an eye on any future PR that
changes a task and see if the freshly built image
of that task gets picked up by this script
and pushed to trusted tasks repo.
tracked-by: [EC-1441](https://issues.redhat.com//browse/EC-1441)
=> Re-enable building new bundle to "latest" tag

task/sast-snyk-check-oci-ta/0.4/sast-snyk-check-oci-ta.yaml, task/sast-snyk-check/0.4/sast-snyk-check.yaml
The main change here is changing the csfilter-kfp --kfp-git-url param to --kfp-dir and doing a git clone of KFP earlier in the task. If the git clone succeeds a new var KFP_CLONED=1 will be set, and if this is unset, csfilter-kfp will not run, and the scan results will be unfiltered.
In case there is some issue with this logic, the KFP_DIR will still exist (although empty) and csfilter-kfp should run without errors.
Also improves some of the log messages with log level prefixes.
[PSSECAUT-1297](https://issues.redhat.com//browse/PSSECAUT-1297)
=> sast-snyk: don't fail task when KFP unreachable

.github/scripts/test_tekton_tasks.sh
I found when running tests locally in a loop that I would have to delete my namespace everytime. This allows me to keep the namespace in place which speeds things up more than you might expect - no waiting for finalizers.
I also moved the namespace creation before the apply hooks call so that I can introduce hooks that create things in the namespace (secrets, configmaps, etc..).
=> Make it easier to re-run tests locally without creating the namespace

pipelines/core-services/README.md, pipelines/core-services/core-services.yaml, pipelines/core-services/kustomization.yaml, pipelines/core-services/patch.yaml
We have made a concerted effort to ensure that Konflux controllers can run on both amd64 and arm64 hosts. While this is beneficial, none of the pipelines that we produce can currently run on both hosts since the step images are not all being built for both platforms. In order to assist with making all tasks support both architectures, we will make the pipeline which is focused on building Konflux components default to building both architectures.
Use of this pipeline now requires the multi-platform controller to be deployed on the cluster.
=> feat: change the core services pipeline to multi-arch

CODEOWNERS, hack/check-task-owners.sh, renovate.json
Add missing CODEOWNERS for external-task/rpms-signature-scan
Check external-task/* owners in CI
=> Fix external-task CODEOWNERS

task/sast-snyk-check-oci-ta/0.4/recipe.yaml, task/sast-snyk-check-oci-ta/0.4/sast-snyk-check-oci-ta.yaml
Add volume mount to sast-snyk-check.
I am running Konflux locally on a kind cluster on my laptop. When running my pipeline, the ecosystem-cert-preflight-checks task fails with TLS errors. This is rectified by adding `useTAVolumeMount: true` to the recipe.yaml files which will add the volume mounts for the certificates in the task when it is generated.
=> Add volume mount to sast-snyk-check-oci-ta.

task/tkn-bundle-oci-ta/0.2/MIGRATION.md, task/tkn-bundle-oci-ta/0.2/migrations/0.2.1.sh, task/tkn-bundle-oci-ta/0.2/tkn-bundle-oci-ta.yaml, task/tkn-bundle/0.2/MIGRATION.md, task/tkn-bundle/0.2/migrations/0.2.1.sh, task/tkn-bundle/0.2/tkn-bundle.yaml
This PR replace https://github.com/konflux-ci/build-definitions/pull/2564 and it will also get the task bundle in addition to the code change in https://github.com/konflux-ci/build-definitions/pull/2564
* copy the code from build-and-push.sh including functions mainly find_previous_migration_bundle_digest, attach_migration_file, get_concrete_task_version
* annotate dev.konflux-ci.task.has-migration to task bundle when has_migration script bundle has migration script
* annotate dev.konflux-ci.task.previous-migration-bundle to task bundle if migration script file is found in previous digest
* split long function attach_migration_file since generate-ta-task.sh can't handle it well
* remove the limit when get task bundle image tag list
* get task bundle by checking content_type and layers[0] …
=> feat(STONEINTG-1232): attach migration script to task bundle image

task/apply-tags/0.2/apply-tags.yaml
Use `appstudio-utils` image which contains both `skopeo` and `jq`
Fixes: https://github.com/konflux-ci/build-definitions/issues/2719
=> fix: change image used in  apply-tags task

.tekton/pull-request.yaml, .tekton/push.yaml, .tekton/tasks/task-switchboard.yaml, appstudio-utils/Dockerfile
konflux-ci/konflux-ci can install on arm, but we cannot run our pipelines on arm unless all step images are built for both x86 and arm.
This change starts to build the appstudio-utils image for both architectures.
=> feat: build appstudio-utils for arm

task/run-opm-command-oci-ta/0.1/run-opm-command-oci-ta.yaml
I made a mistake - replacing pullspec was done before catalog.json is generated. Therefore the users could not replace it in generated catalog.json. This PR will swap it and replacing will be done correctly. 
[KFLUXSPRT-5013]
=> Replacing pull spec after generating catalog.json

.tekton/push.yaml
This is the same fix as 7cdbc4a78e62f294fc758c5e0541ab0d685894e4, but for push pipelines.
=> CI: work around git repo ownership problem

archived-tasks/buildah-remote-oci-ta/0.4/buildah-remote-oci-ta.yaml, archived-tasks/buildah-remote/0.4/buildah-remote.yaml, task-generator/remote/main.go, task/buildah-remote-oci-ta/0.5/buildah-remote-oci-ta.yaml, task/buildah-remote/0.5/buildah-remote.yaml
In this PR:
Adding `-W` key to all transfers, as we're always sending forward to a clean machine, and no files are modified when sending back, only new ones added. There is no need to calculate the deltas.
Adding `-z`. Even though it doesn't add much profit, it still cuts 2-3-5%, which is notable on slow IBM conn-s.
Adding `--stats` output, to analyze the network perf. and collect some more stats
=> Add  rsync command arguments to improve transfer speed back and forth on remote build machines

task/init/0.2/init.yaml, task/init/0.2/migrations/0.2.2.sh
Older FBC pipelines without run-opm-command has been accidentally migrated to docker format. Fix this by changing default to oci.
=> fix(init): hotfix for migration 0.2.1

task/run-script-oci-ta/0.1/run-script-oci-ta.yaml
The flag is for 'buildah from', not for 'buildah run'
Tested in:
- https://github.com/acmiel-rhtap/merge-queue-test/pull/27 (task from main, fails as expected)
- https://github.com/acmiel-rhtap/merge-queue-test/pull/28 (task from PR, works as expected)
=> run-script: fix --security-opt flag usage

stepactions/fips-operator-check-step-action/0.1/fips-operator-check-step-action.yaml
Image references with tag and digest are not supported when converting the image to OCI format using skopeo. To circumvent that, we need to sanitize it.
=> fix: sanitize relatedImages before conversion to OCI format

task/git-clone-oci-ta/0.1/git-clone-oci-ta.yaml, task/git-clone/0.1/git-clone.yaml, task/pnc-prebuild-git-clone-oci-ta/0.1/pnc-prebuild-git-clone-oci-ta.yaml
Bumping to image version which contains the fix for retries.
Fix: https://github.com/tektoncd-catalog/git-clone/commit/828ece013ff71e0a7156fd0379ed661f650300ce
=> fix(git-clone): bump git image version to support retries

task/ecosystem-cert-preflight-checks/0.2/ecosystem-cert-preflight-checks.yaml
To address the below error, which happens when using an `application/vnd.oci.image.index.v1+json` (or manifest list) is used and the Host OS architecture is not one of the architectures in the list. If this isn't clear, this would happen when the konflux pipeline is configured for `"platform": "linux/s390x"` and the pipeline is running on `linux/amd64`, and an `image.index`, is used over `image manifest`.
Error:
```
STEP-APP-SET-OUTCOME
{"result":"FAILURE","timestamp":"1757076008","note":"Task preflight is a FAILURE: Refer to Tekton task logs for more information","successes":7,"failures":1,"warnings":0}time="2025-09-05T12:40:08Z" level=fatal msg="Error parsing manifest for image: choosing image instance: no image found in image index for architecture \"amd64\", variant \"\", OS …
```
=> switch to oras manifest fetch for image digest lookup in set-outcome
