konflux-ci/build-definitions

pipelines/build-templates-bundle/devfile-build.yaml, pipelines/build-templates-bundle/docker-build.yaml, pipelines/build-templates-bundle/java-builder.yaml, pipelines/build-templates-bundle/nodejs-builder.yaml, pipelines/build-templates-bundle/noop.yaml, pipelines/release-build.sh
Ensure all build pipelines have standard params.
=> add standard parameters to all pipelines

pipelines/build-templates-bundle/tekton-bundle-build.yaml, tasks/appstudio-utils/release-build.sh, tasks/appstudio-utils/util-tasks/appstudio-tekton-bundle.yaml, tasks/appstudio-utils/util-tasks/kustomization.yaml
* Create ClusterTask and Pipeline for building tekton bundle
* Add tasks/appstudio-utils/util-tasks/kustomization.yaml to allow load
tasks by external repositories.
Part of #10
=> Add tekton-bundle-build pipeline

pipelines/build-templates-bundle/prototype-build-compliance.yaml, pipelines/release-build.sh
Tested in
CodeReady Containers version: 1.35.0+751824a9
OpenShift version: 4.9.5 (bundle installed at /Applications/CodeReady Containers.app/Contents/Resources/crc_hyperkit_4.9.5.crcbundle)
=> initial prototype of a compliance pipeline

pipelines/build-templates-bundle/tekton-bundle-build.yaml
=> fix yaml format

pipelines/docker-build.yaml
=> consume the Dockerfile path

tasks/sanity-label-check.yaml
Initial script for HACBS test team basic sanity tests check.
=> Adding HACBS basic sanity tests standalone task

.tekton/push.yaml
Currently PaC does not allow to have multiple pipelineRuns.
=> PaC: use one push PipelineRun

appstudio-utils/util-scripts/check-ec-policy.sh, appstudio-utils/util-scripts/ec-pass-fail.sh, appstudio-utils/util-scripts/fetch-ec-data.sh, appstudio-utils/util-scripts/fetch-ec-policies.sh, appstudio-utils/util-scripts/lib/fetch.sh, appstudio-utils/util-scripts/lib/fetch/cluster.sh, appstudio-utils/util-scripts/lib/fetch/data.sh, appstudio-utils/util-scripts/lib/fetch/git.sh, appstudio-utils/util-scripts/lib/fetch/rekor.sh, appstudio-utils/util-scripts/lib/fetch/tekton.sh, appstudio-utils/util-scripts/lib/title.sh, appstudio-utils/util-scripts/lib/workdir.sh, appstudio-utils/util-scripts/show-ec-data.sh, hack/start-ec-task.sh, tasks/enterprise-contract.yaml, test/fetch-ec-data_spec.sh
Add the Enterprise Contract task definition and some related bash scripts.
(See commit messages for further details.)
JIRA: [HACBS-235](https://issues.redhat.com/browse/HACBS-235)
=> Enterprise Contract task definition

.tekton/pull-request.yaml, .yamllint, pipelines/base/docker-build.yaml, pipelines/base/java-builder.yaml, pipelines/base/nodejs-builder.yaml, pipelines/base/noop.yaml, pipelines/base/prototype-build-compliance.yaml
Add yamllint checking for the tasks and pipelines yaml files in the repo
Signed-off-by: jinqi <jinqi@dell-per740xd-16.lab.eng.pek2.redhat.com>
=> Add yamllint checking before pull request is merged

pipelines/hacbs/hacbs-test.yaml, tasks/sanity-label-check.yaml
- Update sanity-label-check parameter in pipelines/hacbs/hacbs-test.yaml
- Remove usage of workspace in sanity-label-check
=> sanity-label-check without workspace

pipelines/hacbs/hacbs-test.yaml, tasks/kustomization.yaml, tasks/sanity-inspect-image.yaml
@dirgim @Dannyb48 @jsztuka @staticf0x How about your ideas? Thank you!
=> Add tasks for image inspection

appstudio-utils/util-scripts/verify-attestation-with-policy.sh
=> Fix doc typo in verify-attestation-with-policy

.tekton/push.yaml, tasks/update-infra-deployments.yaml
Task for update infra-deployments
=> Create re-usable update-infra-deployments task

.tekton/push.yaml, tasks/update-infra-deployments.yaml
Instead of using personal token use the GitHub App
=> Update infra-deployments and create MR using GitHub App

appstudio-utils/util-scripts/verify-attestation-with-policy.sh, hack/start-verify-ec-task.sh, tasks/verify-enterprise-contract.yaml
=> Introduce strict mode for ec policy

pipelines/hacbs/hacbs-test.yaml, tasks/hacbs-test-evaluation.yaml, tasks/kustomization.yaml, tasks/sanity-inspect-image.yaml, tasks/sanity-label-check.yaml
Use workspace in tests, work inside  `$(workspaces.workspace.path)/hacbs/$(context.task.name)`
Add finally task which evaluates tests.
=> Use main workspace for tests, add evaluation finally task

pipelines/hacbs/hacbs-test.yaml, tasks/conftest-clair.yaml, tasks/get-clair-results.yaml, tasks/kustomization.yaml
I will provide logs for multiple outcomes, could be good point for discussion at least.
**Image not found**
```
[curl-magic : get-vulnerabilities]                                  Dload  Upload   Total   Spent    Left  Speed
100   168  100   168    0     0    361      0 --:--:-- --:--:-- --:--:--   361
[curl-magic : get-vulnerabilities]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[curl-magic : get-vulnerabilities]                                  Dload  Upload   Total   Spent    Left  Speed
100   168  100   168    0     0    366      0 --:--:-- --:--:-- --:--:--   366
[curl-magic : get-vulnerabilities] Error, response code is not 200. Response code: 404
[curl-magic : get-vulnerabilities] Body of response: {"detail": "Not Found", "error_message": "Not …
```
=> [HACBS-74]-clair result data parsing and preserving

appstudio-utils/util-scripts/fetch-test-data.sh, appstudio-utils/util-scripts/lib/fetch/tekton.sh, tasks/verify-enterprise-contract.yaml
Search through all TaskRuns in a Pipeline run for test output
For reference the policy PR https://github.com/hacbs-contract/ec-policies/pull/15
=> fetch test results

tasks/cosign-verify-attestation.yaml, tasks/cosign-verify.yaml, tasks/verify-enterprise-contract.yaml
We should be using `SSL_CERT_DIR` here.
=> Fix typo SSL_CERTS_DIR -> SSL_CERT_DIR

hack/start-ec-task.sh, hack/start-verify-ec-task.sh
=> Use deterministic TaskRun name when hacking

.yamllint, pipelines/base/noop.yaml, tasks/cleanup-build-directories.yaml, tasks/configure-build.yaml, tasks/get-clair-scan.yaml, tasks/git-clone.yaml, tasks/hacbs-test-evaluation.yaml, tasks/init.yaml, tasks/summary.yaml, tasks/update-infra-deployments.yaml, tasks/utils-task.yaml
Remove trailing spaces and add check into yamllint
=> Yamllint - remove trailing spaces

appstudio-utils/util-scripts/check-ec-policy.sh
Follow up needed for the change in:
https://github.com/hacbs-contract/ec-policies/pull/22
=> Update package name to drop `hacbs.contract`

tasks/kustomization.yaml
=> Add verify-enterprise-contract task to bundle

tasks/sanity-label-check.yaml
* Add base image json as data to the conftest command
=> [HACBS-202] Add the base image to the sanity-label-check

pipelines/hacbs-core-service/infra-deploy.yaml, tasks/sanity-label-check.yaml, tasks/update-infra-deployments.yaml
When PR is merged then update description of PR in infra-deployments
pointing to merged PR.
=> infra-deployment-update: set description in new PR

hack/test-build.sh
=> Fix test-build.sh chains artifacts

tasks/deprecated-image-check.yaml, tasks/hacbs-test-evaluation.yaml, tasks/sanity-label-check.yaml
* Check https://tekton.dev/docs/pipelines/migrating-v1alpha1-to-v1beta1/#changes-to-fields
=> Change the inputs.params references to params

hack/start-verify-ec-task.sh, tasks/verify-enterprise-contract.yaml
=> Remove deprecated policy repo refs

appstudio-utils/Dockerfile, appstudio-utils/util-scripts/check-ec-policy.sh, appstudio-utils/util-scripts/ec-pass-fail.sh, appstudio-utils/util-scripts/fetch-test-data.sh, appstudio-utils/util-scripts/lib/fetch.sh, appstudio-utils/util-scripts/lib/fetch/cluster.sh, appstudio-utils/util-scripts/lib/fetch/data.sh, appstudio-utils/util-scripts/verify-attestation-with-policy.sh, tasks/verify-enterprise-contract.yaml, test/fetch-test-data_spec.sh
=> Use conftest instead of opa for the EC

tasks/buildah.yaml
=> Update buildah task to include SBOM generation

tasks/buildah.yaml
PLNSRVCE-184
To improve Syft's report, both the image and the source code were scanned and two distinct SBOM's were generated. This PR will merge both contents into a single file to make it more concise.
=> Update buildah task to merge both generated SBOMs 

tasks/buildah.yaml, tasks/s2i-java.yaml, tasks/s2i-nodejs.yaml
Avoid issue with available cpus in development env
=> Set limits to be able to run in development env

tasks/sast-go.yaml, tasks/sast-java-sec-check.yaml
Increase limits for SAST tasks.
PLNSRVCE-352
=> sast: set build limits

pipelines/hacbs/force-rebuild.yaml, pipelines/hacbs/kustomization.yaml
Switch default parameter for rebuild to 'true' in hacbs pipelines.
=> Always build with HACBS pipelines

appstudio-utils/util-scripts/fetch-ec-policies.sh, appstudio-utils/util-scripts/verify-attestation-with-policy.sh, tasks/verify-enterprise-contract.yaml
=> Support policy configuration in verify-ec task

tasks/verify-enterprise-contract.yaml
=> Fix typo in verify-ec task doc

tasks/patches/add-sbom-and-push.yaml
=> Add converter from cyclonedx to purl format

tasks/patches/add-sbom-and-push.yaml
Put files to /root/buildinfo/content_manifests/
=> SBOM: change place and add indention, merge sbom steps

pipelines/hacbs/hacbs-test.yaml, tasks/kustomization.yaml, tasks/sast-snyk-check.yaml
Signed-off-by: Jing Qi <jinqi@redhat.com>
Test example:  ./test-build.sh https://github.com/jduimovich/single-container-app docker-build
=> Add snyk code test task for doing SAST check

pipelines/base/template-build/template-build.yaml, pipelines/hacbs/hacbs-java-builder/kustomization.yaml, pipelines/hacbs/hacbs-java-builder/patch.yaml, pipelines/hacbs/kustomization.yaml, tasks/hacbs-java.yaml, tasks/kustomization.yaml
Using jvm-build-service which should trigger rebuild of community
packages.
Limitation - only for basic quarkus applications, tested with
`./hack/test-build.sh https://github.com/devfile-samples/devfile-sample-code-with-quarkus hacbs-java-builder`
=> Initial version of HACBS Java pipeline

tasks/sast-go.yaml, tasks/sast-java-sec-check.yaml, tasks/sast-snyk-check.yaml
Signed-off-by: Jing Qi <jinqi@redhat.com>
It's to add SKIPPED status for the SAST tasks
=> Add SKIPPED test output status for SAST tasks

tasks/conftest-clair.yaml, tasks/deprecated-image-check.yaml, tasks/get-clair-scan.yaml, tasks/hacbs-test-evaluation.yaml, tasks/sanity-label-check.yaml
Image tag change from hacbs-test:stable to hacbs-test:latest.
=> Add latest tag to hacbs-test images

appstudio-utils/Dockerfile, hack/start-verify-ec-task-v2.sh, pipelines/hacbs/e2e-ec.yaml, tasks/kustomization.yaml, tasks/verify-enterprise-contract-v2.yaml
https://issues.redhat.com/browse/HACBS-535
=> Add verify-enterprise-contract-v2 task

.tekton/push.yaml, .tekton/tasks/buildah.yaml, tasks/update-infra-deployments.yaml
https://issues.redhat.com/browse/HACBS-748
=> Update ec-policies on new Pipeline Bundles

tasks/sast-go.yaml
Signed-off-by: Jing Qi <jinqi@redhat.com>
=> Add the sarif output in the log for sast-go task

tasks/buildah.yaml, tasks/patches/add-sbom-and-push.yaml, tasks/s2i-java.yaml, tasks/s2i-nodejs.yaml
=> PLNSRVCE-426 Expose Digest of Base Images

tasks/patches/add-sbom-and-push.yaml
This requires https://github.com/redhat-appstudio/jvm-build-service/pull/105 to also be merged.
=> PLNSRVCE-539 move to workspace based caches

pipelines/hacbs/e2e-ec.yaml
https://issues.redhat.com/browse/HACBS-536
=> Remove verify-ec(v1) task from e2e pipeline

.tekton/pull-request.yaml, hack/build-and-push.sh
This PR partially completes the task defined in https://issues.redhat.com/browse/PLNSRVCE-181
* test HACBS pipeline per PR
TBD (once https://issues.redhat.com/browse/PLNSRVCE-542 is completed):
* test all HACBS pipelines (s2i-nodejs, s2i-java) in parallel
=> feat: test hacbs pipeline

tasks/sast-go.yaml
=> Add the gosec-output.json contents the sast-go task logs

hack/build-and-push.sh
When the pipeline images are built `taskRef`'s `bundle` field is set with the reference to the bundle image containing the task identified by it's name. That image reference does not include the task bundle image digest.
This adds the task bundle image digest to the `bundle` field as well.
Fixes https://issues.redhat.com/browse/HACBS-1086
=> Include image digest in task references

.tekton/push.yaml, appstudio-utils/Dockerfile
=> Check if ec command is installed properly

.tekton/tasks/yaml-lint.yaml, pipelines/base/docker-build/patch.yaml, pipelines/base/java-builder/patch.yaml, pipelines/hacbs/hacbs-java-builds.yaml, task/buildah/0.1/buildah.yaml, task/init/0.1/init.yaml, task/s2i-java/0.1/s2i-java.yaml, task/s2i-nodejs/0.1/s2i-nodejs.yaml
Draft for now, as I seem to be having some issues testing this on my local KCP environment.
=> PLNSRVCE-798 Update to latest JVM Build Service

pipelines/template-build/template-build.yaml, task/sbom-json-check/0.1/sbom-json-check.yaml, task/sbom-json-check/OWNERS
=> feat(HACBS-1213): add task sbom-json-check.yaml

hack/build-and-push.sh
Create HACBS enabled pipeline for testing purposes.
=> Create temporary pipeline with HACBS enabled

task/buildah/0.1/buildah.yaml
=> PLNSRVCE-817: allow build from Dockerfile fetched from URL

task/clamav-scan/0.1/clamav-scan.yaml
Signed-off-by: Sri Vignesh <sselvan@redhat.com>
=> feat[HACBS-1271]: Store output from ClamAV into result

task/configure-build/0.1/configure-build.yaml
Restore the sharedsecret removed in 0d4a20ba6f44112cd25fb3fe122f53d090bc3e52
=> PLNSRVCE-937: enable SharedSecret for accessing user-workloads

pipelines/template-build/template-build.yaml, task/deprecated-image-check/0.1/deprecated-image-check.yaml
Jira: [HACBS-1428 ](https://issues.redhat.com/browse/HACBS-1428)
Implement deprecated base images checks with each base images digests contents
=> feat[HACBS-1428]: add deprecated base images checks

.tekton/pull-request.yaml, .tekton/scripts/check-task-pipeline-bundle-repos.sh
=> PLNSRVCE-938: check task and pipeline image repo existence

hack/test-build.sh, hack/test-builds.sh, pipelines/java-builder/patch.yaml, pipelines/template-build/template-build.yaml, task/buildah/0.1/buildah.yaml, task/init/0.1/init.yaml, task/s2i-java/0.1/s2i-java.yaml
=> PLNSRVCE-956: replace pipeline param hacbs with skip-checks

hack/test-builds.sh, pipelines/fbc-builder/kustomization.yaml, pipelines/fbc-builder/patch.yaml, pipelines/kustomization.yaml
FBC build pipeline placeholder - copy of docker-builder since it should have only updated tests.
=> PLNSRVCE-884: Add FBC build pipeline

task/clair-scan/0.1/clair-scan.yaml, task/sanity-label-check/0.1/sanity-label-check.yaml, task/sast-go/0.1/sast-go.yaml, task/sast-java-sec-check/0.1/sast-java-sec-check.yaml, task/sast-snyk-check/0.1/sast-snyk-check.yaml
Use shell function parse_hacbs_test_output to parse hacbs test result file
=> feat(HACBS-1386): parse hacbs test result file

task/buildah/0.1/buildah.yaml, task/git-clone/0.1/git-clone.yaml, task/init/0.1/init.yaml, task/s2i-java/0.1/s2i-java.yaml, task/s2i-nodejs/0.1/s2i-nodejs.yaml, task/summary/0.1/summary.yaml, task/update-infra-deployments/0.1/update-infra-deployments.yaml
Trying to avoid issues with pulling from registry.redhat.io
=> Update version of images from redhat repositories

task/buildah/0.1/buildah.yaml, task/s2i-java/0.1/s2i-java.yaml
Set maven mirror when cache service is available.
=> PLNSRVCE-990: Use java cache when it's available

hack/test-build.sh
Allow to use podman to create secret
=> fix(hack): Add secret from podman login

task/clair-scan/0.1/clair-scan.yaml, task/clamav-scan/0.1/clamav-scan.yaml, task/deprecated-image-check/0.1/deprecated-image-check.yaml, task/fbc-validation/0.1/fbc-validation.yaml, task/sanity-label-check/0.1/sanity-label-check.yaml, task/sbom-json-check/0.1/sbom-json-check.yaml
All test tasks should return results in the same format with the same fields
=> feat(HACBS-1598): Standardize result output

task/buildah/0.1/buildah.yaml
fix for #285 (was updated only in s2i-java)
=> PLNSRVCE-1039 Update build request processor

hack/build-and-push.sh
HACBS pipeline is not used anymore, the switch to advanced pipeline is now based on skip-checks parameter. This is also fixing issue with missing pipeline-docker-build:devel
=> STONEBLD-27: Do not build pipeline-hacbs-docker-build

task/deprecated-image-check/0.1/deprecated-image-check.yaml
Handle hacbs_test_output result output for missing images.
=> fix: deprecated image for special images

.tekton/push.yaml
=> STONEBLD-27: stop updating digest for removed default pipeline bundles

task/buildah/0.1/buildah.yaml
- Enable network-isolation on new linux namespace level.
- Prefetch images used by dockerfile
- Inject sourcing of cachi2.env
=> STONEBLD-682: hermetic build with unshare

task/fbc-related-image-check/0.1/fbc-related-image-check.yaml
Fixes url construction for skopeo inspect
=> fix(HACBS-1509): fix URL construction in fbc-related-image check

pipelines/fbc-builder/patch.yaml, pipelines/template-build/template-build.yaml, task/fbc-related-image-check/0.1/fbc-related-image-check.yaml, task/fbc-validation/0.1/fbc-validation.yaml, task/sanity-inspect-image/0.1/sanity-inspect-image.yaml, task/sbom-json-check/0.1/sbom-json-check.yaml
Make sure we test the expected image, we cannot rely on floating tags
=> Use image digests in tasks

task/prefetch-dependencies/0.1/prefetch-dependencies.yaml
=> Cachi2: bump image to update docs links, call inject-files subcommand

.tekton/pull-request.yaml, pipelines/core-services/kustomization.yaml, pipelines/core-services/snyk-secret.yaml
Enable sast-snyk for core services and run it in this PaC as well.
=> enable sast-snyk in core and this ci

pipelines/enterprise-contract.yaml
See commentary for explanation. I'm not sure if this will require a change in the tests, but I'll push the PR and see how it goes.
=> Change STRICT param to true in the EC pipeline

task/update-infra-deployments/0.1/update-infra-deployments.yaml
Fixing update-infra-deployments which was broken by #343
=> STONEBLD-683: Fix of update-infra-deployments

task/buildah/0.1/buildah.yaml
Space was missing after periods.
=> fix(buildah): add space after period in description

.tekton/push.yaml, appstudio-utils/Dockerfile
https://issues.redhat.com/browse/HACBS-2004
=> Update references to new GitHub org name

task/buildah/0.1/buildah.yaml, task/s2i-java/0.1/s2i-java.yaml, task/s2i-nodejs/0.1/s2i-nodejs.yaml, task/tkn-bundle/0.1/tkn-bundle.yaml
The label will be used by a policy to identify which build pipeline ran.
https://issues.redhat.com/browse/HACBS-1883
=> feat(HACBS-1883): Create label to identify the build task for each pipeline.

task/sast-go/0.1/README.md, task/sast-java-sec-check/0.1/README.md, task/sast-snyk-check/0.1/README.md, task/sbom-json-check/0.1/README.md
This PR adds content inside the README.md files of the following tasks:
- [sast-go](https://issues.redhat.com/browse/STONEINTG-269)
- [sast-java-sec-check](https://issues.redhat.com/browse/STONEINTG-268)
- [sast-snyk-check](https://issues.redhat.com/browse/STONEINTG-267)
- [sbom-json-check](https://issues.redhat.com/browse/STONEINTG-266)
=> feat: add README.md files for the tasks

hack/generate-build-team-readme.sh, hack/generate-readme.sh, task/buildah/0.1/README.md, task/buildah/0.1/buildah.yaml, task/git-clone/0.1/README.md, task/git-clone/0.1/git-clone.yaml, task/init/0.1/README.md, task/init/0.1/init.yaml, task/prefetch-dependencies/0.1/README.md, task/prefetch-dependencies/0.1/prefetch-dependencies.yaml, task/s2i-java/0.1/README.md, task/s2i-java/0.1/s2i-java.yaml, task/s2i-nodejs/0.1/README.md, task/s2i-nodejs/0.1/s2i-nodejs.yaml, task/summary/0.1/README.md, task/summary/0.1/summary.yaml, task/update-infra-deployments/0.1/README.md, task/update-infra-deployments/0.1/update-infra-deployments.yaml
- Update task descriptions
- create script for generating readme based on task
- generate README.md for tasks owned by Build team
=> STONEBLD-663: Generate README.md for tasks owned by Build team

.tekton/tasks/e2e-test.yaml, hack/build-and-push.sh, hack/util-install-bundle.sh
https://issues.redhat.com/browse/STONEBLD-33
Added 2 new components for testing java & nodejs s2i build templates
* https://github.com/redhat-appstudio-qe/nodejs-no-dockerfile
* https://github.com/redhat-appstudio-qe/maven-hello-world
=> test: add java and nodejs components for testing

.tekton/pull-request.yaml, .tekton/scripts/check-partner-tasks.sh, hack/check-partner-tasks.sh
This commit also introduces a directory structure for partner tasks, that should follow the same structure of existing tasks with versions.
=> Add CI job to check partner task submission

hack/check-partner-tasks.sh
=> Fix task directory search under partners/

partners/README.md
This PR will address story https://issues.redhat.com/browse/STONEBLD-815
=> Partner task submission documentation

pipelines/enterprise-contract.yaml, task/clair-scan/0.1/README.md, task/clair-scan/0.1/clair-scan.yaml, task/clamav-scan/0.1/README.md, task/clamav-scan/0.1/clamav-scan.yaml, task/deprecated-image-check/0.1/README.md, task/deprecated-image-check/0.1/deprecated-image-check.yaml, task/deprecated-image-check/0.2/README.md, task/deprecated-image-check/0.2/deprecated-image-check.yaml, task/fbc-related-image-check/0.1/README.md, task/fbc-related-image-check/0.1/fbc-related-image-check.yaml, task/fbc-validation/0.1/README.md, task/fbc-validation/0.1/fbc-validation.yaml, task/inspect-image/0.1/README.md, task/inspect-image/0.1/inspect-image.yaml, task/label-check/0.1/README.md, task/label-check/0.1/label-check.yaml, task/sast-go/0.1/README.md, task/sast-go/0.1/sast-go.yaml, task/sast-java-sec-check/0.1/README.md, task/sast-java-sec-check/0.1/sast-java-sec-check.yaml, task/sast-snyk-check/0.1/README.md, task/sast-snyk-check/0.1/sast-snyk-check.yaml, task/sbom-json-check/0.1/README.md, task/sbom-json-check/0.1/sbom-json-check.yaml
Removing `HACBS` prefix from tekton results for Integration-service side.
=> feat(STONEINTG-203): remove HACBS prefix from tekton results

pipelines/enterprise-contract.yaml
This should hopefully fix a regression introduced earlier today.
=> Bump ec task bundle version

pipelines/docker-build/patch.yaml, pipelines/fbc-builder/patch.yaml, pipelines/java-builder/patch.yaml, pipelines/nodejs-builder/patch.yaml, pipelines/template-build/template-build.yaml, task/buildah/0.1/README.md, task/buildah/0.1/buildah.yaml, task/s2i-java/0.1/README.md, task/s2i-java/0.1/s2i-java.yaml, task/s2i-nodejs/0.1/README.md, task/s2i-nodejs/0.1/s2i-nodejs.yaml, task/update-infra-deployments/0.1/README.md
- Allow to set expiration of image tag
- by default do not expire
=> STONEBLD-1157: Allow to set expiration on image tags

.tekton/tasks/buildah.yaml, task/buildah/0.1/buildah.yaml, task/s2i-java/0.1/s2i-java.yaml, task/s2i-nodejs/0.1/s2i-nodejs.yaml
buildah bud could be confusing, alias build is more clear.
=> STONEBLD-1207: Use buildah build

pipelines/template-build/template-build.yaml, task/init/0.1/README.md, task/init/0.1/init.yaml
This change will allow optional label check to be run only in case that the parameter: **skip-optional** is set to "false".
=> feat(STONEINTG-415): optional-label-check should be skipped by default

task/init/0.1/README.md, task/init/0.1/init.yaml
https://issues.redhat.com/browse/STONEBLD-867
=> STONEBLD-867: Remove shared secret

task/clamav-scan/0.1/clamav-scan.yaml, task/fbc-validation/0.1/fbc-validation.yaml, task/sbom-json-check/0.1/sbom-json-check.yaml
Avoid warning message by pointing to the file.
=> STONEBLD-876: define registry auth for oc to avoid warning

task/buildah/0.1/buildah.yaml, task/s2i-java/0.1/s2i-java.yaml, task/s2i-nodejs/0.1/s2i-nodejs.yaml
Some images are having issue with custom group permission on volume created by emptyDir, updating folder group to root.
=> STONEBLD-1250: fix permission on /var/lib/containers

task/init/0.1/init.yaml, task/summary/0.1/summary.yaml
Select smaller images which provides tools which are needed.
As bonus "fix" [RHTAPBUGS-397](https://issues.redhat.com//browse/RHTAPBUGS-397)
=> Update images of init and summary

partners/README.md, partners/example-hello-world/0.1/example-hello-world.yaml, partners/example-hello-world/OWNERS
Add example partner task and document way how to include in user's pipelinerun.
=> STONEBLD-1305: Example of partner task

task/buildah/0.1/buildah.yaml, task/s2i-java/0.1/s2i-java.yaml, task/s2i-nodejs/0.1/s2i-nodejs.yaml
Rename sbom-get to sbom-syft-generate to cleary name the step based on what it's doing.
=> Rename step to sbom-syft-generate

pipelines/enterprise-contract-redhat.yaml
https://issues.redhat.com/browse/HACBS-2370
=> Add RedHat EC pipeline

appstudio-utils/Dockerfile, task/buildah/0.1/buildah.yaml, task/s2i-java/0.1/s2i-java.yaml, task/s2i-nodejs/0.1/s2i-nodejs.yaml, task/show-sbom/0.1/show-sbom.yaml
=> Increase cosign version to 2.1.1

.tekton/scripts/check-task-pipeline-bundle-repos.sh, hack/build-and-push.sh, hack/ec-checks.sh, hack/test-builds.sh, task/buildah-10gb/0.1/kustomization.yaml, task/buildah-10gb/0.1/patch.yaml, task/buildah-10gb/OWNERS, task/buildah-6gb/0.1/kustomization.yaml, task/buildah-6gb/0.1/patch.yaml, task/buildah-6gb/OWNERS, task/buildah-8gb/0.1/kustomization.yaml, task/buildah-8gb/0.1/patch.yaml, task/buildah-8gb/OWNERS, task/buildah/0.1/kustomization.yaml
Use kustomize to allow generate multiple buildah task version with different memory configuration.
=> STONEBLD-1494: add variation of buildah with different memory

syft.Dockerfile, task/buildah/0.1/buildah.yaml, task/s2i-java/0.1/s2i-java.yaml, task/s2i-nodejs/0.1/s2i-nodejs.yaml, task/sbom-json-check/0.1/sbom-json-check.yaml
[STONEBLD-1491](https://issues.redhat.com//browse/STONEBLD-1491)
=> Upgrade syft version

pipelines/enterprise-contract-everything.yaml, pipelines/enterprise-contract-redhat.yaml, pipelines/enterprise-contract-slsa1.yaml, pipelines/enterprise-contract-slsa2.yaml, pipelines/enterprise-contract-slsa3.yaml, pipelines/enterprise-contract.yaml
This commit adds and explicitly sets the value of IGNORE_REKOR to true for enterprise-contract tasks.
=> refactor: Explicitly set IGNORE_REKOR value

pipelines/enterprise-contract-everything.yaml, pipelines/enterprise-contract-redhat.yaml, pipelines/enterprise-contract-slsa1.yaml, pipelines/enterprise-contract-slsa2.yaml, pipelines/enterprise-contract-slsa3.yaml, pipelines/enterprise-contract.yaml
https://issues.redhat.com/browse/HACBS-2359
=> Do not rely on public key from config

pipelines/enterprise-contract-redhat-no-hermetic.yaml
https://issues.redhat.com/browse/HACBS-2657
=> Add ec redhat-no-hermetic pipeline

.tekton/push.yaml
Ref: https://issues.redhat.com/browse/HACBS-2689
=> Use the --freshen flag in ec track bundle

.tekton/push.yaml
Path where bundles are stored in infra repo has changed.
=> chore(infra): update infra path

.tekton/pull-request.yaml, .tekton/tasks/buildah.yaml, .tekton/tasks/ec-checks.yaml, .tekton/tasks/yaml-lint.yaml, task/buildah-remote/0.1/buildah-remote.yaml, task/buildah/0.1/buildah.yaml, task/git-clone/0.1/git-clone.yaml, task/prefetch-dependencies/0.1/prefetch-dependencies.yaml, task/s2i-java/0.1/s2i-java.yaml, task/s2i-nodejs/0.1/s2i-nodejs.yaml, task/sast-snyk-check/0.1/sast-snyk-check.yaml
The source code will be present in the source directory in the root of
the workspace.
[STONEBLD-1570](https://issues.redhat.com//browse/STONEBLD-1570)
=> Clone source code into a dedicated directory

pipelines/enterprise-contract-everything.yaml, pipelines/enterprise-contract-redhat-no-hermetic.yaml, pipelines/enterprise-contract-redhat.yaml, pipelines/enterprise-contract-slsa3.yaml, pipelines/enterprise-contract.yaml
Ref: https://issues.redhat.com/browse/EC-143
=> Use the in-cluster ECP resources by default

.tekton/tasks/ec-checks.yaml
Ref: https://issues.redhat.com/browse/EC-14
=> Use new data source in ec-checks

renovate.json
Update renovate bot reviewers: remove `Michkov`, add `mmorhun`
=> Update renovate bot reviewers

task/rpm-ostree/0.1/rpm-ostree.yaml
This allows the multi platform controller to create images that are bootable on VMs.
=> STONEBLD-1803 Add rpm-ostree task

task/deprecated-image-check/0.3/deprecated-image-check.yaml, task/sast-snyk-check/0.1/sast-snyk-check.yaml
Ref: [STONEINTG-681](https://issues.redhat.com//browse/STONEINTG-681)
=> Change no-op checks from SKIPPED to SUCCESS

task/rpm-ostree/0.1/rpm-ostree.yaml
- add support to the rpm-ostree task in order to specify an image-config file to be used.
=> feat(KFLUXBUGS-12): add support for image-config parameter

task/buildah-20gb/0.1/kustomization.yaml, task/buildah-20gb/0.1/patch.yaml, task/buildah-20gb/OWNERS, task/buildah-24gb/0.1/kustomization.yaml, task/buildah-24gb/0.1/patch.yaml, task/buildah-24gb/OWNERS
=> Adding buildah images with 20 and 24GB RAM config

pipelines/rhtap/kustomization.yaml, task/acs-deploy-check/0.1/acs-deploy-check.yaml, task/acs-image-check/0.1/acs-image-check.yaml, task/acs-image-scan/0.1/acs-image-scan.yaml, task/buildah-remote/0.1/buildah-remote.yaml, task/buildah/0.1/buildah.yaml, task/s2i-java/0.1/s2i-java.yaml, task/s2i-nodejs/0.1/s2i-nodejs.yaml, task/update-infra-deployments/0.1/update-infra-deployments.yaml
=> Fix yaml lint errors

pipelines/docker-build-rhtap/patch.yaml, task/update-deployment/0.1/README.md, task/update-deployment/0.1/update-deployment.yaml, task/update-deployment/OWNERS
Add task to update gitops repository.
=> Add update-deployment task

.tekton/tasks/e2e-test.yaml
[STONEBLD-1874](https://issues.redhat.com//browse/STONEBLD-1874)
Relates to the changes of resolving parent images made in build-tasks-dockerfiles/source-container-build.
Requires https://github.com/redhat-appstudio/build-tasks-dockerfiles/pull/33
=> Add test cases for source-build

README.md
Ref: https://issues.redhat.com/browse/EC-362
=> Add EC compliance expectation to docs

task/update-deployment/0.1/update-deployment.yaml
=> Fix yamllint on update-deployment task

task/sast-snyk-check/0.1/README.md, task/sast-snyk-check/0.1/sast-snyk-check.yaml
This PR is to add the help doc and update TEST_OUTPUT note to help users enable the snyk task for their products.
=> fix(STONEINTG-728): add a help doc to enable snyk

task/sast-snyk-check/0.1/sast-snyk-check.yaml
=> fix(STONEINTG-728): fix TEST_OUTPUT link in Snyk task

.tekton/push.yaml
* add finally task to .tekton/push.yaml to send message to slack in case tasks fails
=> feat(STONEINTG-711): add finally task to push.yaml

pipelines/tekton-bundle-builder/kustomization.yaml, pipelines/template-build/template-build.yaml, task/summary/0.1/summary.yaml
[STONEBLD-1608](https://issues.redhat.com//browse/STONEBLD-1608)
=> Show source image URL in summary

pipelines/docker-build-rhtap/patch.yaml, task/acs-deploy-check/0.1/acs-deploy-check.yaml, task/acs-image-check/0.1/acs-image-check.yaml, task/acs-image-scan/0.1/acs-image-scan.yaml
After this change the secret with the ACS configuration should be created the following way:
```
oc create secret generic rox-api-token --from-literal=rox-api-token="${ROX_TOKEN}" --from-literal=rox-api-endpoint="${ROX_ENDPOINT}"
```
=> Consume ACS API endpoint from the secret together with the token

pipelines/tekton-bundle-builder/kustomization.yaml, pipelines/template-build/template-build.yaml, task/summary/0.1/summary.yaml
[STONEBLD-1608](https://issues.redhat.com//browse/STONEBLD-1608)
This reverts commit 13025987234ce81966a942b70e2fa78d0e07b0bb.
=> Revert "Show source image URL in summary"

task/acs-deploy-check/0.1/acs-deploy-check.yaml, task/acs-image-check/0.1/acs-image-check.yaml, task/acs-image-scan/0.1/acs-image-scan.yaml
=> Align ACS tasks output and annotations according to RHDH requirements

task/buildah/0.1/README.md
[STONEBLD-1589](https://issues.redhat.com//browse/STONEBLD-1589)
=> Document the new parameter that allows enabling subscription

pipelines/docker-build-rhtap/patch.yaml
=> update removed tasks after recent changes

task/verify-enterprise-contract/0.1/README.md, task/verify-enterprise-contract/0.1/kustomization.yaml, task/verify-enterprise-contract/0.1/verify-enterprise-contract.yaml, task/verify-enterprise-contract/OWNERS
Adding verify enterprise contract task to be managed with other tasks belonging to dance/rhtap.
https://issues.redhat.com/browse/EC-429
=> add verify enterprise contract task

pipelines/gitops-pull-request-rhtap/gitops-pull-request.yaml, pipelines/gitops-pull-request-rhtap/kustomization.yaml, task/gather-deploy-images/0.1/README.md, task/gather-deploy-images/0.1/gather-deploy-images.yaml
=> RHTAP gitops PR pipeline

task/buildah-rhtap/0.1/buildah-rhtap.yaml
=> buildah-rhtap: use productized syft and cosign

.tekton/scripts/build-acceptable-bundles.sh
Update git diff command to examine merge commits, git diff-tree only examined non merge commits.
Also, remove revision from the task format. EC tracker does not support it.
This change is dependent on https://github.com/enterprise-contract/ec-cli/pull/1494
=> Examine merge commits on bundle updates

task/clair-scan/0.1/clair-scan.yaml
=> [CVP-4034] support scanning Image Index in clair-scan task

.tekton/tasks/ec-checks.yaml, pipelines/enterprise-contract-everything.yaml, pipelines/enterprise-contract-redhat-no-hermetic.yaml, pipelines/enterprise-contract-redhat.yaml, pipelines/enterprise-contract-slsa3.yaml, pipelines/enterprise-contract.yaml
Reverts redhat-appstudio/build-definitions#874
=> Revert "chore(deps): update ec"

task/prefetch-dependencies/0.1/prefetch-dependencies.yaml
* modelled on git-clone
* tested on rhel-bootc project
=> Custom CA bundle for prefetch-dependencies

pipelines/docker-build-rhtap/patch.yaml, pipelines/docker-build/patch.yaml, pipelines/template-build/template-build.yaml, task/buildah-rhtap/0.1/buildah-rhtap.yaml
also support it in buildah-rhtap task
=> move build-args params only to docker-build pipelines

task/ecosystem-cert-preflight-checks/0.1/ecosystem-cert-preflight-checks.yaml
- **add support for private container repos by passing credentials to preflight via exported docker config json**
=> export path to docker config json for preflight 

.tekton/tasks/e2e-test.yaml
=> STONEBLD-2419: disabled source build test with parent using latest image

hack/generate-pipelines-readme.py, pipelines/docker-build-rhtap/README.md, pipelines/docker-build/README.md, pipelines/fbc-builder/README.md, pipelines/gitops-pull-request-rhtap/README.md, pipelines/java-builder/README.md, pipelines/nodejs-builder/README.md, pipelines/tekton-bundle-builder/README.md
[STONEBLD-2330](https://issues.redhat.com//browse/STONEBLD-2330)
=> script for generating pipelines README.md

.tekton/tasks/e2e-test.yaml
=> STONEBLD-2419: reenable tests for source build image parent using latest

pipelines/template-build/template-build.yaml, task/apply-tags/0.1/README.md, task/apply-tags/0.1/apply-tags.yaml, task/apply-tags/OWNERS
This new task "apply-tags" allows specifying additional-tags that will be added to the specified image.
[STONEBLD-2418](https://issues.redhat.com//browse/STONEBLD-2418)
=> Add new task for tagging images

.tekton/tasks/e2e-test.yaml
[STONEBLD-2256](https://issues.redhat.com//browse/STONEBLD-2256)
=> Add e2e-tests test repo

hack/trusted-tasks-update.sh, partners/README.md, pipelines/gitops-pull-request-rhtap/README.md, task/gather-deploy-images/0.1/README.md, task/gather-deploy-images/0.1/gather-deploy-images.yaml, task/prefetch-dependencies-oci-ta/0.1/prefetch-dependencies-oci-ta.yaml, task/prefetch-dependencies/0.1/prefetch-dependencies.yaml
[STONEBLD-2339](https://issues.redhat.com//browse/STONEBLD-2339)
=> Move repo to konflux-ci

.tekton/tasks/e2e-test.yaml
Part of story: https://issues.redhat.com/browse/STONEBLD-2353
=> chore: remove source build related test repos

.tekton/push.yaml
=> no need to update removed build pipeline selectore anymore

task/buildah-oci-ta/0.1/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml, task/buildah-remote/0.1/buildah-remote.yaml, task/buildah/0.1/buildah.yaml
This lets the volume sync properly for the oci ta remote task
=> Move shared to step template

task/buildah-oci-ta/0.1/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml, task/git-clone-oci-ta/0.1/git-clone-oci-ta.yaml, task/prefetch-dependencies-oci-ta/0.1/prefetch-dependencies-oci-ta.yaml
=> Fix Tekton variable subs in -oci-ta Tasks

task/deprecated-image-check/0.4/deprecated-image-check.yaml
resolves #1072
[KFLUXBUGS-1316](https://issues.redhat.com//browse/KFLUXBUGS-1316)
=> feat: support multi-arch images in deprecated-base-image-check task

renovate.json
=> chore(STONEINTG-972): update integration team members

hack/generate-ta-tasks.sh
A more verbose version will be emitted on GitHub with the instructions on how to fix the issue.
=> Emit less confusing message from TA generator

task/fbc-related-image-check/0.1/fbc-related-image-check.yaml
=> fix: missing bracket in related images check

task/source-build-oci-ta/0.1/source-build-oci-ta.yaml, task/source-build/0.1/source-build.yaml
[STONEBLD-2563](https://issues.redhat.com//browse/STONEBLD-2563)
=> Use quay.io/konflux-ci/source-container-build

renovate.json
=> feat: setup renovate to update source-container-build image

task/buildah-oci-ta/0.1/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml, task/git-clone-oci-ta/0.1/git-clone-oci-ta.yaml, task/oci-copy-oci-ta/0.1/oci-copy-oci-ta.yaml, task/prefetch-dependencies-oci-ta/0.1/prefetch-dependencies-oci-ta.yaml, task/sast-snyk-check-oci-ta/0.1/sast-snyk-check-oci-ta.yaml, task/source-build-oci-ta/0.1/source-build-oci-ta.yaml
This is a dupe of https://github.com/konflux-ci/build-definitions/pull/1137
=> chore: bump build-trusted-artifacts

task/source-build-oci-ta/0.1/source-build-oci-ta.yaml, task/source-build/0.1/source-build.yaml
Addresses: https://issues.redhat.com/browse/KFLUXBUGS-1331
=> fix: remove trailing newlines from source-build results

pipelines/docker-build-oci-ta/README.md, pipelines/docker-build-rhtap/README.md, pipelines/docker-build/README.md, pipelines/fbc-builder/README.md, pipelines/gitops-pull-request-rhtap/README.md, pipelines/java-builder/README.md, pipelines/nodejs-builder/README.md, pipelines/tekton-bundle-builder/README.md
=> pipelines: re-generate READMEs

task/buildah-oci-ta/0.1/buildah-oci-ta.yaml, task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.1/buildah-remote-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.1/buildah-remote.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.1/buildah.yaml, task/buildah/0.2/buildah.yaml, task/prefetch-dependencies-oci-ta/0.1/prefetch-dependencies-oci-ta.yaml, task/prefetch-dependencies/0.1/prefetch-dependencies.yaml, task/rpm-ostree/0.1/rpm-ostree.yaml
https://github.com/containerbuildsystem/cachi2/releases/tag/0.9.1
=> Update to cachi2 0.9.1

.github/workflows/check-readmes.yaml, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/java-builder/README.md, pipelines/nodejs-builder/README.md, pipelines/tekton-bundle-builder/README.md
[STONEBLD-2401](https://issues.redhat.com//browse/STONEBLD-2401)
=> CI: check if pipeline READMEs are up to date

task/ecosystem-cert-preflight-checks/0.1/ecosystem-cert-preflight-checks.yaml
=> Fix typo: `prelifght` --> `preflight`

task/operator-sdk-generate-bundle/0.1/operator-sdk-generate-bundle.yaml
needed to write out the generated files
Signed-off-by: Brady Pratt <bpratt@redhat.com>
=> SDCICD-1337: run generate bundle as root

pipelines/gitops-pull-request-rhtap/README.md, pipelines/gitops-pull-request-rhtap/gitops-pull-request.yaml
Change introduced by RHTAP 1.2.
=> fix: update default RHTAP URLs

pipelines/enterprise-contract.yaml
=> enterprise contract update

renovate.json
=> chore: add jencull to the integration team

pipelines/enterprise-contract.yaml
Add ConfigMap parameters to support custom certificate in enterprise-contract pipeline.
Jira-Url: https://issues.redhat.com/browse/RHTAPWATCH-1038
=> feat(RHTAPWATCH-1038): Support custom certificate in ec pipeline

task/sast-snyk-check-oci-ta/0.2/MIGRATION.md, task/sast-snyk-check/0.2/MIGRATION.md
Including more information about sast snyk check migration within migration.md files.
=> STONEINTG-1020: Expand migration.md with more precise info

pipelines/enterprise-contract.yaml
- does not correctly handle large snapshots.
=> fix(KFLUXBUGS-1582): remove reduce-snapshot task

.tekton/tasks/e2e-test.yaml
This PR is part of https://issues.redhat.com/browse/STONEBLD-2085
=> feat: add a test repo with dockerfile using from scratch

task/sbom-json-check/0.2/MIGRATION.md
=> Fix markdown formatting

pipelines/enterprise-contract.yaml
Ref: https://issues.redhat.com/browse/EC-784
=> Add WORKERS parameter to ec Pipeline

hack/build-and-push.sh
The purpose is to make it easier to understand where a bundle came from if all you have is the bundle reference.
Inspect with `skopeo inspect --raw docker://pullspec | jq .annotations`
See also:
* https://github.com/tektoncd/pipeline/issues/7354
* https://issues.redhat.com/browse/KONFLUX-1229
=> Declare some OCI annotations on bundles

task/clamav-scan/0.1/clamav-scan.yaml
=> feat(STONEINTG-1030): added db version to clamav report

hack/build-and-push.sh, hack/generate-pipelines-readme.py, pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-multi-platform-oci-ta/patch.yaml, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build-oci-ta/patch.yaml, pipelines/docker-build-rhtap/README.md, pipelines/docker-build/README.md, pipelines/docker-build/patch.yaml, pipelines/fbc-builder/README.md, pipelines/fbc-builder/patch.yaml, pipelines/gitops-pull-request-rhtap/README.md, pipelines/java-builder/README.md, pipelines/nodejs-builder/README.md, pipelines/tekton-bundle-builder/README.md
As well as more metadata to the Tekton bundles.
=> add descriptions to pipelines

.tekton/tasks/e2e-test.yaml, pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/java-builder/README.md, pipelines/nodejs-builder/README.md, pipelines/tekton-bundle-builder/README.md, pipelines/template-build/template-build.yaml, policies/all-tasks.yaml, task/clair-scan/0.2/MIGRATION.md, task/clair-scan/0.2/README.md, task/clair-scan/0.2/clair-scan.yaml
Renaming of results for clair-scan required bumping up the version of task itself. Migration markdown created together with it to let customer know what to expect.
=> feat(STONEINTG-660): rename CLAIR_SCAN_RESULT to SCAN_OUTPUT

task/clamav-scan/0.1/README.md
=> chore(STONEINTG-1032): updated README after ClamAV update

task/rpm-ostree/0.1/rpm-ostree.yaml, task/rpm-ostree/0.2/rpm-ostree.yaml
=> mount secrets for rpm-ostree task

task/rpm-ostree/0.1/rpm-ostree.yaml, task/rpm-ostree/0.2/rpm-ostree.yaml
=> mount actually .docker with registry secrets for rpm-ostree task

task/rpm-ostree/0.1/rpm-ostree.yaml, task/rpm-ostree/0.2/rpm-ostree.yaml
=> rsync .docker directory to host in rpm-ostree task

renovate.json
This repo has too many dependencies, increase concurrency limit, so other teams are not waiting for changes indefinitelly
=> fix(renovate): increase PR concurency limit

task/sast-snyk-check-oci-ta/0.1/sast-snyk-check-oci-ta.yaml, task/sast-snyk-check-oci-ta/0.2/sast-snyk-check-oci-ta.yaml, task/sast-snyk-check-oci-ta/0.3/README.md, task/sast-snyk-check-oci-ta/0.3/sast-snyk-check-oci-ta.yaml, task/sast-snyk-check/0.1/README.md, task/sast-snyk-check/0.1/sast-snyk-check.yaml, task/sast-snyk-check/0.2/README.md, task/sast-snyk-check/0.2/sast-snyk-check.yaml, task/sast-snyk-check/0.3/README.md, task/sast-snyk-check/0.3/sast-snyk-check.yaml
Replaces outdated synk documentation link
=> update synk upstream docs link

task/acs-deploy-check/0.1/acs-deploy-check.yaml, task/acs-image-check/0.1/acs-image-check.yaml, task/acs-image-scan/0.1/acs-image-scan.yaml
* fix copy-paste typo in output
* add retry mechanism to acs-image-scan to help with [RHTAPBUGS-1316](https://issues.redhat.com//browse/RHTAPBUGS-1316)
=> fix: ACS tasks

hack/missing-ta-tasks.sh, task/tkn-bundle-oci-ta/0.1/README.md, task/tkn-bundle-oci-ta/0.1/recipe.yaml, task/tkn-bundle-oci-ta/0.1/tkn-bundle-oci-ta.yaml, task/tkn-bundle-oci-ta/OWNERS, task/tkn-bundle/0.1/tkn-bundle.yaml
Resolves: https://issues.redhat.com/browse/EC-979
=> Add OCI/TA variant of the tkn-bundle Task

.tekton/tasks/ec-checks.yaml, .tekton/tasks/task-lint.yaml, task-generator/trusted-artifacts/golden/source-build/base.yaml, task-generator/trusted-artifacts/golden/source-build/ta.yaml, task/acs-deploy-check/0.1/acs-deploy-check.yaml, task/build-image-index/0.1/build-image-index.yaml, task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.2/buildah.yaml, task/download-sbom-from-url-in-attestation/0.1/download-sbom-from-url-in-attestation.yaml, task/ecosystem-cert-preflight-checks/0.1/ecosystem-cert-preflight-checks.yaml, task/gather-deploy-images/0.1/gather-deploy-images.yaml, task/oci-copy-oci-ta/0.1/oci-copy-oci-ta.yaml, task/oci-copy/0.1/oci-copy.yaml, task/opm-get-bundle-version/0.1/opm-get-bundle-version.yaml, task/rpm-ostree-oci-ta/0.2/rpm-ostree-oci-ta.yaml, task/rpm-ostree/0.1/rpm-ostree.yaml, task/rpm-ostree/0.2/rpm-ostree.yaml, task/show-sbom/0.1/show-sbom.yaml, task/slack-webhook-notification/0.1/slack-webhook-notification.yaml, task/source-build-oci-ta/0.1/source-build-oci-ta.yaml, task/source-build/0.1/source-build.yaml, task/summary/0.2/summary.yaml, task/update-deployment/0.1/update-deployment.yaml, task/upload-sbom-to-trustification/0.1/upload-sbom-to-trustification.yaml
This is need for RHTAP in order to integrate with TAS 1.1.
=> fix: update quay.io/konflux-ci/appstudio-utils digest to 48c311

task/clamav-scan/0.1/clamav-scan.yaml
=> Clamav: parse version from clamscan

renovate.json
=> Renovate: group gh-actions

task/buildah-oci-ta/0.2/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.2/buildah-remote-oci-ta.yaml, task/buildah-remote/0.2/buildah-remote.yaml, task/buildah/0.2/buildah.yaml
=> use regex to ignore commented  "subscription-manager register"

.github/workflows/check-buildah-remote.yaml, pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/template-build/template-build.yaml, task/clamav-scan/0.2/MIGRATION.md, task/clamav-scan/0.2/README.md, task/clamav-scan/0.2/clamav-scan.yaml
=> feat(STONEINTG-1072): removing sidecard and implement it by Clamav DB

pipelines/fbc-builder/README.md, pipelines/maven-zip-build-oci-ta/README.md, pipelines/maven-zip-build/README.md
* fbc-builder
* maven-zip-build
* maven-zip-build-oci-ta
=> fix: pipelines README out of date

task/fbc-validation/0.2/MIGRATION.md
=> improve completeness of FBC validation migration

task/clamav-scan/0.2/README.md, task/clamav-scan/0.2/clamav-scan.yaml
=> fix(STONEINTG-1074): set the option max file size to 2000M as in doc

task/eaas-provision-space/0.1/README.md, task/eaas-provision-space/0.1/eaas-provision-space.yaml
Update eaas-provision-space task to use new claim resource instead of SpaceRequests.
Jira-Url: https://issues.redhat.com/browse/KFLUXVNGD-93
=> chore(KFLUXVNGD-93): Update eaas-provision-space task

hack/build-and-push.sh
[STONEBLD-3026](https://issues.redhat.com//browse/STONEBLD-3026)
This is a fix to add missing annotation to task bundles.
=> Annotate task bundle if it has a migration

task/buildah-oci-ta/0.3/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.3/buildah-remote-oci-ta.yaml, task/buildah-remote/0.3/buildah-remote.yaml, task/buildah/0.3/buildah.yaml
For [KONFLUX-5684](https://issues.redhat.com//browse/KONFLUX-5684)
=> Remove quotes from BASE_IMAGES

CODEOWNERS, renovate.json, task/sealights-go-oci-ta/0.1/README.md, task/sealights-nodejs-oci-ta/0.1/README.md, task/sealights-nodejs-oci-ta/0.1/sealights-nodejs-oci-ta.yaml, task/sealights-python-oci-ta/0.1/README.md
This is a follow-up on https://github.com/konflux-ci/build-definitions/pull/1868
=> sealights: Node.js instrumentation Task

task/sast-coverity-check-oci-ta/0.2/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.2/patch.yaml, task/sast-coverity-check/0.2/sast-coverity-check.yaml
... in the Containerfile/Dockerfile
Resolves: https://issues.redhat.com/browse/OSH-805
=> sast-coverity-check: do not fail with no RUN directive

task/sealights-go-oci-ta/0.1/kustomization.yaml, task/sealights-go-oci-ta/0.1/sealights-go-oci-ta.yaml, task/sealights-nodejs-oci-ta/0.1/kustomization.yaml, task/sealights-nodejs-oci-ta/0.1/sealights-nodejs-oci-ta.yaml, task/sealights-python-oci-ta/0.1/kustomization.yaml, task/sealights-python-oci-ta/0.1/sealights-python-oci-ta.yaml
Add kustomization to manage Sealights patches when we version in the future. See a good example here: https://github.com/konflux-ci/build-definitions/blob/main/task/fbc-validation/0.2/kustomization.yaml#L1-L15
=> feat: add kustomization files to sealights task to manage future versions

task/sealights-go-oci-ta/0.1/sealights-go-oci-ta.yaml
=> feat: bump sealights Golang computeResources

task/build-paketo-builder-oci-ta/0.2/MIGRATION.md, task/build-paketo-builder-oci-ta/0.2/README.md, task/build-paketo-builder-oci-ta/0.2/build-paketo-builder-oci-ta.yaml
Switch the default SBOM format to SPDX.
Bump the version label, add the MIGRATION.md file.
=> paketo/0.2: default to SPDX

task/sealights-go-oci-ta/0.1/README.md, task/sealights-go-oci-ta/0.1/sealights-go-oci-ta.yaml
=> fix: remove unused parameters from sl go task

task/prefetch-dependencies-oci-ta/0.1/prefetch-dependencies-oci-ta.yaml, task/prefetch-dependencies-oci-ta/0.2/prefetch-dependencies-oci-ta.yaml, task/prefetch-dependencies/0.1/prefetch-dependencies.yaml, task/prefetch-dependencies/0.2/prefetch-dependencies.yaml
=> prefetch-dependencies: Include SBOM summary for RPM

task/prefetch-dependencies-oci-ta/0.1/prefetch-dependencies-oci-ta.yaml, task/prefetch-dependencies-oci-ta/0.2/prefetch-dependencies-oci-ta.yaml, task/prefetch-dependencies/0.1/prefetch-dependencies.yaml, task/prefetch-dependencies/0.2/prefetch-dependencies.yaml
=> prefetch-dependencies: Fix RPM check

pipelines/tekton-bundle-builder/README.md, pipelines/tekton-bundle-builder/patch.yaml, pipelines/tekton-bundle-builder/tekton-bundle-builder.yaml
Remove `coverity-availability-check` task
Remove `sast-coverity-check` task
=> chore(KFLUXVNGD-194): remove coverity checks from tekton-bundle-builder

hack/build-and-push.sh
The task bundles and migration artifacts are now annotated specifically.
As promised in https://github.com/konflux-ci/build-definitions/pull/1861#pullrequestreview-2621391050
=> Refine annotations

README.md
We often recommend this approach to contributors looking to try out their Task changes. Document it.
Also delete a bit of outdated content from the README
=> Document how to push tasks for development

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, pipelines/fbc-builder/README.md, pipelines/maven-zip-build-oci-ta/README.md, pipelines/maven-zip-build/README.md, task/buildah-min/0.4/buildah-min.yaml, task/buildah-oci-ta/0.4/README.md, task/buildah-oci-ta/0.4/buildah-oci-ta.yaml, task/buildah-remote-oci-ta/0.4/README.md, task/buildah-remote-oci-ta/0.4/buildah-remote-oci-ta.yaml, task/buildah-remote/0.4/README.md, task/buildah-remote/0.4/buildah-remote.yaml, task/buildah/0.4/README.md, task/buildah/0.4/buildah.yaml, task/sast-coverity-check-oci-ta/0.2/README.md, task/sast-coverity-check-oci-ta/0.2/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.2/sast-coverity-check.yaml
Add support to pass `--annotation` parameters to buildah task
=> Buildah: support for image annotations

CODEOWNERS
@jeremychoi will no longer be working on SAST tasks in konflux.
=> Remove @jeremychoi from CODEOWNERS

stepactions/fips-operator-check-step-action/0.1/fips-operator-check-step-action.yaml
Refers to [CLOUDDST-26028](https://issues.redhat.com//browse/CLOUDDST-26028)
=> Update konflux-test to 1.4.18 in fips stepaction

renovate.json, task/build-vm-image/0.1/build-vm-image.yaml
Follow-up to #1988 , use specific image tag (current latest) for reproducible builds
=> use buildah image tag current latest

task/tkn-bundle-oci-ta/0.1/tkn-bundle-oci-ta.yaml, task/tkn-bundle/0.1/tkn-bundle.yaml
Replace the image with the appstudio-utils image
which contains all the needed tools
=> chore(KFLUXVNGD-213): update image for tkn-bundle

hack/build-manifests.sh, pipelines/core-services/core-services.yaml, pipelines/docker-build-multi-platform-oci-ta/docker-build-multi-platform-oci-ta.yaml, pipelines/docker-build-oci-ta/docker-build-oci-ta.yaml, pipelines/docker-build-rhtap/docker-build-rhtap.yaml, pipelines/docker-build/docker-build.yaml, pipelines/fbc-builder/fbc-builder.yaml, pipelines/maven-zip-build-oci-ta/maven-zip-build-oci-ta.yaml, pipelines/maven-zip-build/maven-zip-build.yaml, pipelines/rhtap/rhtap.yaml, pipelines/tekton-bundle-builder/tekton-bundle-builder.yaml, task/build-image-manifest/0.1/build-image-manifest.yaml, task/buildah-10gb/0.1/buildah-10gb.yaml, task/buildah-10gb/0.2/buildah-10gb.yaml, task/buildah-20gb/0.1/buildah-20gb.yaml, task/buildah-20gb/0.2/buildah-20gb.yaml, task/buildah-24gb/0.1/buildah-24gb.yaml, task/buildah-24gb/0.2/buildah-24gb.yaml, task/buildah-6gb/0.1/buildah-6gb.yaml, task/buildah-6gb/0.2/buildah-6gb.yaml, task/buildah-8gb/0.1/buildah-8gb.yaml, task/buildah-8gb/0.2/buildah-8gb.yaml, task/buildah-min/0.1/buildah-min.yaml, task/buildah-min/0.2/buildah-min.yaml, task/coverity-availability-check-oci-ta/0.2/coverity-availability-check-oci-ta.yaml, task/fbc-related-image-check/0.2/fbc-related-image-check.yaml, task/fbc-validation/0.2/fbc-validation.yaml, task/inspect-image/0.2/inspect-image.yaml, task/pnc-prebuild-git-clone-oci-ta/0.1/pnc-prebuild-git-clone-oci-ta.yaml, task/sast-coverity-check/0.2/sast-coverity-check.yaml
This PR add a warning message in the kustomize generated files, to notify the users to avoid accidentally editing them
=> chore: add a warning message in the kustomize generated files

task/build-helm-chart-oci-ta/OWNERS, task/build-helm-chart/OWNERS
=> Remove owners files

task/ecosystem-cert-preflight-checks/0.2/MIGRATION.md
Small fix to preflight task migration doc.
=> Fix preflight migration doc

task/sealights-go-oci-ta/0.1/sealights-go-oci-ta.yaml
=> Add TEST_OUTPUT parameter to sealights go tasks to monitor in Konflux UI if something goes wrong with Sealights

pipelines/gitops-pull-request-rhtap/README.md, task/verify-enterprise-contract/0.1/verify-enterprise-contract.yaml
=> Update RHTAP EC Task to use 0.6 version

task/build-helm-chart-oci-ta/0.1/build-helm-chart-oci-ta.yaml, task/build-helm-chart/0.1/build-helm-chart.yaml
tools was moved to a new quay repo
=> chore: update tools image location

pipelines/docker-build-multi-platform-oci-ta/README.md, pipelines/docker-build-oci-ta/README.md, pipelines/docker-build/README.md, task/push-dockerfile-oci-ta/0.1/README.md, task/push-dockerfile-oci-ta/0.1/push-dockerfile-oci-ta.yaml, task/push-dockerfile/0.1/README.md, task/push-dockerfile/0.1/push-dockerfile.yaml
OCI trusted artifact variant is also supported.
=> Add custom certificates support to push-dockerfile task

hack/build-and-push.sh
[STONEBLD-3063](https://issues.redhat.com//browse/STONEBLD-3063)
=> Handle skopeo exit status during building task bundles

hack/create-task-migration.sh
[STONEBLD-2826](https://issues.redhat.com//browse/STONEBLD-2826)
=> Create script to assist in migration creation

task/clair-scan/0.2/clair-scan.yaml
Signed-off-by: Jiri Sztuka <jsztuka@redhat.com>
* this step was running into OOMkilled issue
* in multiple occasions for multiple users
* increasing resources should resolve the issue
=> fix(KONFLUX-5714): increase compute resources for step

pipelines/tekton-bundle-builder/README.md, task/tkn-bundle-oci-ta/0.1/README.md, task/tkn-bundle-oci-ta/0.1/recipe.yaml, task/tkn-bundle-oci-ta/0.1/tkn-bundle-oci-ta.yaml, task/tkn-bundle/0.1/README.md, task/tkn-bundle/0.1/tkn-bundle.yaml
- Update recipe.yml to update workspace
- Add `SOURCE_CODE_DIR` to point to the source folder (defaults to `source`)
- Update `tkn-bundle-oci-ta` task
=> chore(KFLUXVNGD-210): Add source dir to tkn bundle

hack/validate-migration.sh
Without -x, script behaves more informative to tell what is being done and necessary output from the command executed.
=> Better output from migrations validation

README.md
This update provides more information about task migrations, and a new section describing fictional task update for adding tasks to Konflux pipelines.
=> Add more content for task migrations

task/build-image-index/0.1/build-image-index.yaml, task/build-image-manifest/0.1/build-image-manifest.yaml
available after rebuild
[KONFLUX-7444](https://issues.redhat.com//browse/KONFLUX-7444)
=> tag image index with unique tag based on taskrun, so it will be

pipelines/tekton-bundle-builder/README.md, task/tkn-bundle-oci-ta/0.1/README.md, task/tkn-bundle-oci-ta/0.1/tkn-bundle-oci-ta.yaml, task/tkn-bundle/0.1/README.md, task/tkn-bundle/0.1/tkn-bundle.yaml
- update `SOURCE_CODE_DIR` environment variable to get `source` as a fixed value 
- remove `SOURCE_CODE_DIR` parameter
=> fix(KFLUXVNGD-210): update SOURCE_CODE_DIR env var

CODEOWNERS
Update tkn-bundle owners:
Add avi-biton, gbenhaim and yftacherzog
=> update tkn-bundle owners

pipelines/kustomization.yaml, pipelines/tekton-bundle-builder-oci-ta/README.md, pipelines/tekton-bundle-builder-oci-ta/kustomization.yaml, pipelines/tekton-bundle-builder-oci-ta/patch.yaml, pipelines/tekton-bundle-builder-oci-ta/tekton-bundle-builder-oci-ta.yaml, renovate.json
Create an oci-ta version of the tekton-bundle-builder pipeline
=> chore(KFLUXVNGD-239):create oci-ta version of tekton-bundle-builder

task/sast-coverity-check-oci-ta/0.2/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.2/patch.yaml, task/sast-coverity-check/0.2/sast-coverity-check.yaml
See the individual commit messages for details.
Resolves: https://issues.redhat.com/browse/PSSECAUT-1051
Resolves: https://issues.redhat.com/browse/KFLUXSPRT-2270
=> sast-coverity-check: fix scan failures reported by users

CODEOWNERS, renovate.json
Update CODEOWNERS file for `tkn-bundle-builder`
and `tkn-bundle-builder-oci-ta` pipelines
=> Update CODEOWNERS for tkn-bundle-builder

policies/all-tasks.yaml, policies/step-actions.yaml, task/sast-coverity-check-oci-ta/0.1/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check-oci-ta/0.2/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check-oci-ta/0.3/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.1/sast-coverity-check.yaml, task/sast-coverity-check/0.2/patch.yaml, task/sast-coverity-check/0.2/sast-coverity-check.yaml, task/sast-coverity-check/0.3/patch.yaml, task/sast-coverity-check/0.3/sast-coverity-check.yaml
https://github.com/konflux-ci/buildah-container/pull/130
=> sast-coverity-check: bump image for base buildah fix

renovate.json
Preflight currently has policies that are not applicable to older konflux tasks, so the current renovate pr has been on hold for awhile. This means that other dependencies updates we are not getting in our tasks.
- #1738 
Create a specific group in the renovate config to explicitly disable old tasks from getting updated by renovate. Also, explicitly enable the tasks we care about getting updates for.
```bash
❯ jq < deps.json '.config[][] | select(.packageFile | test("preflight.*0.1"))'
{
"deps": [
{
"depName": "quay.io/opdev/preflight",
"packageName": "quay.io/opdev/preflight",
"currentValue": "stable",
"currentDigest": "sha256:3f5b988200a3fd490e0a102a4851e0a81f2f41e724e7482a726b79b9d5ccd3b6",
"replaceString": "quay.io/opdev/preflight:stable@sha256:3f5b988200a3fd490e0a102a4851e0a81f2f41e72 …
```
=> updating renovate config to exclude older preflight tasks from updates

.github/workflows/checkton.yaml, .github/workflows/go-ci.yaml, .github/workflows/run-task-tests.yaml
Addresses: https://issues.redhat.com/browse/STONEBLD-3354
=> fix: run-task-tests, checkton and security scan gha in merge queue

stepactions/fips-operator-check-step-action/0.1/fips-operator-check-step-action.yaml
=> Update konflux-test ref for fips stepaction

task/clair-scan/0.2/clair-scan.yaml, task/clamav-scan/0.1/clamav-scan.yaml, task/clamav-scan/0.2/clamav-scan.yaml, task/sast-coverity-check-oci-ta/0.1/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check-oci-ta/0.3/sast-coverity-check-oci-ta.yaml, task/sast-coverity-check/0.1/sast-coverity-check.yaml, task/sast-coverity-check/0.3/patch.yaml, task/sast-coverity-check/0.3/sast-coverity-check.yaml, task/sast-shell-check-oci-ta/0.1/sast-shell-check-oci-ta.yaml, task/sast-shell-check/0.1/sast-shell-check.yaml, task/sast-snyk-check-oci-ta/0.1/sast-snyk-check-oci-ta.yaml, task/sast-snyk-check-oci-ta/0.2/sast-snyk-check-oci-ta.yaml, task/sast-snyk-check-oci-ta/0.3/sast-snyk-check-oci-ta.yaml, task/sast-snyk-check-oci-ta/0.4/sast-snyk-check-oci-ta.yaml, task/sast-snyk-check/0.1/sast-snyk-check.yaml, task/sast-snyk-check/0.2/sast-snyk-check.yaml, task/sast-snyk-check/0.3/sast-snyk-check.yaml, task/sast-snyk-check/0.4/sast-snyk-check.yaml, task/sast-unicode-check-oci-ta/0.1/sast-unicode-check-oci-ta.yaml, task/sast-unicode-check-oci-ta/0.2/sast-unicode-check-oci-ta.yaml, task/sast-unicode-check/0.1/sast-unicode-check.yaml, task/sast-unicode-check/0.2/sast-unicode-check.yaml
=> feat(STONEINTG-1211): add retry to oras attach command

CODEOWNERS
=> adding caxu-rh to CODEOWNERS for preflight group

.tekton/push.yaml
When moving tasks to new locations, we broke the PAC resolver. This change corrects the reference.
=> Fix reference to snyk task

CODEOWNERS
=> add @a-ovchinnikov to CODEOWNERS for prefetch task

CLAUDE.md
Add a CLAUDE.md which simply references all the currently existing Cursor rules.
=> AI: add Claude instructions

task/generate-labels/0.1/README.md, task/generate-labels/0.1/generate-labels.yaml
Allow custom date formats for `ACTUAL_DATE` and `SOURCE_DATE`
=> chore: allow custom date formats

task/fbc-fips-check-oci-ta/0.1/fbc-fips-check-oci-ta.yaml, task/fbc-fips-check/0.1/fbc-fips-check.yaml
Added better handling of pre-ga index images for the fbc-fips-check.
=> fix(KONFLUX-8857): pre-ga improvements for fbc-fips-check

task/fbc-fips-check-oci-ta/0.1/fbc-fips-check-oci-ta.yaml, task/fbc-fips-check/0.1/fbc-fips-check.yaml, task/fips-operator-bundle-check-oci-ta/0.1/fips-operator-bundle-check-oci-ta.yaml, task/fips-operator-bundle-check/0.1/fips-operator-bundle-check.yaml
Refers to [KONFLUX-10332](https://issues.redhat.com//browse/KONFLUX-10332)
=> Update stepaction ref for FIPS tasks

task/git-clone-oci-ta/0.1/git-clone-oci-ta.yaml, task/git-clone/0.1/git-clone.yaml, task/pnc-prebuild-git-clone-oci-ta/0.1/pnc-prebuild-git-clone-oci-ta.yaml
Do retries in task code for git operations
=> fix(git-clone): do retries for git server operations
